import {NextResponse} from 'next/server';
import {configured,supabase} from '../../../lib/supabase';
import {validOrigin} from '../../../lib/request-security';
import {DirectoryError,readDirectoryAccess,readDirectoryCatalogue,readDirectoryBody,saveDirectory,reconcileDirectory} from '../../../lib/directory';
import {directoryAccessQuerySchema,directoryQuerySchema,directoryRecoverySchema,directoryMutationSchema} from '../../../lib/directory-validation';
const response=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
const failed=(e:unknown)=>e instanceof DirectoryError?response({error:e.message},e.status):response({error:'Directory action could not be confirmed.'},503);
export async function GET(request:Request){try{if(!configured())return response({error:'Company sign-in is not configured.'},503);const params=new URL(request.url).searchParams;const q:Record<string,unknown>={};for(const [k,v]of params){if(k in q)return response({error:'Check the Directory search.'},400);q[k]=k==='limit'?Number(v):v;}const client=await supabase();if(q.mode==='access'){const p=directoryAccessQuerySchema.safeParse(q);if(!p.success)return response({error:'Choose a company.'},400);return response({data:await readDirectoryAccess(client,p.data.tenantId)});}const p=directoryQuerySchema.safeParse(q);if(!p.success)return response({error:'Check the Directory search.'},400);return response({data:await readDirectoryCatalogue(client,p.data)});}catch(e){return failed(e);}}
export async function POST(request:Request){try{if(!validOrigin(request))return response({error:'Invalid request origin.'},403);if(!configured())return response({error:'Company sign-in is not configured.'},503);const body=await readDirectoryBody(request),client=await supabase();if(body&&typeof body==='object'&&'mode'in body){const p=directoryRecoverySchema.safeParse(body);if(!p.success)return response({error:'Check the pending Directory action.'},400);return response({reconciliation:await reconcileDirectory(client,p.data)});}const p=directoryMutationSchema.safeParse(body);if(!p.success)return response({error:'Check the contact details.'},400);return response({saved:await saveDirectory(client,p.data)});}catch(e){return failed(e);}}
