import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const fixtures=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8'));
if(fixtures.url!=='http://127.0.0.1:54821')throw new Error('Local fixtures required');
test('owner can add, edit, search, export, archive and restore a user',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');
 await page.getByLabel('Email',{exact:true}).fill(fixtures.accounts.owner.email);
 await page.getByLabel('Password',{exact:true}).fill(fixtures.accounts.owner.password);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Users',exact:true})).toBeVisible();
 await page.getByText('Add users',{exact:false}).first().click();
 await page.getByRole('button',{name:'Add manually'}).click();
 const dialog=page.getByRole('dialog',{name:'Add users',exact:true});
 await expect(dialog).toBeVisible();
 await expect(dialog.getByRole('button',{name:'Confirm',exact:true})).toBeDisabled();
 expect(await dialog.getByLabel('First name row', {exact:false}).count()).toBe(5);
 const suffix=Date.now().toString().slice(-7);
 await dialog.getByLabel('First name row 1',{exact:true}).fill('Browser');
 await dialog.getByLabel('Last name row 1',{exact:true}).fill('Synthetic '+suffix);
 await dialog.getByLabel('Mobile phone row 1',{exact:true}).fill('07700'+suffix);
 await expect(dialog.getByRole('button',{name:'Confirm',exact:true})).toBeDisabled();
 await dialog.getByLabel('Client row 1',{exact:true}).fill('Demo client');
 await expect(dialog.getByRole('button',{name:'Confirm',exact:true})).toBeEnabled();
 await dialog.getByRole('button',{name:'Confirm',exact:true}).click();
 await expect(dialog).not.toBeVisible();
 await expect(page.getByRole('status')).toContainText('No invitations were sent');
 await page.getByRole('searchbox').fill(suffix);
 const row=page.getByRole('row').filter({hasText:'Synthetic '+suffix});
 await expect(row).toBeVisible();
 await row.getByRole('button',{name:'Edit',exact:false}).click();
 await page.getByRole('dialog').getByLabel('Title row 1',{exact:true}).fill('Changed title');
 await page.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click();
 await expect(row).toContainText('Changed title');
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Export visible users'}).click();
 expect((await download).suggestedFilename()).toBe('users.csv');
 await row.getByRole('button',{name:'Archive',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Archive',exact:true}).click();
 await expect(row).not.toBeVisible();
 await page.getByRole('tab',{name:/Archived/}).click();
 await expect(row).toBeVisible();
 await row.getByRole('button',{name:'Restore',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Restore',exact:true}).click();
 await page.getByRole('tab',{name:/Users/}).click();
 await expect(row).toBeVisible();
 await page.getByRole('searchbox').fill('');
 await page.screenshot({path:'test-results/users-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/users-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 expect(errors).toEqual([]);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Sign in to your company'})).toBeVisible();
 await page.goto('/agents');
 await expect(page).toHaveURL(/\/login$/);
});
test('manager has a directory but cannot add or edit users',async({page})=>{
 await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(fixtures.accounts.manager.email);await page.getByLabel('Password',{exact:true}).fill(fixtures.accounts.manager.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Users',exact:true})).toBeVisible();
 await expect(page.locator('.add-menu')).toHaveCount(0);
 await expect(page.getByRole('button',{name:/^Edit /})).toHaveCount(0);
});
