import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import type {ChatSearchData} from '../../lib/chat-search-types';
const fixture=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8'));
const db='supabase_db_ct-alt-independent',origin='http://127.0.0.1:5180',uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
if(fixture.url!=='http://127.0.0.1:54821'||!/^[0-9a-f]{8}$/.test(fixture.fixtureLabel)||![fixture.tenantA,fixture.tenantB,...Object.values(fixture.accounts).map(account=>(account as {id:string}).id)].every(id=>uuid.test(id)))throw Error('Owned isolated loopback fixture required');
test.describe.configure({mode:'serial'});test.setTimeout(90_000);test.use({viewport:{width:1444,height:960}});
const shared='63000000-0000-4000-8000-000000000001',privateChat='63000000-0000-4000-8000-000000000002',management='63000000-0000-4000-8000-000000000003',huge='63000000-0000-4000-8000-000000000004';
let workforce:string,seedHistory:string,members:string;const errors=new WeakMap<Page,string[]>();
const literal=(value:string)=>"'"+value.replaceAll("'","''")+"'";
function sql(query:string){const label=spawnSync('docker',['inspect',db,'--format','{{index .Config.Labels "ct-alt.test"}}'],{encoding:'utf8'});if(label.status!==0||label.stdout.trim()!==fixture.fixtureLabel)throw Error('Wrong owned fixture database');const result=spawnSync('docker',['exec','-i',db,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{input:query,encoding:'utf8',timeout:30_000});if(result.error||result.status!==0)throw Error(result.error?.message||result.stderr);return result.stdout.trim();}
const workforceSQL=`select md5(jsonb_build_object('tenants',(select jsonb_agg(to_jsonb(t) order by id) from public.tenants t),'memberships',(select jsonb_agg(to_jsonb(m) order by tenant_id,user_id) from public.tenant_memberships m),'agents',(select jsonb_agg(to_jsonb(a) order by id) from public.agents a),'fields',(select jsonb_agg(to_jsonb(f) order by tenant_id,key) from public.agent_fields f))::text);`;
const historySQL=`select md5(coalesce(jsonb_agg(to_jsonb(m) order by conversation_id,sequence),'[]')::text) from public.chat_messages m where conversation_id in ('${shared}','${privateChat}','${management}','${huge}') and (conversation_id<>'${shared}' or sequence<=1006);`;
const membersSQL=`select md5(jsonb_agg(to_jsonb(m) order by conversation_id,user_id)::text) from public.chat_members m;`;
function url(query='dense needle',conversationId=shared,extra:Record<string,string>={}){return '/api/chat/search?'+new URLSearchParams({tenantId:fixture.tenantA,conversationId,query,...extra});}
async function search(request:APIRequestContext,query='dense needle',conversationId=shared,extra:Record<string,string>={}):Promise<ChatSearchData>{const response=await request.get(url(query,conversationId,extra));expect(response.status()).toBe(200);expect(response.headers()['cache-control']).toContain('no-store');return response.json();}
async function login(page:Page,account='employee'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(fixture.accounts[account].email);await page.getByLabel('Password',{exact:true}).fill(fixture.accounts[account].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}
async function choose(page:Page,name='Synthetic search group'){await page.locator('aside[aria-label="Conversations"] button').filter({has:page.getByText(name,{exact:true})}).click();await expect(page.getByLabel('Search this conversation',{exact:true})).toBeEnabled();}
async function queryUI(page:Page,value:string){await page.getByLabel('Search this conversation',{exact:true}).fill(value);await page.getByLabel('Search this conversation',{exact:true}).press('Enter');await expect(page.getByRole('region',{name:'Message search results'})).toHaveAttribute('aria-busy','false');}
async function send(request:APIRequestContext,body:string){const response=await request.post('/api/chat',{headers:{Origin:origin},data:{tenantId:fixture.tenantA,payload:{action:'send',conversationId:shared,clientId:randomUUID(),body}}});expect(response.status()).toBe(200);return response.json();}
function restoreMember(row:string){sql(`insert into public.chat_members select * from jsonb_populate_record(null::public.chat_members,${literal(row)}::jsonb);`);}
const memberRow=(conversationId=shared)=>sql(`select to_jsonb(m) from public.chat_members m where conversation_id='${conversationId}' and user_id='${fixture.accounts.employee.id}';`);
test.beforeAll(()=>{sql(`insert into public.chat_conversations(id,tenant_id,kind,name,last_sequence,management_only) values('${shared}','${fixture.tenantA}','group','Synthetic search group',1006,false),('${privateChat}','${fixture.tenantA}','group','Synthetic private group',1,false),('${management}','${fixture.tenantA}','group','Synthetic management group',2,true),('${huge}','${fixture.tenantA}','group','Synthetic bigint group',0,false);
 insert into public.chat_members(tenant_id,conversation_id,user_id) select '${fixture.tenantA}','${shared}',user_id from public.tenant_memberships where tenant_id='${fixture.tenantA}';
 insert into public.chat_members(tenant_id,conversation_id,user_id) values('${fixture.tenantA}','${privateChat}','${fixture.accounts.employee.id}'),('${fixture.tenantA}','${privateChat}','${fixture.accounts.manager.id}'),('${fixture.tenantA}','${management}','${fixture.accounts.manager.id}'),('${fixture.tenantA}','${management}','${fixture.accounts.owner.id}'),('${fixture.tenantA}','${huge}','${fixture.accounts.employee.id}');
 insert into public.chat_messages(tenant_id,conversation_id,sequence,sender_id,sender_name,client_id,body,created_at) select '${fixture.tenantA}','${shared}',i,'${fixture.accounts.owner.id}','Synthetic stored sender',gen_random_uuid(),'Dense Needle row '||i,'2026-10-03T10:00:00.123456Z' from generate_series(1,1005)i;
 update public.chat_messages set body=body||E' literal 100%_back\\\\slash café Ζebra <b>' where conversation_id='${shared}' and sequence=1;
 insert into public.chat_messages(tenant_id,conversation_id,sequence,sender_id,sender_name,client_id,body,created_at) values('${fixture.tenantA}','${shared}',1006,'${fixture.accounts.owner.id}','Synthetic owner',gen_random_uuid(),'barrier token','2026-10-03T10:00:00.123456Z'),('${fixture.tenantA}','${privateChat}',1,'${fixture.accounts.manager.id}','Synthetic manager',gen_random_uuid(),'Private literal message','2026-10-03T10:00:00.123456Z'),('${fixture.tenantA}','${management}',1,'${fixture.accounts.manager.id}','Synthetic manager',gen_random_uuid(),'Management needle','2026-10-03T10:00:00.123456Z'),('${fixture.tenantA}','${management}',2,'${fixture.accounts.manager.id}','Synthetic manager',gen_random_uuid(),'Management needle two','2026-10-03T10:00:00.123456Z');
 insert into public.chat_messages(tenant_id,conversation_id,sequence,sender_id,sender_name,client_id,body,created_at) select '${fixture.tenantA}','${huge}',i,'${fixture.accounts.employee.id}','Synthetic employee',gen_random_uuid(),'Bigint precise needle','2026-10-03T10:00:00.123456Z' from generate_series(9007199254740992::bigint,9007199254740994::bigint)i;`);workforce=sql(workforceSQL);seedHistory=sql(historySQL);members=sql(membersSQL);});
test.afterAll(()=>{expect(sql(workforceSQL)).toBe(workforce);expect(sql(historySQL)).toBe(seedHistory);expect(sql(membersSQL)).toBe(members);});
test.beforeEach(({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',error=>list.push(error.message));});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));

test('signed joined privacy and literal case-insensitive wildcard, backslash and Unicode matching',async({page,browser})=>{expect((await page.request.get(url())).status()).toBe(401);await login(page);for(const query of ['100%_back\\slash','CAFÉ','ζEBRA','<b>']){const result=await search(page.request,query);expect(result.total).toBe(1);expect(result.messages[0].sequence).toBe('1');}expect((await search(page.request,'no matching synthetic phrase')).total).toBe(0);expect((await search(page.request,'  DENSE NEEDLE  ')).query).toBe('DENSE NEEDLE');for(const account of ['owner','admin','manager','foreign']){const context=await browser.newContext();const other=await context.newPage();try{await login(other,account);expect((await other.request.get(url())).status()).toBe(account==='foreign'?403:200);expect((await other.request.get(url('literal',privateChat))).status()).toBe(account==='manager'?200:403);}finally{await context.close();}}expect((await page.request.get(url('dense needle',shared,{tenantId:fixture.tenantB}))).status()).toBe(403);expect((await page.request.get(url(''))).status()).toBe(400);});

test('exact1005 matches, bounded sequence keysets and concurrent arrivals retain bigint text and read positions',async({page})=>{await login(page);const readBefore=sql(`select coalesce(jsonb_agg(to_jsonb(r) order by conversation_id,user_id),'[]') from public.chat_reads r;`);let result=await search(page.request,'dense needle',shared,{limit:'100'});expect(result.total).toBe(1005);expect(result.messages).toHaveLength(100);await send(page.request,'Dense needle concurrent arrival');const ids=new Set<string>();for(;;){for(const message of result.messages){expect(ids.has(message.sequence)).toBe(false);ids.add(message.sequence);expect(message.created_at).toContain('.123456');expect('client_id' in message).toBe(false);}if(!result.nextCursor)break;const decoded=JSON.parse(Buffer.from(result.nextCursor,'base64url').toString());expect(decoded.sequence).toBe(result.messages.at(-1)!.sequence);result=await search(page.request,'dense needle',shared,{limit:'100',cursor:result.nextCursor});expect(result.total).toBe(1006);}expect(ids.size).toBe(1005);expect(ids.has('1007')).toBe(false);expect((await search(page.request)).messages[0].sequence).toBe('1007');const first=await search(page.request,'precise',huge,{limit:'1'}),second=await search(page.request,'precise',huge,{limit:'1',cursor:first.nextCursor!}),third=await search(page.request,'precise',huge,{limit:'1',cursor:second.nextCursor!});expect([first.messages[0].sequence,second.messages[0].sequence,third.messages[0].sequence]).toEqual(['9007199254740994','9007199254740993','9007199254740992']);expect(third.nextCursor).toBeNull();expect(sql(`select coalesce(jsonb_agg(to_jsonb(r) order by conversation_id,user_id),'[]') from public.chat_reads r;`)).toBe(readBefore);});

test('current removal, suspension, management downgrade and actor-scoped old cursors deny existing signed cookies',async({page,browser})=>{await login(page);const previous=await search(page.request,'dense needle',shared,{limit:'1'}),row=memberRow();try{sql(`delete from public.chat_members where conversation_id='${shared}' and user_id='${fixture.accounts.employee.id}';`);expect((await page.request.get(url('dense needle',shared,{cursor:previous.nextCursor!}))).status()).toBe(403);}finally{restoreMember(row);}try{sql(`update public.tenant_memberships set status='suspended' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.employee.id}';`);expect((await page.request.get(url())).status()).toBe(403);}finally{sql(`update public.tenant_memberships set status='active' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.employee.id}';`);}const context=await browser.newContext();const other=await context.newPage();try{await login(other,'manager');const managed=await search(other.request,'needle',management,{limit:'1'});expect(managed.total).toBe(2);expect(managed.nextCursor).not.toBeNull();try{sql(`update public.tenant_memberships set role='employee' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.manager.id}';`);expect((await other.request.get(url('needle',management,{cursor:managed.nextCursor!}))).status()).toBe(403);}finally{sql(`update public.tenant_memberships set role='manager' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.manager.id}';`);}expect((await other.request.get(url('dense needle',shared,{cursor:previous.nextCursor!}))).status()).toBe(400);}finally{await context.close();}});

test('post-RPC signed RLS recheck denies removal committed after the stable search snapshot began',async({page})=>{await login(page);const signature="'public.search_chat_messages(uuid,uuid,text,integer,jsonb)'::regprocedure",definition=sql(`select pg_get_functiondef(${signature});`),source=sql(`select prosrc from pg_proc where oid=${signature};`),migration=readFileSync('supabase/migrations/20261003231213_chat_message_search.sql','utf8');expect(source).toBe(migration.split('as $$\n')[1].split('$$;')[0].trim());const metadata=sql(`select jsonb_build_object('owner',proowner,'acl',proacl,'stable',provolatile,'definer',prosecdef,'config',proconfig) from pg_proc where oid=${signature};`),row=memberRow();const delayed=definition.replace('-- Count and page',"if normalized_query='barrier token' then perform pg_catalog.pg_sleep(3);end if;\n -- Count and page");expect(delayed).not.toBe(definition);try{sql(delayed);const response=page.request.get(url('barrier token'));await expect.poll(()=>sql(`select count(*) from pg_stat_activity where datname=current_database() and pid<>pg_backend_pid() and wait_event='PgSleep' and query like '%search_chat_messages%';`)).toBe('1');sql(`delete from public.chat_members where conversation_id='${shared}' and user_id='${fixture.accounts.employee.id}';`);expect((await response).status()).toBe(403);}finally{sql(definition);if(sql(`select count(*) from public.chat_members where conversation_id='${shared}' and user_id='${fixture.accounts.employee.id}';`)==='0')restoreMember(row);}expect(sql(`select pg_get_functiondef(${signature});`)).toBe(definition);expect(sql(`select jsonb_build_object('owner',proowner,'acl',proacl,'stable',provolatile,'definer',prosecdef,'config',proconfig) from pg_proc where oid=${signature};`)).toBe(metadata);});

test('desktop search and paging are read-only; Clear resumes normal history and read marking',async({page})=>{await login(page);await page.goto(`/chat?company=${fixture.tenantA}`);await choose(page);await queryUI(page,'dense needle');const results=page.getByRole('region',{name:'Message search results'});await expect(results.locator('article')).toHaveCount(50);await page.getByRole('button',{name:'Load older results',exact:true}).click();await expect(results.locator('article')).toHaveCount(100);const before=sql(`select coalesce((select sequence::text from public.chat_reads where conversation_id='${shared}' and user_id='${fixture.accounts.employee.id}'),'0');`);await send(page.request,'Dense needle unread during search');await queryUI(page,'CAFÉ');await expect(results).toContainText('1 matching message');expect(sql(`select coalesce((select sequence::text from public.chat_reads where conversation_id='${shared}' and user_id='${fixture.accounts.employee.id}'),'0');`)).toBe(before);await page.screenshot({path:'test-results/chat-search-live-desktop.png',fullPage:true});await page.getByRole('button',{name:'Clear search',exact:true}).click();await expect(results).toHaveCount(0);await expect(page.getByRole('log',{name:'Messages'})).toBeVisible();await expect.poll(()=>Number(sql(`select sequence from public.chat_reads where conversation_id='${shared}' and user_id='${fixture.accounts.employee.id}';`))).toBe(1008);});

test('failed search clears matches, delayed query/context reads are fenced and actual403 clears the composer',async({page})=>{await login(page);await page.goto(`/chat?company=${fixture.tenantA}`);await choose(page);await queryUI(page,'dense needle');await page.route('**/api/chat/search?**',route=>route.fulfill({status:503,json:{error:'Synthetic failed search'}}));await queryUI(page,'dense needle');await expect(page.getByRole('region',{name:'Message search results'}).getByRole('alert')).toContainText('Synthetic failed search');await expect(page.locator('.chat-message-results article')).toHaveCount(0);await page.unroute('**/api/chat/search?**');async function hold(){let release:()=>void=()=>{},ready:()=>void=()=>{},settled:()=>void=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;}),started=new Promise<void>(resolve=>{ready=resolve;}),done=new Promise<void>(resolve=>{settled=resolve;});await page.route('**/api/chat/search?**',async route=>{if(new URL(route.request().url()).searchParams.get('query')!=='dense needle')return route.continue();const response=await route.fetch();expect(response.status()).toBe(200);ready();await gate;try{await route.fulfill({response});}catch{}finally{settled();}});await page.getByLabel('Search this conversation',{exact:true}).fill('dense needle');await page.getByLabel('Search this conversation',{exact:true}).press('Enter');await started;return async()=>{release();await done;await page.unroute('**/api/chat/search?**');await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));};}let release=await hold();await queryUI(page,'CAFÉ');await release();await expect(page.locator('.chat-message-results article')).toHaveCount(1);await expect(page.getByRole('region',{name:'Message search results'})).toContainText('Results for “CAFÉ”');release=await hold();await choose(page,'Synthetic private group');await release();await expect(page.getByRole('region',{name:'Message search results'})).toHaveCount(0);await choose(page);release=await hold();await expect(page.getByPlaceholder('Write a message…')).toBeVisible();const row=memberRow();try{sql(`delete from public.chat_members where conversation_id='${shared}' and user_id='${fixture.accounts.employee.id}';`);const denied=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/chat/search'&&response.status()===403);await page.getByLabel('Search this conversation',{exact:true}).fill('CAFÉ');await page.getByLabel('Search this conversation',{exact:true}).press('Enter');expect((await denied).status()).toBe(403);await expect(page.getByPlaceholder('Write a message…')).toHaveCount(0);await release();await expect(page.locator('.chat-message-results article')).toHaveCount(0);await expect(page.getByPlaceholder('Write a message…')).toHaveCount(0);}finally{restoreMember(row);}});
