import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import type {DirectoryAccess,DirectoryCatalogue,DirectoryChange,DirectoryMutation,DirectorySaved,DirectoryReconciliation,DirectoryRecoveryQuery} from '../../lib/directory-types';

const fixture=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8'));
const origin='http://127.0.0.1:5180',endpoint='/api/directory',database='supabase_db_ct-alt-independent';
if(fixture.url!=='http://127.0.0.1:54821'||!/^[0-9a-f]{8}$/.test(fixture.fixtureLabel))throw Error('Owned CT Alt loopback fixture required');
test.describe.configure({mode:'serial'});test.setTimeout(180000);
const quote=(s:string)=>"'"+s.replaceAll("'","''")+"'";
function sql(input:string){const owned=spawnSync('docker',['inspect',database,'--format','{{index .Config.Labels "ct-alt.test"}}'],{encoding:'utf8',timeout:10000});if(owned.status!==0||owned.stdout.trim()!==fixture.fixtureLabel)throw Error('Directory fixture ownership mismatch');const r=spawnSync('docker',['exec','-i',database,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{input,encoding:'utf8',timeout:60000,maxBuffer:16*1024*1024});if(r.status!==0||r.error)throw Error(r.error?.message||r.stderr);return r.stdout.trim();}
function functions(){return sql("select md5(jsonb_agg(jsonb_build_array(p.oid,pg_get_functiondef(p.oid),p.proowner,p.proacl,p.proconfig,p.prosecdef,p.proleakproof,p.proisstrict,p.provolatile,p.proparallel)order by p.oid)::text)from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','workforce_private','chat_private','auth','storage')");}
function permissions(){return sql("select md5(jsonb_agg(jsonb_build_object('oid',c.oid,'name',n.nspname||'.'||c.relname,'kind',c.relkind,'owner',c.relowner,'acl',c.relacl,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'policies',(select jsonb_agg(to_jsonb(p)order by p.oid)from pg_policy p where p.polrelid=c.oid),'triggers',(select jsonb_agg(jsonb_build_object('row',to_jsonb(t),'definition',pg_get_triggerdef(t.oid))order by t.oid)from pg_trigger t where t.tgrelid=c.oid),'attributes',(select jsonb_agg(to_jsonb(a)order by a.attnum)from pg_attribute a where a.attrelid=c.oid),'constraints',(select jsonb_agg(jsonb_build_object('row',to_jsonb(k),'definition',pg_get_constraintdef(k.oid))order by k.oid)from pg_constraint k where k.conrelid=c.oid))order by c.oid)::text)from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','workforce_private','chat_private','auth','storage')");}
function retained(){const tables=sql("select schemaname||'.'||tablename from pg_tables where schemaname in('public','workforce_private','chat_private','storage')and(schemaname||'.'||tablename)not in('public.directory_state','public.directory_work_contacts','public.directory_audit','workforce_private.directory_operations')order by 1").split('\n');return sql('select jsonb_object_agg(name,hash)from('+tables.map(t=>`select ${quote(t)}name,(select md5(coalesce(jsonb_agg(to_jsonb(x)order by to_jsonb(x)::text),'[]')::text)from ${t} x)hash`).join(' union all ')+')x');}
function authIdentities(){return sql("select md5(jsonb_agg(jsonb_build_array(id,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,is_anonymous,deleted_at)order by id)::text)from auth.users");}
function directoryRows(){return sql(`select jsonb_build_object('state',(select to_jsonb(s)from public.directory_state s where tenant_id='${fixture.tenantA}'),'contacts',(select coalesce(jsonb_agg(to_jsonb(c)order by id),'[]')from public.directory_work_contacts c where tenant_id='${fixture.tenantA}'),'audit',(select coalesce(jsonb_agg(to_jsonb(a)order by id),'[]')from public.directory_audit a where tenant_id='${fixture.tenantA}'),'operations',(select coalesce(jsonb_agg(to_jsonb(o)order by operation_id),'[]')from workforce_private.directory_operations o where tenant_id='${fixture.tenantA}'))`);}
let oldFunctions:string,oldPermissions:string,oldRows:string,oldAuth:string;
test.beforeAll(()=>{oldFunctions=functions();oldPermissions=permissions();oldRows=retained();oldAuth=authIdentities();});
test.afterAll(()=>{expect(functions()).toBe(oldFunctions);expect(permissions()).toBe(oldPermissions);expect(retained()).toBe(oldRows);expect(authIdentities()).toBe(oldAuth);});
async function login(page:Page,role='owner'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(fixture.accounts[role].email);await page.getByLabel('Password',{exact:true}).fill(fixture.accounts[role].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}
async function other(page:Page,role:string){const context=await page.context().browser()!.newContext({baseURL:origin});const signed=await context.newPage();await login(signed,role);return{context,page:signed};}
function privacy(r:{headers:()=>Record<string,string>}){expect(r.headers()['cache-control']).toContain('no-store');}
const post=(request:APIRequestContext,data:unknown)=>request.post(endpoint,{headers:{Origin:origin},data});
const operation=(change:DirectoryChange):DirectoryMutation=>({tenantId:fixture.tenantA,operationId:randomUUID(),change});
async function access(request:APIRequestContext,tenant=fixture.tenantA):Promise<DirectoryAccess>{const r=await request.get(endpoint+'?'+new URLSearchParams({mode:'access',tenantId:tenant}));expect(r.status(),await r.text()).toBe(200);privacy(r);const b=await r.json();expect(Object.keys(b)).toEqual(['data']);return b.data;}
async function catalogue(request:APIRequestContext,q='',limit=100,cursor?:string):Promise<DirectoryCatalogue>{const r=await request.get(endpoint+'?'+new URLSearchParams({tenantId:fixture.tenantA,q,limit:String(limit),...(cursor?{cursor}:{})}));expect(r.status(),await r.text()).toBe(200);privacy(r);const b=await r.json();expect(Object.keys(b)).toEqual(['data']);expect(b.data.search).toBe(q.trim());expect(b.data.contacts.length).toBeLessThanOrEqual(limit);expect(new Set(b.data.contacts.map((c:{id:string})=>c.id)).size).toBe(b.data.contacts.length);return b.data;}
async function saved(request:APIRequestContext,v:DirectoryMutation):Promise<DirectorySaved>{const r=await post(request,v);expect(r.status(),await r.text()).toBe(200);privacy(r);const b=await r.json();expect(Object.keys(b)).toEqual(['saved']);expect(Object.keys(b.saved).sort()).toEqual(['schemaVersion','tenantId','actorId','operationId','action','directory_revision','contact_id','contact_revision','active'].sort());expect(b.saved).toMatchObject({schemaVersion:1,tenantId:v.tenantId,actorId:fixture.accounts.owner.id,operationId:v.operationId,action:v.change.action,directory_revision:v.change.directory_revision+1,active:true});if(v.change.action==='create')expect(b.saved.contact_revision).toBe(1);if(v.change.action==='visibility')expect(b.saved).toMatchObject({contact_id:v.change.contact_id,contact_revision:v.change.contact_revision+1});return b.saved;}
async function create(request:APIRequestContext,name:string,description='',phone='',email=''){const v=operation({action:'create',directory_revision:(await access(request)).viewRevision,name,description,phone,email});return{value:v,ack:await saved(request,v)};}
async function visibility(request:APIRequestContext,id:string,visible:boolean){const row=JSON.parse(sql(`select to_jsonb(c)from public.directory_work_contacts c where tenant_id='${fixture.tenantA}'and id='${id}'`));return saved(request,operation({action:'visibility',directory_revision:(await access(request)).viewRevision,contact_id:id,contact_revision:row.revision,visible_in_app:visible}));}
function recovery(v:DirectoryMutation):DirectoryRecoveryQuery{return{mode:'reconcile',tenantId:v.tenantId,operationId:v.operationId,action:v.change.action,contactId:v.change.action==='visibility'?v.change.contact_id:null};}
async function reconcile(request:APIRequestContext,v:DirectoryMutation):Promise<DirectoryReconciliation>{const r=await post(request,recovery(v));expect(r.status(),await r.text()).toBe(200);privacy(r);const b=await r.json();expect(Object.keys(b)).toEqual(['reconciliation']);expect(b.reconciliation).toMatchObject({schemaVersion:1,...Object.fromEntries(Object.entries(recovery(v)).filter(([key])=>key!=='mode'))});return b.reconciliation;}
async function openDirectory(page:Page){await page.goto('/directory?company='+fixture.tenantA);await expect(page.getByRole('heading',{name:'Directory',exact:true})).toBeVisible();}
async function openAdd(page:Page,name:string){await page.getByRole('button',{name:'Add Contact',exact:true}).click();const drawer=page.getByRole('dialog',{name:'Add new contact',exact:true});await expect(drawer).toBeVisible();await drawer.getByRole('textbox',{name:'Type name',exact:true}).fill(name);return drawer;}
function mutationResponse(page:Page,action:string){return page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST'&&r.request().postDataJSON()?.change?.action===action);}
function catalogueResponse(page:Page){return page.waitForResponse(r=>new URL(r.url()).pathname===endpoint&&r.request().method()==='GET'&&!new URL(r.url()).searchParams.has('mode'));
}
async function submitContact(page:Page,name:string){const drawer=await openAdd(page,name),ack=mutationResponse(page,'create'),list=catalogueResponse(page);await drawer.getByRole('button',{name:'Save Contact',exact:true}).click();const r=await ack;expect(r.status(),await r.text()).toBe(200);expect((await list).status()).toBe(200);await expect(drawer).toHaveCount(0);await expect(page.getByText(name,{exact:true})).toBeVisible();return(await r.json()).saved as DirectorySaved;}
function markers(page:Page){return page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('ct-alt:directory-operation:v1:')).map(key=>({key,value:JSON.parse(localStorage.getItem(key)!)})));}
function operationCount(id:string){return Number(sql(`select count(*)from workforce_private.directory_operations where tenant_id='${fixture.tenantA}'and actor_id='${fixture.accounts.owner.id}'and operation_id='${id}'`));}
async function bearer(request:APIRequestContext,role:string){const r=await request.post(fixture.url+'/auth/v1/token?grant_type=password',{headers:{apikey:fixture.key},data:{email:fixture.accounts[role].email,password:fixture.accounts[role].password}});expect(r.status()).toBe(200);const b=await r.json();if(typeof b.access_token!=='string')throw Error('Owned fixture authentication failed');return b.access_token as string;}
async function rpc(request:APIRequestContext,token:string,name:string,args:unknown){return request.post(fixture.url+'/rest/v1/rpc/'+name,{headers:{apikey:fixture.key,Authorization:'Bearer '+token},data:args});}
const contactsPrefix='d3000000-0000-4000-8000-',operationsPrefix='d4000000-0000-4000-8000-';
function fillContactCapacity(){const count=Number(sql(`select count(*)from public.directory_work_contacts where tenant_id='${fixture.tenantA}'`)),add=1000-count;if(add<1)throw Error('Fresh bounded contact fixture expected');sql(`insert into public.directory_work_contacts(id,tenant_id,name,description,phone,email,visible_in_app)select ('${contactsPrefix}'||lpad(n::text,12,'0'))::uuid,'${fixture.tenantA}','Paging contact '||lpad(n::text,4,'0'),'Catalogue page fixture','','',n%2=1 from generate_series(1,${add})n`);return add;}
function clearContactCapacity(){sql(`delete from public.directory_work_contacts where tenant_id='${fixture.tenantA}'and id::text like'${contactsPrefix}%'`);}
function fillOperationCapacity(){const count=Number(sql(`select count(*)from workforce_private.directory_operations where tenant_id='${fixture.tenantA}'`));sql(`insert into workforce_private.directory_operations(tenant_id,actor_id,operation_id,action,contact_id,state,payload_hash,result)select '${fixture.tenantA}','${fixture.accounts.owner.id}',('${operationsPrefix}'||lpad(n::text,12,'0'))::uuid,'create',null,'closed_absent',null,null from generate_series(1,${20000-count})n`);}
function clearOperationCapacity(){sql(`delete from workforce_private.directory_operations where tenant_id='${fixture.tenantA}'and actor_id='${fixture.accounts.owner.id}'and operation_id::text like'${operationsPrefix}%'`);}

test('genuine desktop activation create catalog search and visibility reflect authoritative Work Contacts',async({page})=>{
 await login(page);expect(await access(page.request)).toMatchObject({active:false,canManage:true,viewRevision:0,company:{id:fixture.tenantA,time_zone:'Europe/London'}});
 for(const role of['admin','manager','employee']){const s=await other(page,role);try{expect((await s.page.request.get(endpoint+'?tenantId='+fixture.tenantA)).status()).toBe(403);}finally{await s.context.close();}}
 await openDirectory(page);await expect(page.getByText('Get Started with Directory',{exact:true})).toBeVisible();await expect(page.getByText('Click here to activate your Directory',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'ACTIVATE DIRECTORY',exact:true})).toBeEnabled();if(process.env.CT_ALT_DIRECTORY_CAPTURE)await page.screenshot({path:'/workspace/scratch/ct-alt-directory-activation.png'});
 const activation=mutationResponse(page,'activate');await page.getByRole('button',{name:'ACTIVATE DIRECTORY',exact:true}).click();const activated=await activation;expect(activated.status(),await activated.text()).toBe(200);expect((await activated.json()).saved).toMatchObject({directory_revision:1,contact_id:null,contact_revision:null});await expect(page.getByRole('button',{name:'Add Contact',exact:true})).toBeVisible();
 const name='Morgan Lee · Facilities',drawer=await openAdd(page,name);await drawer.getByRole('textbox',{name:'Description (optional)',exact:true}).fill('Building access and contractor enquiries');await drawer.getByRole('textbox',{name:'Phone number',exact:true}).fill('Reception ext. 204');await drawer.getByRole('textbox',{name:'Email',exact:true}).fill('morgan.lee@example.test');
 await expect(drawer.getByRole('button',{name:/Photo|Information|Review|Preview/})).toHaveCount(0);await expect(drawer.getByRole('textbox')).toHaveCount(4);if(process.env.CT_ALT_DIRECTORY_CAPTURE)await page.screenshot({path:'/workspace/scratch/ct-alt-directory-add-contact.png'});
 const ack=mutationResponse(page,'create');await drawer.getByRole('button',{name:'Save Contact',exact:true}).click();const r=await ack;expect(r.status(),await r.text()).toBe(200);const receipt:DirectorySaved=(await r.json()).saved;await expect(drawer).toHaveCount(0);await expect(page.getByText(name,{exact:true})).toBeVisible();const actual=await catalogue(page.request,name);expect(actual.page.total).toBe(1);expect(actual.contacts[0]).toMatchObject({id:receipt.contact_id,name,description:'Building access and contractor enquiries',phone:'Reception ext. 204',email:'morgan.lee@example.test',visible_in_app:true,revision:1});expect(sql(`select count(*)from public.agents where id='${receipt.contact_id}'`)).toBe('0');expect(sql(`select count(*)from auth.users where id='${receipt.contact_id}'`)).toBe('0');
 await page.getByRole('searchbox',{name:'Search',exact:true}).fill(name);await expect(page.getByText(name,{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Add Contact',exact:true})).toBeEnabled();await expect(page.getByRole('status',{name:'Loading',exact:true})).toHaveCount(0);if(process.env.CT_ALT_DIRECTORY_CAPTURE)await page.screenshot({path:'/workspace/scratch/ct-alt-directory-work-contacts.png'});
 const row=page.getByRole('row').filter({has:page.getByText(name,{exact:true})}),change=mutationResponse(page,'visibility');await row.getByRole('switch').click();const changed=await change;expect(changed.status(),await changed.text()).toBe(200);expect((await catalogue(page.request,name)).contacts[0]).toMatchObject({visible_in_app:false,revision:2});await expect(row.getByRole('switch')).not.toBeChecked();
 await expect(page.getByRole('button',{name:/Edit|Delete|Options|Mobile preview/i})).toHaveCount(0);await expect(page.getByRole('tab',{name:'Users',exact:true})).toHaveCount(0);await expect(page.locator('a[href^="tel:"],a[href^="mailto:"]')).toHaveCount(0);
});

test('all nonowner roles read only visible scope and cannot activate create change visibility or reconcile',async({page})=>{
 await login(page);const shown=await create(page.request,'Front desk public contact','Visitor support'),hidden=await create(page.request,'Hidden procurement reference','Internal supplier number','Private channel','private@example.test');await visibility(page.request,hidden.ack.contact_id!,false);
 for(const role of['admin','manager','employee']){const s=await other(page,role);try{const data=await catalogue(s.page.request);expect(data).toMatchObject({role,canManage:false,active:true});expect(data.contacts.some(c=>c.id===shown.ack.contact_id)).toBe(true);expect(JSON.stringify(data)).not.toContain(hidden.ack.contact_id!);expect(JSON.stringify(data)).not.toContain('Hidden procurement reference');expect(JSON.stringify(data)).not.toContain('private@example.test');expect((await catalogue(s.page.request,'Hidden procurement reference')).page.total).toBe(0);
 for(const change of[{action:'activate',directory_revision:0},{action:'create',directory_revision:0,name:'Denied',description:'',phone:'',email:''},{action:'visibility',directory_revision:0,contact_id:shown.ack.contact_id,contact_revision:1,visible_in_app:false}])expect((await post(s.page.request,{tenantId:fixture.tenantA,operationId:randomUUID(),change})).status()).toBe(403);expect((await post(s.page.request,recovery(hidden.value))).status()).toBe(403);await openDirectory(s.page);await expect(s.page.getByRole('button',{name:'Add Contact',exact:true})).toHaveCount(0);await expect(s.page.getByRole('switch')).toHaveCount(0);await expect(s.page.getByText('Hidden procurement reference',{exact:true})).toHaveCount(0);
 }finally{await s.context.close();}}
 const foreign=await other(page,'foreign');try{expect((await foreign.page.request.get(endpoint+'?tenantId='+fixture.tenantA)).status()).toBe(403);expect((await post(foreign.page.request,shown.value)).status()).toBe(403);}finally{await foreign.context.close();}
});

test('hidden-only changes preserve visible revision cursor totals and literal search for every nonowner',async({page})=>{
 await login(page);const hidden=await create(page.request,'Hidden only revision fence','Unshared details');await visibility(page.request,hidden.ack.contact_id!,false);for(const role of['admin','manager','employee']){const s=await other(page,role);try{const before=await catalogue(s.page.request,'',1),ownerBefore=await access(page.request);await visibility(page.request,hidden.ack.contact_id!,false);const after=await catalogue(s.page.request,'',1);expect(after).toEqual(before);expect((await access(page.request)).viewRevision).toBe(ownerBefore.viewRevision+1);if(before.page.nextCursor){const next=await catalogue(s.page.request,'',1,before.page.nextCursor);expect(next.viewRevision).toBe(before.viewRevision);}expect((await catalogue(s.page.request,'Unshared details')).page.total).toBe(0);}finally{await s.context.close();}}
});

test('Unicode raw UTF16 limits plain optional channels and literal percent underscore search agree with persisted bytes',async({page})=>{
 await login(page);const name='\u00a0Ariél 😀 %_ Operations\u3000',description='Supplier café · 東京',contact=await create(page.request,name,description,'extension ABC','unspecified inbox');const data=await catalogue(page.request,'%_');expect(data.contacts.find(c=>c.id===contact.ack.contact_id)).toMatchObject({name:name.trim(),description,phone:'extension ABC',email:'unspecified inbox'});expect((await catalogue(page.request,'no%_match')).page.total).toBe(0);await create(page.request,'😀'.repeat(50));const before=directoryRows();
 for(const patch of[{name:'😀'.repeat(51)},{name:' '.repeat(100)+'A'},{description:' '.repeat(1001)},{phone:' '.repeat(65)},{email:' '.repeat(255)},{name:'\u00a0\u3000'},{name:'Bad\u0085name'},{description:'Bad\u0001description'},{name:'\ud800'}]){const v=operation({action:'create',directory_revision:(await access(page.request)).viewRevision,name:'Valid',description:'',phone:'',email:'',...patch});expect((await post(page.request,v)).status()).toBe(400);expect(directoryRows()).toBe(before);}
 expect((await page.request.get(endpoint+'?'+new URLSearchParams({tenantId:fixture.tenantA,q:' '.repeat(101)}))).status()).toBe(400);
});

test('strict HTTP envelope rejects duplicates unknown fields invalid UTF8 oversized bodies and unsafe origins atomically',async({page})=>{
 await login(page);const v=operation({action:'create',directory_revision:(await access(page.request)).viewRevision,name:'Envelope unchanged',description:'',phone:'',email:''}),before=directoryRows();const raw=JSON.stringify(v);
 for(const body of[raw.replace('"action":"create"','"action":"create","action":"create"'),JSON.stringify({...v,extra:true}),raw.replace('"name":"Envelope unchanged"','"name":"Envelope unchanged","unknown":"x"')])expect((await page.request.post(endpoint,{headers:{Origin:origin,'Content-Type':'application/json'},data:body})).status()).toBe(400);
 expect((await page.request.post(endpoint,{headers:{Origin:origin,'Content-Type':'application/json'},data:Buffer.from([0xc3,0x28])})).status()).toBe(400);expect((await page.request.post(endpoint,{headers:{Origin:origin,'Content-Type':'application/json'},data:' '.repeat(65537)})).status()).toBe(413);expect((await page.request.post(endpoint,{headers:{Origin:'https://foreign.example.test'},data:v})).status()).toBe(403);expect((await page.request.get(endpoint+'?tenantId='+fixture.tenantA+'&q=a&q=b')).status()).toBe(400);expect(directoryRows()).toBe(before);
});

test('recorded operations replay original acknowledgement once and closed absence permanently fences late creation',async({page})=>{
 await login(page);const c=await create(page.request,'Replay receipt contact');expect(await saved(page.request,c.value)).toEqual(c.ack);expect(operationCount(c.value.operationId)).toBe(1);expect(sql(`select count(*)from public.directory_audit where tenant_id='${fixture.tenantA}'and operation_id='${c.value.operationId}'`)).toBe('1');await visibility(page.request,c.ack.contact_id!,false);const r=await reconcile(page.request,c.value);expect(r).toMatchObject({status:'recorded',saved:c.ack});const before=directoryRows();expect((await post(page.request,{...c.value,change:{...c.value.change,name:'Changed replay payload'}})).status()).toBe(409);expect(directoryRows()).toBe(before);
 const missing=operation({action:'create',directory_revision:(await access(page.request)).viewRevision,name:'Late absent contact',description:'',phone:'',email:''});expect(await reconcile(page.request,missing)).toMatchObject({status:'not_recorded',saved:null});expect(await reconcile(page.request,missing)).toMatchObject({status:'not_recorded',saved:null});expect((await post(page.request,missing)).status()).toBe(409);expect((await catalogue(page.request,'Late absent contact')).page.total).toBe(0);expect(operationCount(missing.operationId)).toBe(1);expect(sql(`select count(*)from public.directory_audit where tenant_id='${fixture.tenantA}'and operation_id='${missing.operationId}'`)).toBe('0');
});

test('genuine authenticated RPC validates raw fields and RLS hides contacts audit and operation receipts',async({page})=>{
 await login(page);const token=await bearer(page.request,'owner'),revision=(await access(page.request)).viewRevision,change={action:'create',directory_revision:revision,name:'\u00a0Direct RPC Zoë 😀\u3000',description:'external work contact',phone:'Desk: ABC',email:''},op=randomUUID();const r=await rpc(page.request,token,'save_directory',{target_tenant:fixture.tenantA,operation_id:op,raw_change:JSON.stringify(change)});expect(r.status(),await r.text()).toBe(200);const ack:DirectorySaved=await r.json();expect((await catalogue(page.request,'Direct RPC Zoë 😀')).contacts[0]).toMatchObject({id:ack.contact_id,name:change.name.trim(),phone:'Desk: ABC'});const before=directoryRows();
 for(const patch of[{name:' '.repeat(100)+'Z'},{name:'😀'.repeat(51)},{description:'Bad\u0085description'},{email:'x'.repeat(255)},{name:'\u00a0\u3000'}]){const invalid=await rpc(page.request,token,'save_directory',{target_tenant:fixture.tenantA,operation_id:randomUUID(),raw_change:JSON.stringify({...change,directory_revision:revision+1,...patch})});expect(invalid.status(),await invalid.text()).toBe(400);expect(directoryRows()).toBe(before);}
 await visibility(page.request,ack.contact_id!,false);for(const role of['admin','manager','employee']){const jwt=await bearer(page.request,role),headers={apikey:fixture.key,Authorization:'Bearer '+jwt};const contacts=await page.request.get(fixture.url+'/rest/v1/directory_work_contacts?select=*&id=eq.'+ack.contact_id,{headers});expect(contacts.status()).toBe(200);expect(await contacts.json()).toEqual([]);for(const table of['directory_state','directory_audit']){const denied=await page.request.get(fixture.url+'/rest/v1/'+table+'?select=*',{headers});expect(denied.status()).toBe(403);}const write=await rpc(page.request,jwt,'save_directory',{target_tenant:fixture.tenantA,operation_id:randomUUID(),raw_change:JSON.stringify({...change,directory_revision:0})});expect(write.status()).toBe(403);}
});

test('complete 1000-contact catalogue pages and search find later records without leaking hidden rows or cursor scope',async({page})=>{
 await login(page);const added=fillContactCapacity();try{const ids:string[]=[];let cursor:string|undefined;for(let i=0;i<10;i++){const data=await catalogue(page.request,'',100,cursor);expect(data.page.total).toBe(1000);expect(data.contacts).toHaveLength(100);ids.push(...data.contacts.map(c=>c.id));cursor=data.page.nextCursor??undefined;expect(Boolean(cursor)).toBe(i<9);}expect(new Set(ids).size).toBe(1000);
 const last='Paging contact '+String(added).padStart(4,'0');await openDirectory(page);await page.getByRole('searchbox',{name:'Search',exact:true}).fill(last);await expect(page.getByText(last,{exact:true})).toBeVisible();expect((await catalogue(page.request,last)).contacts).toHaveLength(1);
 const first=await catalogue(page.request,'',1);expect(first.page.nextCursor).not.toBeNull();const s=await other(page,'employee');try{const visible=await catalogue(s.page.request,'',100),expected=Number(sql(`select count(*)from public.directory_work_contacts where tenant_id='${fixture.tenantA}'and visible_in_app`));expect(visible.page.total).toBe(expected);expect(visible.contacts.every(c=>c.visible_in_app)).toBe(true);const crossed=await s.page.request.get(endpoint+'?'+new URLSearchParams({tenantId:fixture.tenantA,cursor:first.page.nextCursor!}));expect(crossed.status()).toBe(403);expect(Object.keys(await crossed.json())).toEqual(['error']);const hidden='Paging contact 0002';expect((await catalogue(s.page.request,hidden)).page.total).toBe(0);}finally{await s.context.close();}
 expect((await page.request.get(endpoint+'?'+new URLSearchParams({tenantId:fixture.tenantB,cursor:first.page.nextCursor!}))).status()).toBe(400);expect((await page.request.get(endpoint+'?'+new URLSearchParams({tenantId:fixture.tenantA,q:'Different search',cursor:first.page.nextCursor!}))).status()).toBe(409);const before=directoryRows();expect((await post(page.request,operation({action:'create',directory_revision:(await access(page.request)).viewRevision,name:'Over 1000 contacts',description:'',phone:'',email:''}))).status()).toBe(409);expect(directoryRows()).toBe(before);await visibility(page.request,contactsPrefix+'000000000001',false);expect((await page.request.get(endpoint+'?'+new URLSearchParams({tenantId:fixture.tenantA,cursor:first.page.nextCursor!}))).status()).toBe(409);expect((await catalogue(page.request)).page.total).toBe(1000);
 }finally{clearContactCapacity();}
});

test('full operation capacity keeps original recorded recovery and rejects fresh closure or write atomically',async({page})=>{
 await login(page);const c=await create(page.request,'Capacity original receipt');fillOperationCapacity();try{expect(sql(`select count(*)from workforce_private.directory_operations where tenant_id='${fixture.tenantA}'`)).toBe('20000');expect(await reconcile(page.request,c.value)).toMatchObject({status:'recorded',saved:c.ack});expect(await saved(page.request,c.value)).toEqual(c.ack);const before=directoryRows(),absent=operation({action:'create',directory_revision:(await access(page.request)).viewRevision,name:'Capacity pending absent',description:'',phone:'',email:''});const closed=await post(page.request,recovery(absent));expect(closed.status(),await closed.text()).toBe(409);expect(await closed.text()).not.toContain('not_recorded');expect(operationCount(absent.operationId)).toBe(0);expect((await post(page.request,absent)).status()).toBe(409);expect(directoryRows()).toBe(before);
 }finally{clearOperationCapacity();}
});

test('current owner membership confirmation and company status denial precede stale write and recovery',async({page})=>{
 await login(page);const v=operation({action:'create',directory_revision:0,name:'Revoked cannot create',description:'',phone:'',email:''}),membership=JSON.parse(sql(`select to_jsonb(m)from public.tenant_memberships m where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`)),user=JSON.parse(sql(`select jsonb_build_object('confirmed',email_confirmed_at,'anonymous',is_anonymous)from auth.users where id='${fixture.accounts.owner.id}'`)),tenant=JSON.parse(sql(`select to_jsonb(t)from public.tenants t where id='${fixture.tenantA}'`));const before=directoryRows();
 try{for(const change of[`update public.tenant_memberships set status='suspended'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`,`update public.tenant_memberships set role='admin'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`,`update auth.users set email_confirmed_at=null where id='${fixture.accounts.owner.id}'`,`update auth.users set is_anonymous=true where id='${fixture.accounts.owner.id}'`,`update public.tenants set status='suspended'where id='${fixture.tenantA}'`]){sql(change);expect((await post(page.request,v)).status()).toBe(403);expect((await post(page.request,recovery(v))).status()).toBe(403);sql(`update public.tenant_memberships set role=${quote(membership.role)},status=${quote(membership.status)}where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}';update auth.users set email_confirmed_at=${quote(user.confirmed)}::timestamptz,is_anonymous=${user.anonymous} where id='${fixture.accounts.owner.id}';update public.tenants set status=${quote(tenant.status)}where id='${fixture.tenantA}'`);}expect(directoryRows()).toBe(before);
 }finally{sql(`update public.tenant_memberships set role=${quote(membership.role)},status=${quote(membership.status)}where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}';update auth.users set email_confirmed_at=${quote(user.confirmed)}::timestamptz,is_anonymous=${user.anonymous} where id='${fixture.accounts.owner.id}';update public.tenants set status=${quote(tenant.status)}where id='${fixture.tenantA}'`);}
});

test('held genuine committed Save acknowledgement locks controls and retains only opaque recovery identity',async({page})=>{
 await login(page);await openDirectory(page);let release!:()=>void,seen!:()=>void;const gate=new Promise<void>(r=>release=r),committed=new Promise<void>(r=>seen=r);let value:DirectoryMutation|undefined;await page.route('**/api/directory',async route=>{const data=route.request().method()==='POST'?route.request().postDataJSON():null;if(data?.change?.action!=='create')return route.continue();value=data;const r=await route.fetch();expect(r.status(),await r.text()).toBe(200);expect(operationCount(data.operationId)).toBe(1);seen();await gate;await route.fulfill({response:r});});
 try{const drawer=await openAdd(page,'Held ACK work contact');await drawer.getByRole('button',{name:'Save Contact',exact:true}).click();await committed;await expect(drawer.getByRole('button',{name:'Save Contact',exact:true})).toBeDisabled();await expect(drawer.getByRole('textbox',{name:'Type name',exact:true})).toBeDisabled();expect(await markers(page)).toEqual([{key:`ct-alt:directory-operation:v1:${fixture.accounts.owner.id}:${fixture.tenantA}`,value:recovery(value!)}]);expect(JSON.stringify(await markers(page))).not.toContain('Held ACK work contact');release();await expect(drawer).toHaveCount(0);await expect(page.getByText('Held ACK work contact',{exact:true})).toBeVisible();await expect.poll(()=>markers(page)).toEqual([]);expect(operationCount(value!.operationId)).toBe(1);
 }finally{release();await page.unroute('**/api/directory');}
});

test('lost real Save acknowledgement remount automatically recovers one original receipt and fresh nonempty catalogue',async({page})=>{
 await login(page);await openDirectory(page);let released!:()=>void,seen!:()=>void;const gate=new Promise<void>(r=>released=r),held=new Promise<void>(r=>seen=r);let value:DirectoryMutation|undefined,departed=false;await page.route('**/api/directory',async route=>{if(route.request().method()!=='POST')return route.continue();const data=route.request().postDataJSON();if(data.change?.action==='create'){value=data;const r=await route.fetch();expect(r.status(),await r.text()).toBe(200);expect(operationCount(data.operationId)).toBe(1);return route.abort('failed');}if(data.mode==='reconcile'){seen();await gate;if(departed)return;return route.continue();}return route.continue();});
 try{const drawer=await openAdd(page,'Recovered contact after lost ACK');await drawer.getByRole('button',{name:'Save Contact',exact:true}).click();await held;expect(await markers(page)).toHaveLength(1);expect(operationCount(value!.operationId)).toBe(1);departed=true;await page.goto('/agents?company='+fixture.tenantA);released();await page.unroute('**/api/directory');const proof=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST'&&r.request().postDataJSON().mode==='reconcile');await openDirectory(page);const response=await proof;expect(response.status(),await response.text()).toBe(200);expect((await response.json()).reconciliation).toMatchObject({status:'recorded',saved:{operationId:value!.operationId,contact_revision:1}});await expect.poll(()=>markers(page)).toEqual([]);await expect(page.getByText('Recovered contact after lost ACK',{exact:true})).toBeVisible();expect((await catalogue(page.request,'Recovered contact after lost ACK')).page.total).toBe(1);expect(operationCount(value!.operationId)).toBe(1);expect(sql(`select count(*)from public.directory_audit where tenant_id='${fixture.tenantA}'and operation_id='${value!.operationId}'`)).toBe('1');
 }finally{departed=true;released();await page.unroute('**/api/directory');}
});

test('ordinary optional blank fields and raw Unicode contact name Save reload the authoritative catalogue',async({page})=>{
 await login(page);await openDirectory(page);const name='Renée 東京 😀 · Service desk',ack=await submitContact(page,name),data=await catalogue(page.request,name);expect(data.page.total).toBe(1);expect(data.contacts[0]).toMatchObject({id:ack.contact_id,name,description:'',phone:'',email:'',visible_in_app:true});await expect.poll(()=>markers(page)).toEqual([]);await expect(page.getByRole('button',{name:/Review|Recover|Check status|Retry|Send|Invite/i})).toHaveCount(0);
});

test('uncertain absent Save at full operation quota retains identity until remount can verify closed absence',async({page})=>{
 await login(page);await openDirectory(page);let value:DirectoryMutation|undefined;await page.route('**/api/directory',async route=>{if(route.request().method()!=='POST')return route.continue();const data=route.request().postDataJSON();if(data.change?.action==='create'){value=data;fillOperationCapacity();return route.abort('failed');}return route.continue();});
 try{const drawer=await openAdd(page,'Not dispatched contact');const closure=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST'&&r.request().postDataJSON().mode==='reconcile');await drawer.getByRole('button',{name:'Save Contact',exact:true}).click();expect((await closure).status()).toBe(409);await expect(drawer.getByRole('button',{name:'Save Contact',exact:true})).toBeDisabled();expect(await markers(page)).toHaveLength(1);expect(operationCount(value!.operationId)).toBe(0);expect((await catalogue(page.request,'Not dispatched contact')).page.total).toBe(0);await expect(page.getByText('The change was not saved.',{exact:true})).toHaveCount(0);
 clearOperationCapacity();await page.goto('/agents?company='+fixture.tenantA);await page.unroute('**/api/directory');const verified=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST'&&r.request().postDataJSON().mode==='reconcile');await openDirectory(page);const proof=await verified;expect(proof.status(),await proof.text()).toBe(200);expect((await proof.json()).reconciliation).toMatchObject({status:'not_recorded',saved:null,operationId:value!.operationId});await expect.poll(()=>markers(page)).toEqual([]);await expect(page.getByRole('button',{name:'Add Contact',exact:true})).toBeEnabled();await expect(page.getByText('Renée 東京 😀 · Service desk',{exact:true})).toBeVisible();expect((await post(page.request,value)).status()).toBe(409);expect(operationCount(value!.operationId)).toBe(1);expect(sql(`select count(*)from public.directory_audit where tenant_id='${fixture.tenantA}'and operation_id='${value!.operationId}'`)).toBe('0');
 }finally{clearOperationCapacity();await page.unroute('**/api/directory');}
});

test('malformed acknowledgement after real commit cannot clear recovery identity and remount restores original receipt',async({page})=>{
 await login(page);await openDirectory(page);let release!:()=>void,seen!:()=>void;const gate=new Promise<void>(r=>release=r),held=new Promise<void>(r=>seen=r);let value:DirectoryMutation|undefined,departed=false;await page.route('**/api/directory',async route=>{if(route.request().method()!=='POST')return route.continue();const data=route.request().postDataJSON();if(data.change?.action==='create'){value=data;const r=await route.fetch();expect(r.status(),await r.text()).toBe(200);const body=await r.json();return route.fulfill({response:r,json:{saved:{...body.saved,operationId:randomUUID()}}});}if(data.mode==='reconcile'){seen();await gate;if(departed)return;return route.continue();}return route.continue();});
 try{const drawer=await openAdd(page,'Malformed ACK original contact');await drawer.getByRole('button',{name:'Save Contact',exact:true}).click();await held;expect(await markers(page)).toHaveLength(1);expect(operationCount(value!.operationId)).toBe(1);departed=true;await page.goto('/agents?company='+fixture.tenantA);release();await page.unroute('**/api/directory');await openDirectory(page);await expect.poll(()=>markers(page)).toEqual([]);await expect(page.getByText('Malformed ACK original contact',{exact:true})).toBeVisible();expect((await catalogue(page.request,'Malformed ACK original contact')).page.total).toBe(1);expect(operationCount(value!.operationId)).toBe(1);
 }finally{departed=true;release();await page.unroute('**/api/directory');}
});

test('fresh current owner denial after held committed acknowledgement clears fields and keeps pending proof',async({page})=>{
 await login(page);await openDirectory(page);let release!:()=>void,seen!:()=>void;const gate=new Promise<void>(r=>release=r),held=new Promise<void>(r=>seen=r);let value:DirectoryMutation|undefined;await page.route('**/api/directory',async route=>{const data=route.request().method()==='POST'?route.request().postDataJSON():null;if(data?.change?.action!=='create')return route.continue();value=data;const r=await route.fetch();expect(r.status(),await r.text()).toBe(200);seen();await gate;return route.fulfill({response:r});});
 try{const drawer=await openAdd(page,'Held ACK then owner denied');await drawer.getByRole('button',{name:'Save Contact',exact:true}).click();await held;sql(`update public.tenant_memberships set role='admin'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);release();await expect(drawer).toHaveCount(0);await expect(page.getByRole('button',{name:'Add Contact',exact:true})).toHaveCount(0);await expect(page.getByRole('table')).toHaveCount(0);await expect(page.getByRole('alert').filter({hasText:'Directory is unavailable.'})).toHaveText('Directory is unavailable.');expect(await markers(page)).toHaveLength(1);expect(operationCount(value!.operationId)).toBe(1);expect((await catalogue(page.request,'Hidden procurement reference')).page.total).toBe(0);
 }finally{sql(`update public.tenant_memberships set role='owner'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);release();await page.unroute('**/api/directory');}
 await page.goto('/agents?company='+fixture.tenantA);await openDirectory(page);await expect.poll(()=>markers(page)).toEqual([]);await expect(page.getByText('Held ACK then owner denied',{exact:true})).toBeVisible();expect(operationCount(value!.operationId)).toBe(1);
});

test('held older privileged catalogue cannot restore protected content after departure and fresh access denial',async({page})=>{
 await login(page);let release!:()=>void,seen!:()=>void;const gate=new Promise<void>(r=>release=r),held=new Promise<void>(r=>seen=r);let departed=false;await page.route('**/api/directory?**',async route=>{const url=new URL(route.request().url());if(url.searchParams.has('mode'))return route.continue();const r=await route.fetch();expect(r.status(),await r.text()).toBe(200);expect((await r.json()).data.contacts.some((c:{name:string})=>c.name==='Hidden procurement reference')).toBe(true);seen();await gate;if(departed)return;return route.fulfill({response:r});});
 try{await openDirectory(page);await held;departed=true;await page.goto('/agents?company='+fixture.tenantA);sql(`update public.tenant_memberships set status='suspended'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);await openDirectory(page);await expect(page.locator('main > p[role="alert"]')).toBeVisible();await expect(page.getByRole('table')).toHaveCount(0);await expect(page.getByText('Hidden procurement reference',{exact:true})).toHaveCount(0);release();await expect(page.getByRole('button',{name:'Add Contact',exact:true})).toHaveCount(0);await expect(page.getByText('private@example.test',{exact:true})).toHaveCount(0);
 }finally{sql(`update public.tenant_memberships set status='active'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);departed=true;release();await page.unroute('**/api/directory?**');}
});

test('anonymous HTTP and foreign-company contact visibility identities are denied without changing either tenant',async({page})=>{
 await login(page);const context=await page.context().browser()!.newContext({baseURL:origin});try{const anonymous=await context.newPage();expect((await anonymous.request.get(endpoint+'?tenantId='+fixture.tenantA)).status()).toBe(401);expect((await post(anonymous.request,operation({action:'activate',directory_revision:0}))).status()).toBe(401);}finally{await context.close();}
 const before=directoryRows(),foreign=await other(page,'foreign');try{const response=await post(page.request,operation({action:'visibility',directory_revision:(await access(page.request)).viewRevision,contact_id:randomUUID(),contact_revision:1,visible_in_app:false}));expect(response.status()).toBe(409);expect((await foreign.page.request.get(endpoint+'?tenantId='+fixture.tenantA)).status()).toBe(403);expect(directoryRows()).toBe(before);expect(sql(`select count(*)from public.directory_state where tenant_id='${fixture.tenantB}'`)).toBe('0');}finally{await foreign.context.close();}
});

test('same actor downgraded owner cursor is currently denied while new reader scope cannot expose hidden records',async({page})=>{
 await login(page);const first=await catalogue(page.request,'',1);expect(first.page.nextCursor).not.toBeNull();try{sql(`update public.tenant_memberships set role='employee'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);const denied=await page.request.get(endpoint+'?'+new URLSearchParams({tenantId:fixture.tenantA,cursor:first.page.nextCursor!}));expect(denied.status()).toBe(403);expect(Object.keys(await denied.json())).toEqual(['error']);const reader=await catalogue(page.request);expect(reader).toMatchObject({role:'employee',canManage:false});expect(reader.contacts.every(c=>c.visible_in_app)).toBe(true);expect(JSON.stringify(reader)).not.toContain('Hidden procurement reference');}finally{sql(`update public.tenant_memberships set role='owner'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);}
});

test('lost activation acknowledgement recovers automatically into an active authoritative empty company catalogue',async({page})=>{
 const id=fixture.accounts.foreign.id;let value:DirectoryMutation|undefined,release!:()=>void,seen!:()=>void,departed=false;const gate=new Promise<void>(r=>release=r),held=new Promise<void>(r=>seen=r);
 try{await login(page,'foreign');await page.goto('/directory?company='+fixture.tenantB);await expect(page.getByRole('button',{name:'ACTIVATE DIRECTORY',exact:true})).toBeEnabled();await page.route('**/api/directory',async route=>{if(route.request().method()!=='POST')return route.continue();const data=route.request().postDataJSON();if(data.change?.action==='activate'){value=data;const r=await route.fetch();expect(r.status(),await r.text()).toBe(200);return route.abort('failed');}if(data.mode==='reconcile'){seen();await gate;if(departed)return;return route.continue();}return route.continue();});await page.getByRole('button',{name:'ACTIVATE DIRECTORY',exact:true}).click();await held;expect(await markers(page)).toEqual([{key:`ct-alt:directory-operation:v1:${id}:${fixture.tenantB}`,value:recovery(value!)}]);departed=true;await page.goto('/agents?company='+fixture.tenantB);release();await page.unroute('**/api/directory');const receipt=page.waitForResponse(r=>r.url().endsWith(endpoint)&&r.request().method()==='POST'&&r.request().postDataJSON().mode==='reconcile');await page.goto('/directory?company='+fixture.tenantB);const r=await receipt;expect(r.status(),await r.text()).toBe(200);expect((await r.json()).reconciliation).toMatchObject({status:'recorded',saved:{tenantId:fixture.tenantB,actorId:id,action:'activate',directory_revision:1,contact_id:null,contact_revision:null}});await expect.poll(()=>markers(page)).toEqual([]);await expect(page.getByRole('button',{name:'Add Contact',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'ACTIVATE DIRECTORY',exact:true})).toHaveCount(0);const list=await page.request.get(endpoint+'?tenantId='+fixture.tenantB);expect(list.status()).toBe(200);expect((await list.json()).data).toMatchObject({active:true,canManage:true,viewRevision:1,contacts:[],page:{total:0,nextCursor:null}});expect(sql(`select count(*)from public.directory_audit where tenant_id='${fixture.tenantB}'and operation_id='${value!.operationId}'`)).toBe('1');expect(sql(`select count(*)from workforce_private.directory_operations where tenant_id='${fixture.tenantB}'and operation_id='${value!.operationId}'`)).toBe('1');
 }finally{departed=true;release?.();await page.unroute('**/api/directory');}
});
