import{test,expect,type Page,type APIRequestContext,type APIResponse}from'@playwright/test';
import{readFileSync}from'node:fs';
import{spawn,spawnSync}from'node:child_process';
import{randomUUID}from'node:crypto';
import type{RequestChange,RequestsMutation,RequestsBoardData,RequestsColumnData,RequestsSaved,WorkRequest}from'../../lib/requests-types';
const f=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8')),origin='http://127.0.0.1:5180',db='supabase_db_ct-alt-independent';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
if(f.url!=='http://127.0.0.1:54821'||!/^[0-9a-f]{8}$/.test(f.fixtureLabel)||![f.tenantA,f.tenantB,...Object.values(f.accounts).map(a=>(a as{id:string}).id)].every(id=>uuid.test(id)))throw Error('Owned loopback fixture required');
test.describe.configure({mode:'serial'});test.setTimeout(120000);test.use({viewport:{width:1444,height:960}});
let employeeAgent:string,replacementAgent:string,originalRows:string,originalFunctions:string,privateRequest:RequestsSaved,assignedRequest:RequestsSaved;
const quote=(v:string)=>"'"+v.replaceAll("'","''")+"'";
function sql(input:string){const own=spawnSync('docker',['inspect',db,'--format','{{index .Config.Labels "ct-alt.test"}}'],{encoding:'utf8'});if(own.status!==0||own.stdout.trim()!==f.fixtureLabel)throw Error('Owned database label mismatch');const r=spawnSync('docker',['exec','-i',db,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{input,encoding:'utf8',timeout:30000});if(r.error||r.status!==0)throw Error(r.error?.message||r.stderr);return r.stdout.trim();}
function baseline(){const tables=sql("select schemaname||'.'||tablename from pg_tables where schemaname in('public','workforce_private','chat_private')and tablename not in('work_requests','work_request_audit','request_operations')order by 1").split('\n');if(tables.some(t=>!/^(public|workforce_private|chat_private)\.[a-z_]+$/.test(t)))throw Error('Unexpected table name');return sql('select jsonb_object_agg(name,hash)from('+tables.map(t=>`select ${quote(t)}name,(select md5(coalesce(jsonb_agg(to_jsonb(x)order by to_jsonb(x)::text),'[]')::text)from ${t} x)hash`).join(' union all ')+')b');}
const functions=()=>sql("select md5(jsonb_agg(jsonb_build_array(p.oid,pg_get_functiondef(p.oid),p.proowner,p.proacl,p.proconfig)order by p.oid)::text)from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','workforce_private','chat_private')");
const publicState=()=>sql("select md5(jsonb_build_array((select jsonb_agg(to_jsonb(w)order by id)from public.work_requests w),(select jsonb_agg(to_jsonb(a)order by id)from public.work_request_audit a))::text)");
const operation=(change:RequestChange):RequestsMutation=>({tenantId:f.tenantA,operationId:randomUUID(),change});
const create=(title:string,extra:Partial<Extract<RequestChange,{action:'create'}>>={}):Extract<RequestChange,{action:'create'}>=>({action:'create',title,description:'Original synthetic work request 東京 😀',priority:'normal',dueDate:'2026-10-05',assigneeAgentId:null,assigneeActorId:null,...extra});
const query=(extra:Record<string,string>={},tenant=f.tenantA)=>'/api/requests?'+new URLSearchParams({tenantId:tenant,...extra});
function identity(value:{actorId:string;role:string;company?:{id:string};tenantId?:string},account='owner',role=f.accounts[account].role){expect(value).toMatchObject({actorId:f.accounts[account].id,role});expect(value.company?.id??value.tenantId).toBe(f.tenantA);}
async function login(page:Page,account='owner'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(f.accounts[account].email);await page.getByLabel('Password',{exact:true}).fill(f.accounts[account].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}
async function other(page:Page,account:string){const context=await page.context().browser()!.newContext({baseURL:origin}),p=await context.newPage();await login(p,account);return{context,page:p};}
async function board(request:APIRequestContext,extra:Record<string,string>={},account='owner'):Promise<RequestsBoardData>{const r=await request.get(query(extra));expect(r.status(),await r.text()).toBe(200);expect(r.headers()['cache-control']).toContain('no-store');const b=await r.json();identity(b,account);return b;}
async function detail(request:APIRequestContext,id:string,account='owner'):Promise<WorkRequest>{const r=await request.get(query({mode:'detail',requestId:id}));expect(r.status(),await r.text()).toBe(200);const d=await r.json();identity(d,account);expect(d.request.id).toBe(id);return d.request;}
const post=(request:APIRequestContext,value:RequestsMutation)=>request.post('/api/requests',{headers:{Origin:origin},data:value});
async function saved(request:APIRequestContext,value:RequestsMutation,account='owner'):Promise<RequestsSaved>{const r=await post(request,value);expect(r.status(),await r.text()).toBe(200);const b=await r.json();expect(Object.keys(b)).toEqual(['saved']);identity(b.saved,account);expect(b.saved).toMatchObject({schemaVersion:1,operationId:value.operationId,action:value.change.action,revision:value.change.action==='create'?1:value.change.revision+1});return b.saved;}
const reconcile=(request:APIRequestContext,value:RequestsMutation)=>request.post('/api/requests',{headers:{Origin:origin},data:{mode:'reconcile',tenantId:value.tenantId,operationId:value.operationId,action:value.change.action}});
function tx(input:string){sql('select 1');const child=spawn('docker',['exec','-i',db,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{stdio:['pipe','pipe','pipe']});let error='';child.stderr.on('data',b=>error+=b);child.stdout.resume();const done=new Promise<void>((resolve,reject)=>{child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(Error(error)));});child.stdin.end(input);return{done};}
async function sleepBarrier(){await expect.poll(()=>sql("select count(*)from pg_stat_activity where datname=current_database()and wait_event='PgSleep'and pid<>pg_backend_pid()"),{timeout:15000}).not.toBe('0');}
const edit=(w:WorkRequest,extra:Partial<Extract<RequestChange,{action:'edit'}>>={}):Extract<RequestChange,{action:'edit'}>=>({action:'edit',requestId:w.id,revision:w.revision,title:w.title,description:w.description,priority:w.priority,dueDate:w.dueDate,assigneeAgentId:w.assignee?.agentId??null,assigneeActorId:w.assignee?.actorId??null,...extra});
test.beforeAll(()=>{employeeAgent=sql(`select id from public.agents where tenant_id='${f.tenantA}'and user_id='${f.accounts.employee.id}'`);replacementAgent=randomUUID();sql(`insert into public.agents(id,tenant_id,first_name,last_name,phone,custom_fields,created_by)values('${replacementAgent}','${f.tenantA}','Synthetic','replacement Requests','+447700901899','{"client":"Demo client"}','${f.accounts.owner.id}')`);originalRows=baseline();originalFunctions=functions();});
test.afterAll(()=>{if(originalRows){expect(baseline()).toBe(originalRows);expect(functions()).toBe(originalFunctions);}});

test('signed roles see only their requested/currently assigned cards; requester New editing and management assignment are distinct',async({page})=>{
 expect((await page.request.get(query())).status()).toBe(401);await login(page);privateRequest=await saved(page.request,operation(create('Owner private original 東京')));assignedRequest=await saved(page.request,operation(create('Owner assigned employee',{assigneeAgentId:employeeAgent,assigneeActorId:f.accounts.employee.id})));expect((await board(page.request)).counts.total).toBe(2);
 for(const account of['admin','manager','employee','foreign']){const o=await other(page,account);try{const r=await o.page.request.get(query());expect(r.status()).toBe(account==='foreign'?403:200);if(account==='foreign'){expect((await o.page.request.get(query({mode:'detail',requestId:privateRequest.requestId}))).status()).toBe(403);continue;}const b=await r.json();identity(b,account);expect(b.capabilities.canManage).toBe(account==='admin');expect(b.counts.total).toBe(account==='admin'?2:account==='employee'?1:0);if(account!=='admin'){expect((await o.page.request.get(query({mode:'detail',requestId:privateRequest.requestId}))).status()).toBe(403);expect((await o.page.request.get(query({mode:'assignees'}))).status()).toBe(403);}
 if(account==='employee'){const originalCreate=operation(create('Employee original requester')),own=await saved(o.page.request,originalCreate,account);const d=await detail(o.page.request,own.requestId,account);const changed=await saved(o.page.request,operation(edit(d,{title:'Employee edited own New'})),account);expect(changed.revision).toBe(2);expect((await post(o.page.request,operation({action:'move',requestId:changed.requestId,revision:2,status:'done'}))).status()).toBe(403);expect((await post(o.page.request,operation(create('Unauthorized assignment',{assigneeAgentId:employeeAgent,assigneeActorId:f.accounts.employee.id})))).status()).toBe(403);const current=await detail(page.request,own.requestId);await saved(page.request,operation(edit(current,{assigneeAgentId:employeeAgent,assigneeActorId:f.accounts.employee.id})));expect((await post(o.page.request,originalCreate)).status()).toBe(403);expect((await detail(page.request,own.requestId)).revision).toBe(3);}
 await o.page.goto('/requests?company='+f.tenantA);await expect(o.page.getByRole('heading',{name:'Requests',exact:true})).toBeVisible();if(account==='manager')await expect(o.page.getByRole('button',{name:'Owner private original 東京',exact:true})).toHaveCount(0);
 }finally{await o.context.close();}}
 expect((await page.request.get(query({},f.tenantB))).status()).toBe(403);const auth=await page.request.post(f.url+'/auth/v1/token?grant_type=password',{headers:{apikey:f.key},data:{email:f.accounts.employee.email,password:f.accounts.employee.password}});expect(auth.status()).toBe(200);const token=(await auth.json()).access_token,r=await page.request.get(f.url+'/rest/v1/work_requests?select=id,title',{headers:{apikey:f.key,Authorization:'Bearer '+token}});expect(r.status()).toBe(200);expect((await r.json()).some((w:{id:string})=>w.id===privateRequest.requestId)).toBe(false);expect((await page.request.post(f.url+'/rest/v1/work_requests',{headers:{apikey:f.key,Authorization:'Bearer '+token},data:{title:'Direct write'}})).status()).toBe(403);
});

test('exact counts and literal Unicode search span1005 precise tied records; cursor query/actor/version fences reject stale pages',async({page})=>{
 await login(page);sql(`insert into public.work_requests(id,tenant_id,title,description,priority,status,revision,requester_id,requester_name,created_at,updated_at)select ('bb000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'${f.tenantA}',${quote('Literal %_\\ 東京 İ BULK ')}||lpad(i::text,4,'0'),'Synthetic bounded exact population','normal','new',1,'${f.accounts.owner.id}','Synthetic owner','2026-10-04T00:00:00Z'::timestamptz+floor(i/2)*interval'1 microsecond','2026-10-04T00:00:00Z'::timestamptz+floor(i/2)*interval'1 microsecond'from generate_series(1,1005)i;insert into public.work_request_audit(tenant_id,request_id,actor_id,action,revision,status)select tenant_id,id,requester_id,'create',1,status from public.work_requests where id::text like'bb000000-%';`);
 const search='literal %_\\ 東京',b=await board(page.request,{search,limit:'50'});expect(b.counts).toEqual({new:1005,in_progress:0,done:0,total:1005});expect(b.columns.new.requests).toHaveLength(50);const firstCursor=b.columns.new.nextCursor!;let cursor:string|null=firstCursor;const all=[...b.columns.new.requests];while(cursor){const r:APIResponse=await page.request.get(query({mode:'column',status:'new',search,limit:'50',cursor}));expect(r.status(),await r.text()).toBe(200);const d:RequestsColumnData=await r.json();expect(d.counts.total).toBe(1005);all.push(...d.requests);cursor=d.nextCursor;expect(all.length).toBeLessThanOrEqual(1005);}expect(new Set(all.map(w=>w.id)).size).toBe(1005);const expected=JSON.parse(sql("select jsonb_agg(id order by created_at desc,id desc)from public.work_requests where id::text like'bb000000-%'"));expect(all.map(w=>w.id)).toEqual(expected);expect(all.some(w=>/\.000001Z$/.test(w.createdAt))).toBe(true);
 for(const changed of[{search:'different'},{status:'done'}])expect((await page.request.get(query({mode:'column',status:'new',search,limit:'50',cursor:firstCursor,...changed}))).status()).toBe(409);const admin=await other(page,'admin');try{expect((await admin.page.request.get(query({mode:'column',status:'new',search,limit:'50',cursor:firstCursor}))).status()).toBe(409);}finally{await admin.context.close();}
 await saved(page.request,operation(create('Literal %_\\ 東京 arrived')));expect((await page.request.get(query({mode:'column',status:'new',search,limit:'50',cursor:firstCursor}))).status()).toBe(409);expect((await board(page.request,{search})).counts.total).toBe(1006);
});

test('same UUID is one card/audit, stale edits and invalid calendars/bodies are atomic, and assignees bind both current identities',async({page})=>{
 await login(page);const op=operation(create('Exact receipt safety',{dueDate:'2028-02-29',priority:'high'}));const a=await saved(page.request,op);expect(await saved(page.request,op)).toEqual(a);expect(sql(`select count(*)from public.work_request_audit where request_id='${a.requestId}'`)).toBe('1');expect((await post(page.request,{...op,change:create('Changed UUID payload')})).status()).toBe(409);const d=await detail(page.request,a.requestId);expect(d.dueDate).toBe('2028-02-29');await saved(page.request,operation(edit(d,{description:'Confirmed new text'})));expect((await post(page.request,operation(edit(d,{description:'Stale overwrite'})))).status()).toBe(409);expect((await detail(page.request,a.requestId)).description).toBe('Confirmed new text');
 const before=publicState();expect((await post(page.request,operation(create('Bad date',{dueDate:'2026-02-30'})))).status()).toBe(400);expect((await page.request.post('/api/requests',{headers:{Origin:'https://foreign.invalid'},data:operation(create('Bad Origin'))})).status()).toBe(403);expect((await page.request.get(query({mode:'board',status:'new'}))).status()).toBe(400);expect((await page.request.get(query()+'&tenantId='+f.tenantA)).status()).toBe(400);expect((await page.request.post('/api/requests',{headers:{Origin:origin},data:{...operation(create('Bad identity')),actorId:f.accounts.owner.id}})).status()).toBe(400);expect((await page.request.post('/api/requests',{headers:{Origin:origin,'Content-Type':'application/json'},data:Buffer.from('{"change":"'+ 'x'.repeat(41000)+'"}')})).status()).toBe(413);expect(publicState()).toBe(before);
 const unavailable=operation(create('Mismatched assignee',{assigneeAgentId:employeeAgent,assigneeActorId:f.accounts.manager.id}));expect((await post(page.request,unavailable)).status()).toBe(403);
});

test('archived/relinked/suspended assignees lose old-cookie move/read/receipt access while requester/management retain resolution',async({page})=>{
 await login(page);const employee=await other(page,'employee');try{const w=await detail(employee.page.request,assignedRequest.requestId,'employee'),op=operation({action:'move',requestId:w.id,revision:w.revision,status:'in_progress'});const ack=await saved(employee.page.request,op,'employee');for(const [change,restore]of[[`update public.agents set status='archived'where id='${employeeAgent}'`,`update public.agents set status='active'where id='${employeeAgent}'`],[`update public.agents set user_id=null where id='${employeeAgent}';update public.agents set user_id='${f.accounts.employee.id}'where id='${replacementAgent}'`,`update public.agents set user_id=null where id='${replacementAgent}';update public.agents set user_id='${f.accounts.employee.id}'where id='${employeeAgent}'`],[`update public.tenant_memberships set status='suspended'where tenant_id='${f.tenantA}'and user_id='${f.accounts.employee.id}'`,`update public.tenant_memberships set status='active'where tenant_id='${f.tenantA}'and user_id='${f.accounts.employee.id}'`]]){sql(change);try{expect((await employee.page.request.get(query({mode:'detail',requestId:w.id}))).status()).toBe(403);expect((await post(employee.page.request,op)).status()).toBe(403);expect((await reconcile(employee.page.request,op)).status()).toBe(403);expect((await detail(page.request,w.id)).assignee?.eligible).toBe(false);}finally{sql(restore);}}expect(await saved(employee.page.request,op,'employee')).toEqual(ack);}finally{await employee.context.close();}
 const admin=await other(page,'admin');try{const w=await detail(page.request,privateRequest.requestId),op=operation(edit(w,{title:'Owner card triaged by admin'}));await saved(admin.page.request,op,'admin');sql(`update public.tenant_memberships set role='employee'where tenant_id='${f.tenantA}'and user_id='${f.accounts.admin.id}'`);try{expect((await post(admin.page.request,op)).status()).toBe(403);const r=await admin.page.request.get(query());expect(r.status()).toBe(200);expect((await r.json()).counts.total).toBe(0);}finally{sql(`update public.tenant_memberships set role='admin'where tenant_id='${f.tenantA}'and user_id='${f.accounts.admin.id}'`);}}finally{await admin.context.close();}
});

test('a real STABLE read held after initial identity cannot release data after original Auth confirmation revocation',async({page})=>{
 await login(page);const signature='public.read_requests(uuid,text,text,integer,text,jsonb,uuid)',definition=sql(`select pg_get_functiondef('${signature}'::regprocedure)`),marker='identity:=public.read_requests_access(target_tenant,read_mode,detail_id);',confirmed=sql(`select email_confirmed_at from auth.users where id='${f.accounts.owner.id}'`);expect(definition.split(marker)).toHaveLength(2);sql(definition.replace(marker,marker+'perform pg_sleep(2.5);'));const pending=page.request.get(query({search:'Owner'}));try{await sleepBarrier();sql(`update auth.users set email_confirmed_at=null where id='${f.accounts.owner.id}'`);const r=await pending;expect(r.status(),await r.text()).toBe(403);expect(Object.keys(await r.json())).toEqual(['error']);}finally{await pending.catch(()=>{});sql(`update auth.users set email_confirmed_at=${quote(confirmed)} where id='${f.accounts.owner.id}'`);sql(definition);expect(sql(`select pg_get_functiondef('${signature}'::regprocedure)`)).toBe(definition);}
});

test('genuinely uncommitted writes reconcile after commit/rollback; authoritative absence fences delayed HTTP and current revocation after mutex wait',async({page})=>{
 await login(page);for(const commit of[true,false]){const op=operation(create('Real pending transaction '+commit)),t=tx(`begin;set role authenticated;select set_config('request.jwt.claim.sub','${f.accounts.owner.id}',false);select public.save_request('${f.tenantA}','${op.operationId}',${quote(JSON.stringify(op.change))});select pg_sleep(2.5);${commit?'commit':'rollback'};`);await sleepBarrier();let finished=false;const pending=reconcile(page.request,op).then(r=>{finished=true;return r;});await page.waitForTimeout(100);expect(finished).toBe(false);await t.done;const r=await pending;expect(r.status(),await r.text()).toBe(200);const d=await r.json();identity(d);expect(d.status).toBe(commit?'recorded':'not_recorded');if(!commit){expect(d.saved).toBe(null);expect((await post(page.request,op)).status()).toBe(409);}}
 const op=operation(create('Delayed before database')),state=publicState();let held:import('@playwright/test').Route|undefined;await page.route('**/api/requests',async r=>{if(r.request().method()==='POST'&&!r.request().postDataJSON().mode)held=r;else await r.continue();});const pending=page.evaluate(async value=>{const r=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});return r.status;},op);await expect.poll(()=>!!held).toBe(true);const closed=await reconcile(page.request,op);expect(closed.status()).toBe(200);expect((await closed.json()).status).toBe('not_recorded');expect(JSON.parse(sql(`select to_jsonb(o)from workforce_private.request_operations o where actor_id='${f.accounts.owner.id}'and operation_id='${op.operationId}'`))).toMatchObject({state:'closed_absent',payload_hash:null,result:null,request_id:null});await held!.continue();expect(await pending).toBe(409);expect(publicState()).toBe(state);expect((await reconcile(page.request,op)).status()).toBe(200);expect((await page.request.post('/api/requests',{headers:{Origin:origin},data:{mode:'reconcile',tenantId:f.tenantA,operationId:op.operationId,action:'edit'}})).status()).toBe(409);await page.unroute('**/api/requests');await saved(page.request,{...op,operationId:randomUUID()});
 const revoked=operation(create('Waiting current scope')),lock=tx(`begin;select pg_advisory_xact_lock(hashtextextended('${f.accounts.owner.id}:${revoked.operationId}',90));select pg_sleep(2.5);commit;`);await sleepBarrier();const waiting=reconcile(page.request,revoked);sql(`update public.tenant_memberships set status='suspended'where tenant_id='${f.tenantA}'and user_id='${f.accounts.owner.id}'`);try{await lock.done;expect((await waiting).status()).toBe(403);}finally{await waiting.catch(()=>{});sql(`update public.tenant_memberships set status='active'where tenant_id='${f.tenantA}'and user_id='${f.accounts.owner.id}'`);}
});

async function app(page:Page){await login(page);await page.goto('/requests?company='+f.tenantA);await expect(page.getByRole('heading',{name:'Requests',exact:true})).toBeVisible();}
async function searchUI(page:Page,text:string){await page.getByRole('textbox',{name:'Search requests',exact:true}).fill(text);const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/requests'&&r.request().method()==='GET'&&new URL(r.url()).searchParams.get('search')===text);await page.getByRole('button',{name:'Search',exact:true}).click();expect((await pending).status()).toBe(200);}
async function force(button:import('@playwright/test').Locator){await button.evaluate(el=>{const key=Object.keys(el).find(k=>k.startsWith('__reactProps$')),p=key?(el as unknown as Record<string,{onClick?:(v:unknown)=>void}>)[key]:undefined;if(typeof p?.onClick!=='function')throw Error('Actual React handler missing');p.onClick({preventDefault(){},stopPropagation(){},currentTarget:el,target:el});});}
async function cleanCapture(page:Page){await page.evaluate(async()=>{await document.fonts.ready;if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo(0,0);await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});await page.screenshot({path:'test-results/requests-live-desktop-review.png',fullPage:true});}
test('desktop create/edit/assignee, real keyboard and native drag moves, search counts and paging all reflect signed persisted state',async({page})=>{
 await app(page);await page.getByRole('button',{name:'Create request',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Create request',exact:true});await dialog.getByLabel('Title',{exact:true}).fill('Desktop actionable original 東京');await dialog.getByLabel('Description',{exact:true}).fill('Real signed desktop assignment and board move');await dialog.getByLabel('Priority',{exact:true}).selectOption('high');await dialog.getByLabel('Due date',{exact:true}).fill('2026-10-06');await dialog.getByRole('textbox',{name:'Search assignees',exact:true}).fill('employee');const roster=page.waitForResponse(r=>new URL(r.url()).searchParams.get('mode')==='assignees');await dialog.getByRole('button',{name:'Find users',exact:true}).click();expect((await roster).status()).toBe(200);await dialog.getByRole('button',{name:'Synthetic employee',exact:true}).click();const ack=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/requests'&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Save request',exact:true}).click();const raw=await ack;expect(raw.status(),await raw.text()).toBe(200);const card=(await raw.json()).saved;await expect(dialog).toHaveCount(0);await searchUI(page,'Desktop actionable');await expect(page.getByRole('button',{name:'Desktop actionable original 東京',exact:true})).toBeVisible();const dropdown=page.getByLabel('Status for Desktop actionable original 東京',{exact:true});await dropdown.focus();const moved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/requests'&&r.request().method()==='POST');await dropdown.press('ArrowDown');await dropdown.press('Enter');expect((await moved).status()).toBe(200);await expect(page.getByRole('region',{name:'In progress',exact:true}).getByRole('button',{name:'Desktop actionable original 東京',exact:true})).toBeVisible();const dragged=page.locator('.requests-card').filter({has:page.getByRole('button',{name:'Desktop actionable original 東京',exact:true})}),done=page.getByRole('region',{name:'Done',exact:true});const dropped=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/requests'&&r.request().method()==='POST');await dragged.dragTo(done);expect((await dropped).status()).toBe(200);await expect(done.getByRole('button',{name:'Desktop actionable original 東京',exact:true})).toBeVisible();expect((await detail(page.request,card.requestId)).status).toBe('done');
 const opened=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/requests'&&r.request().method()==='GET'&&new URL(r.url()).searchParams.get('mode')==='detail'&&new URL(r.url()).searchParams.get('requestId')===card.requestId);await done.getByRole('button',{name:'Desktop actionable original 東京',exact:true}).click();const leaf=await opened;expect(leaf.status(),await leaf.text()).toBe(200);const leafData=await leaf.json();identity(leafData);expect(leafData.request).toMatchObject({id:card.requestId,revision:3,status:'done',canEdit:true});const editDialog=page.getByRole('dialog',{name:'Edit request',exact:true});try{await expect(editDialog).toBeVisible({timeout:5000});}catch(cause){console.error('Owned signed request detail diagnostic',JSON.stringify({leaf:leafData,dom:await page.locator('.requests-page').evaluate(el=>({dialogHeadings:Array.from(el.querySelectorAll('[role=dialog] h2')).map(n=>n.textContent),alerts:Array.from(el.querySelectorAll('.requests-error')).map(n=>n.textContent),titleInputs:Array.from(el.querySelectorAll<HTMLInputElement>('[role=dialog] input')).map(n=>({value:n.value,disabled:n.disabled})),dialogHTML:el.querySelector('[role=dialog]')?.outerHTML}))}));throw cause;}console.log('Owned actual signed editor labels',JSON.stringify({exactLabelCount:await editDialog.getByLabel('Description',{exact:true}).count(),exactAccessibleTextboxCount:await editDialog.getByRole('textbox',{name:'Description',exact:true}).count(),textareaLabelText:await editDialog.locator('textarea').evaluate(el=>(el as HTMLTextAreaElement).labels?.[0]?.textContent)}));await editDialog.getByRole('textbox',{name:'Description',exact:true}).fill('Edited after actual drag acknowledgement');const edited=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/requests'&&r.request().method()==='POST');await editDialog.getByRole('button',{name:'Save request',exact:true}).click();expect((await edited).status()).toBe(200);await expect(editDialog).toHaveCount(0);expect((await detail(page.request,card.requestId)).description).toBe('Edited after actual drag acknowledgement');await cleanCapture(page);
 await searchUI(page,'BULK');const column=page.getByRole('region',{name:'New',exact:true});expect(await column.locator('.requests-card').count()).toBe(20);const more=page.waitForResponse(r=>new URL(r.url()).searchParams.get('mode')==='column');await column.getByRole('button',{name:'Load more new requests',exact:true}).click();expect((await more).status()).toBe(200);await expect(column.locator('.requests-card')).toHaveCount(40);await expect(page.getByLabel('New request count',{exact:true})).toHaveText('1005');
});

test('held real POST/decoded ACK guards React refresh and departure; persistent field-free recovery cannot unlock on failed reads or current denial',async({page})=>{
 await app(page);await page.getByRole('button',{name:'Create request',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Create request',exact:true});await dialog.getByLabel('Title',{exact:true}).fill('Held real request unknown');let held:import('@playwright/test').Route|undefined;await page.route('**/api/requests',async r=>{if(r.request().method()==='POST'&&!r.request().postDataJSON().mode)held=r;else await r.continue();});await dialog.getByRole('button',{name:'Save request',exact:true}).click();await expect.poll(()=>!!held).toBe(true);const payload=held!.request().postDataJSON(),key=`ct-alt:requests:v1:${f.accounts.owner.id}:${f.tenantA}`,marker=await page.evaluate(k=>sessionStorage.getItem(k),key);expect(JSON.parse(marker!)).toEqual({schemaVersion:1,operationId:payload.operationId,action:'create'});let requests=0;const listener=(r:import('@playwright/test').Request)=>{if(new URL(r.url()).pathname==='/api/requests')requests++;};page.on('request',listener);await force(page.getByRole('button',{name:'Refresh requests',exact:true}));await page.waitForTimeout(80);expect(requests).toBe(0);expect(await page.evaluate(k=>sessionStorage.getItem(k),key)).toBe(marker);
 await page.evaluate(()=>{const json=Response.prototype.json;Response.prototype.json=async function(){const data=await json.call(this);if(this.url.includes('/api/requests')&&data?.saved){(window as unknown as{heldRequestAck:unknown}).heldRequestAck=data;await new Promise<void>(resolve=>(window as unknown as{releaseRequestAck:()=>void}).releaseRequestAck=resolve);}return data;};});await held!.continue();await page.waitForFunction(()=>!!(window as unknown as{heldRequestAck:unknown}).heldRequestAck);expect(sql(`select state from workforce_private.request_operations where actor_id='${f.accounts.owner.id}'and operation_id='${payload.operationId}'`)).toBe('recorded');requests=0;await force(page.getByRole('button',{name:'Refresh requests',exact:true}));await page.waitForTimeout(80);expect(requests).toBe(0);// Force the genuine Next link's same-document departure while the modal correctly blocks background pointer clicks.
 await page.getByRole('link',{name:'Users',exact:true}).evaluate(el=>(el as HTMLAnchorElement).click());await expect(page).toHaveURL(/\/agents/);await expect(page.getByRole('heading',{name:'Requests',exact:true})).toHaveCount(0);await page.evaluate(()=>(window as unknown as{releaseRequestAck:()=>void}).releaseRequestAck());expect(await page.evaluate(k=>sessionStorage.getItem(k),key)).toBe(marker);page.off('request',listener);await page.unroute('**/api/requests');await page.goto('/requests?company='+f.tenantA);const review=page.getByRole('button',{name:'Review save outcome',exact:true}).first();await expect(review).toBeVisible();await expect(page.getByRole('button',{name:'Retry exact save',exact:true})).toHaveCount(0);let recoveryBody:unknown,failed=false;await page.route('**/api/requests**',async r=>{if(r.request().method()==='POST'){recoveryBody=r.request().postDataJSON();await r.continue();}else if(recoveryBody){failed=true;await r.fulfill({status:503,json:{error:'Owned current recovery read failure'}});}else await r.continue();});await review.click();await expect.poll(()=>failed).toBe(true);expect(recoveryBody).toEqual({mode:'reconcile',tenantId:f.tenantA,operationId:payload.operationId,action:'create'});expect(await page.evaluate(k=>sessionStorage.getItem(k),key)).toBe(marker);await expect(page.getByRole('button',{name:'Create request',exact:true})).toBeDisabled();await page.unroute('**/api/requests**');await review.click();await expect.poll(()=>page.evaluate(k=>sessionStorage.getItem(k),key)).toBe(null);await expect(page.getByRole('button',{name:'Create request',exact:true})).toBeEnabled();
 // Actual current denial must clear a verified visible private card, not merely disable a move.
 await expect(page.getByRole('button',{name:'Held real request unknown',exact:true})).toBeVisible();
 sql(`update public.tenant_memberships set status='suspended'where tenant_id='${f.tenantA}'and user_id='${f.accounts.owner.id}'`);try{await page.getByRole('button',{name:'Refresh requests',exact:true}).click();await expect(page.locator('.requests-card')).toHaveCount(0);await expect(page.getByRole('button',{name:'Create request',exact:true})).toBeDisabled();}finally{sql(`update public.tenant_memberships set status='active'where tenant_id='${f.tenantA}'and user_id='${f.accounts.owner.id}'`);}
});
