import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import type {RotaData,RotaShift,Schedule} from '../../lib/rota-types';

const fixture=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8'));
const origin='http://127.0.0.1:5180',database='supabase_db_ct-alt-independent';
if(fixture.url!=='http://127.0.0.1:54821'||!/^[0-9a-f]{8}$/.test(fixture.fixtureLabel))throw Error('Owned CT Alt loopback fixture required');
test.describe.configure({mode:'serial'});test.setTimeout(120000);
type Publication={tenantId:string;scheduleId:string;scheduleRevision:number;shifts:{id:string;revision:number}[]};
function sql(input:string){
 const owned=spawnSync('docker',['inspect',database,'--format','{{index .Config.Labels "ct-alt.test"}}'],{encoding:'utf8',timeout:10000});
 if(owned.status!==0||owned.stdout.trim()!==fixture.fixtureLabel)throw Error('Publication fixture ownership mismatch');
 const result=spawnSync('docker',['exec','-i',database,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{input,encoding:'utf8',timeout:30000});
 if(result.status!==0||result.error)throw Error(result.error?.message||result.stderr);return result.stdout.trim();
}
const quote=(value:string)=>"'"+value.replaceAll("'","''")+"'";
function functions(){return sql("select md5(jsonb_agg(jsonb_build_array(p.oid,pg_get_functiondef(p.oid),p.proowner,p.proacl,p.proconfig)order by p.oid)::text)from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','workforce_private','chat_private')");}
function permissions(){return sql("select md5(jsonb_agg(jsonb_build_object('oid',c.oid,'name',n.nspname||'.'||c.relname,'owner',c.relowner,'acl',c.relacl,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'policies',(select jsonb_agg(to_jsonb(p)order by p.oid)from pg_policy p where p.polrelid=c.oid))order by c.oid)::text)from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='r'and n.nspname in('public','workforce_private','chat_private','auth','storage')");}
function unrelated(){const tables=sql("select schemaname||'.'||tablename from pg_tables where schemaname in('public','workforce_private','chat_private')and tablename not like'rota_%'order by 1").split('\n');return sql('select jsonb_object_agg(name,hash)from('+tables.map(table=>`select ${quote(table)}name,(select md5(coalesce(jsonb_agg(to_jsonb(x)order by to_jsonb(x)::text),'[]')::text)from ${table} x)hash`).join(' union all ')+')x');}
function retainedSchedule(id:string){return sql(`select jsonb_build_object('schedule',(select to_jsonb(s)from public.rota_schedules s where id='${id}'),'shifts',(select jsonb_agg(to_jsonb(s)order by id)from public.rota_shifts s where schedule_id='${id}'),'audits',(select count(*)from public.rota_audit where schedule_id='${id}'))`);}
let oldFunctions:string,oldRows:string,oldPermissions:string;
test.beforeAll(()=>{oldFunctions=functions();oldRows=unrelated();oldPermissions=permissions();});
test.afterAll(()=>{expect(functions()).toBe(oldFunctions);expect(unrelated()).toBe(oldRows);expect(permissions()).toBe(oldPermissions);});
async function login(page:Page,role='owner'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(fixture.accounts[role].email);await page.getByLabel('Password',{exact:true}).fill(fixture.accounts[role].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}
async function other(page:Page,role:string){const context=await page.context().browser()!.newContext({baseURL:origin});const signed=await context.newPage();await login(signed,role);return{context,page:signed};}
async function rotas(request:APIRequestContext):Promise<RotaData>{const response=await request.get('/api/rotas?tenantId='+fixture.tenantA);expect(response.status(),await response.text()).toBe(200);return response.json();}
async function legacy(request:APIRequestContext,change:unknown){const response=await request.post('/api/rotas',{headers:{Origin:origin},data:{tenantId:fixture.tenantA,change}});expect(response.status(),await response.text()).toBe(200);return response.json();}
async function setup(request:APIRequestContext,name:string){const data=await rotas(request),employee=data.agents.find(a=>a.last_name==='employee')!.id,manager=data.agents.find(a=>a.last_name==='manager')!.id;await legacy(request,{action:'create_schedule',name,time_zone:'UTC',agent_ids:[employee,manager],admin_ids:[fixture.accounts.manager.id]});let current=await rotas(request);const schedule=current.schedules.find(s=>s.name===name)!;await legacy(request,{action:'add_job',schedule_id:schedule.id,revision:schedule.revision,name:'Reception cover',color:'#3487ee'});current=await rotas(request);return{schedule:current.schedules.find(s=>s.id===schedule.id)!,job:current.jobs.find(j=>j.schedule_id===schedule.id)!,employee,manager};}
async function shift(request:APIRequestContext,scheduleId:string,jobId:string,agentId:string,title:string,start:string,end:string){const data=await rotas(request),schedule=data.schedules.find(s=>s.id===scheduleId)!;await legacy(request,{action:'save_shift',schedule_id:scheduleId,revision:schedule.revision,agent_id:agentId,job_id:jobId,title,starts_at:start,ends_at:end,allow_overlap:true});return(await rotas(request)).shifts.find(s=>s.schedule_id===scheduleId&&s.title===title)!;}
async function subset(request:APIRequestContext,scheduleId:string,rows:RotaShift[]):Promise<Publication>{const current=await rotas(request);return{tenantId:fixture.tenantA,scheduleId,scheduleRevision:current.schedules.find(s=>s.id===scheduleId)!.revision,shifts:rows.map(s=>({id:s.id,revision:s.revision}))};}
const publish=(request:APIRequestContext,value:unknown)=>request.post('/api/rota-publication',{headers:{Origin:origin},data:value});
async function acknowledged(request:APIRequestContext,value:Publication,role='owner'){
 const response=await publish(request,value);expect(response.status(),await response.text()).toBe(200);expect(response.headers()['cache-control']).toContain('no-store');const body=await response.json();expect(Object.keys(body)).toEqual(['saved']);expect(body.saved).toMatchObject({schemaVersion:1,tenantId:fixture.tenantA,actorId:fixture.accounts[role].id,schedule_id:value.scheduleId,schedule_revision:value.scheduleRevision+1,published_count:value.shifts.length});expect([...body.saved.shifts].sort((a,b)=>a.id.localeCompare(b.id))).toEqual(value.shifts.map(s=>({id:s.id,revision:s.revision+1})).sort((a,b)=>a.id.localeCompare(b.id)));return body.saved;
}
async function openSchedule(page:Page,schedule:Schedule,date='2026-10-24'){await page.goto('/rotas?company='+fixture.tenantA);await expect(page.getByText('Loading schedules…')).not.toBeVisible();await page.getByRole('button',{name:schedule.name,exact:true}).click();await expect(page.getByRole('heading',{name:schedule.name,exact:true})).toBeVisible();await page.getByLabel('Date',{exact:true}).fill(date);}
async function confirm(page:Page,count:number){await page.getByRole('button',{name:`Publish (${count})`,exact:true}).click();const dialog=page.getByRole('dialog',{name:'Publish draft shifts',exact:true});await expect(dialog).toBeVisible();return dialog;}

test('current owner admin and delegated manager publish exact private subsets',async({page})=>{
 await login(page);for(const role of['owner','admin','manager']){const s=await setup(page.request,'Publication role '+role),selected=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Selected '+role,'2026-11-01T09:00:00Z','2026-11-01T17:00:00Z'),hidden=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Hidden '+role,'2026-11-08T09:00:00Z','2026-11-08T17:00:00Z'),user=role==='owner'?null:await other(page,role);try{await acknowledged(user?.page.request||page.request,await subset(page.request,s.schedule.id,[selected]),role);const data=await rotas(page.request);expect(data.shifts.find(x=>x.id===selected.id)).toMatchObject({status:'published',revision:selected.revision+1});expect(data.shifts.find(x=>x.id===hidden.id)).toEqual(hidden);}finally{await user?.context.close();}}
});
test('employee foreign and revoked manager receive field-free denial without writes',async({page})=>{
 await login(page);const s=await setup(page.request,'Publication denial'),draft=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Denied draft','2026-11-02T09:00:00Z','2026-11-02T17:00:00Z'),value=await subset(page.request,s.schedule.id,[draft]),before=retainedSchedule(s.schedule.id);
 for(const role of['employee','foreign','manager']){const signed=await other(page,role);try{if(role==='manager')sql(`delete from public.rota_admins where schedule_id='${s.schedule.id}'and user_id='${fixture.accounts.manager.id}'`);const response=await publish(signed.page.request,value);expect(response.status()).toBe(403);expect(Object.keys(await response.json())).toEqual(['error']);expect(retainedSchedule(s.schedule.id)).toBe(before);}finally{if(role==='manager')sql(`insert into public.rota_admins values('${fixture.tenantA}','${s.schedule.id}','${fixture.accounts.manager.id}')`);await signed.context.close();}}
 expect(sql("select has_table_privilege('authenticated','public.rota_shifts','UPDATE')")).toBe('f');
});
test('invalid subsets and stale revisions reject atomically including a foreign-schedule member',async({page})=>{
 await login(page);const s=await setup(page.request,'Atomic publication'),a=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Atomic A','2026-11-03T09:00:00Z','2026-11-03T12:00:00Z'),b=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Atomic B','2026-11-03T12:00:00Z','2026-11-03T17:00:00Z'),otherSchedule=await setup(page.request,'Atomic other'),foreign=await shift(page.request,otherSchedule.schedule.id,otherSchedule.job.id,otherSchedule.employee,'Other schedule draft','2026-11-04T09:00:00Z','2026-11-04T17:00:00Z'),value=await subset(page.request,s.schedule.id,[a,b]),before=retainedSchedule(s.schedule.id);
 for(const invalid of[{...value,shifts:[]},{...value,shifts:[value.shifts[0],value.shifts[0]]},{...value,shifts:[value.shifts[0],{id:foreign.id,revision:foreign.revision}]},{...value,scheduleRevision:value.scheduleRevision-1},{...value,shifts:[value.shifts[0],{id:b.id,revision:b.revision+1}]},{...value,privileged:true}]){const response=await publish(page.request,invalid);expect(response.status()).toBeGreaterThanOrEqual(400);expect(response.status()).toBeLessThan(500);expect(Object.keys(await response.json())).toEqual(['error']);expect(retainedSchedule(s.schedule.id)).toBe(before);}
 await acknowledged(page.request,value);expect((await publish(page.request,value)).status()).toBe(409);expect(sql(`select count(*)from public.rota_audit where schedule_id='${s.schedule.id}'and action='publish'`)).toBe('1');
});
test('frozen displayed filters exclude other jobs workers dates and deduplicate overnight cells',async({page})=>{
 await login(page);const s=await setup(page.request,'Displayed publication'),overnight=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Displayed overnight','2026-10-23T23:00:00Z','2026-10-24T07:00:00Z'),morning=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Displayed morning','2026-10-24T09:00:00Z','2026-10-24T17:00:00Z'),coworker=await shift(page.request,s.schedule.id,s.job.id,s.manager,'Hidden worker','2026-10-24T09:00:00Z','2026-10-24T17:00:00Z'),outside=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Hidden outside period','2026-11-08T09:00:00Z','2026-11-08T17:00:00Z');
 let current=await rotas(page.request);await legacy(page.request,{action:'add_job',schedule_id:s.schedule.id,revision:current.schedules.find(x=>x.id===s.schedule.id)!.revision,name:'Facilities cover',color:'#285c4c'});current=await rotas(page.request);const otherJob=current.jobs.find(j=>j.schedule_id===s.schedule.id&&j.name==='Facilities cover')!,different=await shift(page.request,s.schedule.id,otherJob.id,s.employee,'Hidden job','2026-10-24T17:00:00Z','2026-10-24T20:00:00Z');
 await openSchedule(page,s.schedule);await page.locator('summary').filter({hasText:'Filters'}).click();await page.getByRole('combobox',{name:'Job',exact:true}).selectOption(s.job.id);await page.getByRole('combobox',{name:'Shift status',exact:true}).selectOption('draft');await page.locator('summary').filter({hasText:'Filters'}).click();await page.getByLabel('Search users',{exact:true}).fill('employee');await expect(page.getByRole('button',{name:/Edit draft Displayed overnight/})).toHaveCount(2);
 const submitted:Publication[]=[];await page.route('**/api/rota-publication',async route=>{submitted.push(route.request().postDataJSON());await route.continue();});const dialog=await confirm(page,2);await expect(dialog).toContainText('employee');await expect(dialog).toContainText('Reception cover');if(process.env.CT_ALT_PUBLICATION_CAPTURE==='1')await page.screenshot({path:'/workspace/scratch/ct-alt-publication-confirmation.png',fullPage:true});await dialog.getByRole('button',{name:'Publish displayed drafts',exact:true}).click();await expect(dialog).not.toBeVisible();expect(submitted).toHaveLength(1);expect(submitted[0].shifts.map(x=>x.id).sort()).toEqual([overnight.id,morning.id].sort());expect(new Set(submitted[0].shifts.map(x=>x.id)).size).toBe(2);const after=await rotas(page.request);for(const selected of[overnight,morning])expect(after.shifts.find(x=>x.id===selected.id)?.status).toBe('published');for(const hidden of[coworker,outside,different])expect(after.shifts.find(x=>x.id===hidden.id)).toEqual(hidden);await page.unroute('**/api/rota-publication');
});
test('employee sees only selected own publication while coworker and unselected drafts stay hidden',async({page})=>{
 await login(page);const s=await setup(page.request,'Employee subset visibility'),own=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Visible own','2026-11-10T09:00:00Z','2026-11-10T17:00:00Z'),privateOwn=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Private own','2026-11-11T09:00:00Z','2026-11-11T17:00:00Z'),coworker=await shift(page.request,s.schedule.id,s.job.id,s.manager,'Published coworker','2026-11-10T09:00:00Z','2026-11-10T17:00:00Z'),employee=await other(page,'employee');try{expect((await rotas(employee.page.request)).shifts.some(x=>[own.id,privateOwn.id,coworker.id].includes(x.id))).toBe(false);await acknowledged(page.request,await subset(page.request,s.schedule.id,[own,coworker]));expect((await rotas(employee.page.request)).shifts.filter(x=>x.schedule_id===s.schedule.id).map(x=>x.id)).toEqual([own.id]);}finally{await employee.context.close();}
});
test('revoked linked access and inactive workers reject atomically while roster removal is constrained',async({page})=>{
 await login(page);const s=await setup(page.request,'Worker fence'),a=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Worker A','2026-11-12T09:00:00Z','2026-11-12T17:00:00Z'),b=await shift(page.request,s.schedule.id,s.job.id,s.manager,'Worker B','2026-11-12T09:00:00Z','2026-11-12T17:00:00Z'),value=await subset(page.request,s.schedule.id,[a,b]),before=retainedSchedule(s.schedule.id);
 const invalidations=[
  ["update public.tenant_memberships set status='suspended'where tenant_id='"+fixture.tenantA+"'and user_id='"+fixture.accounts.employee.id+"'","update public.tenant_memberships set status='active'where tenant_id='"+fixture.tenantA+"'and user_id='"+fixture.accounts.employee.id+"'"],
  ["update public.agents set status='archived'where id='"+s.employee+"'","update public.agents set status='active'where id='"+s.employee+"'"]
 ];
 for(const [invalidate,restore]of invalidations){sql(invalidate);try{const response=await publish(page.request,value);expect(response.status()).toBeGreaterThanOrEqual(400);expect(response.status()).toBeLessThan(500);expect(retainedSchedule(s.schedule.id)).toBe(before);}finally{sql(restore);}}
 expect(()=>sql(`delete from public.rota_agents where schedule_id='${s.schedule.id}'and agent_id='${s.employee}'`)).toThrow(/foreign key constraint/);expect(retainedSchedule(s.schedule.id)).toBe(before);
});
test('legacy all-schedule publication still includes explicitly requested out-of-period drafts',async({page})=>{
 await login(page);const s=await setup(page.request,'Legacy publication unchanged'),a=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Legacy displayed','2026-11-13T09:00:00Z','2026-11-13T17:00:00Z'),b=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Legacy distant','2027-01-13T09:00:00Z','2027-01-13T17:00:00Z');await legacy(page.request,{action:'publish',schedule_id:s.schedule.id,revision:(await rotas(page.request)).schedules.find(x=>x.id===s.schedule.id)!.revision});const data=await rotas(page.request);for(const x of[a,b])expect(data.shifts.find(y=>y.id===x.id)?.status).toBe('published');
});
test('held genuine publication ACK locks confirmation and scheduling writes',async({page})=>{
 await login(page);const s=await setup(page.request,'Held publication'),draft=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Held selected','2026-10-24T09:00:00Z','2026-10-24T17:00:00Z');await openSchedule(page,s.schedule);const dialog=await confirm(page,1);let release!:()=>void,observed!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>observed=resolve);let requests=0;await page.route('**/api/rota-publication',async route=>{requests++;const response=await route.fetch();expect(response.status()).toBe(200);observed();await gate;await route.fulfill({response});});try{await dialog.getByRole('button',{name:'Publish displayed drafts',exact:true}).click();await started;expect((await rotas(page.request)).shifts.find(x=>x.id===draft.id)?.status).toBe('published');await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Templates',exact:true})).toBeDisabled();release();await expect(dialog).not.toBeVisible();expect(requests).toBe(1);}finally{release();await page.unroute('**/api/rota-publication');}
});
test('lost genuine ACK requires manual reload without resending publication',async({page})=>{
 await login(page);const s=await setup(page.request,'Lost publication'),draft=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Lost selected','2026-10-24T09:00:00Z','2026-10-24T17:00:00Z');await openSchedule(page,s.schedule);const dialog=await confirm(page,1);let requests=0;await page.route('**/api/rota-publication',async route=>{requests++;const response=await route.fetch();expect(response.status()).toBe(200);await route.abort('failed');});await dialog.getByRole('button',{name:'Publish displayed drafts',exact:true}).click();await expect(dialog).toContainText('confirmation was lost');await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();expect((await rotas(page.request)).shifts.find(x=>x.id===draft.id)?.status).toBe('published');await dialog.getByRole('button',{name:'Reload schedules to review',exact:true}).click();await expect(dialog).not.toBeVisible();expect(requests).toBe(1);expect(sql(`select count(*)from public.rota_audit where schedule_id='${s.schedule.id}'and action='publish'`)).toBe('1');await page.unroute('**/api/rota-publication');
});
test('current denial fences a delayed genuine publication and an earlier successful read',async({page})=>{
 await login(page);const s=await setup(page.request,'Delayed denied publication'),draft=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Denied protected draft','2026-10-24T09:00:00Z','2026-10-24T17:00:00Z'),manager=await other(page,'manager');
 let release!:()=>void,observed!:()=>void,releaseRead!:()=>void,observedRead!:()=>void,finishedRead!:()=>void;
 const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>observed=resolve),readGate=new Promise<void>(resolve=>releaseRead=resolve),readStarted=new Promise<void>(resolve=>observedRead=resolve),readFinished=new Promise<void>(resolve=>finishedRead=resolve);
 try{
  await openSchedule(manager.page,s.schedule);await manager.page.getByRole('button',{name:'Templates',exact:true}).click();const templates=manager.page.getByRole('dialog',{name:'Shift Templates',exact:true});
  await manager.page.route('**/api/rotas?*',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);expect((await response.json()).shifts.some((x:RotaShift)=>x.id===draft.id)).toBe(true);observedRead();await readGate;try{await route.fulfill({response});}finally{finishedRead();}});
  await templates.getByRole('button',{name:'Refresh templates and schedules',exact:true}).click();await readStarted;await templates.getByRole('button',{name:'Close templates',exact:true}).click();
  const dialog=await confirm(manager.page,1);await manager.page.route('**/api/rota-publication',async route=>{observed();await gate;const response=await route.fetch();expect(response.status()).toBe(403);await route.fulfill({response});});await dialog.getByRole('button',{name:'Publish displayed drafts',exact:true}).click();await started;sql(`delete from public.rota_admins where schedule_id='${s.schedule.id}'and user_id='${fixture.accounts.manager.id}'`);release();await expect(dialog).not.toBeVisible();await expect(manager.page.getByText('Denied protected draft',{exact:true})).toHaveCount(0);
  releaseRead();await readFinished;await expect(manager.page.getByRole('button',{name:'Templates',exact:true})).toHaveCount(0);await expect(manager.page.getByRole('heading',{name:s.schedule.name,exact:true})).toHaveCount(0);await expect(manager.page.getByText('Denied protected draft',{exact:true})).toHaveCount(0);expect((await rotas(page.request)).shifts.find(x=>x.id===draft.id)).toEqual(draft);
 }finally{release?.();releaseRead?.();await manager.page.unroute('**/api/rota-publication');await manager.page.unroute('**/api/rotas?*');await manager.context.close();}
});
test('schedule changes after confirmation reject the frozen revision without publishing',async({page})=>{
 await login(page);const s=await setup(page.request,'Frozen revision publication'),draft=await shift(page.request,s.schedule.id,s.job.id,s.employee,'Frozen selected','2026-10-24T09:00:00Z','2026-10-24T17:00:00Z');await openSchedule(page,s.schedule);const dialog=await confirm(page,1),current=await rotas(page.request);await legacy(page.request,{action:'add_job',schedule_id:s.schedule.id,revision:current.schedules.find(x=>x.id===s.schedule.id)!.revision,name:'Changed after confirmation',color:'#285c4c'});const before=retainedSchedule(s.schedule.id);await dialog.getByRole('button',{name:'Publish displayed drafts',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible();expect(retainedSchedule(s.schedule.id)).toBe(before);expect((await rotas(page.request)).shifts.find(x=>x.id===draft.id)).toEqual(draft);
});
