import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {spawn,spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import type {RotaData,Schedule} from '../../lib/rota-types';
import type {RotaTemplateChange,RotaTemplateMutation,RotaTemplateData,RotaTemplateSaved} from '../../lib/rota-template-types';
const f=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8')),origin='http://127.0.0.1:5180',db='supabase_db_ct-alt-independent';
if(f.url!=='http://127.0.0.1:54821'||!/^[0-9a-f]{8}$/.test(f.fixtureLabel))throw Error('Owned loopback fixture required');
test.describe.configure({mode:'serial'});test.setTimeout(120000);test.use({viewport:{width:1444,height:960}});
const quote=(v:string)=>"'"+v.replaceAll("'","''")+"'";
function sql(input:string){const i=spawnSync('docker',['inspect',db,'--format','{{index .Config.Labels "ct-alt.test"}}'],{encoding:'utf8'});if(i.status!==0||i.stdout.trim()!==f.fixtureLabel)throw Error('Fixture ownership mismatch');const r=spawnSync('docker',['exec','-i',db,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{input,encoding:'utf8',timeout:30000});if(r.status!==0||r.error)throw Error(r.error?.message||r.stderr);return r.stdout.trim();}
function functions(){return sql("select md5(jsonb_agg(jsonb_build_array(p.oid,pg_get_functiondef(p.oid),p.proowner,p.proacl,p.proconfig)order by p.oid)::text)from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','workforce_private','chat_private')");}
function unrelated(){const tables=sql("select schemaname||'.'||tablename from pg_tables where schemaname in('public','workforce_private','chat_private')and tablename not like'rota_%'order by 1").split('\n');return sql('select jsonb_object_agg(name,hash)from('+tables.map(t=>`select ${quote(t)}name,(select md5(coalesce(jsonb_agg(to_jsonb(x)order by to_jsonb(x)::text),'[]')::text)from ${t} x)hash`).join(' union all ')+')x');}
async function login(page:Page,account='owner'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(f.accounts[account].email);await page.getByLabel('Password',{exact:true}).fill(f.accounts[account].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}
async function other(page:Page,account:string){const context=await page.context().browser()!.newContext({baseURL:origin}),p=await context.newPage();await login(p,account);return{context,page:p};}
async function rotas(r:APIRequestContext):Promise<RotaData>{const response=await r.get('/api/rotas?tenantId='+f.tenantA);expect(response.status(),await response.text()).toBe(200);return response.json();}
async function legacy(r:APIRequestContext,change:unknown){const response=await r.post('/api/rotas',{headers:{Origin:origin},data:{tenantId:f.tenantA,change}});expect(response.status(),await response.text()).toBe(200);}
async function list(r:APIRequestContext,sid:string,extra:Record<string,string>={}):Promise<RotaTemplateData>{const response=await r.get('/api/rota-templates?'+new URLSearchParams({tenantId:f.tenantA,scheduleId:sid,...extra}));expect(response.status(),await response.text()).toBe(200);expect(response.headers()['cache-control']).toContain('no-store');const b=await response.json();expect(b).toMatchObject({schemaVersion:1,tenantId:f.tenantA,schedule:{id:sid}});return b;}
const op=(change:RotaTemplateChange):RotaTemplateMutation=>({tenantId:f.tenantA,operationId:randomUUID(),change});
const post=(r:APIRequestContext,v:RotaTemplateMutation)=>r.post('/api/rota-templates',{headers:{Origin:origin},data:v});
async function saved(r:APIRequestContext,v:RotaTemplateMutation,account='owner'):Promise<RotaTemplateSaved>{const response=await post(r,v);expect(response.status(),await response.text()).toBe(200);expect(response.headers()['cache-control']).toContain('no-store');const b=await response.json();expect(Object.keys(b)).toEqual(['saved']);expect(b.saved).toMatchObject({actorId:f.accounts[account].id,tenantId:f.tenantA,operationId:v.operationId,action:v.change.action,schedule_id:v.change.schedule_id,schedule_revision:v.change.schedule_revision+1});return b.saved;}
const recover=(r:APIRequestContext,v:RotaTemplateMutation)=>r.post('/api/rota-templates',{headers:{Origin:origin},data:{mode:'reconcile',tenantId:v.tenantId,operationId:v.operationId,action:v.change.action,scheduleId:v.change.schedule_id,templateId:'template_id'in v.change?v.change.template_id:null}});
let sid:string,jid:string,employee:string,managerAgent:string,oldRows:string,oldFunctions:string,template:RotaTemplateSaved,uiSchedule:Schedule,uiJob:string;
async function setup(r:APIRequestContext,name:string,zone='Europe/London'){const data=await rotas(r);employee=data.agents.find(a=>a.last_name==='employee')!.id;managerAgent=data.agents.find(a=>a.last_name==='manager')!.id;await legacy(r,{action:'create_schedule',name,time_zone:zone,agent_ids:[employee,managerAgent],admin_ids:[f.accounts.manager.id]});const s=(await rotas(r)).schedules.find(s=>s.name===name)!;await legacy(r,{action:'add_job',schedule_id:s.id,revision:s.revision,name:'Community visits',color:'#3487ee'});const d=await rotas(r);return{schedule:d.schedules.find(x=>x.id===s.id)!,job:d.jobs.find(x=>x.schedule_id===s.id)!};}
function create(schedule:{id:string;revision:number},job:string,name:string,extra:Partial<Extract<RotaTemplateChange,{action:'create'}>>={}):RotaTemplateMutation&{change:Extract<RotaTemplateChange,{action:'create'}>}{return{tenantId:f.tenantA,operationId:randomUUID(),change:{action:'create',schedule_id:schedule.id,schedule_revision:schedule.revision,name,title:'Community cover',job_id:job,start_minute:540,end_minute:1020,end_day_offset:0,...extra}};}
async function open(page:Page,name:string,editable=true){await page.goto('/rotas?company='+f.tenantA);await expect(page.getByText('Loading schedules…')).not.toBeVisible();if(!editable){const restored=page.getByRole('dialog',{name:'Shift Templates',exact:true});await expect(restored).toBeVisible();return restored;}await page.getByRole('button',{name,exact:true}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();await page.getByRole('button',{name:'Templates',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Shift Templates',exact:true});if(editable)await expect(dialog.getByRole('button',{name:'Add Template',exact:true})).toBeEnabled();return dialog;}
test.beforeAll(()=>{oldRows=unrelated();oldFunctions=functions();});
test.afterAll(()=>{expect(unrelated()).toBe(oldRows);expect(functions()).toBe(oldFunctions);});
test('signed current schedule roles and tenant isolation deny employee/foreign/undelegated reads and direct writes',async({page})=>{await login(page);const s=await setup(page.request,'Template permissions');sid=s.schedule.id;jid=s.job.id;template=await saved(page.request,create(s.schedule,jid,'Morning visits'));const manager=await other(page,'manager'),employeePage=await other(page,'employee'),foreign=await other(page,'foreign');try{expect((await list(manager.page.request,sid)).actorId).toBe(f.accounts.manager.id);for(const p of[employeePage.page,foreign.page]){const response=await p.request.get('/api/rota-templates?'+new URLSearchParams({tenantId:f.tenantA,scheduleId:sid}));expect(response.status()).toBe(403);expect(Object.keys(await response.json())).toEqual(['error']);expect((await post(p.request,create((await list(page.request,sid)).schedule,jid,'Denied'))).status()).toBe(403);}sql(`delete from public.rota_admins where schedule_id='${sid}'and user_id='${f.accounts.manager.id}'`);expect((await manager.page.request.get('/api/rota-templates?tenantId='+f.tenantA+'&scheduleId='+sid)).status()).toBe(403);sql(`insert into public.rota_admins values('${f.tenantA}','${sid}','${f.accounts.manager.id}')`);expect(sql("select has_table_privilege('authenticated','public.rota_shift_templates','INSERT')or has_table_privilege('authenticated','public.rota_template_audit','DELETE')")).toBe('f');}finally{await manager.context.close();await employeePage.context.close();await foreign.context.close();}});
test('CRUD and UUID replay preserve exact revisions, literal search pagination and tombstoned deletions',async({page})=>{await login(page);const d=await list(page.request,sid),a=create(d.schedule,jid,'Literal %_ 東京');const ack=await saved(page.request,a);expect(await saved(page.request,a)).toEqual(ack);expect(sql(`select count(*)from public.rota_template_audit where template_id='${ack.template_id}'`)).toBe('1');expect((await post(page.request,{...a,change:{...a.change,name:'Changed'}})).status()).toBe(409);const edit=op({action:'edit',schedule_id:sid,schedule_revision:ack.schedule_revision,template_id:ack.template_id,template_revision:1,name:'Literal %_ 東京 edited',title:'Edited visit',job_id:jid,start_minute:540,end_minute:1020,end_day_offset:0});const edited=await saved(page.request,edit);expect((await post(page.request,{...edit,operationId:randomUUID()})).status()).toBe(409);const copy=await saved(page.request,op({action:'duplicate',schedule_id:sid,schedule_revision:edited.schedule_revision,template_id:edited.template_id,template_revision:edited.template_revision,name:'Literal %_ 東京 copy'}));const deleted=await saved(page.request,op({action:'delete',schedule_id:sid,schedule_revision:copy.schedule_revision,template_id:copy.template_id,template_revision:1}));expect((await list(page.request,sid,{q:'%_'})).templates.map(x=>x.id)).toEqual([edited.template_id]);sql(`insert into public.rota_shift_templates(tenant_id,schedule_id,name,title,job_id,start_minute,end_minute,end_day_offset,creator_user_id)select '${f.tenantA}','${sid}','Paged %_ 東京 '||lpad(n::text,2,'0'),'Synthetic', '${jid}',540,1020,0,'${f.accounts.owner.id}'from generate_series(1,31)n`);const first=await list(page.request,sid,{q:'Paged %_',limit:'10'});expect(first.page.total).toBe(31);const second=await list(page.request,sid,{q:'Paged %_',limit:'10',cursor:first.page.nextCursor!});expect(new Set([...first.templates,...second.templates].map(x=>x.id)).size).toBe(20);const changed=await page.request.get('/api/rota-templates?'+new URLSearchParams({tenantId:f.tenantA,scheduleId:sid,q:'different',cursor:first.page.nextCursor!}));expect(changed.status()).toBe(409);expect(deleted.template_revision).toBe(2);});
test('delegated application creates one private draft and legacy Publish reveals only employee own shifts',async({page})=>{await login(page);const manager=await other(page,'manager'),ep=await other(page,'employee');try{const d=await list(manager.page.request,sid),apply=op({action:'apply',schedule_id:sid,schedule_revision:d.schedule.revision,template_id:template.template_id,template_revision:template.template_revision,agent_id:employee,date:'2026-11-03',start_occurrence:'',end_occurrence:'',allow_overlap:false});const ack=await saved(manager.page.request,apply,'manager');expect(await saved(manager.page.request,apply,'manager')).toEqual(ack);let visible=await rotas(ep.page.request);expect(visible.shifts.some(x=>x.id===ack.shift_id)).toBe(false);const owner=await rotas(page.request),schedule=owner.schedules.find(x=>x.id===sid)!;expect(owner.shifts.find(x=>x.id===ack.shift_id)).toMatchObject({status:'draft',starts_at:'2026-11-03T09:00:00+00:00',ends_at:'2026-11-03T17:00:00+00:00'});await legacy(page.request,{action:'save_shift',schedule_id:sid,revision:schedule.revision,agent_id:managerAgent,job_id:jid,starts_at:'2026-11-03T09:00:00Z',ends_at:'2026-11-03T17:00:00Z',title:'Coworker private',allow_overlap:false});await legacy(manager.page.request,{action:'publish',schedule_id:sid,revision:(await list(manager.page.request,sid)).schedule.revision});visible=await rotas(ep.page.request);expect(visible.shifts.find(x=>x.id===ack.shift_id)?.status).toBe('published');expect(visible.shifts.filter(x=>x.schedule_id===sid)).toHaveLength(1);const current=await list(page.request,sid);expect((await post(page.request,{...apply,operationId:randomUUID(),change:{...apply.change,schedule_revision:current.schedule.revision}})).status()).toBe(409);}finally{await manager.context.close();await ep.context.close();}});
test('current timezone changes resolve DST folds/gaps and half-hour wall times through genuine APIs',async({page})=>{await login(page);const s=await setup(page.request,'Clock changes'),fold=await saved(page.request,create(s.schedule,s.job.id,'Fold visit',{start_minute:90,end_minute:150}));const base={action:'apply' as const,schedule_id:s.schedule.id,schedule_revision:fold.schedule_revision,template_id:fold.template_id,template_revision:1,agent_id:employee,date:'2026-10-25',start_occurrence:'' as const,end_occurrence:'' as const,allow_overlap:false};expect((await post(page.request,op(base))).status()).toBe(400);const applied=await saved(page.request,op({...base,start_occurrence:'earlier'}));const shift=(await rotas(page.request)).shifts.find(x=>x.id===applied.shift_id)!;expect(new Date(shift.ends_at).getTime()-new Date(shift.starts_at).getTime()).toBe(2*3600000);expect((await post(page.request,op({...base,schedule_revision:applied.schedule_revision,date:'2026-03-29'}))).status()).toBe(400);await legacy(page.request,{action:'update_schedule',schedule_id:s.schedule.id,revision:applied.schedule_revision,name:'Clock changes',time_zone:'Asia/Kolkata',agent_ids:[employee,managerAgent],admin_ids:[f.accounts.manager.id]});const after=await list(page.request,s.schedule.id),a=await saved(page.request,op({...base,schedule_revision:after.schedule.revision,date:'2026-11-05'}));const moved=(await rotas(page.request)).shifts.find(x=>x.id===a.shift_id)!;expect(new Date(moved.starts_at).toISOString()).toBe('2026-11-04T20:00:00.000Z');});
test('real desktop CRUD, application and signed original capture reflect persisted state',async({page})=>{await login(page);const s=await setup(page.request,'Desktop templates');uiSchedule=s.schedule;uiJob=s.job.id;const drawer=await open(page,uiSchedule.name);await drawer.getByRole('button',{name:'Add Template',exact:true}).click();await drawer.getByLabel('Template name',{exact:true}).fill('Outreach morning');await drawer.getByLabel('Shift title',{exact:true}).fill('Outreach visits');await drawer.getByRole('button',{name:'Save as template',exact:true}).click();await expect(drawer.getByRole('heading',{name:'Outreach morning',exact:true})).toBeVisible();const card=drawer.locator('article').filter({has:page.getByRole('heading',{name:'Outreach morning',exact:true})});await card.getByLabel('Actions for Outreach morning').click();await card.getByRole('button',{name:'Edit',exact:true}).click();await drawer.getByLabel('Template name',{exact:true}).fill('Outreach reviewed');await drawer.getByRole('button',{name:'Save template',exact:true}).click();await expect(drawer.getByRole('heading',{name:'Outreach reviewed',exact:true})).toBeVisible();await page.screenshot({path:'test-results/rota-templates-signed-desktop.png',fullPage:true});await drawer.getByRole('button',{name:'Apply',exact:true}).click();await drawer.getByLabel('Date',{exact:true}).fill('2026-11-07');await drawer.getByRole('combobox',{name:/^Worker/}).selectOption(employee);await drawer.getByRole('button',{name:'Create draft',exact:true}).click();await expect(drawer.getByRole('heading',{name:'Outreach reviewed',exact:true})).toBeVisible();await drawer.getByRole('button',{name:'Close templates',exact:true}).click();await expect(drawer).not.toBeVisible();expect((await rotas(page.request)).shifts.find(x=>x.schedule_id===uiSchedule.id)?.status).toBe('draft');});
test('closed absence rejects delayed save and recorded receipts deny current revoked original actor',async({page})=>{await login(page);const d=await list(page.request,uiSchedule.id),absent=create(d.schedule,uiJob,'Never sent');const r=await recover(page.request,absent);expect(r.status()).toBe(200);expect(await r.json()).toMatchObject({status:'not_recorded',saved:null});expect((await post(page.request,absent)).status()).toBe(409);const actual=create(d.schedule,uiJob,'Recorded recovery'),ack=await saved(page.request,actual);const recorded=await recover(page.request,actual);expect((await recorded.json()).saved).toEqual(ack);sql(`update public.tenant_memberships set status='suspended'where tenant_id='${f.tenantA}'and user_id='${f.accounts.owner.id}'`);try{expect((await recover(page.request,actual)).status()).toBe(403);expect((await post(page.request,actual)).status()).toBe(403);}finally{sql(`update public.tenant_memberships set status='active'where tenant_id='${f.tenantA}'and user_id='${f.accounts.owner.id}'`);}});
test('held genuine POST ACK blocks controls; departure leaves field-free original operation recovery',async({page})=>{await login(page);const drawer=await open(page,uiSchedule.name);await drawer.getByRole('button',{name:'Add Template',exact:true}).click();await drawer.getByLabel('Template name',{exact:true}).fill('Held private fields');let release!:()=>void,observed!:()=>void;const gate=new Promise<void>(r=>release=r),started=new Promise<void>(r=>observed=r);await page.route('**/api/rota-templates',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const response=await route.fetch();expect(response.status()).toBe(200);observed();await gate;await route.fulfill({response}).catch(error=>{if(!String(error).includes("Route is already handled"))throw error;});});try{await drawer.getByRole('button',{name:'Save as template',exact:true}).click();await started;await expect(drawer.getByRole('button',{name:'Close templates',exact:true})).toBeDisabled();const markers=await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('ct-alt:rota-template-operation:')));expect(markers).toHaveLength(1);const marker=JSON.parse(markers[0][1]);expect(Object.keys(marker).sort()).toEqual(['action','mode','operationId','scheduleId','templateId','tenantId'].sort());expect(markers[0][1]).not.toContain('Held private fields');await page.goto('/overview?company='+f.tenantA);release();await page.unroute('**/api/rota-templates');const restored=await open(page,uiSchedule.name,false);await expect(restored.getByRole('button',{name:'Check operation status',exact:true})).toBeVisible();await restored.getByRole('button',{name:'Check operation status',exact:true}).click();await expect(restored.getByRole('heading',{name:'Held private fields',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('ct-alt:rota-template-operation:')).length)).toBe(0);}finally{release();await page.unroute('**/api/rota-templates');}});
test('a delayed genuine read cannot return template fields after current Auth confirmation revocation',async({page})=>{await login(page);const signature='public.read_rota_templates(uuid,uuid,text,integer,jsonb)',definition=sql(`select pg_get_functiondef('${signature}'::regprocedure)`),confirmed=sql(`select email_confirmed_at from auth.users where id='${f.accounts.owner.id}'`);const patched=definition.replace('ident:=public.read_rota_template_access','perform pg_sleep(3);\n ident:=public.read_rota_template_access');expect(patched).not.toBe(definition);sql(patched);const pending=page.request.get('/api/rota-templates?tenantId='+f.tenantA+'&scheduleId='+uiSchedule.id);try{await expect.poll(()=>sql("select count(*)from pg_stat_activity where wait_event='PgSleep'and pid<>pg_backend_pid()"),{timeout:15000}).not.toBe('0');sql(`update auth.users set email_confirmed_at=null where id='${f.accounts.owner.id}'`);const response=await pending;expect(response.status()).toBe(403);expect(Object.keys(await response.json())).toEqual(['error']);}finally{await pending.catch(()=>{});sql(`update auth.users set email_confirmed_at=${quote(confirmed)}where id='${f.accounts.owner.id}'`);sql(definition);}});
test('genuine commit and rollback recovery wait on the original operation mutex and fence late writes',async({page})=>{await login(page);for(const commit of[true,false]){const d=await list(page.request,uiSchedule.id),value=create(d.schedule,uiJob,commit?'Committed mutex recovery':'Rolled back mutex recovery');const child=spawn('docker',['exec','-i',db,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres']);let error='';child.stdout.resume();child.stderr.on('data',v=>error+=v);const finished=new Promise<void>((resolve,reject)=>{child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(Error(error)));});child.stdin.end(`begin;set local role authenticated;select set_config('request.jwt.claim.sub','${f.accounts.owner.id}',true);select public.save_rota_template('${f.tenantA}','${value.operationId}',${quote(JSON.stringify(value.change))});select pg_sleep(3);${commit?'commit':'rollback'};`);try{await expect.poll(()=>sql("select count(*)from pg_stat_activity where wait_event='PgSleep'and pid<>pg_backend_pid()"),{timeout:15000}).not.toBe('0');const response=await recover(page.request,value);expect(response.status()).toBe(200);const b=await response.json();expect(b.status).toBe(commit?'recorded':'not_recorded');if(commit)expect(b.saved.operationId).toBe(value.operationId);else expect((await post(page.request,value)).status()).toBe(409);}finally{await finished;}}});
test('revoked assigned manager A keeps an unknown operation marker while delegated B legacy writes remain usable',async({page})=>{await login(page);const a=await setup(page.request,'Marker scope A'),b=await setup(page.request,'Marker scope B'),manager=await other(page,'manager');let release!:()=>void,observed!:()=>void;const gate=new Promise<void>(r=>release=r),started=new Promise<void>(r=>observed=r);try{const drawer=await open(manager.page,a.schedule.name);await drawer.getByRole('button',{name:'Add Template',exact:true}).click();await drawer.getByLabel('Template name',{exact:true}).fill('Private revoked A outcome');await manager.page.route('**/api/rota-templates',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const response=await route.fetch();expect(response.status()).toBe(200);observed();await gate;await route.fulfill({response}).catch(error=>{if(!String(error).includes("Route is already handled"))throw error;});});await drawer.getByRole('button',{name:'Save as template',exact:true}).click();await started;sql(`delete from public.rota_admins where schedule_id='${a.schedule.id}'and user_id='${f.accounts.manager.id}'`);await manager.page.goto('/overview?company='+f.tenantA);release();await manager.page.unroute('**/api/rota-templates');await manager.page.goto('/rotas?company='+f.tenantA);await expect(manager.page.getByText('Loading schedules…')).not.toBeVisible();await manager.page.getByRole('button',{name:a.schedule.name,exact:true}).click();await expect(manager.page.getByRole('dialog',{name:'Shift Templates'})).toHaveCount(0);await expect(manager.page.getByRole('button',{name:'Templates',exact:true})).toHaveCount(0);await expect(manager.page.getByText('Private revoked A outcome',{exact:true})).toHaveCount(0);expect(await manager.page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('ct-alt:rota-template-operation:')))).toHaveLength(1);await manager.page.getByRole('button',{name:'All schedules',exact:true}).click();await manager.page.getByRole('button',{name:b.schedule.name,exact:true}).click();await expect(manager.page.getByRole('button',{name:'Job list',exact:true})).toBeEnabled();await manager.page.getByRole('button',{name:'Job list',exact:true}).click();const jobs=manager.page.getByRole('dialog');await jobs.getByLabel('Job name',{exact:true}).fill('Delegated B remains editable');await jobs.getByLabel('Job color',{exact:true}).fill('#285c4c');await jobs.getByRole('button',{name:'Add job',exact:true}).click();await expect(jobs).not.toBeVisible();expect((await rotas(page.request)).jobs.some(x=>x.schedule_id===b.schedule.id&&x.name==='Delegated B remains editable')).toBe(true);expect(await manager.page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('ct-alt:rota-template-operation:')))).toHaveLength(1);}finally{release?.();await manager.page.unroute('**/api/rota-templates');await manager.context.close();}});
test('saved shift capture explicitly acknowledges seconds and microseconds normalization and retains original source bytes',async({page})=>{
 await login(page);
 for(const precision of[{date:'2026-11-08',start:'09:00:30',end:'17:00:45',name:'Precise source visit',template:'Normalized precise visit'},{date:'2026-11-09',start:'09:00:00.000001',end:'17:00:00.000002',name:'Microsecond source visit',template:'Normalized microsecond visit'}]){
  const d=await list(page.request,uiSchedule.id);
  await legacy(page.request,{action:'save_shift',schedule_id:uiSchedule.id,revision:d.schedule.revision,agent_id:employee,job_id:uiJob,starts_at:precision.date+'T'+precision.start+'Z',ends_at:precision.date+'T'+precision.end+'Z',title:precision.name,allow_overlap:false});
  const source=(await rotas(page.request)).shifts.find(x=>x.title===precision.name)!;
  if(precision.start.includes('.')){expect(source.starts_at).toContain('.000001');expect(source.ends_at).toContain('.000002');}
  await page.goto('/rotas?company='+f.tenantA);await expect(page.getByText('Loading schedules…')).not.toBeVisible();await page.getByRole('button',{name:uiSchedule.name,exact:true}).click();await page.getByLabel('Date',{exact:true}).fill(precision.date);await page.getByRole('button',{name:new RegExp('Edit draft '+precision.name)}).first().click();
  const editDialog=page.getByRole('dialog');await editDialog.getByRole('button',{name:'Save as template from saved shift',exact:true}).click();
  const drawer=page.getByRole('dialog',{name:'Shift Templates',exact:true});await expect(drawer.getByLabel(/The source includes seconds/)).toBeVisible();await drawer.getByLabel('Template name',{exact:true}).fill(precision.template);
  // Consent is required even when JS Date truncates the persisted microseconds to zero.
  await drawer.getByRole('button',{name:'Save as template',exact:true}).click();await expect(drawer.getByLabel(/The source includes seconds/)).not.toBeChecked();expect((await list(page.request,uiSchedule.id,{q:precision.template})).templates).toHaveLength(0);
  await drawer.getByLabel(/The source includes seconds/).check();await drawer.getByRole('button',{name:'Save as template',exact:true}).click();await expect(drawer.getByRole('heading',{name:precision.template,exact:true})).toBeVisible();
  const capture=(await list(page.request,uiSchedule.id,{q:precision.template})).templates[0];expect(capture).toMatchObject({start_minute:540,end_minute:1020,end_day_offset:0});expect((await rotas(page.request)).shifts.find(x=>x.id===source.id)).toEqual(source);
 }
});
