import{test,expect}from'@playwright/test';
import{readFileSync,readdirSync}from'node:fs';
import{spawn}from'node:child_process';
import{randomUUID}from'node:crypto';
import{createFormsFixture}from'./forms-auth-fixture.mjs';
const fixture=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8')),origin='http://127.0.0.1:5180';
test.describe.configure({mode:'serial'});test.setTimeout(120000);
let legacy,formId,responseId,submittedAt;
const ids=Object.fromEntries(['description','text','yes','single','multiple','number','optionA','optionB'].map(key=>[key,randomUUID()]));
const originalName=String.raw`Synthetic safety form %_\ İ`;
let formName=originalName;
const literal='  Original answers 東京 😀\n<b>Literal plain text</b>\n  ';
/** @type {import('../lib/forms-types').FormsField[]} */
const schema=[{id:ids.description,kind:'description',text:'Original description 東京 😀 <b>Literal</b>'},{id:ids.text,kind:'text',label:'Safety note',required:true},{id:ids.yes,kind:'yes_no',label:'Safety acknowledged',required:true},{id:ids.single,kind:'single_choice',label:'Primary equipment',required:true,options:[{id:ids.optionA,label:'Gloves 東京'},{id:ids.optionB,label:'Mask 😀'}]},{id:ids.multiple,kind:'multiple_choice',label:'Additional equipment',required:true,options:[{id:ids.optionA,label:'Gloves 東京'},{id:ids.optionB,label:'Mask 😀'}]},{id:ids.number,kind:'number',label:'Exact quantity',required:true}];
const completeAnswers=()=>({[ids.text]:literal,[ids.yes]:false,[ids.single]:ids.optionA,[ids.multiple]:[ids.optionA,ids.optionB],[ids.number]:'999999999999.123456'});
const mutation=change=>({tenantId:fixture.tenantA,operationId:randomUUID(),change});
function identity(data,account='owner'){expect(data).toMatchObject({tenantId:fixture.tenantA,actorId:fixture.accounts[account].id,role:fixture.accounts[account].role});}
async function login(page,account='owner'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(fixture.accounts[account].email);await page.getByLabel('Password',{exact:true}).fill(fixture.accounts[account].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}
function formUrl(view='manage',id=formId){return`/api/forms/${id}?${new URLSearchParams({tenantId:fixture.tenantA,view})}`;}
async function form(request,view='manage',account='owner',id=formId){const r=await request.get(formUrl(view,id));expect(r.status()).toBe(200);expect(r.headers()['cache-control']).toContain('no-store');const data=await r.json();identity(data,account);expect(data.view).toBe(view);expect(data.form.id).toBe(id);return data;}
function write(request,value){return request.post('/api/forms',{headers:{Origin:origin},data:value});}
async function saved(request,value,account='owner'){const r=await write(request,value),data=await r.json();expect(r.status(),typeof data.error==='string'?data.error:'Missing saved acknowledgment').toBe(200);expect(r.headers()['cache-control']).toContain('no-store');identity(data.saved,account);expect(data.saved).toMatchObject({operationId:value.operationId,action:value.change.action});return data.saved;}
async function manage(request,change){const data=await form(request);return saved(request,mutation({formId,formRevision:data.form.revision,...change}));}
async function personal(request,action,answers,account='employee'){const data=await form(request,'mine',account);return saved(request,mutation({action,formId,formRevision:data.form.revision,responseRevision:data.response?.revision??0,answers}),account);}
async function responses(request,extra={}){const r=await request.get(`/api/forms/${formId}/responses?${new URLSearchParams({tenantId:fixture.tenantA,...extra})}`);expect(r.status()).toBe(200);const data=await r.json();identity(data);return data;}
async function response(request,extra={}){const r=await request.get(`/api/forms/${formId}/responses/${responseId}?${new URLSearchParams({tenantId:fixture.tenantA,...extra})}`);expect(r.status()).toBe(200);const data=await r.json();identity(data);expect(data.response.id).toBe(responseId);return data;}
async function otherContext(page,account){const context=await page.context().browser().newContext({baseURL:origin});const other=await context.newPage();await login(other,account);return{context,page:other};}
async function signedRest(account,path,method='GET',body){const auth=await fetch(fixture.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:fixture.key,'Content-Type':'application/json'},body:JSON.stringify({email:fixture.accounts[account].email,password:fixture.accounts[account].password})});expect(auth.status).toBe(200);const{access_token}=await auth.json();return fetch(fixture.url+'/rest/v1/'+path,{method,headers:{apikey:fixture.key,Authorization:'Bearer '+access_token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});}
test.beforeAll(()=>{legacy=createFormsFixture(fixture);});test.afterAll(()=>{if(legacy){expect(legacy.capture()).toBe(legacy.beforeRows);expect(legacy.functions()).toBe(legacy.beforeFunctions);}});

test('signed management pages exact full roster, strict draft operations and current original-Auth publication permissions',async({page})=>{
 await login(page);let cursor;const people=[];
 do{const r=await page.request.get('/api/forms/roster?'+new URLSearchParams({tenantId:fixture.tenantA,search:'Synthetic Forms account',limit:'100',...cursor?{cursor}:{}}));expect(r.status()).toBe(200);const data=await r.json();identity(data);expect(data.matchedCount).toBe(1005);expect(data.users.every(user=>user.eligible)).toBe(true);people.push(...data.users.map(user=>user.actorId));cursor=data.nextCursor;}while(cursor);
 expect(people).toHaveLength(1005);expect(new Set(people).size).toBe(1005);
 const payload=mutation({action:'create_form',name:originalName,description:'Original synthetic form',schema,audienceIds:[fixture.accounts.employee.id,fixture.accounts.manager.id],allowRespondentEdit:false});
 const both=await Promise.all([saved(page.request,payload),saved(page.request,payload)]);expect(both[0]).toEqual(both[1]);formId=both[0].formId;expect(both[0].formRevision).toBe(1);
 expect((await write(page.request,{...payload,change:{...payload.change,name:'Different same UUID'}})).status()).toBe(400);
 expect((await page.request.post('/api/forms',{headers:{Origin:'https://foreign.invalid'},data:payload})).status()).toBe(403);
 const empty=await saved(page.request,mutation({action:'create_form',name:'Synthetic empty draft',description:'',schema:[],audienceIds:[],allowRespondentEdit:false}));
 expect((await write(page.request,mutation({action:'publish_form',formId:empty.formId,formRevision:empty.formRevision}))).status()).toBe(409);expect((await form(page.request,'manage','owner',empty.formId)).form).toMatchObject({status:'draft',revision:empty.formRevision,schemaFrozen:false});
 for(const account of['admin','manager','employee','foreign']){const other=await otherContext(page,account);try{const admin=account==='admin';expect((await other.page.request.get(formUrl('manage'))).status()).toBe(admin?200:403);expect((await other.page.request.get(formUrl('mine'))).status()).toBe(403);if(!admin){expect((await other.page.request.get('/api/forms/roster?tenantId='+fixture.tenantA)).status()).toBe(403);expect((await write(other.page.request,mutation({action:'create_form',name:'Forbidden',description:'',schema,audienceIds:[],allowRespondentEdit:false}))).status()).toBe(403);}}finally{await other.context.close();}}
 const optional=await saved(page.request,mutation({action:'create_form',name:'Synthetic optional empty choices',description:'',schema:[{...schema[4],required:false}],audienceIds:[fixture.accounts.owner.id],allowRespondentEdit:false}));const optionalPublished=await saved(page.request,mutation({action:'publish_form',formId:optional.formId,formRevision:1}));await saved(page.request,mutation({action:'submit_response',formId:optional.formId,formRevision:optionalPublished.formRevision,responseRevision:0,answers:{[ids.multiple]:[]}}));expect((await form(page.request,'mine','owner',optional.formId)).response.answers).toEqual({[ids.multiple]:[]});
 await manage(page.request,{action:'publish_form'});expect((await form(page.request)).form).toMatchObject({status:'published',revision:2,schemaFrozen:true});expect((await form(page.request)).schema).toEqual(schema);expect((await page.request.get(formUrl('mine'))).status()).toBe(403);
});

test('personal partial progress stays private from unassigned management and is bound to original Auth actor after Agent relink',async({page})=>{
 await login(page,'employee');const data=await form(page.request,'mine','employee');const operation=mutation({action:'save_progress',formId,formRevision:data.form.revision,responseRevision:0,answers:{[ids.text]:literal,[ids.number]:'12.'}});
 const both=await Promise.all([saved(page.request,operation,'employee'),saved(page.request,operation,'employee')]);expect(both[0]).toEqual(both[1]);responseId=both[0].responseId;expect(both[0]).toMatchObject({responseRevision:1,responseStatus:'in_progress',submittedAt:null});
 const mine=await form(page.request,'mine','employee');expect(mine.response.answers).toEqual(operation.change.answers);expect(mine.response.actorId).toBe(fixture.accounts.employee.id);
 const owner=await otherContext(page,'owner');try{const list=await responses(owner.page.request);expect(list.counts).toEqual({total:0,reviewed:0,notReviewed:0});expect(list.responses).toEqual([]);expect((await owner.page.request.get(`/api/forms/${formId}/responses/${responseId}?tenantId=${fixture.tenantA}`)).status()).toBe(403);
  const direct=await signedRest('owner',`form_responses?form_id=eq.${formId}`);expect(direct.status).toBe(200);expect(await direct.json()).toEqual([]);
 }finally{await owner.context.close();}
 const managerAgent=legacy.sql(`select id from public.agents where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.manager.id}'`);
 legacy.sql(`update public.agents set user_id=null where id in('${legacy.employee}','${managerAgent}');update public.agents set user_id='${fixture.accounts.manager.id}'where id='${legacy.employee}';update public.agents set user_id='${fixture.accounts.employee.id}'where id='${legacy.replacement}';`);
 try{expect((await form(page.request,'mine','employee')).response.answers).toEqual(operation.change.answers);const manager=await otherContext(page,'manager');try{expect((await form(manager.page.request,'mine','manager')).response).toBe(null);expect((await manager.page.request.get(`/api/forms/${formId}/responses/${responseId}?tenantId=${fixture.tenantA}`)).status()).toBe(403);}finally{await manager.context.close();}
  const chat=await page.request.get(`/api/chat/search?tenantId=${fixture.tenantA}&conversationId=${legacy.retainedId}&query=Retained`);expect(chat.status()).toBe(200);const retained=await chat.json();expect(retained).toMatchObject({tenantId:fixture.tenantA,conversationId:legacy.retainedId,actorId:fixture.accounts.employee.id,total:1});expect(retained.messages[0]).toMatchObject({conversation_id:legacy.retainedId,sender_id:fixture.accounts.employee.id,body:'Retained synthetic message'});
 }finally{legacy.sql(`update public.agents set user_id=null where id in('${legacy.employee}','${legacy.replacement}');update public.agents set user_id='${fixture.accounts.employee.id}'where id='${legacy.employee}';update public.agents set user_id='${fixture.accounts.manager.id}'where id='${managerAgent}';`);}
});

async function library(page){await page.goto('/forms?company='+fixture.tenantA);await expect(page.getByRole('heading',{name:'Forms',exact:true})).toBeVisible();}
async function openMine(page){await library(page);await page.getByRole('button',{name:'My forms',exact:true}).click();const read=page.waitForResponse(r=>r.request().method()==='GET'&&r.url().includes(`/api/forms/${formId}?`)&&new URL(r.url()).searchParams.get('view')==='mine');await page.getByRole('button',{name:'Open form '+formName,exact:true}).click();const r=await read;expect(r.status()).toBe(200);const data=await r.json();identity(data,'employee');expect(data.form.id).toBe(formId);return data;}

test('real desktop autosave survives a fresh reload, submits all six original field kinds, and refuses missing or malformed required answers',async({page})=>{
 await login(page,'employee');let data=await form(page.request,'mine','employee');
 for(const answers of[{}, {...completeAnswers(),[ids.number]:'12.'},{...completeAnswers(),[ids.number]:'1e3'},{...completeAnswers(),[ids.single]:randomUUID()},{...completeAnswers(),[ids.multiple]:[ids.optionA,ids.optionA]},{...completeAnswers(),[ids.multiple]:[]},{...completeAnswers(),[ids.description]:'Forged description answer'},{...completeAnswers(),[randomUUID()]:'Unknown field'}]){expect((await write(page.request,mutation({action:'submit_response',formId,formRevision:data.form.revision,responseRevision:data.response.revision,answers}))).status()).toBe(400);}
 for(const incomplete of['-','1.']){await personal(page.request,'save_progress',{[ids.number]:incomplete});const partial=await form(page.request,'mine','employee');expect(partial.response.answers).toEqual({[ids.number]:incomplete});const denied=await write(page.request,mutation({action:'submit_response',formId,formRevision:partial.form.revision,responseRevision:partial.response.revision,answers:{...completeAnswers(),[ids.number]:incomplete}}));expect(denied.status()).toBe(400);expect((await form(page.request,'mine','employee')).response.revision).toBe(partial.response.revision);}
 await openMine(page);await expect(page.getByText(schema[0].text,{exact:true})).toBeVisible();
 await page.getByRole('textbox',{name:'Safety note',exact:true}).fill(literal);
 await page.getByRole('group',{name:/Safety acknowledged/}).getByRole('radio',{name:'No',exact:true}).check();
 await page.getByRole('combobox',{name:'Primary equipment',exact:true}).selectOption(ids.optionA);
 const multiple=page.getByRole('group',{name:/Additional equipment/});await multiple.getByRole('checkbox',{name:'Gloves 東京',exact:true}).check();await multiple.getByRole('checkbox',{name:'Mask 😀',exact:true}).check();
 const autosaved=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='save_progress');
 await page.getByRole('textbox',{name:'Exact quantity',exact:true}).fill('999999999999.123456');expect((await autosaved).status()).toBe(200);
 await expect.poll(async()=>(await form(page.request,'mine','employee')).response.answers).toEqual(completeAnswers());
 await page.reload();await page.getByRole('button',{name:'My forms',exact:true}).click();await page.getByRole('button',{name:'Open form '+formName,exact:true}).click();await expect(page.getByRole('textbox',{name:'Safety note',exact:true})).toHaveValue(literal);await expect(page.getByRole('textbox',{name:'Exact quantity',exact:true})).toHaveValue('999999999999.123456');
 const submission=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='submit_response');await page.getByRole('button',{name:'Send response',exact:true}).click();expect((await submission).status()).toBe(200);await expect(page.getByText('Your response was submitted.',{exact:true})).toBeVisible();
 data=await form(page.request,'mine','employee');expect(data.response.answers).toEqual(completeAnswers());expect(data.response.status).toBe('submitted');submittedAt=data.response.submittedAt;expect(submittedAt).toBeTruthy();expect(data.response.actorId).toBe(fixture.accounts.employee.id);expect(data.form.capabilities.canEditResponse).toBe(false);expect((await write(page.request,mutation({action:'edit_response',formId,formRevision:data.form.revision,responseRevision:data.response.revision,answers:completeAnswers()}))).status()).toBe(409);
});

test('submitted management edits retain original title/schema/first submission, precise paged history, and independent content-editor and review clocks',async({page})=>{
 await login(page);const initial=await response(page.request);expect(initial.response.answers).toEqual(completeAnswers());expect(initial.historyCount).toBe(0);expect((await responses(page.request)).counts).toEqual({total:1,reviewed:0,notReviewed:1});
 const invalid=await form(page.request);expect((await write(page.request,mutation({action:'edit_form',formId,formRevision:invalid.form.revision,name:formName,description:'',schema:[],allowRespondentEdit:true}))).status()).toBe(409);
 formName='Synthetic revised form 東京 😀';await manage(page.request,{action:'edit_form',name:formName,description:'Metadata changed, original question schema stays frozen',schema,allowRespondentEdit:true});
 for(let i=1;i<=12;i++){const current=await response(page.request);await manage(page.request,{action:'admin_edit_response',responseId,responseRevision:current.response.revision,answers:{...completeAnswers(),[ids.text]:`Content edit ${i} 東京 😀`}});}
 const edited=(await response(page.request)).response;expect(edited).toMatchObject({submittedAt,formName:originalName,lastEditedBy:fixture.accounts.owner.id});expect(edited.schema).toEqual(schema);const contentClock={lastEditedBy:edited.lastEditedBy,lastEditorName:edited.lastEditorName,lastEditedAt:edited.lastEditedAt};
 const admin=await otherContext(page,'admin');try{const current=await response(page.request);const base=await form(admin.page.request,'manage','admin');await saved(admin.page.request,mutation({action:'review_response',formId,formRevision:base.form.revision,responseId,responseRevision:current.response.revision,reviewed:true}),'admin');}finally{await admin.context.close();}
 const reviewed=(await response(page.request)).response;expect(reviewed).toMatchObject({...contentClock,reviewed:true,reviewedBy:fixture.accounts.admin.id,submittedAt});expect(reviewed.reviewedAt).toBeTruthy();expect(reviewed.reviewerName).toBeTruthy();expect((await responses(page.request,{review:'reviewed'})).responses).toHaveLength(1);expect((await responses(page.request,{review:'not_reviewed'})).responses).toHaveLength(0);
 await manage(page.request,{action:'review_response',responseId,responseRevision:reviewed.revision,reviewed:false});expect((await response(page.request)).response).toMatchObject({...contentClock,reviewed:false,reviewedAt:null,reviewedBy:null,reviewerName:null,submittedAt});
 const history=[];let cursor;do{const data=await response(page.request,{limit:'10',...cursor?{cursor}:{}});expect(data.history.length).toBeLessThanOrEqual(10);expect(data.historyCount).toBe(12);history.push(...data.history);cursor=data.nextCursor;}while(cursor);
 expect(history).toHaveLength(12);expect(new Set(history.map(item=>item.id)).size).toBe(12);expect(history.every(item=>item.formName===originalName&&item.submittedAt===submittedAt&&!Object.hasOwn(item,'schema'))).toBe(true);expect(history.map(item=>item.answers[ids.text])).toContain(literal);

 const mine=await otherContext(page,'employee');try{const data=await form(mine.page.request,'mine','employee');expect(data.form.capabilities.canEditResponse).toBe(true);await personal(mine.page.request,'edit_response',{...completeAnswers(),[ids.text]:'Original respondent edited 東京 😀'});expect((await response(page.request)).response).toMatchObject({lastEditedBy:fixture.accounts.employee.id,submittedAt});}finally{await mine.context.close();}
});

test('current old cookies and receipts never recover withdrawn assignments, inactive identities or archived forms; retained answers remain management history',async({page})=>{
 await login(page,'employee');const owner=await otherContext(page,'owner');try{
  const current=await form(page.request,'mine','employee');const receipt=mutation({action:'edit_response',formId,formRevision:current.form.revision,responseRevision:current.response.revision,answers:{...completeAnswers(),[ids.text]:'Retained prior to access removal'}});await saved(page.request,receipt,'employee');
  await manage(owner.page.request,{action:'set_audience',audienceIds:[fixture.accounts.manager.id]});
  expect((await page.request.get(formUrl('mine'))).status()).toBe(403);expect((await write(page.request,receipt)).status()).toBe(403);expect((await page.request.post('/api/forms/reconcile',{headers:{Origin:origin},data:{tenantId:fixture.tenantA,operationId:receipt.operationId,action:'edit_response'}})).status()).toBe(403);
  await library(page);await expect(page.getByRole('button',{name:'Open form '+formName,exact:true})).toHaveCount(0);expect((await response(owner.page.request)).response.answers[ids.text]).toBe(receipt.change.answers[ids.text]);
  await manage(owner.page.request,{action:'set_audience',audienceIds:[fixture.accounts.employee.id,fixture.accounts.manager.id]});
  await manage(owner.page.request,{action:'archive_form'});expect((await page.request.get(formUrl('mine'))).status()).toBe(403);expect((await write(page.request,receipt)).status()).toBe(403);await manage(owner.page.request,{action:'restore_form'});expect((await form(page.request,'mine','employee')).response.submittedAt).toBe(submittedAt);
  const priorAuth=legacy.sql(`select jsonb_build_object('email_confirmed_at',email_confirmed_at,'is_anonymous',is_anonymous)from auth.users where id='${fixture.accounts.employee.id}'`);
  const auth=JSON.parse(priorAuth);
  for(const[change,restore]of[
   [`update public.tenant_memberships set status='suspended'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.employee.id}'`,`update public.tenant_memberships set status='active'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.employee.id}'`],
   [`update public.tenants set status='suspended'where id='${fixture.tenantA}'`,`update public.tenants set status='active'where id='${fixture.tenantA}'`],
   [`update auth.users set email_confirmed_at=null where id='${fixture.accounts.employee.id}'`,`update auth.users set email_confirmed_at='${auth.email_confirmed_at}'where id='${fixture.accounts.employee.id}'`],
   [`update auth.users set is_anonymous=true where id='${fixture.accounts.employee.id}'`,`update auth.users set is_anonymous=${auth.is_anonymous?'true':'false'} where id='${fixture.accounts.employee.id}'`],
  ]){legacy.sql(change);try{expect((await page.request.get(formUrl('mine'))).status()).toBe(403);expect((await write(page.request,receipt)).status()).toBe(403);expect((await page.request.post('/api/forms/reconcile',{headers:{Origin:origin},data:{tenantId:fixture.tenantA,operationId:receipt.operationId,action:'edit_response'}})).status()).toBe(403);}finally{legacy.sql(restore);}}
  const manager=await otherContext(page,'manager');try{await library(manager.page);await manager.page.getByRole('button',{name:'Open form '+formName,exact:true}).click();await expect(manager.page.getByRole('textbox',{name:'Safety note',exact:true})).toHaveValue('');await expect(manager.page.getByRole('button',{name:'Create form',exact:true})).toHaveCount(0);expect((await manager.page.request.get(formUrl('manage'))).status()).toBe(403);}finally{await manager.context.close();}
  const foreign=await otherContext(page,'foreign');try{await library(foreign.page);await expect(foreign.page.getByRole('button',{name:'Open form '+formName,exact:true})).toHaveCount(0);expect((await foreign.page.request.get(formUrl('mine'))).status()).toBe(403);}finally{await foreign.context.close();}
 }finally{await owner.context.close();}
});

const quote=value=>"'"+value.replaceAll("'","''")+"'";
function heldTransaction(operation,account,ending){
 // legacy.sql checks the exact random owning Docker label before any new process.
 legacy.sql('select 1');const name='forms-held-'+operation.operationId;
 const child=spawn('docker',['exec','-i','supabase_db_ct-alt-independent','psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{stdio:['pipe','pipe','pipe']});let errors='';child.stderr.on('data',chunk=>{errors+=chunk});child.stdout.resume();const done=new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',code=>code===0?resolve():reject(Error('Guarded synthetic transaction failed: '+errors)))});
 child.stdin.end(`set application_name=${quote(name)};begin;set local role authenticated;set local request.jwt.claims=${quote(JSON.stringify({sub:fixture.accounts[account].id,role:'authenticated'}))};select public.save_form('${fixture.tenantA}','${operation.operationId}',${quote(JSON.stringify(operation.change))});select pg_sleep(2);${ending};`);
 return{name,done};
}

test('field-free signed reconciliation waits for genuine uncommitted progress commit/rollback and rechecks authority after the operation mutex',async({page})=>{
 await login(page);const manager=await otherContext(page,'manager');try{
  for(const ending of['commit','rollback','revoke']){
   const made=await saved(page.request,mutation({action:'create_form',name:'Synthetic transaction '+ending,description:'',schema,audienceIds:[fixture.accounts.manager.id],allowRespondentEdit:false}));const published=await saved(page.request,mutation({action:'publish_form',formId:made.formId,formRevision:made.formRevision}));
   const operation=mutation({action:'save_progress',formId:made.formId,formRevision:published.formRevision,responseRevision:0,answers:{[ids.text]:'Uncommitted original manager progress'}});const held=heldTransaction(operation,'manager',ending==='rollback'?'rollback':'commit');
   await expect.poll(()=>legacy.sql(`select count(*)from pg_stat_activity where application_name=${quote(held.name)}and wait_event='PgSleep'`)).toBe('1');
   let settled=false;const pending=manager.page.request.post('/api/forms/reconcile',{headers:{Origin:origin},data:{tenantId:fixture.tenantA,operationId:operation.operationId,action:'save_progress'}}).then(r=>{settled=true;return r});await new Promise(resolve=>setTimeout(resolve,150));expect(settled).toBe(false);
   if(ending==='revoke')legacy.sql(`update public.tenant_memberships set status='suspended'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.manager.id}'`);
   try{const r=await pending;await held.done;if(ending==='revoke'){expect(r.status()).toBe(403);}else{expect(r.status()).toBe(200);const data=await r.json();identity(data,'manager');expect(Object.keys(data).sort()).toEqual(['action','actorId','operationId','role','saved','status','tenantId']);expect(data.status).toBe(ending==='commit'?'recorded':'not_recorded');if(ending==='rollback')expect(data.saved).toBe(null);expect(JSON.stringify(data)).not.toContain('Uncommitted original manager progress');expect(JSON.stringify(data)).not.toContain(ids.text);}}
   finally{await held.done;if(ending==='revoke')legacy.sql(`update public.tenant_memberships set status='active'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.manager.id}'`);}
  }
  // This original HTTP write is delayed before entering either the app or DB.
  const made=await saved(page.request,mutation({action:'create_form',name:'Synthetic delayed pre-server save',description:'',schema,audienceIds:[fixture.accounts.manager.id],allowRespondentEdit:false}));const published=await saved(page.request,mutation({action:'publish_form',formId:made.formId,formRevision:made.formRevision}));
  const delayed=mutation({action:'save_progress',formId:made.formId,formRevision:published.formRevision,responseRevision:0,answers:{[ids.text]:'Private delayed answer that must never be committed'}});
  const snapshot=()=>legacy.sql(`select jsonb_build_object('responses',(select coalesce(jsonb_agg(to_jsonb(r)order by r.id),'[]')from public.form_responses r where form_id='${made.formId}'),'audit',(select coalesce(jsonb_agg(to_jsonb(a)order by a.id),'[]')from public.form_audit a where form_id='${made.formId}'),'recorded',(select coalesce(jsonb_agg(to_jsonb(o)order by o.operation_id),'[]')from workforce_private.form_operations o where form_id='${made.formId}'and state='recorded'))`);const prior=snapshot();
  let release,ready;const held=new Promise(resolve=>{ready=resolve}),gate=new Promise(resolve=>{release=resolve});const pattern='**/api/forms';
  await manager.page.route(pattern,async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON()?.operationId===delayed.operationId){ready();await gate;await route.continue();}else await route.continue();});
  const original=manager.page.evaluate(async payload=>{const r=await fetch('/api/forms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return{status:r.status,body:await r.json()};},delayed);
  try{await held;expect(legacy.sql(`select count(*)from workforce_private.form_operations where tenant_id='${fixture.tenantA}'and actor_id='${fixture.accounts.manager.id}'and operation_id='${delayed.operationId}'`)).toBe('0');
   const reconcileBody={tenantId:fixture.tenantA,operationId:delayed.operationId,action:'save_progress'};const close=await manager.page.request.post('/api/forms/reconcile',{headers:{Origin:origin},data:reconcileBody});expect(close.status()).toBe(200);const absent=await close.json();identity(absent,'manager');expect(absent).toMatchObject({...reconcileBody,status:'not_recorded',saved:null});
   const tombstone=JSON.parse(legacy.sql(`select to_jsonb(o)from workforce_private.form_operations o where tenant_id='${fixture.tenantA}'and actor_id='${fixture.accounts.manager.id}'and operation_id='${delayed.operationId}'`));expect(tombstone).toMatchObject({tenant_id:fixture.tenantA,actor_id:fixture.accounts.manager.id,operation_id:delayed.operationId,action:'save_progress',state:'closed_absent',form_id:null,response_id:null,payload_hash:null,result:null});expect(JSON.stringify(tombstone)).not.toContain(delayed.change.answers[ids.text]);expect(snapshot()).toBe(prior);
   release();const late=await original;expect(late.status).toBe(409);expect(snapshot()).toBe(prior);expect(legacy.sql(`select state from workforce_private.form_operations where tenant_id='${fixture.tenantA}'and actor_id='${fixture.accounts.manager.id}'and operation_id='${delayed.operationId}'`)).toBe('closed_absent');
   const repeat=await manager.page.request.post('/api/forms/reconcile',{headers:{Origin:origin},data:reconcileBody});expect(repeat.status()).toBe(200);expect(await repeat.json()).toEqual(absent);expect((await manager.page.request.post('/api/forms/reconcile',{headers:{Origin:origin},data:{...reconcileBody,action:'submit_response'}})).status()).toBe(400);expect(snapshot()).toBe(prior);
   await saved(manager.page.request,{...delayed,operationId:randomUUID()},'manager');expect((await form(manager.page.request,'mine','manager',made.formId)).response.answers).toEqual(delayed.change.answers);expect(legacy.sql(`select state from workforce_private.form_operations where tenant_id='${fixture.tenantA}'and actor_id='${fixture.accounts.manager.id}'and operation_id='${delayed.operationId}'`)).toBe('closed_absent');
  }finally{release?.();await original.catch(()=>{});await manager.page.unroute(pattern);}
 }finally{await manager.context.close();}
});

async function captureDesktop(page,path){await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo(0,0);});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path,fullPage:true});}

async function invokeReact(button){await button.evaluate(element=>{const key=Object.keys(element).find(key=>key.startsWith('__reactProps$'));if(!key||typeof element[key].onClick!=='function')throw Error('Expected the actual React button handler');element[key].onClick({preventDefault(){},stopPropagation(){}});});}

test('stable signed read snapshots recheck revoked management and delayed prior leaves never restore cleared private panes',async({page})=>{
 await login(page);const signature='public.read_forms(uuid,text,text,uuid,uuid,text,text,text,integer,jsonb)';const definition=legacy.sql(`select pg_get_functiondef(${quote(signature)}::regprocedure)`),barrier="version:=case when read_kind='roster'";expect(definition.split(barrier)).toHaveLength(2);const candidates=readdirSync('supabase/migrations').filter(file=>file.endsWith('_desktop_forms.sql'));expect(candidates).toHaveLength(1);expect(readFileSync('supabase/migrations/'+candidates[0],'utf8')).toContain(barrier);
 legacy.sql(definition.replace(barrier,`if search_text='Synthetic Forms snapshot barrier' then perform pg_sleep(2);end if;${barrier}`));
 try{const pending=page.request.get('/api/forms?'+new URLSearchParams({tenantId:fixture.tenantA,view:'manage',search:'Synthetic Forms snapshot barrier'}));await expect.poll(()=>legacy.sql("select count(*)from pg_stat_activity where wait_event='PgSleep'and query like '%read_forms%'")).toBe('1');legacy.sql(`update public.tenant_memberships set role='manager'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);expect((await pending).status()).toBe(403);}
 finally{legacy.sql(`update public.tenant_memberships set role='owner'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);legacy.sql(definition);}
 await library(page);await page.getByRole('button',{name:'Manage forms',exact:true}).click();await page.getByRole('button',{name:'Open form '+formName,exact:true}).click();await expect(page.getByRole('button',{name:'View submissions',exact:true})).toBeVisible();
 let release,ready;const held=new Promise(resolve=>{ready=resolve}),gate=new Promise(resolve=>{release=resolve});let first=true;
 await page.route('**/api/forms/**',async route=>{if(first&&route.request().method()==='GET'&&new URL(route.request().url()).pathname===`/api/forms/${formId}`){first=false;const r=await route.fetch();expect(r.status()).toBe(200);const body=await r.body();ready();await gate;await route.fulfill({response:r,body}).catch(()=>{});}else await route.continue();});
 await page.getByRole('button',{name:'Refresh Forms',exact:true}).click();await held;legacy.sql(`update public.tenant_memberships set role='manager'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);
 try{const denied=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname==='/api/forms');await invokeReact(page.getByRole('button',{name:'Refresh Forms',exact:true}));expect((await denied).status()).toBe(403);await expect(page.getByRole('region',{name:'Forms recovery',exact:true})).toBeVisible();release();await expect(page.getByRole('button',{name:'Create form',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'View submissions',exact:true})).toHaveCount(0);await expect(page.getByRole('textbox',{name:'Safety note',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Open form '+formName,exact:true})).toHaveCount(0);}
 finally{release();legacy.sql(`update public.tenant_memberships set role='owner'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);}
});

test('held durable progress ACK blocks actual handlers, departure preserves field-free recovery, and a failed fresh read cannot unlock or recover discarded answers',async({page})=>{
 await login(page);const made=await saved(page.request,mutation({action:'create_form',name:'Synthetic held autosave form',description:'',schema,audienceIds:[fixture.accounts.employee.id],allowRespondentEdit:false}));await saved(page.request,mutation({action:'publish_form',formId:made.formId,formRevision:made.formRevision}));
 const employee=await otherContext(page,'employee'),reader=employee.page,key=`ct-alt:forms:${fixture.accounts.employee.id}:${fixture.tenantA}`;let release;try{
  await library(reader);await reader.getByRole('button',{name:'Open form Synthetic held autosave form',exact:true}).click();await expect(reader.getByRole('textbox',{name:'Safety note',exact:true})).toHaveValue('');let ready,attempt;const held=new Promise(resolve=>{ready=resolve}),gate=new Promise(resolve=>{release=resolve});const calls=[];
  reader.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/forms'))calls.push({method:r.method(),url:r.url(),body:r.method()==='POST'?r.postDataJSON():null});});
  await reader.route('**/api/forms',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}attempt=route.request().postDataJSON();const r=await route.fetch();expect(r.status()).toBe(200);const data=await r.json();identity(data.saved,'employee');const body=await r.body();ready();await gate;await route.fulfill({response:r,body}).catch(()=>{});});
  const privateText='Private held original answer 東京 😀';await reader.getByRole('textbox',{name:'Safety note',exact:true}).fill(privateText);await held;const marker=await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key);expect(marker).toEqual({action:'save_progress',operationId:attempt.operationId});expect(JSON.stringify(marker)).not.toContain(privateText);expect(JSON.stringify(marker)).not.toContain(made.formId);const count=calls.length;
  await invokeReact(reader.getByRole('button',{name:'Refresh Forms',exact:true}));await invokeReact(reader.getByRole('button',{name:'Save progress',exact:true}));await invokeReact(reader.getByRole('button',{name:'Recover Forms',exact:true}));expect(calls).toHaveLength(count);expect(await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key)).toEqual(marker);
  await reader.getByRole('link',{name:'Users',exact:true}).click();await expect(reader).toHaveURL(/\/agents/);await expect(reader.getByRole('heading',{name:'Forms',exact:true})).toHaveCount(0);release();await reader.unroute('**/api/forms');await library(reader);await expect(reader.getByRole('region',{name:'Forms recovery',exact:true})).toBeVisible();expect(await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key)).toEqual(marker);expect(calls.filter(call=>call.method==='POST'&&new URL(call.url).pathname==='/api/forms')).toHaveLength(1);
  let fail=true;await reader.route(`**/api/forms/${made.formId}?*`,async route=>{if(fail){fail=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Synthetic failed fresh current read'})});}else await route.continue();});
  const recovery=reader.waitForResponse(r=>new URL(r.url()).pathname==='/api/forms/reconcile');await reader.getByRole('button',{name:'Recover Forms',exact:true}).click();const reconciled=await recovery;expect(reconciled.status()).toBe(200);const body=await reconciled.json();identity(body,'employee');expect(body.status).toBe('recorded');expect(body.saved.formId).toBe(made.formId);await expect(reader.getByRole('region',{name:'Forms recovery',exact:true})).toBeVisible();expect(await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key)).toEqual(marker);await expect(reader.getByRole('textbox',{name:'Safety note',exact:true})).toHaveCount(0);
  await reader.getByRole('button',{name:'Recover Forms',exact:true}).click();await expect(reader.getByRole('textbox',{name:'Safety note',exact:true})).toHaveValue(privateText);await expect(reader.getByRole('region',{name:'Forms recovery',exact:true})).toHaveCount(0);expect(await reader.evaluate(key=>sessionStorage.getItem(key),key)).toBe(null);expect(calls.filter(call=>call.method==='POST'&&new URL(call.url).pathname==='/api/forms')).toHaveLength(1);
  const reconciles=calls.filter(call=>new URL(call.url).pathname==='/api/forms/reconcile');expect(reconciles).toHaveLength(2);for(const call of reconciles)expect(call.body).toEqual({tenantId:fixture.tenantA,...marker});
  await captureDesktop(reader,'test-results/forms-live-desktop-review.png');
 }finally{release?.();await employee.context.close();}
});

test('desktop owner builder saves and edits an ordered typed schema, searches fixed Auth assignees, publishes, and accepts the assigned original response',async({page})=>{
 await login(page);await library(page);await page.getByRole('button',{name:'Manage forms',exact:true}).click();await page.getByRole('button',{name:'Create form',exact:true}).click();const name='Synthetic desktop-built form 東京 😀';await page.getByLabel('Form name',{exact:true}).fill(name);await page.getByLabel('Form description',{exact:true}).fill('Real desktop builder, fixed original Auth recipient');
 await page.getByRole('button',{name:'Add text',exact:true}).click();await page.getByLabel('Question label 1',{exact:true}).fill('Builder text');await page.getByRole('checkbox',{name:'Required question 1',exact:true}).check();
 await page.getByRole('button',{name:'Add yes no',exact:true}).click();await page.getByLabel('Question label 2',{exact:true}).fill('Builder acknowledgement');await page.getByRole('checkbox',{name:'Required question 2',exact:true}).check();
 await page.getByRole('button',{name:'Add number',exact:true}).click();await page.getByLabel('Question label 3',{exact:true}).fill('Builder quantity');await page.getByRole('checkbox',{name:'Required question 3',exact:true}).check();await page.getByRole('button',{name:'Move question 3 up',exact:true}).click();
 await page.getByLabel('Search eligible people',{exact:true}).fill('Synthetic employee');const roster=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname==='/api/forms/roster'&&new URL(r.url()).searchParams.get('search')==='Synthetic employee');await page.getByRole('button',{name:'Search people',exact:true}).click();const rosterResponse=await roster;expect(rosterResponse.status()).toBe(200);const people=await rosterResponse.json();identity(people);expect(people.users).toEqual([{actorId:fixture.accounts.employee.id,name:'Synthetic employee',eligible:true}]);await page.getByRole('checkbox',{name:'Synthetic employee',exact:true}).check();
 const create=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='create_form');await page.getByRole('button',{name:'Save draft form',exact:true}).click();const created=await create;expect(created.status()).toBe(200);const createdBody=await created.json();identity(createdBody.saved);const independentId=createdBody.saved.formId,submittedSchema=created.request().postDataJSON().change.schema;expect(submittedSchema.map(field=>field.kind)).toEqual(['text','number','yes_no']);expect(created.request().postDataJSON().change.audienceIds).toEqual([fixture.accounts.employee.id]);await expect(page.getByRole('button',{name:'Edit form',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit form',exact:true}).click();await page.getByRole('button',{name:'Move question 1 down',exact:true}).click();await page.getByLabel('Question label 2',{exact:true}).fill('Builder text edited');const edit=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='edit_form');await page.getByRole('button',{name:'Save form changes',exact:true}).click();expect((await edit).status()).toBe(200);await expect(page.getByRole('button',{name:'Publish form',exact:true})).toBeEnabled();const draft=await form(page.request,'manage','owner',independentId);expect(draft.schema.map(field=>[field.kind,field.label])).toEqual([['number','Builder quantity'],['text','Builder text edited'],['yes_no','Builder acknowledgement']]);expect(draft.assignees).toEqual([{actorId:fixture.accounts.employee.id,name:'Synthetic employee',eligible:true}]);
 const publish=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='publish_form');await page.getByRole('button',{name:'Publish form',exact:true}).click();const published=await publish;expect(published.status()).toBe(200);identity((await published.json()).saved);const frozen=await form(page.request,'manage','owner',independentId);expect(frozen.form).toMatchObject({status:'published',schemaFrozen:true,revision:draft.form.revision+1});expect(frozen.schema).toEqual(draft.schema);
 const employee=await otherContext(page,'employee');try{await library(employee.page);await employee.page.getByRole('button',{name:'Open form '+name,exact:true}).click();await employee.page.getByRole('textbox',{name:'Builder quantity',exact:true}).fill('2.000001');await employee.page.getByRole('textbox',{name:'Builder text edited',exact:true}).fill('Desktop original answer 東京 😀');await employee.page.getByRole('group',{name:/Builder acknowledgement/}).getByRole('radio',{name:'No',exact:true}).check();const submit=employee.page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='submit_response');await employee.page.getByRole('button',{name:'Send response',exact:true}).click();expect((await submit).status()).toBe(200);await expect(employee.page.getByText('Your response was submitted.',{exact:true})).toBeVisible();const fresh=await form(employee.page.request,'mine','employee',independentId);expect(fresh.response.status).toBe('submitted');expect(fresh.response.schema).toEqual(frozen.schema);expect(fresh.response.answers).toEqual(Object.fromEntries(frozen.schema.map(field=>[field.id,field.kind==='number'?'2.000001':field.kind==='text'?'Desktop original answer 東京 😀':false])));}finally{await employee.context.close();}
});

test('desktop management table and precise history paging edit submitted content and review independently with signed scope and persisted revision checks',async({page})=>{
 await login(page);const before=await response(page.request);await library(page);await page.getByRole('button',{name:'Manage forms',exact:true}).click();await page.getByRole('button',{name:'Open form '+formName,exact:true}).click();const listed=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname===`/api/forms/${formId}/responses`);await page.getByRole('button',{name:'View submissions',exact:true}).click();const listResponse=await listed;expect(listResponse.status()).toBe(200);const list=await listResponse.json();identity(list);expect(list.form.id).toBe(formId);expect(list.responses.map(item=>item.id)).toEqual([responseId]);
 const leaf=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname===`/api/forms/${formId}/responses/${responseId}`);await page.getByRole('button',{name:'Open response Synthetic employee',exact:true}).click();const detailResponse=await leaf;expect(detailResponse.status()).toBe(200);const detail=await detailResponse.json();identity(detail);expect(detail.response.id).toBe(responseId);expect(detail.form.id).toBe(formId);expect(detail.history).toHaveLength(10);const pane=page.getByRole('region',{name:'Submission detail',exact:true});await expect(pane).toBeVisible();
 const next=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname===`/api/forms/${formId}/responses/${responseId}`&&new URL(r.url()).searchParams.has('cursor'));await pane.getByRole('button',{name:'Load more history',exact:true}).click();const nextResponse=await next;expect(nextResponse.status()).toBe(200);const nextData=await nextResponse.json();identity(nextData);expect(nextData.response.id).toBe(responseId);expect(nextData.collectionVersion).toBe(detail.collectionVersion);await expect(pane.locator('.forms-history details')).toHaveCount(before.historyCount);
 await pane.getByRole('button',{name:'Edit submitted answers',exact:true}).click();await pane.getByRole('textbox',{name:'Safety note',exact:true}).fill('Desktop administrator content edit 東京 😀');const edited=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='admin_edit_response');await pane.getByRole('button',{name:'Save edited answers',exact:true}).click();const editResponse=await edited;expect(editResponse.status()).toBe(200);const ack=(await editResponse.json()).saved;identity(ack);expect(ack).toMatchObject({formId,responseId,responseRevision:before.response.revision+1});await expect(pane.getByRole('button',{name:'Edit submitted answers',exact:true})).toBeVisible();const changed=await response(page.request);expect(changed.response.answers[ids.text]).toBe('Desktop administrator content edit 東京 😀');expect(changed.response).toMatchObject({submittedAt,lastEditedBy:fixture.accounts.owner.id,formName:originalName,revision:ack.responseRevision});expect(changed.response.schema).toEqual(schema);expect(changed.historyCount).toBe(before.historyCount+1);
 const reviewed=!changed.response.reviewed,reviewWrite=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/forms'&&r.request().postDataJSON()?.change?.action==='review_response');await pane.getByRole('button',{name:reviewed?'Mark reviewed':'Mark not reviewed',exact:true}).click();expect((await reviewWrite).status()).toBe(200);await expect(pane.getByRole('button',{name:reviewed?'Mark not reviewed':'Mark reviewed',exact:true})).toBeVisible();const fresh=await response(page.request);expect(fresh.response).toMatchObject({revision:changed.response.revision+1,reviewed,lastEditedBy:changed.response.lastEditedBy,lastEditorName:changed.response.lastEditorName,lastEditedAt:changed.response.lastEditedAt,submittedAt});expect(fresh.historyCount).toBe(changed.historyCount);if(reviewed){expect(fresh.response.reviewedBy).toBe(fixture.accounts.owner.id);expect(fresh.response.reviewedAt).toBeTruthy();}
 const persisted=JSON.parse(legacy.sql(`select jsonb_build_object('revision',revision,'answers',answers,'lastEditedBy',last_edited_by,'lastEditedAt',workforce_private.forms_time(last_edited_at),'reviewed',reviewed,'reviewedBy',reviewed_by)from public.form_responses where id='${responseId}'and form_id='${formId}'and tenant_id='${fixture.tenantA}'`));expect(persisted).toEqual({revision:fresh.response.revision,answers:fresh.response.answers,lastEditedBy:fresh.response.lastEditedBy,lastEditedAt:fresh.response.lastEditedAt,reviewed,reviewedBy:fresh.response.reviewedBy});await captureDesktop(page,'test-results/forms-management-live-desktop-review.png');
});
