import{test,expect}from'@playwright/test';
import{readFileSync}from'node:fs';
import{spawnSync}from'node:child_process';
import{createFormsReportingFixture,reportingIds as I,literalWorkbookText,quote}from'./forms-reporting-auth-fixture.mjs';
const fixture=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8')),origin='http://127.0.0.1:5180';let data;
test.describe.configure({mode:'serial'});test.setTimeout(120000);
function identity(value,actor='owner'){expect(value).toMatchObject({tenantId:fixture.tenantA,actorId:fixture.accounts[actor].id,role:fixture.accounts[actor].role});}
async function login(page,actor='owner'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(fixture.accounts[actor].email);await page.getByLabel('Password',{exact:true}).fill(fixture.accounts[actor].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}
async function context(page,actor){const ctx=await page.context().browser().newContext({baseURL:origin}),p=await ctx.newPage();await login(p,actor);return{ctx,page:p};}
const reportUrl=(kind='entries',extra={},id=I.form)=>`/api/forms/${id}/reports?${new URLSearchParams({tenantId:fixture.tenantA,kind,...extra})}`;
const exportUrl=(kind='entries',extra={},id=I.form)=>`/api/forms/${id}/reports/export?${new URLSearchParams({tenantId:fixture.tenantA,kind,...extra})}`;
async function report(request,kind='entries',extra={},actor='owner',id=I.form){const r=await request.get(reportUrl(kind,extra,id));expect(r.status(),await r.text()).toBe(200);expect(r.headers()['cache-control']).toContain('no-store');const body=await r.json();identity(body,actor);expect(body).toMatchObject({kind,company:{id:fixture.tenantA,time_zone:'Europe/London'},form:{id}});return body;}
async function workbook(request,kind='entries',extra={},actor='owner',id=I.form){const r=await request.get(exportUrl(kind,extra,id));expect(r.status(),r.status()===200?'Expected genuine XLSX':await r.text()).toBe(200);const h=r.headers();expect(h['content-type']).toContain('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');expect(h['cache-control']).toContain('no-store');expect(h['x-content-type-options']).toBe('nosniff');expect(h['content-disposition']).toContain(`forms-${id}-${kind}.xlsx`);expect(h).toMatchObject({'x-ct-alt-actor-id':fixture.accounts[actor].id,'x-ct-alt-company-id':fixture.tenantA,'x-ct-alt-form-id':id,'x-ct-alt-role':fixture.accounts[actor].role,'x-ct-alt-report-kind':kind,'x-ct-alt-form-revision':'2'});expect(h['x-ct-alt-collection-version']).toBeTruthy();const bytes=await r.body();expect(bytes.byteLength).toBeLessThanOrEqual(8388608);return{bytes,headers:h,parsed:parseWorkbook(bytes)};}
// Independent standard-library ZIP CRC and XML parser; no import from the exporter.
function parseWorkbook(bytes){const code=String.raw`
import sys,io,json,zipfile,re,xml.etree.ElementTree as E
z=zipfile.ZipFile(io.BytesIO(sys.stdin.buffer.read()))
assert z.testzip() is None
assert sum(i.file_size for i in z.infolist())<=8388608
assert all(i.compress_type==zipfile.ZIP_STORED for i in z.infolist())
assert len(z.namelist())==len(set(z.namelist()))
assert all(not n.startswith('/') and '..' not in n.split('/') and not any(x in n.lower() for x in ['vba','macro','external','connections']) for n in z.namelist())
ns={'s':'http://schemas.openxmlformats.org/spreadsheetml/2006/main','r':'http://schemas.openxmlformats.org/package/2006/relationships'}
for n in z.namelist():
 if n.endswith('.rels'):
  for rel in E.fromstring(z.read(n)):
   assert rel.get('TargetMode')!='External' and 'hyperlink' not in rel.get('Type','').lower()
w=E.fromstring(z.read('xl/workbook.xml'));rels={r.get('Id'):r.get('Target') for r in E.fromstring(z.read('xl/_rels/workbook.xml.rels'))};sheets=[]
def literal(s):
 s=re.sub(r'_x([0-9a-fA-F]{4})_',lambda m:chr(int(m.group(1),16)),s)
 return s.encode('utf-16','surrogatepass').decode('utf-16')
for sheet in w.findall('s:sheets/s:sheet',ns):
 target=rels[sheet.get('{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id')]
 path=target.lstrip('/') if target.startswith('/') else 'xl/'+target
 root=E.fromstring(z.read(path));assert root.find('.//s:f',ns) is None and root.find('.//s:hyperlinks',ns) is None
 rows=[]
 for row in root.findall('s:sheetData/s:row',ns):
  cells=[]
  for c in row.findall('s:c',ns):
   if c.get('t')=='inlineStr':cells.append(literal(''.join(c.itertext())))
   else:cells.append(c.findtext('s:v','',ns))
  rows.append(cells)
 sheets.append({'name':sheet.get('name'),'rows':rows})
print(json.dumps({'files':z.namelist(),'sheets':sheets},ensure_ascii=True))
`;const parsed=spawnSync('python3',['-c',code],{input:bytes,encoding:'utf8',timeout:10000,maxBuffer:16777216});if(parsed.error||parsed.status!==0)throw Error(parsed.error?.message||parsed.stderr);return JSON.parse(parsed.stdout);}
const sheet=(value,name)=>{const found=value.sheets.find(sheet=>sheet.name===name);expect(found).toBeTruthy();return found.rows;};
test.beforeAll(()=>{data=createFormsReportingFixture(fixture);});test.afterAll(()=>{if(data){expect(data.capture()).toBe(data.beforeRows);expect(data.functions()).toBe(data.beforeFunctions);}});

test('current signed reporting denies foreign and nonmanagement identities, while private progress is indistinguishable from no response',async({page})=>{
 await login(page);const entries=await report(page.request),status=await report(page.request,'status'),summary=await report(page.request,'summary');expect(entries.counts).toEqual({total:1006,reviewed:502,notReviewed:504});expect(status.counts).toEqual({total:4,submitted:3,notSubmitted:1,eligible:3,assignmentTotal:4,assignmentEligible:3});expect(status.users.find(row=>row.actorId===fixture.accounts.employee.id)?.response).toBe(null);expect(JSON.stringify([entries,status,summary])).not.toContain('Private unfinished answer');expect(JSON.stringify([entries,status,summary])).not.toContain(I.private);expect((await page.request.get(`/api/forms/${I.form}?tenantId=${fixture.tenantA}&view=mine`)).status()).toBe(403);
 const privateRow=data.sql(`select to_jsonb(r)from public.form_responses r where id='${I.private}'`);data.sql(`delete from public.form_responses where id='${I.private}'`);try{const absent=await report(page.request,'status'),noProgress=await report(page.request,'summary');expect(absent.collectionVersion).toBe(status.collectionVersion);expect(absent.users).toEqual(status.users);expect(absent.counts).toEqual(status.counts);expect(noProgress.collectionVersion).toBe(summary.collectionVersion);expect(noProgress.fields).toEqual(summary.fields);}finally{data.sql(`insert into public.form_responses select *from jsonb_populate_record(null::public.form_responses,${quote(privateRow)}::jsonb)`);}
 for(const actor of['admin','manager','employee','foreign']){const other=await context(page,actor);try{for(const kind of['entries','status','summary','field']){const extra=kind==='field'?{fieldId:I.yes}:{};expect((await other.page.request.get(reportUrl(kind,extra))).status()).toBe(actor==='admin'?200:403);}expect((await other.page.request.get(exportUrl())).status()).toBe(actor==='admin'?200:403);if(actor==='employee'){const own=await other.page.request.get(`/api/forms/${I.form}?tenantId=${fixture.tenantA}&view=mine`);expect(own.status()).toBe(200);expect((await own.json()).response.answers[I.text]).toBe('Private unfinished answer never in reports');}}finally{await other.ctx.close();}}
});

test('inclusive company-calendar spring/fall DST, exact scoped status, strict invalid dates and literal filters preserve first-submission semantics',async({page})=>{
 await login(page);const spring=await report(page.request,'entries',{from:'2026-03-29',to:'2026-03-29'});expect(spring.counts).toEqual({total:1000,reviewed:500,notReviewed:500});const fall=await report(page.request,'entries',{from:'2026-10-25',to:'2026-10-25'});expect(fall.counts).toEqual({total:2,reviewed:1,notReviewed:1});expect(new Set(fall.responses.map(row=>row.id))).toEqual(new Set([data.bulkResponse(4),data.bulkResponse(5)]));const status=await report(page.request,'status',{from:'2026-03-29',to:'2026-03-29'});expect(status.counts).toEqual({total:4,submitted:1,notSubmitted:3,eligible:3,assignmentTotal:4,assignmentEligible:3});expect(status.users.find(row=>row.actorId===fixture.accounts.manager.id).response).toBe(null);
 const literal=await report(page.request,'entries',{search:'%_\\'});expect(literal.counts.total).toBe(1);expect(literal.responses[0].id).toBe(data.bulkResponse(1));const selected=await report(page.request,'status',{search:'%_\\',submission:'submitted'});expect(selected.counts).toEqual({total:1,submitted:1,notSubmitted:0,eligible:0,assignmentTotal:4,assignmentEligible:3});
 for(const extra of[{from:'2026-03-29'},{from:'2026-02-30',to:'2026-03-01'},{from:'2026-10-25',to:'2026-03-29'},{from:'2025-01-01',to:'2026-12-31'},{submission:'not_submitted'},{fieldId:I.yes},{fieldAnswer:'empty'}])expect((await page.request.get(reportUrl('entries',extra))).status()).toBe(400);
 expect((await page.request.get(reportUrl('summary',{limit:'1'}))).status()).toBe(400);expect((await page.request.get(reportUrl('field',{fieldId:I.description}))).status()).toBe(400);expect((await page.request.get(reportUrl()+'&kind=entries')).status()).toBe(400);expect((await page.request.get(exportUrl('entries',{limit:'50'}))).status()).toBe(400);
});

test('exact ordered summaries and field response paging count false, optional whitespace and empty multi-choice with retained option labels',async({page})=>{
 await login(page);const summary=await report(page.request,'summary');expect(summary.schema).toEqual(data.schema);expect(summary.fields.map(field=>field.fieldId)).toEqual([I.text,I.yes,I.single,I.multiple,I.number]);const byId=Object.fromEntries(summary.fields.map(field=>[field.fieldId,field]));expect(byId[I.text]).toMatchObject({total:1006,answered:670,empty:336});expect(byId[I.yes]).toMatchObject({total:1006,answered:1006,empty:0});expect(byId[I.yes].options.map(option=>[option.label,option.count])).toEqual([['Yes',1],['No',1005]]);expect(byId[I.single]).toMatchObject({answered:805,empty:201});expect(byId[I.multiple]).toMatchObject({answered:503,empty:503});expect(byId[I.multiple].options.map(option=>[option.label,option.count])).toEqual([['Gloves, 東京',503],['Mask | "😀"',503]]);expect(byId[I.number]).toMatchObject({answered:863,empty:143});
 const empty=await report(page.request,'field',{fieldId:I.multiple,fieldAnswer:'empty',limit:'100'});expect(empty.counts).toEqual({total:1006,answered:503,empty:503,matched:503});expect(empty.responses.every(row=>row.answered===false&&Array.isArray(row.answer)&&row.answer.length===0)).toBe(true);let cursor=empty.nextCursor,rows=[...empty.responses];while(cursor){const next=await report(page.request,'field',{fieldId:I.multiple,fieldAnswer:'empty',limit:'100',cursor});rows.push(...next.responses);cursor=next.nextCursor;}expect(rows).toHaveLength(503);expect(new Set(rows.map(row=>row.response.id)).size).toBe(503);expect(JSON.stringify(rows)).not.toContain(I.private);
 const falseRows=await report(page.request,'field',{fieldId:I.yes,limit:'100'});expect(falseRows.responses.every(row=>row.answered)).toBe(true);expect(falseRows.responses.some(row=>row.answer===false)).toBe(true);
});

test('complete >1000-row XLSX is independent of visible paging and preserves exact strings, UTC microseconds and inert OOXML content',async({page})=>{
 await login(page);const first=await report(page.request,'entries',{limit:'50'});expect(first.responses).toHaveLength(50);expect(first.nextCursor).toBeTruthy();const entries=await workbook(page.request);expect(entries.headers['x-ct-alt-collection-version']).toBe(first.collectionVersion);expect(entries.parsed.sheets.map(sheet=>sheet.name)).toEqual(['Report','Submissions']);const rows=sheet(entries.parsed,'Submissions');expect(rows).toHaveLength(1007);const header=rows[0];for(const field of data.schema.filter(field=>field.kind!=='description'))expect(header).toContain(field.label);expect(header).not.toContain(data.schema[0].text);const body=rows.slice(1);expect(new Set(body.map(row=>row[0])).size).toBe(1006);expect(body.some(row=>row.includes(I.private))).toBe(false);const special=body.find(row=>row.includes(data.bulkResponse(1)));expect(special).toBeTruthy();expect(special[header.indexOf(data.schema[1].label)]).toBe(literalWorkbookText);expect(special[header.indexOf(data.schema[2].label)]).toBe('No');expect(special[header.indexOf(data.schema[4].label)]).toBe(JSON.stringify(['Gloves, 東京','Mask | "😀"']));expect(special[header.indexOf(data.schema[5].label)]).toBe('-999999999999.123456');expect(special).toContain('2026-03-29T00:00:00.123456Z');expect(special).toContain('2026-10-04T01:02:03.123456Z');expect(special).toContain('=Original retained form title 東京 😀');expect(sheet(entries.parsed,'Report').flat()).toContain('Europe/London');
 const status=await workbook(page.request,'status');expect(status.parsed.sheets.map(sheet=>sheet.name)).toEqual(['Report','Assigned users']);expect(sheet(status.parsed,'Assigned users')).toHaveLength(5);expect(JSON.stringify(status.parsed)).not.toContain(I.private);expect(JSON.stringify(status.parsed)).not.toContain('Private unfinished answer');const zero=await workbook(page.request,'entries',{from:'2025-01-01',to:'2025-01-01'});expect(sheet(zero.parsed,'Submissions')).toHaveLength(1);
 const ids=[];let cursor;do{const next=await report(page.request,'entries',{limit:'100',...cursor?{cursor}:{}});ids.push(...next.responses.map(row=>row.id));cursor=next.nextCursor;}while(cursor);expect(ids).toHaveLength(1006);expect(new Set(ids).size).toBe(1006);expect(new Set(body.map(row=>row[0]))).toEqual(new Set(ids));
});

test('full summary/export limits refuse oversize scopes without truncation, and changed cursor filters/version/current permissions remain scoped',async({page})=>{
 await login(page);for(const id of[I.answersOversize,I.rowsOversize]){const visible=await report(page.request,'entries',{limit:'1'},'owner',id);expect(visible.responses).toHaveLength(1);expect((await page.request.get(reportUrl('summary',{},id))).status()).toBe(413);const r=await page.request.get(exportUrl('entries',{},id));expect(r.status()).toBe(413);expect(r.headers()['content-type']).toContain('application/json');expect(r.headers()['cache-control']).toContain('no-store');expect(r.headers()['content-disposition']).toBeUndefined();}
 const first=await report(page.request,'entries',{limit:'1'});expect(first.nextCursor).toBeTruthy();expect((await page.request.get(reportUrl('entries',{cursor:first.nextCursor,search:'Different literal'}))).status()).toBe(409);const admin=await context(page,'admin');try{expect((await admin.page.request.get(reportUrl('entries',{cursor:first.nextCursor}))).status()).toBe(409);}finally{await admin.ctx.close();}
 const prior=data.sql(`select reviewed,reviewed_at,reviewed_by,reviewer_name,revision from public.form_responses where id='${data.bulkResponse(2)}'`);expect(prior).toBeTruthy();const record=data.sql(`select to_jsonb(r)from public.form_responses r where id='${data.bulkResponse(2)}'`);data.sql(`update public.form_responses set revision=revision+1 where id='${data.bulkResponse(2)}'`);try{expect((await page.request.get(reportUrl('entries',{cursor:first.nextCursor}))).status()).toBe(409);}finally{const value=JSON.parse(record);data.sql(`update public.form_responses set revision=${value.revision} where id='${data.bulkResponse(2)}'`);}
});

test('old signed cookies, original Auth relinks and post-snapshot revocation preserve current report access without changing legacy rows',async({page})=>{
 await login(page);const original=(await report(page.request,'status')).collectionVersion,managerAgent=data.sql(`select id from public.agents where user_id='${fixture.accounts.manager.id}'and tenant_id='${fixture.tenantA}'`);data.sql(`update public.agents set user_id=null where id in('${data.employee}','${managerAgent}');update public.agents set user_id='${fixture.accounts.manager.id}'where id='${data.employee}';update public.agents set user_id='${fixture.accounts.employee.id}'where id='${data.replacement}'`);try{expect((await report(page.request,'status')).collectionVersion).toBe(original);const employee=await context(page,'employee');try{expect((await employee.page.request.get(reportUrl())).status()).toBe(403);const own=await employee.page.request.get(`/api/forms/${I.form}?tenantId=${fixture.tenantA}&view=mine`);expect(own.status()).toBe(200);expect((await own.json()).response.actorId).toBe(fixture.accounts.employee.id);}finally{await employee.ctx.close();}}finally{data.sql(`update public.agents set user_id=null where id in('${data.employee}','${data.replacement}');update public.agents set user_id='${fixture.accounts.employee.id}'where id='${data.employee}';update public.agents set user_id='${fixture.accounts.manager.id}'where id='${managerAgent}'`);}
 const auth=JSON.parse(data.sql(`select to_jsonb(u)from auth.users u where id='${fixture.accounts.owner.id}'`));for(const[change,restore]of[
 [`update public.tenant_memberships set role='manager'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`,`update public.tenant_memberships set role='owner'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`],
 [`update public.tenant_memberships set status='suspended'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`,`update public.tenant_memberships set status='active'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`],
 [`update public.tenants set status='suspended'where id='${fixture.tenantA}'`,`update public.tenants set status='active'where id='${fixture.tenantA}'`],
 [`update auth.users set email_confirmed_at=null where id='${fixture.accounts.owner.id}'`,`update auth.users set email_confirmed_at=${quote(auth.email_confirmed_at)} where id='${fixture.accounts.owner.id}'`],
 [`update auth.users set is_anonymous=true where id='${fixture.accounts.owner.id}'`,`update auth.users set is_anonymous=${auth.is_anonymous?'true':'false'} where id='${fixture.accounts.owner.id}'`],
 ]){data.sql(change);try{expect((await page.request.get(reportUrl())).status()).toBe(403);expect((await page.request.get(exportUrl())).status()).toBe(403);}finally{data.sql(restore);}}
 // Guarded disposable-fixture-only STABLE snapshot barrier; exact source and ACL restoration is asserted afterAll.
 const signature='public.read_forms_reporting(uuid,uuid,text,jsonb,integer,jsonb,boolean)',definition=data.sql(`select pg_get_functiondef('${signature}'::regprocedure)`),marker=' perform workforce_private.forms_reporting_filters(report_kind,filters);';
 expect(definition.split(marker)).toHaveLength(2);const heldDefinition=definition.replace(marker,` perform pg_sleep(2.5);${marker}`);data.sql(heldDefinition);const pending=page.request.get(reportUrl());
 try{await expect.poll(()=>Number(data.sql("select count(*)from pg_stat_activity where pid<>pg_backend_pid()and wait_event='PgSleep'and query like '%read_forms_reporting%'")),{timeout:15000}).toBeGreaterThan(0);data.sql(`update public.tenant_memberships set role='manager'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);const denied=await pending;expect(denied.status(),await denied.text()).toBe(403);expect(denied.headers()['cache-control']).toContain('no-store');}finally{await pending.catch(()=>{});data.sql(`update public.tenant_memberships set role='owner'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);data.sql(definition);expect(data.sql(`select pg_get_functiondef('${signature}'::regprocedure)`)).toBe(definition);}

});

async function signedUiReport(page,action,kind='entries',extra={}){
 const pending=page.waitForResponse(r=>{const u=new URL(r.url());return u.pathname===`/api/forms/${I.form}/reports`&&u.searchParams.get('kind')===kind&&Object.entries(extra).every(([key,value])=>u.searchParams.get(key)===value);});
 await action();const response=await pending;expect(response.status(),await response.text()).toBe(200);const body=await response.json();identity(body);expect(body).toMatchObject({kind,form:{id:I.form,revision:2}});return body;
}
async function openReporting(page){
 await page.goto('/forms?company='+fixture.tenantA);await expect(page.getByRole('heading',{name:'Forms',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Manage forms',exact:true}).click();
 const detail=page.waitForResponse(r=>{const u=new URL(r.url());return u.pathname===`/api/forms/${I.form}`&&u.searchParams.get('view')==='manage';});
 await page.getByRole('button',{name:'Open form Synthetic reporting form 東京 😀',exact:true}).click();const response=await detail;expect(response.status(),await response.text()).toBe(200);identity(await response.json());
 await signedUiReport(page,()=>page.getByRole('button',{name:'Reporting',exact:true}).click());return page.getByRole('region',{name:'Forms reporting',exact:true});
}
async function captureDesktop(page,name){await page.evaluate(async()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo(0,0);await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});await page.screenshot({path:`test-results/forms-reporting-${name}-desktop-review.png`,fullPage:true});}
async function forceClick(locator){await locator.evaluate(button=>{const key=Object.keys(button).find(key=>key.startsWith('__reactProps$'));const props=key&&button[key];if(typeof props?.onClick!=='function')throw Error('Expected actual React onClick handler');props.onClick({preventDefault(){},stopPropagation(){},currentTarget:button,target:button});});}
async function holdRealWorkbook(page){
 await page.evaluate(()=>{
  window.reportFence={urls:0,clicks:0,held:false,size:0};const originalBlob=Response.prototype.blob,originalUrl=URL.createObjectURL,originalClick=HTMLAnchorElement.prototype.click;
  URL.createObjectURL=function(blob){window.reportFence.urls++;return originalUrl.call(this,blob);};
  HTMLAnchorElement.prototype.click=function(){if(this.download.endsWith('.xlsx'))window.reportFence.clicks++;return originalClick.call(this);};
  Response.prototype.blob=async function(){const blob=await originalBlob.call(this);if(this.url.includes('/reports/export?')){window.reportFence.held=true;window.reportFence.size=blob.size;window.reportFence.headers=Object.fromEntries(this.headers);await new Promise(resolve=>window.releaseReportBlob=resolve);}return blob;};
 });
 await page.getByRole('button',{name:'Export XLSX',exact:true}).click();await page.waitForFunction(()=>window.reportFence?.held===true);
 const proof=await page.evaluate(()=>window.reportFence);expect(proof.size).toBeGreaterThan(1000);expect(proof.headers['x-ct-alt-actor-id']).toBe(fixture.accounts.owner.id);expect(proof.headers['x-ct-alt-form-id']).toBe(I.form);expect(proof.headers['x-ct-alt-report-kind']).toBe('entries');
}
async function releaseWithoutDownload(page){await page.evaluate(()=>window.releaseReportBlob());await page.waitForTimeout(100);expect(await page.evaluate(()=>({urls:window.reportFence.urls,clicks:window.reportFence.clicks}))).toEqual({urls:0,clicks:0});}

test('signed desktop reporting applies real date scopes, renders exact question summaries/drilldown and downloads every matching submission',async({page})=>{
 await login(page);const pane=await openReporting(page);await expect(pane.getByText('1006 submissions · 502 reviewed · 504 not reviewed',{exact:true})).toBeVisible();expect(await pane.locator('tbody tr').count()).toBe(50);
 await pane.getByLabel('From',{exact:true}).fill('2026-10-25');await pane.getByLabel('To',{exact:true}).fill('2026-10-25');const filtered=await signedUiReport(page,()=>pane.getByRole('button',{name:'Apply filters',exact:true}).click(),'entries',{from:'2026-10-25',to:'2026-10-25'});expect(filtered.counts.total).toBe(2);await expect(pane.locator('tbody tr')).toHaveCount(2);
 await signedUiReport(page,()=>pane.getByRole('button',{name:'Show all',exact:true}).click());
 const summary=await signedUiReport(page,()=>pane.getByRole('button',{name:'Summary',exact:true}).click(),'summary');expect(summary.fields).toHaveLength(5);await expect(pane.locator('article')).toHaveCount(5);await captureDesktop(page,'summary');
 // Locate the immutable schema label rather than deriving behavior from display counts.
 const question=pane.locator('article').filter({has:page.getByRole('heading',{name:data.schema[4].label,exact:true})});
 await expect(question.getByText('503 answered · 503 empty · 1006 submissions',{exact:true})).toBeVisible();
 const field=await signedUiReport(page,()=>question.getByRole('button',{name:'View question responses',exact:true}).click(),'field',{fieldId:I.multiple});expect(field.counts).toEqual({total:1006,answered:503,empty:503,matched:1006});
 await signedUiReport(page,()=>pane.getByLabel('Question response status',{exact:true}).selectOption('empty'),'field',{fieldId:I.multiple,fieldAnswer:'empty'});
 await signedUiReport(page,()=>pane.getByRole('button',{name:'Assigned users',exact:true}).click(),'status');await expect(pane.locator('tbody tr')).toHaveCount(4);await expect(pane.locator('.fr-counts p').filter({hasText:/^4 assigned users in scope · 3 submitted · 1 not submitted · 3 eligible\s*4 assigned overall · 3 currently eligible$/})).toBeVisible();await captureDesktop(page,'status');
 await signedUiReport(page,()=>pane.getByRole('button',{name:'Submissions',exact:true}).click());const downloadPromise=page.waitForEvent('download');await pane.getByRole('button',{name:'Export XLSX',exact:true}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe(`forms-${I.form}-entries.xlsx`);const parsed=parseWorkbook(readFileSync(await download.path()));expect(sheet(parsed,'Submissions')).toHaveLength(1007);
 await expect(pane.getByRole('button',{name:'Export XLSX',exact:true})).toBeEnabled();await captureDesktop(page,'live');
 await signedUiReport(page,()=>pane.getByRole('button',{name:'Assigned users',exact:true}).click(),'status');const manager=pane.locator('tbody tr').filter({has:page.getByText('Synthetic manager',{exact:true})});const detail=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/forms/${I.form}/responses/${data.managerResponse}`);await manager.getByRole('button',{name:'Open response',exact:true}).click();const response=await detail;expect(response.status(),await response.text()).toBe(200);const retained=await response.json();identity(retained);expect(retained.response).toMatchObject({id:data.managerResponse,actorId:fixture.accounts.manager.id,status:'submitted',answers:{[I.yes]:true,[I.number]:'000000000001.000001'}});await expect(page.getByRole('region',{name:'Submission detail',exact:true})).toBeVisible();
});

test('genuine held workbook cannot download after filter changes, SPA departure, parent pending/unknown write, or current access denial',async({page})=>{
 await login(page);
 // A draft filter change invalidates the already decoded export scope, even before Apply.
 await openReporting(page);await holdRealWorkbook(page);await page.getByLabel('Search respondents',{exact:true}).fill('A different literal');await releaseWithoutDownload(page);
 // Wait for the actual signed Users route and component departure before releasing old bytes.
 await openReporting(page);await holdRealWorkbook(page);await page.getByRole('link',{name:'Users',exact:true}).click();await expect(page).toHaveURL(/\/agents/);await expect(page.getByRole('region',{name:'Forms reporting',exact:true})).toHaveCount(0);await releaseWithoutDownload(page);
 // Hold an actual parent write before server entry. Handler guards, not disabled DOM, must enforce pending state.
 await openReporting(page);await holdRealWorkbook(page);let writeRoute;await page.route('**/api/forms',async route=>{if(route.request().method()==='POST'){writeRoute=route;}else await route.continue();});
 await page.getByRole('button',{name:'Archive form',exact:true}).click();await expect.poll(()=>Boolean(writeRoute)).toBe(true);const envelope=writeRoute.request().postDataJSON();expect(envelope.change).toMatchObject({action:'archive_form',formId:I.form,formRevision:2});
 const markerKey=`ct-alt:forms:${fixture.accounts.owner.id}:${fixture.tenantA}`,marker=await page.evaluate(key=>sessionStorage.getItem(key),markerKey);expect(JSON.parse(marker)).toEqual({action:'archive_form',operationId:envelope.operationId});let requests=0;const count=request=>{if(new URL(request.url()).pathname.startsWith('/api/forms'))requests++;};page.on('request',count);
 const refresh=page.getByRole('button',{name:'Refresh Forms',exact:true});await forceClick(refresh);await page.waitForTimeout(75);expect(requests).toBe(0);expect(await page.evaluate(key=>sessionStorage.getItem(key),markerKey)).toBe(marker);
 await writeRoute.abort('failed');await expect(page.getByRole('region',{name:'Forms recovery',exact:true})).toBeVisible();await releaseWithoutDownload(page);expect(await page.evaluate(key=>sessionStorage.getItem(key),markerKey)).toBe(marker);page.off('request',count);await page.unroute('**/api/forms');
 // Unknown navigation must not replay anything. A fresh page recovery is intentionally left to retained Forms tests.
 await page.evaluate(key=>sessionStorage.removeItem(key),markerKey);await openReporting(page);await holdRealWorkbook(page);
 data.sql(`update public.tenant_memberships set role='manager'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);
 try{const denied=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/forms/${I.form}/reports`);await page.getByRole('button',{name:'Assigned users',exact:true}).click();expect((await denied).status()).toBe(403);await expect(page.getByRole('region',{name:'Forms reporting',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Archive form',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Reporting',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'Forms recovery',exact:true})).toBeVisible();await releaseWithoutDownload(page);}finally{data.sql(`update public.tenant_memberships set role='owner'where tenant_id='${fixture.tenantA}'and user_id='${fixture.accounts.owner.id}'`);}
 // Corrupt only an identity header on otherwise genuine signed bytes: fail closed before any object URL.
 await openReporting(page);await page.evaluate(()=>{window.invalidExportUrls=0;window.invalidExportClicks=0;const original=URL.createObjectURL,click=HTMLAnchorElement.prototype.click;URL.createObjectURL=function(blob){window.invalidExportUrls++;return original.call(this,blob);};HTMLAnchorElement.prototype.click=function(){if(this.download.endsWith('.xlsx'))window.invalidExportClicks++;return click.call(this);};});
 await page.route('**/reports/export?*',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);await route.fulfill({response,headers:{...response.headers(),'x-ct-alt-company-id':fixture.tenantB}});});
 await page.getByRole('button',{name:'Export XLSX',exact:true}).click();const verified=page.getByRole('region',{name:'Forms reporting',exact:true});await expect(verified.getByRole('alert')).toHaveText('The workbook identity or size could not be verified.');await expect(verified.getByText('1006 submissions · 502 reviewed · 504 not reviewed',{exact:true})).toBeVisible();expect(await page.evaluate(()=>({urls:window.invalidExportUrls,clicks:window.invalidExportClicks}))).toEqual({urls:0,clicks:0});await page.unroute('**/reports/export?*');
});
