import {test,expect} from '@playwright/test';
import {readFileSync,readdirSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';

const fixture=JSON.parse(readFileSync('/tmp/ct-alt-local-fixtures.json','utf8'));
const db='supabase_db_ct-alt-independent',origin='http://127.0.0.1:5180',uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
if(fixture.url!=='http://127.0.0.1:54821'||!/^[0-9a-f]{8}$/.test(fixture.fixtureLabel)||![fixture.tenantA,fixture.tenantB,...Object.values(fixture.accounts).map(account=>account.id)].every(id=>uuid.test(id)))throw Error('Owned isolated loopback fixture required');
test.describe.configure({mode:'serial'});test.setTimeout(120_000);
const bulk='68000000-0000-4000-8000-',retainedId=bulk+'000000002001',replacement=bulk+'000000002002';
const policy='  Synthetic policy\n<b>Literal plain text</b>\n<img src=x onerror="window.__ctKbXSS=1">\nMüller 東京 😀\n  ';
let employee,baseId,sectionId,folderId,textId,linkId,legacy,functions,legacyTables;
const errors=new WeakMap();
const quote=value=>"'"+value.replaceAll("'","''")+"'";
function sql(query){const label=spawnSync('docker',['inspect',db,'--format','{{index .Config.Labels "ct-alt.test"}}'],{encoding:'utf8'});if(label.status!==0||label.stdout.trim()!==fixture.fixtureLabel)throw Error('Wrong owned fixture database');const result=spawnSync('docker',['exec','-i',db,'psql','-X','-q','-At','-v','ON_ERROR_STOP=1','-U','postgres'],{input:query,encoding:'utf8',timeout:30_000});if(result.error||result.status!==0)throw Error(result.error?.message||result.stderr);return result.stdout.trim();}
function snapshot(tables=legacyTables){return sql(`select jsonb_object_agg(name,hash) from (${tables.map(table=>`select ${quote(table)} as name,(select md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]')::text) from ${table} t) as hash`).join(' union all ')}) retained;`);}
const functionSnapshot=`select md5(jsonb_agg(jsonb_build_object('id',p.oid,'definition',pg_get_functiondef(p.oid),'owner',p.proowner,'acl',p.proacl,'config',p.proconfig) order by p.oid)::text) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','workforce_private','chat_private') and p.prokind='f';`;
/** @param {import('../lib/knowledge-base-types').KnowledgeChange} change */
const operation=change=>({tenantId:fixture.tenantA,operationId:randomUUID(),change});
const write=(request,value)=>request.post('/api/knowledge-base',{headers:{Origin:origin},data:value});
function url(kind='catalog',extra={}){const {base=baseId,node,parent,...query}=extra;const path=kind==='catalog'?'/api/knowledge-base':kind==='assignees'?'/api/knowledge-base/assignees':kind==='base'?`/api/knowledge-base/${base}`:kind==='node'?`/api/knowledge-base/${base}/nodes/${node}`:`/api/knowledge-base/${base}/${kind}`;return path+'?'+new URLSearchParams({tenantId:fixture.tenantA,...parent?{parentId:parent}:{},...query});}
async function read(request,kind='catalog',extra={}){const response=await request.get(url(kind,extra));expect(response.status()).toBe(200);expect(response.headers()['cache-control']).toContain('no-store');return response.json();}
async function saved(request,value){const response=await write(request,value);expect(response.status()).toBe(200);expect(response.headers()['cache-control']).toContain('no-store');const {saved}=await response.json();expect(saved.operationId).toBe(value.operationId);expect(saved.action).toBe(value.change.action);return saved;}
async function manage(request,change){const definition=await read(request,'base',{view:'manage',base:change.baseId??baseId});return saved(request,operation({baseId:definition.base.id,revision:definition.base.revision,...change}));}
async function createNode(request,parentId,content){return manage(request,{action:'create_node',parentId,...content});}
async function nodeChange(request,action,nodeId,extra={}){const detail=await read(request,'node',{view:'manage',node:nodeId});return manage(request,{action,nodeId,nodeRevision:detail.node.revision,...extra});}
async function viewOperation(request,nodeId=null){const definition=await read(request,nodeId?'node':'base',{view:'library',...nodeId?{node:nodeId}:{}});return operation({action:'view',baseId,revision:definition.base.revision,nodeId,nodeRevision:nodeId?definition.node.revision:null});}
async function reconcile(request,operationId){return request.post('/api/knowledge-base/reconcile-view',{headers:{Origin:origin},data:{tenantId:fixture.tenantA,operationId}});}
async function login(page,account='owner'){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(fixture.accounts[account].email);await page.getByLabel('Password',{exact:true}).fill(fixture.accounts[account].password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/agents/);}

test.beforeAll(()=>{
 employee=sql(`select id from public.agents where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.employee.id}';`);expect(uuid.test(employee)).toBe(true);
 sql(`insert into auth.users(id,email,email_confirmed_at,role,aud,is_anonymous) select ('${bulk}'||lpad(i::text,12,'0'))::uuid,'knowledge-assignee-'||i||'@example.test',now(),'authenticated','authenticated',false from generate_series(1,1005)i;
 insert into public.tenant_memberships(tenant_id,user_id,display_name,role) select '${fixture.tenantA}',('${bulk}'||lpad(i::text,12,'0'))::uuid,'Synthetic KB account '||lpad(i::text,4,'0'),'employee' from generate_series(1,1005)i;
 insert into public.agents(id,tenant_id,first_name,last_name,phone,created_by) values('${replacement}','${fixture.tenantA}','Synthetic','replacement','+447700902101','${fixture.accounts.owner.id}');
   insert into public.rota_schedules(id,tenant_id,name,time_zone) values('${retainedId}','${fixture.tenantA}','Retained synthetic diary','Europe/London');
 insert into public.rota_admins values('${fixture.tenantA}','${retainedId}','${fixture.accounts.owner.id}');insert into public.rota_agents values('${fixture.tenantA}','${retainedId}','${employee}');
 insert into public.rota_jobs(id,tenant_id,schedule_id,name,color) values('${retainedId}','${fixture.tenantA}','${retainedId}','Retained diary job','#2998ff');
 insert into public.rota_shifts(id,tenant_id,schedule_id,agent_id,job_id,starts_at,ends_at,title,status,published_at) values('${retainedId}','${fixture.tenantA}','${retainedId}','${employee}','${retainedId}','2026-10-03T08:00:00Z','2026-10-03T09:00:00Z','Retained diary shift','published','2026-10-02T12:00:00Z');
 insert into public.time_clock_jobs(id,tenant_id,name) values('${retainedId}','${fixture.tenantA}','Retained clock job');insert into public.time_clock_entries(id,tenant_id,agent_id,job_id,agent_name,job_name,started_at,ended_at) values('${retainedId}','${fixture.tenantA}','${employee}','${retainedId}','Retained employee','Retained clock job','2026-10-03T08:00:00Z','2026-10-03T09:00:00Z');
 insert into public.chat_conversations(id,tenant_id,kind,name,last_sequence) values('${retainedId}','${fixture.tenantA}','group','Retained chat',1);insert into public.chat_members(tenant_id,conversation_id,user_id) values('${fixture.tenantA}','${retainedId}','${fixture.accounts.owner.id}'),('${fixture.tenantA}','${retainedId}','${fixture.accounts.employee.id}');insert into public.chat_messages(tenant_id,conversation_id,sequence,sender_id,sender_name,client_id,body) values('${fixture.tenantA}','${retainedId}',1,'${fixture.accounts.employee.id}','Retained employee',gen_random_uuid(),'Retained synthetic message');



 `);
 sql(`insert into public.time_off_types(id,tenant_id,name,description,paid,created_by) values('${retainedId}','${fixture.tenantA}','Retained leave','Retained leave type',true,'${fixture.accounts.owner.id}');insert into public.time_off_requests(id,tenant_id,agent_id,agent_name,type_id,type_name,type_description,type_paid,start_date,end_date,note,requested_by) values('${retainedId}','${fixture.tenantA}','${employee}','Synthetic employee','${retainedId}','Retained leave','Retained leave type',true,'2026-10-03','2026-10-04','Retained leave request','${fixture.accounts.employee.id}');`);
 sql(`insert into public.updates_posts(id,tenant_id,title,body,status,revision,content_revision,allow_comments,allow_reactions,require_confirmation,created_by,created_name,published_at) values('${retainedId}','${fixture.tenantA}','Retained synthetic bulletin','Retained Updates history','published',2,1,true,true,true,'${fixture.accounts.owner.id}','Synthetic owner','2026-10-03T10:00:00.123456Z');insert into public.updates_recipients(tenant_id,post_id,actor_id,name,viewed_at,confirmed_at) values('${fixture.tenantA}','${retainedId}','${fixture.accounts.employee.id}','Synthetic employee','2026-10-03T10:01:00.123456Z','2026-10-03T10:02:00.654321Z');insert into public.updates_comments(tenant_id,post_id,actor_id,author_name,body) values('${fixture.tenantA}','${retainedId}','${fixture.accounts.employee.id}','Synthetic employee','Retained synthetic comment');
 insert into public.smart_group_segments(id,tenant_id,name,description) values('${retainedId}','${fixture.tenantA}','Retained organizational segment','Synthetic retained definition');insert into public.smart_groups(id,tenant_id,segment_id,name,description,rules) values('${retainedId}','${fixture.tenantA}','${retainedId}','Retained organizational group','Synthetic retained rule','[{"field":"team","values":["North"]}]');`);
 legacyTables=sql(`select schemaname||'.'||tablename from pg_tables where schemaname in('public','workforce_private','chat_private') and tablename not like 'knowledge_%' order by schemaname,tablename;`).split('\n');expect(legacyTables.every(table=>/^(public|workforce_private|chat_private)\.[a-z_]+$/.test(table))).toBe(true);legacy=snapshot();functions=sql(functionSnapshot);
});
test.afterAll(()=>{expect(snapshot()).toBe(legacy);expect(sql(functionSnapshot)).toBe(functions);});test.beforeEach(({page})=>{const found=[];errors.set(page,found);page.on('pageerror',error=>found.push(error.message));});test.afterEach(({page})=>expect(errors.get(page)).toEqual([]));


test('current signed management, whole searched roster, privacy and payload-bound draft receipts',async({page})=>{
 await login(page);const request=page.request;const all=[];let cursor;
 do{const data=await read(request,'assignees',{search:'Synthetic KB account',limit:'100',...cursor?{cursor}:{}});expect(data.matchedCount).toBe(1005);expect(data.users.every(user=>user.eligible)).toBe(true);all.push(...data.users.map(user=>user.actorId));cursor=data.nextCursor;}while(cursor);
 expect(all).toHaveLength(1005);expect(new Set(all).size).toBe(1005);
 const payload=operation({action:'create_base',name:'Synthetic employee handbook',description:'Original synthetic reference',audienceIds:[fixture.accounts.employee.id,fixture.accounts.manager.id]});
 const acknowledgements=await Promise.all([saved(request,payload),saved(request,payload)]);expect(acknowledgements[0]).toEqual(acknowledgements[1]);baseId=acknowledgements[0].baseId;
 expect((await write(request,{...payload,change:{...payload.change,name:'Changed payload'}})).status()).toBe(409);
 const empty=await saved(request,operation({action:'create_base',name:'Synthetic empty draft',description:'',audienceIds:[]})),emptyPublish=operation({action:'publish_base',baseId:empty.baseId,revision:empty.revision});
 const emptyState=`select jsonb_build_object('base',to_jsonb(b),'audience',(select count(*) from public.knowledge_audience where base_id=b.id),'audit',(select count(*) from public.knowledge_audit where base_id=b.id),'receipt',(select count(*) from workforce_private.knowledge_operations where tenant_id='${fixture.tenantA}' and actor_id='${fixture.accounts.owner.id}' and operation_id='${emptyPublish.operationId}')) from public.knowledge_bases b where b.id='${empty.baseId}';`,beforeEmptyPublish=sql(emptyState);
 expect((await write(request,emptyPublish)).status()).toBe(409);expect(sql(emptyState)).toBe(beforeEmptyPublish);expect((await read(request,'base',{base:empty.baseId,view:'manage'})).base).toMatchObject({status:'draft',revision:empty.revision,audienceCount:0});
 expect((await request.post('/api/knowledge-base',{headers:{Origin:'https://foreign.invalid'},data:payload})).status()).toBe(403);
 for(const account of ['admin','manager','employee','foreign']){const context=await page.context().browser().newContext({baseURL:origin});const other=await context.newPage();await login(other,account);const admin=account==='admin';
  expect((await other.request.get(url('catalog',{view:'manage',status:'all'}))).status()).toBe(admin?200:403);expect((await other.request.get(url('assignees'))).status()).toBe(admin?200:403);
  if(!admin){expect((await write(other.request,operation({action:'create_base',name:'Forbidden',description:'',audienceIds:[]}))).status()).toBe(403);expect((await other.request.get(url('base',{view:'library'}))).status()).toBe(403);}else{const authored=await saved(other.request,operation({action:'create_base',name:'Synthetic admin draft',description:'',audienceIds:[]}));await manage(other.request,{action:'edit_base',baseId:authored.baseId,name:'Synthetic admin retained draft',description:'Edited by current admin'});await manage(other.request,{action:'archive_base',baseId:authored.baseId});await manage(other.request,{action:'restore_base',baseId:authored.baseId});}
  await context.close();
 }
 expect(sql(`select count(*) from public.knowledge_bases where tenant_id='${fixture.tenantA}' and name='Synthetic employee handbook'`)).toBe('1');
});

test('real nested resources preserve plain text and ordered identities; invalid links, cycles and archive ancestors fail closed',async({page})=>{
 await login(page);const request=page.request;
 sectionId=(await createNode(request,null,{kind:'folder',name:'Policies',description:''})).nodeId;
 folderId=(await createNode(request,sectionId,{kind:'folder',name:'Safety',description:''})).nodeId;
 textId=(await createNode(request,folderId,{kind:'text',name:'Synthetic safety policy',description:'Plain text only',body:policy})).nodeId;
 linkId=(await createNode(request,folderId,{kind:'link',name:'Official public guide',description:'External destination',url:'https://help.connecteam.com/en/'})).nodeId;
 const text=await read(request,'node',{node:textId,view:'manage'});expect(text.body).toBe(policy);expect(text.path.map(item=>item.id)).toEqual([sectionId,folderId]);
 const orderBefore=(await read(request,'nodes',{parent:folderId,view:'manage'})).nodes.map(node=>node.id);expect(orderBefore).toEqual([textId,linkId]);
 await nodeChange(request,'order_node',linkId,{direction:'earlier'});expect((await read(request,'nodes',{parent:folderId,view:'manage'})).nodes.map(node=>node.id)).toEqual([linkId,textId]);
 await nodeChange(request,'move_node',textId,{parentId:sectionId});expect((await read(request,'node',{node:textId,view:'manage'})).path.map(item=>item.id)).toEqual([sectionId]);await nodeChange(request,'move_node',textId,{parentId:folderId});
 const definition=await read(request,'base',{view:'manage'}),section=await read(request,'node',{node:sectionId,view:'manage'});
 expect((await write(request,operation({action:'move_node',baseId,revision:definition.base.revision,nodeId:sectionId,nodeRevision:section.node.revision,parentId:folderId}))).status()).toBe(400);
 expect((await write(request,operation({action:'archive_node',baseId,revision:definition.base.revision,nodeId:sectionId,nodeRevision:section.node.revision}))).status()).toBe(409);
 for(const invalid of ['javascript:alert(1)','data:text/html,private','file:///etc/passwd'])expect((await write(request,operation({action:'create_node',baseId,revision:definition.base.revision,parentId:folderId,kind:'link',name:'Unsafe',description:'',url:invalid}))).status()).toBe(400);
 for(const name of ['😀'.repeat(51),'\u0000','\ud800'])expect((await write(request,operation({action:'create_node',baseId,revision:definition.base.revision,parentId:folderId,kind:'folder',name,description:''}))).status()).toBe(400);
 expect((await write(request,operation({action:'create_node',baseId,revision:definition.base.revision,parentId:folderId,kind:'text',name:'Oversize transport',description:'',body:'\u0001'.repeat(50000)}))).status()).toBe(413);
 await nodeChange(request,'archive_node',linkId);expect((await read(request,'node',{node:linkId,view:'manage'})).node.status).toBe('archived');await nodeChange(request,'restore_node',linkId);
 await manage(request,{action:'publish_base'});expect((await read(request,'base',{view:'manage'})).base.status).toBe('published');expect(sql(`select count(*) from public.knowledge_events`)).toBe('0');
});

test('assigned original readers explicitly record once; management reads never mark and insights count actual resource opens',async({page})=>{
 await login(page);const request=page.request;const initial=await read(request,'insights',{view:'manage',nodeId:textId});expect(initial.counts.totalViews).toBe('0');expect(initial.counts.eligible).toBe(2);
 for(const account of ['manager','employee']){const context=await page.context().browser().newContext({baseURL:origin});const reader=await context.newPage();await login(reader,account);const client=reader.request;
  expect((await read(client,'catalog',{view:'library'})).bases.some(base=>base.id===baseId)).toBe(true);expect((await read(client,'node',{node:textId,view:'library'})).body).toBe(policy);
  expect((await client.get(url('insights',{view:'library'}))).status()).toBe(403);expect((await client.get(url('base',{view:'manage'}))).status()).toBe(403);
  const definition=await read(client,'base',{view:'library'}),payload=await viewOperation(client,textId),ack=await saved(client,payload);expect(ack.revision).toBe(definition.base.revision);expect(uuid.test(ack.eventId)).toBe(true);expect(await saved(client,payload)).toEqual(ack);
  const result=await reconcile(client,payload.operationId);expect(result.status()).toBe(200);const recovered=await result.json();expect(Object.keys(recovered).sort()).toEqual(['actorId','operationId','role','status','tenantId']);expect(recovered.status).toBe('recorded');expect(JSON.stringify(recovered)).not.toContain(textId);
  expect((await (await reconcile(client,randomUUID())).json()).status).toBe('not_recorded');await context.close();
 }
 const insights=await read(request,'insights',{view:'manage',nodeId:textId});expect(insights.counts).toMatchObject({assigned:2,eligible:2,unavailable:0,distinctEligibleViewers:2,eligibleViewedPercentage:100,totalViews:'2'});expect(insights.users.map(user=>user.totalViews)).toEqual(['1','1']);expect(insights.chart).toHaveLength(30);
 expect((await read(request,'insights',{view:'manage',nodeId:folderId})).counts.totalViews).toBe('0');expect((await read(request,'insights',{view:'manage'})).counts.totalViews).toBe('2');expect((await request.get(url('base',{view:'library'}))).status()).toBe(403);
});

test('fixed Auth assignments survive Agent relink; current audience, eligibility and lifecycle gate old cookies and view reconciliation',async({page})=>{
 await login(page);const request=page.request,context=await page.context().browser().newContext({baseURL:origin}),reader=await context.newPage();await login(reader,'employee');const client=reader.request,payload=await viewOperation(client,textId);await saved(client,payload);
 sql(`update public.agents set user_id=null where id='${employee}';update public.agents set user_id='${fixture.accounts.employee.id}' where id='${replacement}';`);
 try{expect((await read(client,'node',{view:'library',node:textId})).body).toBe(policy);expect(await saved(client,payload)).toMatchObject({operationId:payload.operationId});}
 finally{sql(`update public.agents set user_id=null where id='${replacement}';update public.agents set user_id='${fixture.accounts.employee.id}' where id='${employee}';`);}
 sql(`update public.tenant_memberships set status='suspended' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.employee.id}';`);
 try{expect((await client.get(url('node',{node:textId,view:'library'}))).status()).toBe(403);expect((await write(client,payload)).status()).toBe(403);expect((await reconcile(client,payload.operationId)).status()).toBe(403);
  await manage(request,{action:'edit_base',name:'Synthetic employee handbook',description:'Preserve unavailable assignment'});await manage(request,{action:'set_audience',audienceIds:[fixture.accounts.employee.id,fixture.accounts.manager.id]});const insights=await read(request,'insights',{view:'manage',nodeId:textId});expect(insights.counts).toMatchObject({assigned:2,eligible:1,unavailable:1,distinctEligibleViewers:1,eligibleViewedPercentage:100});
  sql(`update public.tenant_memberships set status='suspended' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.manager.id}';`);try{expect((await read(request,'insights',{view:'manage',nodeId:textId})).counts).toMatchObject({eligible:0,unavailable:2,distinctEligibleViewers:0,eligibleViewedPercentage:null});}finally{sql(`update public.tenant_memberships set status='active' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.manager.id}';`);}
 }finally{sql(`update public.tenant_memberships set status='active' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.employee.id}';`);}
 await manage(request,{action:'set_audience',audienceIds:[fixture.accounts.manager.id]});expect((await client.get(url('base',{view:'library'}))).status()).toBe(403);expect((await reconcile(client,payload.operationId)).status()).toBe(403);expect((await read(request,'insights',{view:'manage',nodeId:textId})).counts.totalViews).toBe('1');expect(sql(`select count(*) from public.knowledge_events where base_id='${baseId}' and actor_id='${fixture.accounts.employee.id}'`)).toBe('2');
 await manage(request,{action:'set_audience',audienceIds:[fixture.accounts.employee.id,fixture.accounts.manager.id]});await manage(request,{action:'archive_base'});expect((await client.get(url('base',{view:'library'}))).status()).toBe(403);expect((await write(client,payload)).status()).toBe(403);await manage(request,{action:'restore_base'});expect((await read(client,'base',{view:'library'})).base.status).toBe('published');
 await context.close();
});

test('whole title search is literal, precisely paged and version-bound across more than one thousand resources',async({page})=>{
 await login(page);const request=page.request;
 sql(`insert into public.knowledge_nodes(id,tenant_id,base_id,parent_id,kind,name,description,body,depth,rank) select ('69000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'${fixture.tenantA}','${baseId}','${folderId}','text',case when i<=1001 then 'Synthetic search %_\\ İ tie' else 'Other synthetic title' end,'','Synthetic bounded body',3,1000+i from generate_series(1,1005)i;update public.knowledge_bases set revision=revision+1 where id='${baseId}';`);
 const ids=[];let cursor,first;
 do{const data=await read(request,'search',{view:'manage',search:'%_\\ İ',limit:'100',...cursor?{cursor}:{}});expect(data.matchedCount).toBe(1001);if(!first)first=data;ids.push(...data.results.map(item=>item.node.id));cursor=data.nextCursor;}while(cursor);
 expect(ids).toHaveLength(1001);expect(new Set(ids).size).toBe(1001);expect(first.nextCursor).toBeTruthy();expect((await request.get(url('search',{view:'manage',search:'Other',cursor:first.nextCursor}))).status()).toBe(409);
 await nodeChange(request,'edit_node',textId,{kind:'text',name:'Synthetic safety policy',description:'Updated metadata',body:policy});expect((await request.get(url('search',{view:'manage',search:'%_\\ İ',cursor:first.nextCursor}))).status()).toBe(409);
 const context=await page.context().browser().newContext({baseURL:origin}),admin=await context.newPage();await login(admin,'admin');expect((await admin.request.get(url('search',{view:'manage',search:'%_\\ İ',cursor:first.nextCursor}))).status()).toBe(409);await context.close();
});


test('current confirmed actor, management role and company gate old reads, writes and receipts without mutating other workforce data',async({page})=>{
 await login(page);const request=page.request,payload=operation({action:'create_base',name:'Synthetic current-authority probe',description:'',audienceIds:[]});await saved(request,payload);
 const probes=[
  [`update public.tenant_memberships set role='manager' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`,`update public.tenant_memberships set role='owner' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`],
  [`update public.tenant_memberships set status='suspended' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`,`update public.tenant_memberships set status='active' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`],
  [`update public.tenants set status='suspended' where id='${fixture.tenantA}';`,`update public.tenants set status='active' where id='${fixture.tenantA}';`],
  [`update auth.users set is_anonymous=true where id='${fixture.accounts.owner.id}';`,`update auth.users set is_anonymous=false where id='${fixture.accounts.owner.id}';`]
 ];
 for(const [deny,restore]of probes){sql(deny);try{for(const kind of ['catalog','assignees','base','insights'])expect((await request.get(url(kind,kind==='catalog'?{view:'manage',status:'all'}:kind==='assignees'?{}:{view:'manage'}))).status()).toBe(403);expect((await write(request,payload)).status()).toBe(403);}finally{sql(restore);}}
 const confirmed=sql(`select email_confirmed_at::text from auth.users where id='${fixture.accounts.owner.id}';`);sql(`update auth.users set email_confirmed_at=null where id='${fixture.accounts.owner.id}';`);try{expect((await request.get(url('base',{view:'manage'}))).status()).toBe(403);expect((await write(request,payload)).status()).toBe(403);}finally{sql(`update auth.users set email_confirmed_at=${quote(confirmed)} where id='${fixture.accounts.owner.id}';`);}
 expect(await saved(request,payload)).toMatchObject({operationId:payload.operationId});expect((await request.get(url('catalog',{view:'manage',tenantId:fixture.tenantB}))).status()).toBe(403);
 // Owned local-only replacement is restored with the exact original declaration/metadata.
 const signature=sql(`select p.oid::regprocedure::text from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='read_knowledge_base';`);expect(signature.split('\n')).toHaveLength(1);
 const definition=sql(`select pg_get_functiondef(${quote(signature)}::regprocedure);`),barrier='select time_zone into tz from public.tenants where id=target_tenant;';expect(definition.split(barrier)).toHaveLength(2);
 const migration=readdirSync('supabase/migrations').filter(file=>file.endsWith('_knowledge_base.sql'));expect(migration).toHaveLength(1);expect(readFileSync('supabase/migrations/'+migration[0],'utf8')).toContain(barrier);
 sql(definition.replace(barrier,`if search_text='Synthetic snapshot barrier' then perform pg_catalog.pg_sleep(2);end if;${barrier}`));
 try{const pending=request.get(url('catalog',{view:'manage',search:'Synthetic snapshot barrier'}));await expect.poll(()=>sql(`select count(*) from pg_stat_activity where wait_event='PgSleep' and query like '%read_knowledge_base%'`)).toBe('1');sql(`update public.tenant_memberships set role='manager' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`);expect((await pending).status()).toBe(403);}
 finally{sql(`update public.tenant_memberships set role='owner' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`);sql(definition);expect(sql(functionSnapshot)).toBe(functions);}

});


async function pageLibrary(page){await page.goto(`/knowledge-base?company=${fixture.tenantA}`);await expect(page.getByRole('heading',{name:'Knowledge Base',exact:true})).toBeVisible();}
const rosterResponse=(page,search)=>page.waitForResponse(response=>{const target=new URL(response.url());return target.pathname==='/api/knowledge-base/assignees'&&target.searchParams.get('search')===search&&response.request().method()==='GET';});
async function assertRoster(response){expect(response.status(),'Actual signed picker GET must succeed before selection').toBe(200);const target=new URL(response.url());expect([...target.searchParams.keys()].every(key=>['tenantId','search','limit','cursor'].includes(key)),'Picker sends only its strict query contract').toBe(true);const data=await response.json();expect(data).toMatchObject({tenantId:fixture.tenantA,actorId:fixture.accounts.owner.id,role:'owner',view:'manage'});expect(data.users.every(user=>user.eligible)).toBe(true);return data;}
async function baseForm(page,name){const initialRoster=rosterResponse(page,'');await page.getByRole('button',{name:'Add base',exact:true}).click();await assertRoster(await initialRoster);const dialog=page.getByRole('dialog',{name:'Add base',exact:true});await dialog.getByLabel('Base name',{exact:true}).fill(name);await dialog.getByLabel('Base description',{exact:true}).fill('Synthetic desktop draft');return dialog;}
async function findEligible(page,dialog,term){await dialog.getByLabel('Search eligible users',{exact:true}).fill(term);const response=rosterResponse(page,term);await dialog.getByRole('button',{name:'Find eligible users',exact:true}).click();return assertRoster(await response);}
async function openPolicy(page,actorId=fixture.accounts.owner.id,heldBody=false){await page.getByRole('button',{name:'Open base Synthetic employee handbook',exact:true}).click();await page.getByRole('button',{name:'Open folder Policies',exact:true}).click();await page.getByRole('button',{name:'Open folder Safety',exact:true}).click();
 const title='Synthetic safety policy';await page.getByLabel('Search titles in this base',{exact:true}).fill(title);const search=page.waitForResponse(response=>{const target=new URL(response.url());return target.pathname===`/api/knowledge-base/${baseId}/search`&&target.searchParams.get('search')===title&&response.request().method()==='GET';});await page.getByRole('button',{name:'Find resources',exact:true}).click();const response=await search;expect(response.status(),'Signed title search reaches the actual policy beyond the first folder page').toBe(200);const data=await response.json();expect(data).toMatchObject({tenantId:fixture.tenantA,actorId,baseId,matchedCount:1});expect(data.view).toBe(new URL(response.url()).searchParams.get('view'));expect(data.results).toHaveLength(1);expect(data.results[0].node).toMatchObject({id:textId,baseId,parentId:folderId,kind:'text',name:title,status:'active'});expect(data.results[0].path.map(item=>item.id)).toEqual([sectionId,folderId]);const leaf=page.waitForResponse(response=>new URL(response.url()).pathname===`/api/knowledge-base/${baseId}/nodes/${textId}`&&response.request().method()==='GET');await page.getByRole('button',{name:'Open search result Synthetic safety policy',exact:true}).click();const leafResponse=await leaf;expect(leafResponse.status(),'Signed exact-node reader GET must succeed before rendered body checks').toBe(200);expect(new URL(leafResponse.url()).searchParams.get('view')).toBe(data.view);if(!heldBody){const resource=await leafResponse.json();expect(resource).toMatchObject({tenantId:fixture.tenantA,actorId,role:data.role,view:data.view,baseId,baseRevision:data.baseRevision,audienceVersion:data.audienceVersion,treeVersion:data.treeVersion,body:policy,url:null});expect(resource.base.id).toBe(baseId);expect(resource.node).toMatchObject({id:textId,baseId,parentId:folderId,kind:'text',name:title,status:'active'});expect(resource.path.map(item=>item.id)).toEqual([sectionId,folderId]);}}

test('desktop searched fixed assignments, safe management content and assigned reader opens are real; failed current access clears private panes',async({page,browser})=>{
 await login(page);await pageLibrary(page);const dialog=await baseForm(page,'Synthetic desktop handbook');
 const firstMatch=await findEligible(page,dialog,'Synthetic KB account 0001');expect(firstMatch.users.map(user=>user.actorId)).toEqual([bulk+'000000000001']);await dialog.getByRole('checkbox',{name:'Select user Synthetic KB account 0001',exact:true}).check();
 const employeeMatch=await findEligible(page,dialog,'Synthetic employee');expect(employeeMatch.users.map(user=>user.actorId)).toEqual([fixture.accounts.employee.id]);await dialog.getByRole('checkbox',{name:'Select user Synthetic employee',exact:true}).check();await dialog.getByRole('button',{name:'Save base',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('status').filter({hasText:'Knowledge Base updated.'})).toBeVisible();await expect(page.getByRole('button',{name:'Refresh Knowledge Base',exact:true})).toBeEnabled();
 expect(sql(`select count(*) from public.knowledge_audience a join public.knowledge_bases b on b.id=a.base_id where b.tenant_id='${fixture.tenantA}' and b.name='Synthetic desktop handbook'` )).toBe('2');
 await page.getByRole('button',{name:'Back to bases',exact:true}).click();await expect(page.getByRole('button',{name:'Open base Synthetic employee handbook',exact:true})).toBeEnabled();
 const views=sql(`select count(*) from public.knowledge_events where base_id='${baseId}'`);await openPolicy(page);await expect(page.getByText(policy,{exact:true})).toBeVisible();expect(await page.evaluate(()=>window.__ctKbXSS)).toBeUndefined();await expect(page.locator('main img[src="x"]')).toHaveCount(0);
 await page.getByRole('button',{name:'Overall insights',exact:true}).click();const insights=page.getByRole('region',{name:'Knowledge Base insights',exact:true});await expect(insights).toBeVisible();expect(sql(`select count(*) from public.knowledge_events where base_id='${baseId}'`)).toBe(views);await page.screenshot({path:'test-results/knowledge-base-live-desktop-review.png',fullPage:true});
 for(const account of ['manager','employee']){const context=await browser.newContext({baseURL:origin}),reader=await context.newPage();try{await login(reader,account);await pageLibrary(reader);await expect(reader.getByRole('button',{name:'Add base',exact:true})).toHaveCount(0);const before=Number(sql(`select count(*) from public.knowledge_events where base_id='${baseId}' and actor_id='${fixture.accounts[account].id}'`));await openPolicy(reader,fixture.accounts[account].id);await expect(reader.getByText(policy,{exact:true})).toBeVisible();await expect.poll(()=>Number(sql(`select count(*) from public.knowledge_events where base_id='${baseId}' and actor_id='${fixture.accounts[account].id}'`))).toBe(before+4);await expect(reader.getByRole('button',{name:'Refresh Knowledge Base',exact:true})).toBeEnabled();await reader.getByRole('button',{name:'Refresh Knowledge Base',exact:true}).click();await expect(reader.getByText(policy,{exact:true})).toBeVisible();expect(Number(sql(`select count(*) from public.knowledge_events where base_id='${baseId}' and actor_id='${fixture.accounts[account].id}'`))).toBe(before+4);await expect(reader.getByRole('button',{name:'Overall insights',exact:true})).toHaveCount(0);}finally{await context.close();}}
 const foreignContext=await browser.newContext({baseURL:origin}),foreign=await foreignContext.newPage();try{await login(foreign,'foreign');await foreign.goto(`/knowledge-base?company=${fixture.tenantA}`);await expect(foreign.locator('main').getByRole('alert')).toBeVisible();await expect(foreign.getByText(policy,{exact:true})).toHaveCount(0);await expect(foreign.getByRole('button',{name:'Add base',exact:true})).toHaveCount(0);}finally{await foreignContext.close();}
 await pageLibrary(page);await page.evaluate(({baseId,textId})=>{const original=window.fetch.bind(window);window.fetch=async(input,init)=>{const response=await original(input,init);if(!String(input).startsWith(`/api/knowledge-base/${baseId}/nodes/${textId}?`)||window.kbLeafHeld)return response;window.kbLeafHeld=true;const bytes=await response.arrayBuffer();return new Response(new ReadableStream({start(controller){window.kbLeafReceived=true;window.releaseKbLeaf=()=>{controller.enqueue(new Uint8Array(bytes));controller.close();};}}),{status:response.status,headers:response.headers});};},{baseId,textId});
 await openPolicy(page,fixture.accounts.owner.id,true);await expect.poll(()=>page.evaluate(()=>window.kbLeafReceived)).toBe(true);await page.getByRole('link',{name:'Users',exact:true}).click();await expect(page).toHaveURL(/\/agents/);await expect(page.getByRole('heading',{name:'Knowledge Base',exact:true})).toHaveCount(0);await page.evaluate(()=>window.releaseKbLeaf());await expect(page.getByText(policy,{exact:true})).toHaveCount(0);await pageLibrary(page);await expect(page.getByText(policy,{exact:true})).toHaveCount(0);await openPolicy(page);await page.getByRole('button',{name:'Overall insights',exact:true}).click();await expect(insights).toBeVisible();
 sql(`update public.tenant_memberships set status='suspended' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`);try{await page.getByRole('button',{name:'Refresh Knowledge Base',exact:true}).click();await expect(page.getByRole('region',{name:'Knowledge Base recovery',exact:true})).toBeVisible();await expect(insights).toHaveCount(0);await expect(page.getByText(policy,{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Add base',exact:true})).toHaveCount(0);}finally{sql(`update public.tenant_memberships set status='active' where tenant_id='${fixture.tenantA}' and user_id='${fixture.accounts.owner.id}';`);}
});


test('lost management ACK and failed fresh read keep exact retry locked; held reader ACK departure uses field-free current-permission reconciliation',async({page,browser})=>{
 await login(page);await pageLibrary(page);const dialog=await baseForm(page,'Synthetic uncertain management draft'),writes=[];let lost;
 await page.route('**/api/knowledge-base',async route=>{if(route.request().method()!=='POST')return route.continue();const value=route.request().postDataJSON();writes.push(value);if(!lost){lost=value;const response=await route.fetch();expect(response.status()).toBe(200);return route.abort('failed');}return route.continue();});
 await dialog.getByRole('button',{name:'Save base',exact:true}).click();await expect(page.getByRole('region',{name:'Knowledge Base recovery',exact:true})).toBeVisible();const managementKey=`ct-alt:knowledge-base:${fixture.accounts.owner.id}:${fixture.tenantA}`;
 expect(await page.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),managementKey)).toEqual({action:'create_base',operationId:lost.operationId});await page.route('**/api/knowledge-base?**',route=>route.fulfill({status:503,json:{error:'Synthetic failed current recovery'}}));await page.getByRole('button',{name:'Refresh to recover',exact:true}).click();await expect(page.getByRole('region',{name:'Knowledge Base recovery',exact:true})).toBeVisible();expect(await page.evaluate(key=>sessionStorage.getItem(key)!==null,managementKey)).toBe(true);await expect(page.getByRole('button',{name:'Add base',exact:true})).toHaveCount(0);
 await page.unroute('**/api/knowledge-base?**');await page.getByRole('button',{name:'Retry last action',exact:true}).click();await expect(page.getByRole('button',{name:'Add base',exact:true})).toBeEnabled();expect(writes).toEqual([lost,lost]);expect(await page.evaluate(key=>sessionStorage.getItem(key),managementKey)).toBeNull();expect(sql(`select count(*) from public.knowledge_bases where tenant_id='${fixture.tenantA}' and name='Synthetic uncertain management draft'`)).toBe('1');await page.unroute('**/api/knowledge-base');
 const context=await browser.newContext({baseURL:origin}),reader=await context.newPage();try{await login(reader,'employee');await pageLibrary(reader);const calls=[];reader.on('request',request=>{if(new URL(request.url()).pathname.startsWith('/api/knowledge-base'))calls.push({method:request.method(),url:request.url()});});const key=`ct-alt:knowledge-base:${fixture.accounts.employee.id}:${fixture.tenantA}`,before=Number(sql(`select count(*) from public.knowledge_events where base_id='${baseId}' and actor_id='${fixture.accounts.employee.id}'`));
 await reader.evaluate(()=>{const original=window.fetch.bind(window);window.fetch=async(input,init)=>{const response=await original(input,init);if(String(input)!=='/api/knowledge-base'||init?.method!=='POST'||JSON.parse(String(init.body)).change.action!=='view'||window.kbHeldOnce)return response;window.kbHeldOnce=true;window.kbHeldOperation=JSON.parse(String(init.body)).operationId;const bytes=await response.arrayBuffer();return new Response(new ReadableStream({start(controller){window.kbBodyReceived=true;window.releaseKbBody=()=>{controller.enqueue(new Uint8Array(bytes));controller.close();};}}),{status:response.status,headers:response.headers});};});
 await reader.getByRole('button',{name:'Open base Synthetic employee handbook',exact:true}).click();await expect.poll(()=>reader.evaluate(()=>window.kbBodyReceived)).toBe(true);const refresh=reader.getByRole('button',{name:'Refresh Knowledge Base',exact:true});await expect(refresh).toBeDisabled();
 const marker=await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key),callCount=calls.length,heldPane=reader.getByRole('region',{name:'Folder contents',exact:true}),heldText=await heldPane.textContent();expect(marker).toEqual({action:'view',operationId:await reader.evaluate(()=>window.kbHeldOperation)});expect(JSON.stringify(marker)).not.toContain(baseId);
 // React suppresses disabled props even if the DOM is enabled. Invoke the actual attached handler too.
 await refresh.evaluate(async button=>{button.disabled=false;button.click();const propsKey=Object.keys(button).find(key=>key.startsWith('__reactProps$')),handler=propsKey&&button[propsKey]?.onClick;if(typeof handler!=='function')throw Error('Expected attached React refresh handler');handler({currentTarget:button,target:button,preventDefault(){},stopPropagation(){}});button.disabled=true;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});
 expect(calls).toHaveLength(callCount);expect(calls.filter(call=>call.method==='POST')).toHaveLength(1);expect(await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key)).toEqual(marker);await expect(heldPane).toBeVisible();expect(await heldPane.textContent()).toBe(heldText);
 await reader.getByRole('link',{name:'Users',exact:true}).click();await expect(reader).toHaveURL(/\/agents/);await expect(reader.getByRole('heading',{name:'Knowledge Base',exact:true})).toHaveCount(0);await reader.evaluate(()=>window.releaseKbBody());expect(await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key)).toEqual(marker);
 await manage(page.request,{action:'set_audience',audienceIds:[fixture.accounts.manager.id]});const recoveries=[];reader.on('request',request=>{if(request.url().includes('/api/knowledge-base/reconcile-view'))recoveries.push(request.postDataJSON());});await pageLibrary(reader);await expect(reader.getByRole('region',{name:'Knowledge Base recovery',exact:true})).toBeVisible();await expect(reader.getByRole('button',{name:'Retry last action',exact:true})).toHaveCount(0);await reader.getByRole('button',{name:'Refresh to recover',exact:true}).click();await expect(reader.getByRole('region',{name:'Knowledge Base recovery',exact:true})).toBeVisible();expect(await reader.evaluate(key=>JSON.parse(sessionStorage.getItem(key)),key)).toEqual(marker);await expect(reader.getByRole('button',{name:'Open base Synthetic employee handbook',exact:true})).toHaveCount(0);
 await manage(page.request,{action:'set_audience',audienceIds:[fixture.accounts.employee.id,fixture.accounts.manager.id]});await reader.getByRole('button',{name:'Refresh to recover',exact:true}).click();await expect(reader.getByRole('button',{name:'Open base Synthetic employee handbook',exact:true})).toBeEnabled();expect(await reader.evaluate(key=>sessionStorage.getItem(key),key)).toBeNull();expect(recoveries).toEqual([{tenantId:fixture.tenantA,operationId:marker.operationId},{tenantId:fixture.tenantA,operationId:marker.operationId}]);expect(Number(sql(`select count(*) from public.knowledge_events where base_id='${baseId}' and actor_id='${fixture.accounts.employee.id}'`))).toBe(before+1);
 }finally{const current=await read(page.request,'base',{view:'manage'});if(!current.assignees.some(user=>user.actorId===fixture.accounts.employee.id))await manage(page.request,{action:'set_audience',audienceIds:[fixture.accounts.employee.id,fixture.accounts.manager.id]});await context.close();}
});
