import assert from 'node:assert/strict';
export async function directoryRaceChecks({sql,query,asyncSql}){
 const t='d1000000-0000-4000-8000-000000000020',owner='00000000-0000-4000-8000-000000980960',employee='00000000-0000-4000-8000-000000980961';
 const literal=s=>"'"+String(s).replaceAll("'","''")+"'",json=s=>literal(JSON.stringify(s)),op=n=>`d6200000-0000-4000-8000-${String(n).padStart(12,'0')}`;
 const signed=(a=owner)=>`set role authenticated;select set_config('request.jwt.claim.sub','${a}',false);`;
 const save=(id,c)=>`select public.save_directory('${t}','${id}',${json(c)});`,recover=id=>`select public.reconcile_directory_operation('${t}','${id}','create',null);`;
 const create={action:'create',directory_revision:1,name:'Mira Quinn',description:'',phone:'',email:''};
 sql(`insert into auth.users(id,email_confirmed_at)values('${owner}',now()),('${employee}',now());insert into public.tenants(id,name)values('${t}','Synthetic Directory races');insert into public.tenant_memberships(tenant_id,user_id,display_name,role)values('${t}','${owner}','Owner','owner'),('${t}','${employee}','Reader','employee');`);
 function reset(){sql(`delete from public.directory_audit where tenant_id='${t}';delete from workforce_private.directory_operations where tenant_id='${t}';delete from public.directory_work_contacts where tenant_id='${t}';delete from public.directory_state where tenant_id='${t}';update public.tenants set status='active'where id='${t}';update auth.users set email_confirmed_at=now(),is_anonymous=false where id='${owner}';update public.tenant_memberships set status='active',role='owner'where tenant_id='${t}'and user_id='${owner}';`);sql(signed()+save(op(99),{action:'activate',directory_revision:0}));}
 async function reached(name,predicate){for(let n=0;n<100;n++){if(query(`select count(*)from pg_stat_activity where application_name='${name}'and ${predicate}`)==='1')return;await new Promise(r=>setTimeout(r,30));}throw Error('Directory race did not reach '+name);}
 async function pair(name,firstSql,secondSql,error){const first=asyncSql(`set application_name='directory_${name}_first';${firstSql}`);await reached(`directory_${name}_first`,"wait_event='PgSleep'");const second=asyncSql(`set application_name='directory_${name}_second';${secondSql}`);await reached(`directory_${name}_second`,"wait_event_type='Lock'");const[x,y]=await Promise.all([first,second]);assert.equal(x.status,0,x.stderr);assert.equal(y.status,error?3:0,y.stderr);if(error)assert.match(y.stderr,new RegExp(error));}
 for(const commit of [true,false]){reset();await pair(commit?'commit':'rollback',`begin;${signed()}${save(op(1),create)}select pg_sleep(1.2);${commit?'commit':'rollback'};`,signed()+save(op(1),create));assert.equal(query(`select count(*)from public.directory_work_contacts where tenant_id='${t}'`),'1');assert.equal(query(`select management_revision from public.directory_state where tenant_id='${t}'`),'2');console.log('PASS: Directory identicalcreate '+(commit?'commit replay':'rollback retry')+' yields one contact/ACK/revision');}
 reset();await pair('closure',`begin;${signed()}${recover(op(2))}select pg_sleep(1.2);commit;`,signed()+save(op(2),create),'40001');assert.equal(query(`select count(*)from public.directory_work_contacts where tenant_id='${t}'`),'0');console.log('PASS: Directory durableclosure fences delayedoriginal');
 for(const commit of [true,false]){reset();await pair(commit?'recover_commit':'recover_rollback',`begin;${signed()}${save(op(3),create)}select pg_sleep(1.2);${commit?'commit':'rollback'};`,signed()+recover(op(3)));assert.equal(query(`select state from workforce_private.directory_operations where tenant_id='${t}'and operation_id='${op(3)}'`),commit?'recorded':'closed_absent');console.log('PASS: Directory recovery waitsfor '+(commit?'committed receipt':'rollback then durableabsence'));}
 const changes=[['demotion',`update public.tenant_memberships set role='admin'where tenant_id='${t}'and user_id='${owner}'`],['membership',`update public.tenant_memberships set status='suspended'where tenant_id='${t}'and user_id='${owner}'`],['confirmation',`update auth.users set email_confirmed_at=null where id='${owner}'`],['company',`update public.tenants set status='suspended'where id='${t}'`]];
 for(const[name,change]of changes){reset();await pair(name,`begin;select 1 from public.tenants where id='${t}'for update;${change};select pg_sleep(1.2);commit;`,signed()+save(op(4),create),'42501');assert.equal(query(`select count(*)from public.directory_work_contacts where tenant_id='${t}'`),'0');assert.equal(query(`select count(*)from workforce_private.directory_operations where tenant_id='${t}'`),'1');console.log('PASS: Directory queuedcreate rechecks '+name+' beforestale errors orreceipt');}
 reset();await pair('different_op',`begin;${signed()}${save(op(5),create)}select pg_sleep(1.2);commit;`,signed()+save(op(6),create),'40001');assert.equal(query(`select count(*)from public.directory_work_contacts where tenant_id='${t}'`),'1');console.log('PASS: Directory twooperations oneoptimisticrevision atomic');
 reset();sql(signed()+save(op(7),create));const cid=query(`select id from public.directory_work_contacts where tenant_id='${t}'`);const hide={action:'visibility',directory_revision:2,contact_id:cid,contact_revision:1,visible_in_app:false};await pair('visibility',`begin;${signed()}${save(op(8),hide)}select pg_sleep(1.2);commit;`,signed()+save(op(9),hide),'40001');assert.equal(query(`select revision from public.directory_work_contacts where id='${cid}'`),'2');assert.equal(query(`select visible_revision from public.directory_state where tenant_id='${t}'`),'3');console.log('PASS: Directory visibilityrace changes publicscope exactlyonce');
 reset();await pair('activation',`begin;delete from public.directory_audit where tenant_id='${t}';delete from workforce_private.directory_operations where tenant_id='${t}';delete from public.directory_state where tenant_id='${t}';${signed()}${save(op(10),{action:'activate',directory_revision:0})}select pg_sleep(1.2);commit;`,signed()+save(op(11),{action:'activate',directory_revision:0}),'40001');assert.equal(query(`select management_revision from public.directory_state where tenant_id='${t}'`),'1');console.log('PASS: Directory activationrace commitsone initialrevision');
}
