import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
// Only the owned, network-none PG17 runner supplies these local functions.
export async function runFormsRaces({name,query,sql}) {
 const tenant='88000000-0000-4000-8000-000000000001',owner='00000000-0000-4000-8000-000000000901',member='00000000-0000-4000-8000-000000000903',checks=[];
 const session=actor=>`set role authenticated;select set_config('request.jwt.claim.sub','${actor}',false);`;
 const text=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'";
 const call=(op,c,t=tenant)=>`select public.save_form('${t}','${op}',${text(c)});`;
 const create=name=>({action:'create_form',name,description:'',schema:[],audienceIds:[],allowRespondentEdit:false});
 function asyncSql(command) {const child=spawn('docker',['exec','-i',name,'psql','-X','-At','-v','ON_ERROR_STOP=1','-U','postgres','-d','ct_alt_test']);let out='',err='';child.stdout.on('data',s=>out+=s);child.stderr.on('data',s=>err+=s);child.stdin.end(command);return {done:new Promise(resolve=>child.on('close',code=>resolve({code,out,err})))};}
 async function barrier(marker,event) {for(let i=0;i<100;i++){if(query(`select count(*)from pg_stat_activity where pid<>pg_backend_pid()and query like '%${marker}%'and wait_event='${event}'`)!=='0')return;await new Promise(r=>setTimeout(r,25));}throw Error(`Forms actual ${event} barrier missing: ${marker}`);}
 const dto=r=>JSON.parse(r.out.trim().split('\n').filter(line=>line.startsWith('{')).at(-1));
 for(const outcome of ['commit','rollback','revoked']) {
  const op=randomUUID(),marker='forms_uncommitted_'+outcome;
  const writer=asyncSql(`begin;${session(owner)}${call(op,create(marker))}${outcome==='revoked'?`reset role;update public.tenant_memberships set status='suspended'where tenant_id='${tenant}'and user_id='${owner}';`:''}select pg_sleep(1.2)/*${marker}*/;${outcome==='rollback'?'rollback':'commit'};`);
  await barrier(marker,'PgSleep');const reader=asyncSql(`${session(owner)}select public.reconcile_form_operation('${tenant}','${op}','create_form');/*forms_recovery_${outcome}*/`);await barrier('reconcile_form_operation','advisory');
  const [w,r]=await Promise.all([writer.done,reader.done]);assert.equal(w.code,0,w.err);
  if(outcome==='revoked'){assert.notEqual(r.code,0);assert.match(r.err,/Form recovery unavailable/);sql(`update public.tenant_memberships set status='active'where tenant_id='${tenant}'and user_id='${owner}';`);checks.push('PASS: recovery waits uncommitted operation and rechecks current revoked actor before receipt');}
  else {assert.equal(r.code,0,r.err);const result=dto(r);assert.equal(result.status,outcome==='commit'?'recorded':'not_recorded');assert.equal(query(`select count(*)from public.forms where name='${marker}'`),outcome==='commit'?'1':'0');if(outcome==='rollback'){assert.equal(result.saved,null);assert.equal(query(`select state from workforce_private.form_operations where operation_id='${op}'`),'closed_absent');}checks.push(`PASS: recovery genuinely waits uncommitted ${outcome} and returns ${result.status}`);}
 }
 // An HTTP request reaching PostgreSQL after definitive absence cannot revive the UUID.
 const late=randomUUID();sql(`${session(owner)}select public.reconcile_form_operation('${tenant}','${late}','create_form');reset role;`);const denied=await asyncSql(`${session(owner)}${call(late,create('Forbidden late arrival'))}`).done;assert.notEqual(denied.code,0);assert.match(denied.err,/durably reconciled absent/);assert.equal(query("select count(*)from public.forms where name='Forbidden late arrival'"),'0');checks.push('PASS: delayed-start save cannot revive durable absence tombstone');
 const op=randomUUID(),c=create('Parallel same UUID');const first=asyncSql(`begin;${session(owner)}${call(op,c)}select pg_sleep(1.2)/*forms_duplicate_uuid*/;commit;`);await barrier('forms_duplicate_uuid','PgSleep');const second=asyncSql(`${session(owner)}${call(op,c)}`);await barrier('save_form','advisory');const [a,b]=await Promise.all([first.done,second.done]);assert.equal(a.code,0,a.err);assert.equal(b.code,0,b.err);assert.deepEqual(dto(a),dto(b));assert.equal(query("select count(*)from public.forms where name='Parallel same UUID'"),'1');assert.equal(query(`select count(*)from public.form_audit where form_id=(select form_id from workforce_private.form_operations where operation_id='${op}')`),'1');checks.push('PASS: simultaneous same UUID writes acknowledge one form one audit one receipt');
 // Current management role must survive company-mutex wait, not only initial gate.
 const downgrade=randomUUID();const locker=asyncSql(`begin;select pg_advisory_xact_lock(hashtextextended('${tenant}',64));update public.tenant_memberships set role='employee'where tenant_id='${tenant}'and user_id='${owner}';select pg_sleep(1.2)/*forms_downgrade_lock*/;commit;`);await barrier('forms_downgrade_lock','PgSleep');const management=asyncSql(`${session(owner)}${call(downgrade,create('Forbidden downgrade'))}`);await barrier('save_form','advisory');const [l,m]=await Promise.all([locker.done,management.done]);assert.equal(l.code,0,l.err);assert.notEqual(m.code,0);assert.match(m.err,/Forms unavailable/);assert.equal(query(`select count(*)from workforce_private.form_operations where operation_id='${downgrade}'`),'0');sql(`update public.tenant_memberships set role='owner'where tenant_id='${tenant}'and user_id='${owner}';`);checks.push('PASS: role downgrade during management lock wait denies without form audit or receipt');
 const field=randomUUID(),schema=[{id:field,kind:'text',label:'Answer',required:true}];
 const form=randomUUID();sql(`insert into public.forms(id,tenant_id,name,description,schema,status,schema_frozen,allow_respondent_edit)values('${form}','${tenant}','Concurrent answer','',${text(schema)}::jsonb,'published',true,true);insert into public.form_assignments(tenant_id,form_id,actor_id,name)values('${tenant}','${form}','${member}','Synthetic manager');`);
 const progress={action:'save_progress',formId:form,formRevision:1,responseRevision:0,answers:{[field]:'First'}};
 const p1=asyncSql(`begin;${session(member)}${call(randomUUID(),progress)}select pg_sleep(1.2)/*forms_answer_revision*/;commit;`);await barrier('forms_answer_revision','PgSleep');const p2=asyncSql(`${session(member)}${call(randomUUID(),{...progress,answers:{[field]:'Second'}})}`);await barrier('save_form','advisory');const [r1,r2]=await Promise.all([p1.done,p2.done]);assert.equal(r1.code,0,r1.err);assert.notEqual(r2.code,0);assert.match(r2.err,/Response changed/);assert.equal(query(`select answers->>'${field}'from public.form_responses where form_id='${form}'`),'First');assert.equal(query(`select count(*)from public.form_audit where form_id='${form}'`),'1');checks.push('PASS: concurrent first autosaves serialize with one original-actor row and reject stale answer overwrite');
 // Assignment removal serializes before a waiting personal save, revoking fresh and replay authority.
 const removed=randomUUID();const remove=asyncSql(`begin;select pg_advisory_xact_lock(hashtextextended('${tenant}',64));delete from public.form_assignments where form_id='${form}';select pg_sleep(1.2)/*forms_audience_removed*/;commit;`);await barrier('forms_audience_removed','PgSleep');const save=asyncSql(`${session(member)}${call(removed,{...progress,responseRevision:1})}`);await barrier('save_form','advisory');const [rm,sv]=await Promise.all([remove.done,save.done]);assert.equal(rm.code,0,rm.err);assert.notEqual(sv.code,0);assert.match(sv.err,/Form unavailable/);assert.equal(query(`select count(*)from workforce_private.form_operations where operation_id='${removed}'`),'0');checks.push('PASS: current assignment removal during mutex wait denies new personal save without private receipt');
 // Two companies compete for the last deployment-wide retained answer-history admission.
 const other=randomUUID(),otherForm=randomUUID(),responses=[randomUUID(),randomUUID()];sql(`insert into public.tenants(id,name,time_zone)values('${other}','Synthetic second history company','UTC');insert into public.tenant_memberships(tenant_id,user_id,role,status,display_name)values('${other}','${owner}','owner','active','Synthetic owner');insert into public.forms(id,tenant_id,name,description,schema,status,schema_frozen)values('${otherForm}','${other}','Second history','',${text(schema)}::jsonb,'published',true);insert into public.form_assignments(tenant_id,form_id,actor_id,name)values('${tenant}','${form}','${member}','Synthetic manager');`);
 for(const [t,f,id]of[[tenant,form,responses[0]],[other,otherForm,responses[1]]])sql(`delete from public.form_audit where form_id='${f}';delete from workforce_private.form_operations where form_id='${f}';delete from public.form_responses where form_id='${f}';insert into public.form_responses(id,tenant_id,form_id,actor_id,author_name,status,answers,schema,form_name,submitted_at,last_edited_by,last_editor_name)values('${id}','${t}','${f}','${member}','Synthetic manager','submitted',${text({[field]:'Before'})}::jsonb,${text(schema)}::jsonb,'Original',clock_timestamp(),'${member}','Synthetic manager');`);
 sql('update workforce_private.form_history_counter set retained_rows=4095;');
 const edit=(f,id)=>({action:'admin_edit_response',formId:f,formRevision:1,responseId:id,responseRevision:1,answers:{[field]:'After'}});
 const e1=asyncSql(`begin;${session(owner)}${call(randomUUID(),edit(form,responses[0]))}select pg_sleep(1.2)/*forms_global_history*/;commit;`);await barrier('forms_global_history','PgSleep');const e2=asyncSql(`${session(owner)}${call(randomUUID(),edit(otherForm,responses[1]),other)}`);await barrier('save_form','advisory');const [h1,h2]=await Promise.all([e1.done,e2.done]);assert.equal(h1.code,0,h1.err);assert.notEqual(h2.code,0);assert.match(h2.err,/Retained answer history limit reached/);assert.equal(query('select retained_rows from workforce_private.form_history_counter'),'4096');assert.equal(query(`select count(*)from workforce_private.form_response_history where response_id in('${responses[0]}','${responses[1]}')`),'1');assert.equal(query(`select revision from public.form_responses where id='${responses[1]}'`),'1');checks.push('PASS: competing companies serialize last global history slot one edit commits and rejected edit retains original answers');
 // Reset candidate-only data and the one synthetic tenant; all baseline hashes remain identical.
 sql(`delete from workforce_private.form_operations;delete from public.form_audit;delete from workforce_private.form_response_history;delete from public.form_responses;delete from public.form_assignments;delete from public.forms;update workforce_private.form_history_counter set retained_rows=0;delete from public.tenant_memberships where tenant_id='${other}';delete from public.tenants where id='${other}';`);
 return checks;
}
