import assert from 'node:assert/strict';
const tenant='61000000-0000-0000-0000-000000000001',actor='00000000-0000-0000-0000-000000000401';
const change=title=>JSON.stringify({action:'create',title,description:'',priority:'normal',dueDate:null,assigneeAgentId:null,assigneeActorId:null});
const signed=`set role authenticated;select set_config('request.jwt.claim.sub','${actor}',false);`;
export async function requestsRaceChecks({sql,query,asyncSql}){
 async function reached(name,event){for(let i=0;i<120;i++){if(query(`select count(*) from pg_stat_activity where application_name='${name}' and ${event}`)==='1')return;await new Promise(r=>setTimeout(r,30));}throw Error('Requests race did not reach '+name);}
 for(const [suffix,commit]of [['commit',true],['rollback',false]]){const op=commit?'73000000-0000-0000-0000-000000000001':'73000000-0000-0000-0000-000000000002',title='Requests race '+suffix;
 const writer=asyncSql(`set application_name='requests_writer_${suffix}';begin;${signed}select public.save_request('${tenant}','${op}','${change(title)}');select pg_sleep(1.5);${commit?'commit':'rollback'};`);
 await reached('requests_writer_'+suffix,"wait_event='PgSleep'");const recovery=asyncSql(`set application_name='requests_recovery_${suffix}';${signed}select public.reconcile_request_operation('${tenant}','${op}','create');`);await reached('requests_recovery_'+suffix,"wait_event_type='Lock'");const [w,r]=await Promise.all([writer,recovery]);assert.equal(w.status,0,w.stderr);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,commit?/"status": "recorded"/:/"status": "not_recorded"/);assert.equal(query(`select count(*) from public.work_requests where title='${title}'`),commit?'1':'0');assert.equal(query(`select state from workforce_private.request_operations where operation_id='${op}'`),commit?'recorded':'closed_absent');const late=await asyncSql(`${signed}select public.save_request('${tenant}','${op}','${change(title)}');`);assert.equal(late.status,commit?0:3,late.stderr);if(!commit)assert.match(late.stderr,/40001/);console.log(`PASS: recovery waits for genuine uncommitted ${suffix}, exact receipt/absence and late save fence`);}
 // Writer waits for its company fence while current membership is downgraded.
 const assigned=query(`select id from public.work_requests where title='Assigned'`),rev=query(`select revision from public.work_requests where id='${assigned}'`),audit=query('select count(*) from public.work_request_audit');
 const locker=asyncSql(`set application_name='requests_role_barrier';begin;select pg_advisory_xact_lock(hashtextextended('${tenant}',91));update public.tenant_memberships set role='employee' where tenant_id='${tenant}' and user_id='${actor}';select pg_sleep(1.5);commit;`);await reached('requests_role_barrier',"wait_event='PgSleep'");
 const waiting=asyncSql(`set application_name='requests_role_wait';${signed}select public.save_request('${tenant}','73000000-0000-0000-0000-000000000003','${JSON.stringify({action:'move',requestId:assigned,revision:Number(rev),status:'done'})}');`);await reached('requests_role_wait',"wait_event_type='Lock'");const [l,w]=await Promise.all([locker,waiting]);assert.equal(l.status,0,l.stderr);assert.equal(w.status,3,w.stderr);assert.match(w.stderr,/42501/);assert.equal(query(`select revision from public.work_requests where id='${assigned}'`),rev);assert.equal(query('select count(*) from public.work_request_audit'),audit);assert.equal(query("select count(*) from workforce_private.request_operations where operation_id='73000000-0000-0000-0000-000000000003'"),'0');sql(`update public.tenant_memberships set role='owner' where tenant_id='${tenant}' and user_id='${actor}'`);console.log('PASS: post-lock downgrade denies mutation without receipt/audit/revision');
 // Two distinct UUIDs race the same expected revision. Exactly one persists.
 const id=query("select id from public.work_requests where title='Requests race commit'"),before=query('select count(*) from public.work_request_audit');const a={action:'move',requestId:id,revision:1,status:'in_progress'};const first=asyncSql(`set application_name='requests_revision_first';begin;${signed}select public.save_request('${tenant}','73000000-0000-0000-0000-000000000004','${JSON.stringify(a)}');select pg_sleep(1.5);commit;`);await reached('requests_revision_first',"wait_event='PgSleep'");const second=asyncSql(`set application_name='requests_revision_second';${signed}select public.save_request('${tenant}','73000000-0000-0000-0000-000000000005','${JSON.stringify({...a,status:'done'})}');`);await reached('requests_revision_second',"wait_event_type='Lock'");const [f,s]=await Promise.all([first,second]);assert.equal(f.status,0,f.stderr);assert.equal(s.status,3,s.stderr);assert.match(s.stderr,/40001/);assert.equal(query(`select revision||':'||status from public.work_requests where id='${id}'`),'2:in_progress');assert.equal(Number(query('select count(*) from public.work_request_audit')),Number(before)+1);console.log('PASS: concurrent expected revision permits one state/audit change');
}
