\set ON_ERROR_STOP on
begin;
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label; end if;raise notice 'PASS: %',label;end;$$;
create function pg_temp.expect_error(command text,expected text,label text) returns void language plpgsql as $$begin begin execute command; exception when others then if sqlstate<>expected then raise exception 'FAIL: % expected % got % (%)',label,expected,sqlstate,sqlerrm; end if;raise notice 'PASS: %',label;return;end;raise exception 'FAIL: % unexpectedly succeeded',label;end;$$;
create function pg_temp.settings(extra jsonb default '{}') returns jsonb language sql as $$select jsonb_build_object('action','update_schedule','schedule_id',(select id from public.rota_schedules where name='Main'),'revision',(select revision from public.rota_schedules where name='Main'),'name','Main','time_zone','Europe/London','agent_ids',(select jsonb_agg(agent_id) from public.rota_agents where schedule_id=(select id from public.rota_schedules where name='Main')),'admin_ids',jsonb_build_array('00000000-0000-0000-0000-000000000202'))||extra$$;
create function pg_temp.edit(extra jsonb default '{}') returns jsonb language sql as $$select public.save_rota('50000000-0000-0000-0000-000000000001',pg_temp.settings(extra))$$;
set role authenticated;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000202',false);
select pg_temp.expect_error($q$select pg_temp.edit()$q$,'42501','delegated manager cannot escalate via settings');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000203',false);
select pg_temp.expect_error($q$select pg_temp.edit()$q$,'42501','employee cannot edit schedule settings');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000201',false);
select pg_temp.expect_error($q$select pg_temp.edit('{"revision":1}')$q$,'40001','settings reject stale schedule revision');
select pg_temp.expect_error($q$select pg_temp.edit('{"agent_ids":[]}')$q$,'22023','settings require at least one user');
select pg_temp.expect_error($q$select pg_temp.edit('{"time_zone":"Factory"}')$q$,'22023','settings reject unsupported timezone');
select pg_temp.expect_error($q$select pg_temp.edit('{"admin_ids":["00000000-0000-0000-0000-000000000205"]}')$q$,'22023','settings cannot grant foreign administrator');
select pg_temp.expect_error($q$select pg_temp.edit(jsonb_build_object('agent_ids',(select jsonb_agg(agent_id) from public.rota_agents where schedule_id=(select id from public.rota_schedules where name='Main') and agent_id<>(select id from public.agents where phone='+447700900203'))))$q$,'22023','cannot remove user with published shifts');
select pg_temp.edit('{"time_zone":"America/New_York","admin_ids":[]}');
select pg_temp.check_true((select time_zone='America/New_York' from public.rota_schedules where name='Main'),'schedule timezone updated');
select pg_temp.check_true((select count(*)=4 from public.rota_shifts where status='published' and schedule_id=(select id from public.rota_schedules where name='Main')),'settings preserve published lifecycle');
select pg_temp.check_true((select starts_at='2026-10-24T22:00:00Z' and ends_at='2026-10-25T07:00:00Z' from public.rota_shifts order by starts_at limit 1),'timezone edit preserves absolute instants');
select pg_temp.check_true(not exists(select 1 from public.rota_admins where schedule_id=(select id from public.rota_schedules where name='Main')),'settings revoke delegated manager');
select pg_temp.check_true(exists(select 1 from public.rota_audit where action='update_schedule'),'settings audit emitted');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000202',false);
select pg_temp.expect_error($q$select public.save_rota('50000000-0000-0000-0000-000000000001',jsonb_build_object('action','add_job','schedule_id',(select id from public.rota_schedules where name='Main'),'revision',(select revision from public.rota_schedules where name='Main'),'name','Revoked','color','#123456'))$q$,'42501','revoked manager cannot write');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000201',false);
select pg_temp.edit(jsonb_build_object('agent_ids',(select jsonb_agg(agent_id) from public.rota_agents where schedule_id=(select id from public.rota_schedules where name='Main') and agent_id<>(select id from public.agents where phone='+447700900204'))));
select pg_temp.check_true(not exists(select 1 from public.rota_agents where schedule_id=(select id from public.rota_schedules where name='Main') and agent_id=(select id from public.agents where phone='+447700900204')),'unused assignment removed');
reset role;update public.agents set status='archived' where phone='+447700900203';update public.tenant_memberships set status='suspended' where user_id='00000000-0000-0000-0000-000000000202';
set role authenticated;select pg_temp.edit();
select pg_temp.check_true(exists(select 1 from public.rota_agents where schedule_id=(select id from public.rota_schedules where name='Main') and agent_id=(select id from public.agents where phone='+447700900203')),'retained inactive assignment does not prevent metadata editing');
select pg_temp.check_true(exists(select 1 from public.rota_admins where schedule_id=(select id from public.rota_schedules where name='Main')),'existing suspended grant retained without activation');
reset role;update public.tenant_memberships set status='suspended' where user_id='00000000-0000-0000-0000-000000000204';set role authenticated;
select pg_temp.expect_error($q$select pg_temp.edit(jsonb_build_object('agent_ids',(select jsonb_agg(id) from public.agents where tenant_id='50000000-0000-0000-0000-000000000001')))$q$,'22023','new suspended user cannot be assigned');
select public.save_rota('50000000-0000-0000-0000-000000000001',jsonb_build_object('action','archive','schedule_id',(select id from public.rota_schedules where name='Main'),'revision',(select revision from public.rota_schedules where name='Main')));
select pg_temp.expect_error($q$select pg_temp.edit()$q$,'22023','archived schedule must be restored before settings edit');
rollback;
