import type {SupabaseClient} from '@supabase/supabase-js';
import {formsParseJSON} from './forms';
import {DIRECTORY_LIMITS as L} from './directory-types';
import type {DirectoryQuery,DirectoryAccess,DirectoryCatalogue,DirectoryMutation,DirectorySaved,DirectoryRecoveryQuery,DirectoryReconciliation} from './directory-types';
import {directoryAccessSchema,directoryCatalogueSchema,directoryMutationSchema,directorySavedSchema,directoryRecoverySchema,directoryReconciliationSchema,directoryQuerySchema} from './directory-validation';
export class DirectoryError extends Error{status:number;constructor(message:string,status=503){super(message);this.status=status;}}
function invalid():never{throw new DirectoryError('Directory response could not be confirmed.');}
function fail(e:{code?:string}|null){if(!e)return;if(e.code==='42501')throw new DirectoryError('Directory access is unavailable.',403);if(['40001','40P01'].includes(e.code||''))throw new DirectoryError('Directory changed. Please try again.',409);if(e.code==='54000')throw new DirectoryError('Directory capacity reached.',409);if(e.code?.startsWith('22')||['23503','23514'].includes(e.code||''))throw new DirectoryError('Check the contact details.',400);throw new DirectoryError('Directory action could not be confirmed.');}
async function signed(client:SupabaseClient){const{data,error}=await client.auth.getUser();if(error||!data.user)throw new DirectoryError('Sign in to view Directory.',401);if(data.user.is_anonymous)throw new DirectoryError('Directory access is unavailable.',403);return data.user.id.toLowerCase();}
function bound(value:unknown){if(new TextEncoder().encode(JSON.stringify(value)).length>L.responseBytes)invalid();}
function identity(v:DirectoryAccess,t:string,a:string){if(v.company.id!==t||v.actorId!==a)invalid();}
async function fresh(client:SupabaseClient,t:string,a:string):Promise<DirectoryAccess>{if(await signed(client)!==a)throw new DirectoryError('Current account changed.',403);const r=await client.rpc('read_directory_access',{target_tenant:t});fail(r.error);const p=directoryAccessSchema.safeParse(r.data);if(!p.success)invalid();identity(p.data,t,a);return p.data;}
function scope(current:DirectoryAccess,previous:DirectoryAccess){if(current.role!==previous.role||current.canManage!==previous.canManage)throw new DirectoryError('Directory access changed.',403);if(current.active!==previous.active||current.viewRevision!==previous.viewRevision)throw new DirectoryError('Directory changed. Please try again.',409);}
export async function readDirectoryAccess(client:SupabaseClient,tenantId:string):Promise<DirectoryAccess>{const q=directoryQuerySchema.safeParse({tenantId});if(!q.success)throw new DirectoryError('Choose a company.',400);const a=await signed(client);const first=await fresh(client,q.data.tenantId,a),second=await fresh(client,q.data.tenantId,a);scope(second,first);return second;}
// A cursor contains only the public scope, never a hidden count or fingerprint.
function parseCursor(cursor:string){try{const bytes=Buffer.from(cursor,'base64');if(bytes.toString('base64')!==cursor)throw Error();const raw=formsParseJSON(new TextDecoder('utf8',{fatal:true}).decode(bytes),L.requestBytes) as {scope?:Record<string,unknown>;position?:unknown};if(!raw||Object.keys(raw).sort().join(',')!=='position,scope'||!raw.scope||Object.keys(raw.scope).sort().join(',')!=='actorId,role,search,tenantId,viewRevision'||!['owner','admin','manager','employee'].includes(String(raw.scope.role))||!Number.isInteger(raw.position)||Number(raw.position)<1||Number(raw.position)>L.contacts||!Number.isInteger(raw.scope.viewRevision)||Number(raw.scope.viewRevision)<0||typeof raw.scope.search!=='string')throw Error();return raw as {scope:{tenantId:string;actorId:string;role:string;viewRevision:number;search:string};position:number};}catch{throw new DirectoryError('Check the Directory search.',400);}}
function cursorScope(cursor:string|undefined,t:string,a:string){if(!cursor)return null;const raw=parseCursor(cursor);if(raw.scope.actorId!==a)throw new DirectoryError('Directory access changed.',403);if(raw.scope.tenantId!==t)throw new DirectoryError('Check the Directory search.',400);return raw.scope;}
export async function readDirectoryCatalogue(client:SupabaseClient,query:DirectoryQuery):Promise<DirectoryCatalogue>{const parsed=directoryQuerySchema.safeParse(query);if(!parsed.success)throw new DirectoryError('Check the Directory search.',400);const q=parsed.data,a=await signed(client),cursor=cursorScope(q.cursor,q.tenantId,a),initial=await fresh(client,q.tenantId,a);if(cursor&&cursor.role!==initial.role)throw new DirectoryError('Directory access changed.',403);
 const first=await client.rpc('read_directory',{target_tenant:q.tenantId,raw_query:JSON.stringify(q)});
 if(first.error){const current=await fresh(client,q.tenantId,a);if(current.role!==initial.role||(cursor&&cursor.role!==current.role))throw new DirectoryError('Directory access changed.',403);fail(first.error);}
 const checked=directoryCatalogueSchema.safeParse(first.data);if(!checked.success){const current=await fresh(client,q.tenantId,a);if(current.role!==initial.role)throw new DirectoryError('Directory access changed.',403);invalid();}const value=checked.data;identity(value,q.tenantId,a);
 const again=await client.rpc('read_directory',{target_tenant:q.tenantId,raw_query:JSON.stringify(q)}),current=await fresh(client,q.tenantId,a);
 // Permission proof precedes every transport/schema/stale failure after protected data.
 if(current.role!==initial.role||current.role!==value.role||current.canManage!==value.canManage)throw new DirectoryError('Directory access changed.',403);
 fail(again.error);const next=directoryCatalogueSchema.safeParse(again.data);if(!next.success)invalid();identity(next.data,q.tenantId,a);scope(current,value);scope(current,next.data);
 if(JSON.stringify(value)!==JSON.stringify(next.data))throw new DirectoryError('Directory changed. Please try again.',409);
 const position=q.cursor?decodePosition(q.cursor):0,limit=q.limit??100;
 if(value.search!==(q.q??'')||value.contacts.length!==Math.min(limit,value.page.total-position)||position>value.page.total||Boolean(value.page.nextCursor)!==(position+value.contacts.length<value.page.total))invalid();
 if(value.page.nextCursor){const nextCursor=parseCursor(value.page.nextCursor);if(nextCursor.position!==position+value.contacts.length||nextCursor.scope.tenantId!==q.tenantId||nextCursor.scope.actorId!==a||nextCursor.scope.role!==value.role||nextCursor.scope.viewRevision!==value.viewRevision||nextCursor.scope.search!==value.search)invalid();}bound(value);return value;
}
function decodePosition(cursor:string):number{return parseCursor(cursor).position;}
function acknowledgement(saved:DirectorySaved,v:DirectoryMutation,a:string){if(saved.tenantId!==v.tenantId||saved.actorId!==a||saved.operationId!==v.operationId||saved.action!==v.change.action||saved.directory_revision!==v.change.directory_revision+1)invalid();if(v.change.action==='create'&&saved.contact_revision!==1)invalid();if(v.change.action==='visibility'&&(saved.contact_id!==v.change.contact_id||saved.contact_revision!==v.change.contact_revision+1))invalid();}
async function owner(client:SupabaseClient,t:string,a:string,revision?:number){const now=await fresh(client,t,a);if(!now.canManage)throw new DirectoryError('Directory management is unavailable.',403);if(revision!==undefined&&now.viewRevision<revision)invalid();return now;}
export async function saveDirectory(client:SupabaseClient,value:unknown):Promise<DirectorySaved>{const p=directoryMutationSchema.safeParse(value);if(!p.success)throw new DirectoryError('Check the contact details.',400);const v=p.data,a=await signed(client);await owner(client,v.tenantId,a);const r=await client.rpc('save_directory',{target_tenant:v.tenantId,operation_id:v.operationId,raw_change:JSON.stringify(v.change)});const current=await owner(client,v.tenantId,a);fail(r.error);const result=directorySavedSchema.safeParse(r.data);if(!result.success)invalid();acknowledgement(result.data,v,a);if(current.viewRevision<result.data.directory_revision)invalid();return result.data;}
export async function reconcileDirectory(client:SupabaseClient,value:unknown):Promise<DirectoryReconciliation>{const p=directoryRecoverySchema.safeParse(value);if(!p.success)throw new DirectoryError('Check the pending Directory action.',400);const v:DirectoryRecoveryQuery=p.data,a=await signed(client);await owner(client,v.tenantId,a);const r=await client.rpc('reconcile_directory_operation',{target_tenant:v.tenantId,operation_id:v.operationId,target_action:v.action,target_contact:v.contactId});const current=await owner(client,v.tenantId,a);fail(r.error);const result=directoryReconciliationSchema.safeParse(r.data);if(!result.success)invalid();const x=result.data;if(x.tenantId!==v.tenantId||x.actorId!==a||x.operationId!==v.operationId||x.action!==v.action||x.contactId!==v.contactId||(x.status==='recorded'&&current.viewRevision<x.saved.directory_revision))invalid();return x;}
export async function readDirectoryBody(request:Request):Promise<unknown>{const sizeHeader=request.headers.get('content-length');if(sizeHeader&&(!/^\d+$/.test(sizeHeader)||Number(sizeHeader)>L.requestBytes))throw new DirectoryError('Request is too large.',413);const reader=request.body?.getReader();if(!reader)throw new DirectoryError('Check the contact details.',400);let size=0;const chunks:Uint8Array[]=[];try{for(;;){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>L.requestBytes){await reader.cancel();throw new DirectoryError('Request is too large.',413);}chunks.push(r.value);}}finally{reader.releaseLock();}const raw=new Uint8Array(size);let n=0;for(const c of chunks){raw.set(c,n);n+=c.length;}try{return formsParseJSON(new TextDecoder('utf8',{fatal:true}).decode(raw),L.requestBytes);}catch{throw new DirectoryError('Check the contact details.',400);}}
