import{z}from'zod';import type{SupabaseClient}from'@supabase/supabase-js';import type*as F from'./forms-types';import{FORMS_LIMITS as LIMIT}from'./forms-types';
export class FormsError extends Error{constructor(message:string,status=503){super(message);this.status=status;}status:number;}
export function formsStringValid(s:string){if(s.includes('\0'))return false;for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const next=s.charCodeAt(++i);if(!(next>=0xdc00&&next<=0xdfff))return false;}else if(c>=0xdc00&&c<=0xdfff)return false;}return true;}
const bytes=(s:string)=>new TextEncoder().encode(s).length;
export function formsSemanticJSON(v:unknown):string{if(Array.isArray(v))return'['+v.map(formsSemanticJSON).join(', ')+']';if(v!==null&&typeof v==='object')return'{'+Object.entries(v).map(([k,a])=>JSON.stringify(k)+': '+formsSemanticJSON(a)).join(', ')+'}';return JSON.stringify(v);}
const uuid=z.uuid().transform(v=>v.toLowerCase()),revision=z.number().int().min(1).max(2147483647),count=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),role=z.enum(['owner','admin','manager','employee']),time=z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$/).refine(v=>Number.isFinite(Date.parse(v))),digest=z.string().regex(/^[a-f0-9]{32}$/),view=z.enum(['mine','manage']),status=z.enum(['draft','published','archived']),responseStatus=z.enum(['in_progress','submitted']);
const text=(max:number,min=0)=>z.string().refine(v=>v.length>=min&&v.length<=max&&formsStringValid(v));const name=text(100,1).refine(v=>v.trim().length>0),snapshotName=text(200,1).refine(v=>Array.from(v).length<=100),unique=(a:string[])=>new Set(a).size===a.length;
const option=z.object({id:uuid,label:name}).strict();
export const formsSchema:z.ZodType<F.FormsField[]>=z.array(z.union([z.object({id:uuid,kind:z.literal('description'),text:text(5000)}).strict(),z.object({id:uuid,kind:z.enum(['text','yes_no','number']),label:name,required:z.boolean()}).strict(),z.object({id:uuid,kind:z.enum(['single_choice','multiple_choice']),label:name,required:z.boolean(),options:z.array(option).min(1).max(50).refine(a=>unique(a.map(o=>o.id)))}).strict()])).max(50).refine(a=>unique(a.map(f=>f.id))&&bytes(formsSemanticJSON(a))<=LIMIT.schemaBytes);
const rawAnswers=z.record(z.uuid(),z.union([text(5000),z.boolean(),z.array(uuid).max(50).refine(unique)])).refine(a=>unique(Object.keys(a).map(k=>k.toLowerCase()))&&bytes(formsSemanticJSON(a))<=LIMIT.answersBytes).transform(a=>Object.fromEntries(Object.entries(a).map(([k,v])=>[k.toLowerCase(),v])));
export function formsAnswersValid(schema:F.FormsField[],answers:F.FormsAnswers,complete:boolean){if(bytes(formsSemanticJSON(answers))>LIMIT.answersBytes||Object.keys(answers).some(k=>!schema.some(f=>f.id===k&&f.kind!=='description')))return false;for(const f of schema){if(f.kind==='description')continue;const present=Object.hasOwn(answers,f.id),v=answers[f.id];if(!present){if(complete&&f.required)return false;continue;}if(f.kind==='text'){if(typeof v!=='string'||v.length>5000||!formsStringValid(v)||complete&&f.required&&!v.trim())return false;}else if(f.kind==='yes_no'){if(typeof v!=='boolean')return false;}else if(f.kind==='number'){if(typeof v!=='string'||v.length>32||!(complete?/^[+-]?[0-9]{1,12}(\.[0-9]{1,6})?$/:/^[+-]?[0-9]*(\.[0-9]*)?$/).test(v))return false;}else if(f.kind==='single_choice'){if(typeof v!=='string'||!f.options.some(o=>o.id===v.toLowerCase()))return false;}else if(f.kind==='multiple_choice'){if(!Array.isArray(v)||v.length>50||!unique(v.map(x=>x.toLowerCase()))||v.some(x=>!f.options.some(o=>o.id===x.toLowerCase()))||complete&&f.required&&!v.length)return false;}else return false;}return true;}
const target={formId:uuid,formRevision:revision},responseTarget={...target,responseRevision:z.number().int().min(0).max(2147483647)},audience=z.array(uuid).max(500).refine(unique),details={name,description:text(500),schema:formsSchema,allowRespondentEdit:z.boolean()};
export const formsMutation:z.ZodType<F.FormsMutation>=z.object({tenantId:uuid,operationId:uuid,change:z.union([z.object({action:z.literal('create_form'),...details,audienceIds:audience}).strict(),z.object({action:z.literal('edit_form'),...target,...details}).strict(),z.object({action:z.literal('set_audience'),...target,audienceIds:audience}).strict(),z.object({action:z.enum(['publish_form','archive_form','restore_form']),...target}).strict(),z.object({action:z.enum(['save_progress','submit_response','edit_response']),...responseTarget,answers:rawAnswers}).strict(),z.object({action:z.literal('admin_edit_response'),...responseTarget,responseId:uuid,answers:rawAnswers}).strict(),z.object({action:z.literal('review_response'),...responseTarget,responseId:uuid,reviewed:z.boolean()}).strict()])}).strict().refine(v=>bytes(formsSemanticJSON(v))<=LIMIT.requestBytes&&bytes(JSON.stringify(v))<=LIMIT.requestBytes);
const action=z.enum(['create_form','edit_form','set_audience','publish_form','archive_form','restore_form','save_progress','submit_response','edit_response','admin_edit_response','review_response']);
export const formsReconcileMutation:z.ZodType<F.FormsReconcileQuery>=z.object({tenantId:uuid,operationId:uuid,action}).strict();
/** Per-object duplicate detection, preserving raw subtree byte budgets before normalization. */
export function formsParseJSON(raw:string):unknown{if(bytes(raw)>LIMIT.requestBytes)throw new FormsError('Form request is too large.',413);let i=0;const ws=()=>{while(/\s/.test(raw[i]??'')&&i<raw.length)i++;};function string(){const start=i++;while(i<raw.length){const c=raw[i++];if(c==='"')return JSON.parse(raw.slice(start,i))as string;if(c==='\\')i++;}throw Error();}function value(path:string[]){ws();const start=i,c=raw[i];if(c==='{'){i++;ws();const keys=new Set<string>();if(raw[i]==='}')i++;else{while(true){ws();if(raw[i]!=='"')throw Error();const k=string();if(keys.has(k))throw new FormsError('Duplicate form properties.',400);keys.add(k);ws();if(raw[i++]!==':')throw Error();value([...path,k]);ws();if(raw[i]==='}'){i++;break;}if(raw[i++]!==',')throw Error();}}}else if(c==='['){i++;ws();if(raw[i]===']')i++;else{while(true){value(path);ws();if(raw[i]===']'){i++;break;}if(raw[i++]!==',')throw Error();}}}else if(c==='"')string();else{while(i<raw.length&&!/[\s,}\]]/.test(raw[i]))i++;if(start===i)throw Error();}if(path.join('.')==='change.schema'&&bytes(raw.slice(start,i))>LIMIT.schemaBytes||path.join('.')==='change.answers'&&bytes(raw.slice(start,i))>LIMIT.answersBytes)throw new FormsError('Form schema or answers are too large.',413);}try{value([]);ws();if(i!==raw.length)throw Error();return JSON.parse(raw);}catch(e){if(e instanceof FormsError)throw e;throw new FormsError('Choose a valid form request.',400);}}
export async function formsReadBody(request:Request){const length=request.headers.get('content-length');if(length&&(!/^[0-9]+$/.test(length)||Number(length)>LIMIT.requestBytes))throw new FormsError('Form request is too large.',413);const reader=request.body?.getReader();if(!reader)throw new FormsError('Choose a form request.',400);const parts:Uint8Array[]=[];let size=0;try{while(true){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>LIMIT.requestBytes){await reader.cancel();throw new FormsError('Form request is too large.',413);}parts.push(part.value);}}finally{reader.releaseLock();}const data=new Uint8Array(size);let at=0;for(const p of parts){data.set(p,at);at+=p.length;}try{return formsParseJSON(new TextDecoder('utf-8',{fatal:true}).decode(data));}catch(e){if(e instanceof FormsError)throw e;throw new FormsError('Choose valid UTF8 form details.',400);}}
const paging={search:text(100).refine(s=>bytes(s)<=512).optional(),limit:z.coerce.number().int().min(1).max(100).optional(),cursor:z.string().regex(/^[A-Za-z0-9_-]+$/).max(6000).optional()};
function params<T>(p:URLSearchParams,s:z.ZodType<T>):T{const seen=new Set<string>();for(const[k]of p){if(seen.has(k))throw new FormsError('Duplicate Forms query.',400);seen.add(k);}const parsed=s.safeParse(Object.fromEntries(p));if(!parsed.success)throw new FormsError('Choose a valid Forms query.',400);return parsed.data;}
function id(v:string){const p=uuid.safeParse(v);if(!p.success)throw new FormsError('Choose a valid form identifier.',400);return p.data;}
export function parseFormsQuery(p:URLSearchParams):F.FormsQuery{const q=params(p,z.object({tenantId:uuid,view:view.optional(),status:z.enum(['all','draft','published','archived']).optional(),...paging}).strict());return{...q,view:q.view??'mine',status:q.status??'all',search:q.search??'',limit:q.limit??50};}
export function parseFormsFormQuery(p:URLSearchParams,formId:string):F.FormsFormQuery{const q=params(p,z.object({tenantId:uuid,view:view.optional()}).strict());return{...q,formId:id(formId),view:q.view??'mine'};}
export function parseFormsRosterQuery(p:URLSearchParams):F.FormsRosterQuery{const q=params(p,z.object({tenantId:uuid,...paging}).strict());return{...q,search:q.search??'',limit:q.limit??50};}
export function parseFormsResponsesQuery(p:URLSearchParams,formId:string):F.FormsResponsesQuery{const q=params(p,z.object({tenantId:uuid,status:z.enum(['all','submitted']).optional(),review:z.enum(['all','reviewed','not_reviewed']).optional(),...paging}).strict());return{...q,formId:id(formId),status:q.status??'all',review:q.review??'all',search:q.search??'',limit:q.limit??50};}
export function parseFormsResponseQuery(p:URLSearchParams,formId:string,responseId:string):F.FormsResponseQuery{const q=params(p,z.object({tenantId:uuid,limit:z.coerce.number().int().min(1).max(10).optional(),cursor:paging.cursor}).strict());return{...q,formId:id(formId),responseId:id(responseId),limit:q.limit??10};}
const identity={tenantId:uuid,actorId:uuid,role},company=z.object({id:uuid,name:text(200),time_zone:text(100,1)}).strict(),capabilities=z.object({canEdit:z.boolean(),canPublish:z.boolean(),canArchive:z.boolean(),canRestore:z.boolean(),canSaveProgress:z.boolean(),canSubmit:z.boolean(),canEditResponse:z.boolean(),canViewResponses:z.boolean()}).strict();
const ownResponse=z.object({id:uuid,revision,status:responseStatus,submittedAt:time.nullable(),updatedAt:time}).strict();
const form=z.object({id:uuid,name,description:text(500),status,restoreStatus:z.enum(['draft','published']).nullable(),revision,schemaFrozen:z.boolean(),allowRespondentEdit:z.boolean(),isAssigned:z.boolean(),audienceCount:count.max(500).nullable(),eligibleAudienceCount:count.max(500).nullable(),createdAt:time,updatedAt:time,capabilities,ownResponse:ownResponse.nullable()}).strict();
const responseSummary=z.object({id:uuid,formId:uuid,actorId:uuid,authorName:snapshotName,revision,status:responseStatus,submittedAt:time.nullable(),updatedAt:time,lastEditedBy:uuid,lastEditorName:snapshotName,lastEditedAt:time,reviewed:z.boolean(),reviewedAt:time.nullable(),reviewedBy:uuid.nullable(),reviewerName:snapshotName.nullable(),canEdit:z.boolean(),canReview:z.boolean()}).strict().refine(r=>(r.status==='submitted')===(r.submittedAt!==null)&&r.reviewed===(r.reviewedAt!==null&&r.reviewedBy!==null&&r.reviewerName!==null)&&(!r.reviewed?r.reviewedAt===null&&r.reviewedBy===null&&r.reviewerName===null:true));
const response=responseSummary.safeExtend({answers:rawAnswers,schema:formsSchema,formName:name}).strict().refine(r=>formsAnswersValid(r.schema,r.answers,r.status==='submitted'));
const assignee=z.object({actorId:uuid,name:snapshotName,eligible:z.boolean()}).strict(),assignees=z.array(assignee).max(500).refine(a=>unique(a.map(u=>u.actorId)));
const cursorScope=z.object({...identity,kind:z.enum(['catalog','form','roster','responses','response']),view,formId:uuid.nullable(),responseId:uuid.nullable(),status:text(20),review:text(20),search:text(100).refine(v=>bytes(v)<=512),version:digest}).strict(),cursorSchema=z.object({scope:cursorScope,position:z.object({id:uuid,key:text(200)}).strict()}).strict();
const rawCursor=cursorSchema.nullable();
const catalogSchema=z.object({...identity,company,view,forms:z.array(form).max(100).refine(a=>unique(a.map(f=>f.id))),counts:z.object({total:count,draft:count,published:count,archived:count}).strict().refine(c=>c.total===c.draft+c.published+c.archived),catalogVersion:digest,nextCursor:rawCursor,capabilities:z.object({canManage:z.boolean()}).strict(),serverTime:time}).strict();
const formSchema=z.discriminatedUnion('view',[z.object({...identity,company,view:z.literal('mine'),form,schema:formsSchema,response:response.nullable(),collectionVersion:digest,serverTime:time}).strict(),z.object({...identity,company,view:z.literal('manage'),form,schema:formsSchema,assignees,collectionVersion:digest,serverTime:time}).strict()]);
const rosterSchema=z.object({...identity,users:z.array(assignee).max(100).refine(a=>unique(a.map(u=>u.actorId))&&a.every(u=>u.eligible)),matchedCount:count,rosterVersion:digest,nextCursor:rawCursor,serverTime:time}).strict();
const responsesSchema=z.object({...identity,form,responses:z.array(responseSummary).max(100).refine(a=>unique(a.map(r=>r.id))&&a.every(r=>r.status==='submitted')),counts:z.object({total:count,reviewed:count,notReviewed:count}).strict().refine(c=>c.total===c.reviewed+c.notReviewed),collectionVersion:digest,nextCursor:rawCursor,serverTime:time}).strict();
const history=z.object({id:uuid,responseId:uuid,revision,answers:rawAnswers,formName:name,status:z.literal('submitted'),submittedAt:time,updatedAt:time,lastEditedBy:uuid,lastEditorName:snapshotName,lastEditedAt:time,reviewed:z.boolean(),reviewedAt:time.nullable(),reviewedBy:uuid.nullable(),reviewerName:snapshotName.nullable(),retainedAt:time}).strict();
const responseSchema=z.object({...identity,form,response,history:z.array(history).max(10).refine(a=>unique(a.map(h=>h.id))),historyCount:count.max(50),collectionVersion:digest,nextCursor:rawCursor,serverTime:time}).strict();
function fail(e:{code?:string}|null){if(!e)return;const code=e.code??'';if(code==='42501')throw new FormsError('Current form access is unavailable.',403);if(code==='54000')throw new FormsError('The saved answer history limit has been reached.',409);if(code==='40001')throw new FormsError('The form or response changed. Refresh and review.',409);if(code.startsWith('22'))throw new FormsError('Choose valid form details and answers.',400);throw new FormsError('Form data could not be verified. Refresh and review.');}
function invalid(message='Form response could not be verified.'):never{throw new FormsError(message);}
async function signed(c:SupabaseClient){const{data:{user},error}=await c.auth.getUser();if(error||!user)throw new FormsError('Sign in to view Forms.',401);if(user.is_anonymous)throw new FormsError('Current form access is unavailable.',403);const p=uuid.safeParse(user.id);if(!p.success)invalid('Signed account could not be verified.');return p.data;}
export function decodeFormsCursor(cursor?:string){if(!cursor)return null;try{if(cursor.length>6000||!/^[A-Za-z0-9_-]+$/.test(cursor))throw Error();const value=cursorSchema.parse(JSON.parse(Buffer.from(cursor,'base64url').toString('utf8')));if(Buffer.from(JSON.stringify(value)).toString('base64url')!==cursor)throw Error();return value;}catch{throw new FormsError('Choose a valid Forms cursor.',400);}}
const encode=(c:z.infer<typeof cursorSchema>|null)=>c?Buffer.from(JSON.stringify(c)).toString('base64url'):null;
type Read={tenantId:string;kind:z.infer<typeof cursorScope>['kind'];view:F.FormsView;formId?:string;responseId?:string;status?:string;review?:string;search?:string;limit?:number;cursor?:string};
const accessSchema=z.object({...identity,view,collectionVersion:digest,formRevision:revision.nullable(),responseRevision:revision.nullable()}).strict();
function validateForm(f:F.FormsForm,mode:F.FormsView){if((f.status==='archived')!==(f.restoreStatus!==null)||f.eligibleAudienceCount!==null&&f.audienceCount!==null&&f.eligibleAudienceCount>f.audienceCount)invalid();if(mode==='mine'){if(f.status!=='published'||!f.schemaFrozen||!f.isAssigned||f.audienceCount!==null||f.eligibleAudienceCount!==null||f.capabilities.canEdit||f.capabilities.canPublish||f.capabilities.canArchive||f.capabilities.canRestore||f.capabilities.canViewResponses)invalid();}else if(f.ownResponse!==null||f.audienceCount===null||f.eligibleAudienceCount===null||f.capabilities.canSaveProgress||f.capabilities.canSubmit||f.capabilities.canEditResponse)invalid();if(f.ownResponse&&(f.ownResponse.status==='submitted')!==(f.ownResponse.submittedAt!==null))invalid();}
async function read<T>(c:SupabaseClient,q:Read,schema:z.ZodType<T>){const actor=await signed(c),after=decodeFormsCursor(q.cursor);if(after&&(after.scope.actorId!==actor||after.scope.tenantId!==q.tenantId))throw new FormsError('Cursor belongs to another account or company.',409);const{data,error}=await c.rpc('read_forms',{target_tenant:q.tenantId,read_kind:q.kind,read_view:q.view,target_form:q.formId??null,target_response:q.responseId??null,status_filter:q.status??'all',review_filter:q.review??'all',search_text:q.search??'',page_limit:q.limit??50,after_item:after});fail(error);const p=schema.safeParse(data);if(!p.success)invalid();const d=p.data as T&F.FormsIdentity;if(d.actorId!==actor||d.tenantId!==q.tenantId)invalid('Form identity could not be verified.');if(q.view==='manage'&&!['owner','admin'].includes(d.role))invalid();return d;}
async function recheck(c:SupabaseClient,q:Read,d:F.FormsIdentity,version:string,formRevision?:number,responseRevision?:number){const{data,error}=await c.rpc('read_forms_access',{target_tenant:q.tenantId,read_kind:q.kind,read_view:q.view,target_form:q.formId??null,target_response:q.responseId??null});fail(error);const p=accessSchema.safeParse(data);if(!p.success)invalid('Current Forms access could not be verified.');const a=p.data;if(a.actorId!==d.actorId||a.tenantId!==d.tenantId||a.role!==d.role||a.view!==q.view)throw new FormsError('Company or form access changed.',403);if(a.collectionVersion!==version||formRevision!==undefined&&a.formRevision!==formRevision||responseRevision!==undefined&&a.responseRevision!==responseRevision)throw new FormsError('The form or response changed. Refresh and review.',409);}
function verifyCursor(c:z.infer<typeof cursorSchema>|null,q:Read,d:F.FormsIdentity,version:string,lastId:string|undefined,key?:string){if(!c)return;if(!lastId||c.position.id!==lastId||key!==undefined&&c.position.key!==key||c.scope.tenantId!==d.tenantId||c.scope.actorId!==d.actorId||c.scope.role!==d.role||c.scope.kind!==q.kind||c.scope.view!==q.view||c.scope.formId!==(q.formId??null)||c.scope.responseId!==(q.responseId??null)||c.scope.status!==(q.status??'all')||c.scope.review!==(q.review??'all')||c.scope.search!==(q.search??'')||c.scope.version!==version)invalid('Forms continuation could not be verified.');}
function companyValid(v:{company:F.FormsData['company'];tenantId:string}){if(v.company.id!==v.tenantId)invalid();try{new Intl.DateTimeFormat('en',{timeZone:v.company.time_zone}).format();}catch{invalid('Company calendar could not be verified.');}}
export async function readForms(c:SupabaseClient,q:F.FormsQuery):Promise<F.FormsData>{const query:Read={...q,kind:'catalog'},d=await read(c,query,catalogSchema);if(d.view!==q.view||d.capabilities.canManage!==['owner','admin'].includes(d.role)||d.forms.length>q.limit||d.forms.length>d.counts.total)invalid();companyValid(d);for(const f of d.forms){validateForm(f,d.view);if(q.status!=='all'&&f.status!==q.status)invalid();}verifyCursor(d.nextCursor,query,d,d.catalogVersion,d.forms.at(-1)?.id,d.forms.at(-1)?.createdAt);await recheck(c,query,d,d.catalogVersion);return{...d,nextCursor:encode(d.nextCursor)};}
export async function readFormsForm(c:SupabaseClient,q:F.FormsFormQuery):Promise<F.FormsFormData>{const query:Read={...q,kind:'form'},d=await read(c,query,formSchema);if(d.view!==q.view||d.form.id!==q.formId)invalid();companyValid(d);validateForm(d.form,d.view);if(d.view==='mine'){if(d.response&&(d.response.actorId!==d.actorId||d.response.formId!==d.form.id||d.response.id!==d.form.ownResponse?.id||d.response.revision!==d.form.ownResponse?.revision)||!d.response&&d.form.ownResponse!==null)invalid();}else if(d.assignees.length!==d.form.audienceCount||d.assignees.filter(a=>a.eligible).length!==d.form.eligibleAudienceCount)invalid();await recheck(c,query,d,d.collectionVersion,d.form.revision);return d;}
export async function readFormsRoster(c:SupabaseClient,q:F.FormsRosterQuery):Promise<F.FormsRosterData>{const query:Read={...q,kind:'roster',view:'manage'},d=await read(c,query,rosterSchema);if(d.users.length>q.limit||d.users.length>d.matchedCount)invalid();verifyCursor(d.nextCursor,query,d,d.rosterVersion,d.users.at(-1)?.actorId);await recheck(c,query,d,d.rosterVersion);return{...d,nextCursor:encode(d.nextCursor)};}
export async function readFormsResponses(c:SupabaseClient,q:F.FormsResponsesQuery):Promise<F.FormsResponsesData>{const query:Read={...q,kind:'responses',view:'manage'},d=await read(c,query,responsesSchema);if(d.form.id!==q.formId||d.responses.length>q.limit||d.responses.length>d.counts.total||d.responses.some(r=>r.formId!==q.formId||q.review==='reviewed'&&!r.reviewed||q.review==='not_reviewed'&&r.reviewed))invalid();validateForm(d.form,'manage');verifyCursor(d.nextCursor,query,d,d.collectionVersion,d.responses.at(-1)?.id,d.responses.at(-1)?.submittedAt??undefined);await recheck(c,query,d,d.collectionVersion,d.form.revision);return{...d,nextCursor:encode(d.nextCursor)};}
export async function readFormsResponse(c:SupabaseClient,q:F.FormsResponseQuery):Promise<F.FormsResponseData>{const query:Read={...q,kind:'response',view:'manage'},d=await read(c,query,responseSchema);if(d.form.id!==q.formId||d.response.id!==q.responseId||d.response.formId!==q.formId||d.response.status!=='submitted'||d.history.length>q.limit||d.history.length>d.historyCount||d.history.some((h,i)=>h.responseId!==q.responseId||h.revision>=d.response.revision||i>0&&h.revision>=d.history[i-1].revision||!formsAnswersValid(d.response.schema,h.answers,true)))invalid();validateForm(d.form,'manage');verifyCursor(d.nextCursor,query,d,d.collectionVersion,d.history.at(-1)?.id,d.history.at(-1)?.revision.toString());await recheck(c,query,d,d.collectionVersion,d.form.revision,d.response.revision);return{...d,nextCursor:encode(d.nextCursor)};}
const savedSchema=z.object({...identity,operationId:uuid,action,formId:uuid,formRevision:revision,responseId:uuid.optional(),responseRevision:revision.optional(),responseStatus:responseStatus.optional(),submittedAt:time.nullable().optional(),updatedAt:time}).strict().refine(s=>['save_progress','submit_response','edit_response','admin_edit_response','review_response'].includes(s.action)?s.responseId!==undefined&&s.responseRevision!==undefined&&s.responseStatus===(s.action==='save_progress'?'in_progress':'submitted')&&Object.hasOwn(s,'submittedAt')&&(s.responseStatus==='submitted')===(s.submittedAt!==null):s.responseId===undefined&&s.responseRevision===undefined&&s.responseStatus===undefined&&!Object.hasOwn(s,'submittedAt')).refine(s=>['save_progress','submit_response','edit_response'].includes(s.action)||['owner','admin'].includes(s.role)).refine(s=>s.action!=='create_form'||s.formRevision===1);
export async function saveForm(c:SupabaseClient,value:F.FormsMutation):Promise<F.FormsSaved>{const p=formsMutation.safeParse(value);if(!p.success)throw new FormsError('Choose valid form details and answers.',400);const v=p.data,actor=await signed(c);const{data,error}=await c.rpc('save_form',{target_tenant:v.tenantId,operation_id:v.operationId,change_text:JSON.stringify(v.change)});fail(error);const parsed=savedSchema.safeParse(data);if(!parsed.success)invalid('Form acknowledgement could not be verified.');const s=parsed.data;if(s.actorId!==actor||s.tenantId!==v.tenantId||s.operationId!==v.operationId||s.action!==v.change.action||'formId'in v.change&&s.formId!==v.change.formId)invalid();const personal=['save_progress','submit_response','edit_response'].includes(s.action);if(!personal&&!['owner','admin'].includes(s.role))invalid();if('responseRevision'in v.change){if(s.responseRevision!==v.change.responseRevision+1||s.formRevision!==v.change.formRevision||'responseId'in v.change&&s.responseId!==v.change.responseId||s.responseStatus!==(s.action==='save_progress'?'in_progress':'submitted'))invalid();}else if(s.formRevision!==(v.change.action==='create_form'?1:v.change.formRevision+1))invalid();return s;}
const reconcileSchema=z.object({...identity,operationId:uuid,action,status:z.enum(['recorded','not_recorded']),saved:savedSchema.nullable()}).strict().refine(d=>(d.status==='recorded')===(d.saved!==null));
export async function reconcileForm(c:SupabaseClient,q:F.FormsReconcileQuery):Promise<F.FormsReconciliation>{const p=formsReconcileMutation.safeParse(q);if(!p.success)throw new FormsError('Choose a valid form recovery operation.',400);const actor=await signed(c);async function fresh(){const{data,error}=await c.rpc('reconcile_form_operation',{target_tenant:q.tenantId,operation_id:q.operationId,action_name:q.action});fail(error);const result=reconcileSchema.safeParse(data);if(!result.success)invalid('Form recovery could not be verified.');const d=result.data;if(d.tenantId!==q.tenantId||d.actorId!==actor||d.operationId!==q.operationId||d.action!==q.action||d.saved&&(d.saved.actorId!==actor||d.saved.tenantId!==q.tenantId||d.saved.role!==d.role||d.saved.operationId!==q.operationId||d.saved.action!==q.action))invalid();return d;}await fresh();return fresh();}
