import {z} from 'zod';
import type {SupabaseClient} from '@supabase/supabase-js';
import type * as KB from './knowledge-base-types';
export const KNOWLEDGE_MAX_BYTES=262144;
export function knowledgeStringValid(v:string){if(v.includes('\0'))return false;for(let i=0;i<v.length;i++){const c=v.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const next=v.charCodeAt(++i);if(!(next>=0xdc00&&next<=0xdfff))return false;}else if(c>=0xdc00&&c<=0xdfff)return false;}return true;}
export function knowledgeSemanticBytes(v:unknown):number{if(typeof v==='string')return new TextEncoder().encode(v).length;if(Array.isArray(v))return 32+v.reduce((n,a)=>n+knowledgeSemanticBytes(a),0);if(v!==null&&typeof v==='object')return 64+Object.values(v).reduce<number>((n,a)=>n+knowledgeSemanticBytes(a),0);return 16;}
export function knowledgePayloadFits(v:unknown){return new TextEncoder().encode(JSON.stringify(v)).length<=KNOWLEDGE_MAX_BYTES&&1024+knowledgeSemanticBytes(v)<=KNOWLEDGE_MAX_BYTES;}
const uuid=z.uuid().transform(v=>v.toLowerCase()),revision=z.number().int().min(1).max(2147483647),expected=revision.max(2147483646),count=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),role=z.enum(['owner','admin','manager','employee']),view=z.enum(['manage','library']),digest=z.string().regex(/^[a-f0-9]{32}$/),time=z.iso.datetime({offset:true});
const string=(max:number,min=0)=>z.string().refine(v=>v.length>=min&&v.length<=max&&knowledgeStringValid(v));
export function knowledgeLinkValid(v:string){if(v.length<1||v.length>2000||!knowledgeStringValid(v)||/[\s\\\x00-\x1f\x7f]/.test(v)||/%(?![0-9a-f]{2})/i.test(v))return false;const parts=/^https?:\/\/([^/?#:]+)(?::([0-9]{1,5}))?([/?#].*)?$/i.exec(v);if(!parts)return false;const host=parts[1];if(parts[2]&&(Number(parts[2])<1||Number(parts[2])>65535))return false;const labels=host.split('.');const valid=/^[0-9]+(?:\.[0-9]+){3}$/.test(host)?labels.every(x=>/^(0|[1-9][0-9]{0,2})$/.test(x)&&Number(x)<=255):host.length<=253&&!/^0x[0-9a-f]*$/i.test(labels.at(-1)??'')&&/[a-z]/i.test(labels.at(-1)??'')&&labels.every(x=>!/^xn--/i.test(x)&&x.length>=1&&x.length<=63&&/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i.test(x));if(!valid)return false;try{return !!new URL(v).hostname;}catch{return false;}}
const name=string(100,1).refine(v=>v.trim().length>0),description=string(500),body=string(50000,1),url=string(2000,1).refine(knowledgeLinkValid);
const audienceIds=z.array(uuid).max(500).refine(a=>new Set(a).size===a.length),baseTarget={baseId:uuid,revision:expected},nodeTarget={...baseTarget,nodeId:uuid,nodeRevision:expected},details={name,description};
const createNode={action:z.literal('create_node'),...baseTarget,parentId:uuid.nullable(),...details},editNode={action:z.literal('edit_node'),...nodeTarget,...details};
export const knowledgeMutation:z.ZodType<KB.KnowledgeMutation>=z.object({tenantId:uuid,operationId:uuid,change:z.union([
 z.object({action:z.literal('create_base'),...details,audienceIds}).strict(),z.object({action:z.literal('edit_base'),...baseTarget,...details}).strict(),z.object({action:z.literal('set_audience'),...baseTarget,audienceIds}).strict(),z.object({action:z.enum(['publish_base','archive_base','restore_base']),...baseTarget}).strict(),
 ...[createNode,editNode].flatMap(n=>[z.object({...n,kind:z.literal('folder')}).strict(),z.object({...n,kind:z.literal('text'),body}).strict(),z.object({...n,kind:z.literal('link'),url}).strict()]),
 z.object({action:z.literal('move_node'),...nodeTarget,parentId:uuid.nullable()}).strict(),z.object({action:z.literal('order_node'),...nodeTarget,direction:z.enum(['earlier','later'])}).strict(),z.object({action:z.enum(['archive_node','restore_node']),...nodeTarget}).strict(),
 z.object({action:z.literal('view'),baseId:uuid,revision,nodeId:uuid.nullable(),nodeRevision:revision.nullable()}).strict().refine(v=>(v.nodeId===null)===(v.nodeRevision===null))
])}).strict();
export const knowledgeReconciliation=z.object({tenantId:uuid,operationId:uuid}).strict();
const baseStatus=z.enum(['draft','published','archived']),nodeStatus=z.enum(['active','archived']);
const decimal=z.string().regex(/^(0|[1-9][0-9]{0,18})$/).refine(v=>/^(0|[1-9][0-9]{0,18})$/.test(v)&&BigInt(v)<=9223372036854775807n),rank=decimal.refine(v=>v!=='0');
const base=z.object({id:uuid,...details,status:baseStatus,restoreStatus:z.enum(['draft','published']).nullable(),revision,audienceCount:count.max(500),eligibleAudienceCount:count.max(500),isAssigned:z.boolean(),canRead:z.boolean(),canEdit:z.boolean(),canPublish:z.boolean(),canArchive:z.boolean(),canRestore:z.boolean()}).strict().refine(b=>b.eligibleAudienceCount<=b.audienceCount&&(b.status==='archived')===(b.restoreStatus!==null)&&(!b.canRead||(b.status==='published'&&b.isAssigned))&&(!b.canEdit||b.status!=='archived')&&(!b.canPublish||(b.status==='draft'&&b.audienceCount>0&&b.eligibleAudienceCount===b.audienceCount))&&(!b.canArchive||b.status!=='archived')&&(!b.canRestore||b.status==='archived'));
const node=z.object({id:uuid,baseId:uuid,parentId:uuid.nullable(),kind:z.enum(['folder','text','link']),...details,status:nodeStatus,revision,depth:z.number().int().min(1).max(16),rank,activeChildCount:count,canEdit:z.boolean(),canMove:z.boolean(),canMoveEarlier:z.boolean(),canMoveLater:z.boolean(),canArchive:z.boolean(),canRestore:z.boolean()}).strict().refine(n=>n.parentId!==null||n.kind==='folder').refine(n=>n.parentId===null?n.depth===1:n.depth>1).refine(n=>n.canEdit===n.canMove&&(!n.canMoveEarlier||n.canMove)&&(!n.canMoveLater||n.canMove)&&(!n.canArchive||(n.canEdit&&n.status==='active'&&n.activeChildCount===0))&&(!n.canRestore||(n.canEdit&&n.status==='archived')));
const path=z.array(z.object({id:uuid,name,status:nodeStatus,revision}).strict()).max(16).refine(a=>new Set(a.map(x=>x.id)).size===a.length);
const identity={tenantId:uuid,actorId:uuid,role,view},readScope={...identity,baseId:uuid,baseRevision:revision,audienceVersion:digest,treeVersion:digest};
const cursorScope=z.object({...identity,kind:z.enum(['catalog','base','children','node','search','assignees','insights']),baseId:uuid.nullable(),nodeId:uuid.nullable(),parentId:uuid.nullable(),status:z.enum(['all','draft','published','active','archived']),search:string(100),catalogVersion:digest.nullable(),baseRevision:revision.nullable(),audienceVersion:digest.nullable(),treeVersion:digest.nullable(),rosterVersion:digest.nullable(),eventVersion:digest.nullable(),timeZone:z.string()}).strict();
const cursorSchema=z.object({scope:cursorScope,id:uuid,position:z.string().min(1).max(500)}).strict();
const company=z.object({id:uuid,name:z.string(),time_zone:z.string()}).strict(),assignee=z.object({actorId:uuid,name:z.string().refine(v=>Array.from(v).length>=1&&Array.from(v).length<=100&&knowledgeStringValid(v)),eligible:z.boolean()}).strict();
const catalogSchema=z.object({...identity,company,bases:z.array(base).max(100),counts:z.object({total:count,draft:count,published:count,archived:count}).strict().refine(c=>c.total===c.draft+c.published+c.archived),catalogVersion:digest,nextCursor:cursorSchema.nullable(),serverTime:time,capabilities:z.object({canManage:z.boolean()}).strict()}).strict();
const baseSchema=z.object({...readScope,company,base,assignees:z.array(assignee).max(500),root:z.object({activeChildCount:count}).strict(),serverTime:time}).strict();
const childrenSchema=z.object({...readScope,base,parent:node.nullable(),path,nodes:z.array(node).max(100),matchedCount:count,nextCursor:cursorSchema.nullable(),serverTime:time}).strict();
const nodeSchema=z.object({...readScope,base,node,path,body:body.nullable(),url:url.nullable(),serverTime:time}).strict().refine(d=>d.node.kind==='folder'?d.body===null&&d.url===null:d.node.kind==='text'?d.body!==null&&d.url===null:d.url!==null&&d.body===null);
const searchSchema=z.object({...readScope,base,results:z.array(z.object({node,path}).strict()).max(100),matchedCount:count,nextCursor:cursorSchema.nullable(),serverTime:time}).strict();
const rosterSchema=z.object({...identity,users:z.array(assignee).max(100),matchedCount:count,rosterVersion:digest,nextCursor:cursorSchema.nullable(),serverTime:time}).strict();
const insightsSchema=z.object({...readScope,base,node:node.nullable(),path,eventVersion:digest,timeZone:z.string(),counts:z.object({assigned:count.max(500),eligible:count.max(500),unavailable:count.max(500),distinctEligibleViewers:count.max(500),eligibleViewedPercentage:z.number().min(0).max(100).nullable(),totalViews:decimal}).strict().refine(c=>c.assigned===c.eligible+c.unavailable&&c.distinctEligibleViewers<=c.eligible&&(c.eligible===0?c.eligibleViewedPercentage===null:c.eligibleViewedPercentage!==null&&Math.abs(c.eligibleViewedPercentage-100*c.distinctEligibleViewers/c.eligible)<0.000001)),users:z.array(assignee.extend({totalViews:decimal,lastViewedAt:time.nullable()}).strict().refine(u=>(u.totalViews==='0')===(u.lastViewedAt===null))).max(100),matchedCount:count.max(500),chart:z.array(z.object({date:z.iso.date(),views:decimal}).strict()).length(30),nextCursor:cursorSchema.nullable(),serverTime:time}).strict();
const savedSchema=z.object({operationId:uuid,action:z.enum(['create_base','edit_base','set_audience','publish_base','archive_base','restore_base','create_node','edit_node','move_node','order_node','archive_node','restore_node','view']),baseId:uuid,revision,nodeId:uuid.optional(),nodeRevision:revision.optional(),eventId:uuid.optional(),recordedAt:time.optional()}).strict();
const reconciledSchema=z.object({tenantId:uuid,actorId:uuid,role,operationId:uuid,status:z.enum(['recorded','not_recorded'])}).strict();
export class KnowledgeBaseError extends Error{status:number;constructor(message:string,status=503){super(message);this.status=status;}}
function fail(error:{code?:string}|null){if(!error)return;const code=error.code??'';throw new KnowledgeBaseError(code==='42501'?'Company or Knowledge Base access is unavailable.':code==='40001'?'The resource, audience or hierarchy changed. Refresh and review.':code==='54000'?'Knowledge Base payload exceeds the supported byte limit.':['22023','22P02','22003','23514','23502','22P05'].includes(code)?'Choose valid Knowledge Base details and filters.':'Knowledge Base could not be verified. Refresh and review before another action.',code==='42501'?403:code==='40001'?409:code==='54000'?413:['22023','22P02','22003','23514','23502','22P05'].includes(code)?400:503);}
const limit=z.string().regex(/^[1-9][0-9]{0,2}$/).transform(Number).refine(v=>v<=100).optional(),queryCursor=z.string().regex(/^[A-Za-z0-9_-]+$/).max(5000).optional(),queryView=z.enum(['auto','manage','library']).optional();
function params<T>(p:URLSearchParams,s:z.ZodType<T>):T{if([...p.keys()].some(k=>p.getAll(k).length!==1))throw new KnowledgeBaseError('Choose valid Knowledge Base filters.',400);const v=s.safeParse(Object.fromEntries(p));if(!v.success)throw new KnowledgeBaseError('Choose valid Knowledge Base filters.',400);return v.data;}
const common={tenantId:uuid,view:queryView},paging={search:string(100).optional(),limit,cursor:queryCursor};
function id(v:string){const p=uuid.safeParse(v);if(!p.success)throw new KnowledgeBaseError('Choose a valid resource.',400);return p.data;}
export function parseKnowledgeBasesQuery(p:URLSearchParams):KB.KnowledgeBasesQuery{const q=params(p,z.object({...common,...paging,status:z.enum(['all','draft','published','archived']).optional()}).strict());return {...q,view:q.view??'auto',status:q.status??'all',search:q.search??'',limit:q.limit??50};}
export function parseKnowledgeBaseQuery(p:URLSearchParams,baseId:string):KB.KnowledgeBaseQuery{const q=params(p,z.object(common).strict());return {...q,baseId:id(baseId),view:q.view??'auto'};}
export function parseKnowledgeNodesQuery(p:URLSearchParams,baseId:string):KB.KnowledgeNodesQuery{const q=params(p,z.object({...common,...paging,parentId:uuid.optional(),status:z.enum(['all','active','archived']).optional()}).strict());return {...q,baseId:id(baseId),view:q.view??'auto',status:q.status??'all',search:q.search??'',limit:q.limit??50};}
export function parseKnowledgeNodeQuery(p:URLSearchParams,baseId:string,nodeId:string):KB.KnowledgeNodeQuery{return {...parseKnowledgeBaseQuery(p,baseId),nodeId:id(nodeId)};}
export function parseKnowledgeSearchQuery(p:URLSearchParams,baseId:string):KB.KnowledgeSearchQuery{const q=params(p,z.object({...common,...paging}).strict());return {...q,baseId:id(baseId),view:q.view??'auto',search:q.search??'',limit:q.limit??50};}
export function parseKnowledgeAssigneesQuery(p:URLSearchParams):KB.KnowledgeAssigneesQuery{const q=params(p,z.object({tenantId:uuid,...paging}).strict());return {...q,search:q.search??'',limit:q.limit??50};}
export function parseKnowledgeInsightsQuery(p:URLSearchParams,baseId:string):KB.KnowledgeInsightsQuery{const q=params(p,z.object({...common,...paging,nodeId:uuid.optional()}).strict());return {...q,baseId:id(baseId),view:q.view??'manage',search:q.search??'',limit:q.limit??50};}
export function decodeKnowledgeCursor(v?:string){if(!v)return null;try{if(v.length>5000||!/^[A-Za-z0-9_-]+$/.test(v))throw Error();return cursorSchema.parse(JSON.parse(Buffer.from(v,'base64url').toString()));}catch{throw new KnowledgeBaseError('Choose a valid resource cursor.',400);}}
const encode=(v:z.infer<typeof cursorSchema>|null)=>v?Buffer.from(JSON.stringify(v)).toString('base64url'):null;
type Read={tenantId:string;kind:z.infer<typeof cursorScope>['kind'];view?:'auto'|KB.KnowledgeView;baseId?:string;nodeId?:string;parentId?:string;status?:string;search?:string;limit?:number;cursor?:string};
async function signed(c:SupabaseClient){const{data:{user},error}=await c.auth.getUser();if(error||!user)throw new KnowledgeBaseError('Sign in to view Knowledge Base.',401);return user.id.toLowerCase();}
const accessSchema=z.object({...identity,timeZone:z.string(),catalogVersion:digest,rosterVersion:digest.nullable(),baseRevision:revision.nullable(),baseStatus:baseStatus.nullable(),audienceVersion:digest.nullable(),treeVersion:digest.nullable(),eventVersion:digest.nullable(),nodeRevision:revision.nullable(),nodeStatus:nodeStatus.nullable(),bases:z.array(z.object({id:uuid,revision,status:baseStatus,audienceVersion:digest}).strict()).max(100)}).strict();
function invalid(message='Knowledge Base response could not be verified.'):never{throw new KnowledgeBaseError(message);}
function timezone(v:string){try{new Intl.DateTimeFormat('en',{timeZone:v}).format();}catch{invalid('Company calendar could not be verified.');}}
async function snapshot<T>(c:SupabaseClient,q:Read,s:z.ZodType<T>){const actor=await signed(c),after=decodeKnowledgeCursor(q.cursor);if(after&&(after.scope.actorId!==actor||after.scope.tenantId!==q.tenantId))throw new KnowledgeBaseError('Cursor belongs to another account or company.',409);const{data,error}=await c.rpc('read_knowledge_base',{target_tenant:q.tenantId,read_kind:q.kind,read_view:q.view??'manage',target_base:q.baseId??null,target_node:q.nodeId??null,parent_node:q.parentId??null,status_filter:q.status??'all',search_text:q.search??'',page_limit:q.limit??50,after_item:after});fail(error);const p=s.safeParse(data);if(!p.success)invalid();return{data:p.data,actor};}
async function recheck(c:SupabaseClient,q:Read,d:KB.KnowledgeIdentity&{catalogVersion?:string;rosterVersion?:string;baseRevision?:number;audienceVersion?:string;treeVersion?:string;eventVersion?:string;timeZone?:string;company?:{time_zone:string};base?:KB.KnowledgeBase;node?:KB.KnowledgeNode|null;parent?:KB.KnowledgeNode|null},bases:KB.KnowledgeBase[]=[]){const{data,error}=await c.rpc('read_knowledge_base_access',{target_tenant:q.tenantId,read_view:d.view,target_base:q.baseId??null,target_node:q.nodeId??q.parentId??null,target_bases:bases.map(b=>b.id)});fail(error);const p=accessSchema.safeParse(data);if(!p.success)invalid('Knowledge Base access could not be verified.');const a=p.data;timezone(a.timeZone);if(a.tenantId!==d.tenantId||a.actorId!==d.actorId||a.role!==d.role||a.view!==d.view)throw new KnowledgeBaseError('Company or Knowledge Base access changed.',403);if(d.catalogVersion&&a.catalogVersion!==d.catalogVersion||d.rosterVersion&&a.rosterVersion!==d.rosterVersion||d.baseRevision!==undefined&&a.baseRevision!==d.baseRevision||d.audienceVersion&&a.audienceVersion!==d.audienceVersion||d.treeVersion&&a.treeVersion!==d.treeVersion||d.eventVersion&&a.eventVersion!==d.eventVersion||d.timeZone&&a.timeZone!==d.timeZone||d.company&&a.timeZone!==d.company.time_zone||d.base&&a.baseStatus!==d.base.status||(d.node??d.parent)&&a.nodeRevision!==(d.node??d.parent)!.revision||new Set(a.bases.map(b=>b.id)).size!==a.bases.length||bases.some(b=>!a.bases.some(x=>x.id===b.id&&x.status===b.status&&x.revision===b.revision)))throw new KnowledgeBaseError('The resource, audience or hierarchy changed. Refresh and review.',409);}
function identityCheck(d:KB.KnowledgeIdentity,q:Read,actor:string){const expectedView=q.view==='auto'?(['owner','admin'].includes(d.role)?'manage':'library'):q.view??'manage';if(d.tenantId!==q.tenantId||d.actorId!==actor||d.view!==expectedView||d.view==='manage'&&!['owner','admin'].includes(d.role))invalid();}
function pageCheck(d:KB.KnowledgeIdentity&{nextCursor:z.infer<typeof cursorSchema>|null;catalogVersion?:string;rosterVersion?:string;baseRevision?:number;audienceVersion?:string;treeVersion?:string;eventVersion?:string;timeZone?:string},q:Read,ids:string[],total:number){if(ids.length>(q.limit??50)||ids.length>total||new Set(ids).size!==ids.length)invalid();const n=d.nextCursor;if(n){const s=n.scope;if(ids.length!==(q.limit??50)||n.id!==ids.at(-1)||s.tenantId!==d.tenantId||s.actorId!==d.actorId||s.role!==d.role||s.view!==d.view||s.kind!==q.kind||s.baseId!==(q.baseId??null)||s.nodeId!==(q.nodeId??null)||s.parentId!==(q.parentId??null)||s.status!==(q.status??'all')||s.search!==(q.search??'')||s.catalogVersion!==(d.catalogVersion??null)||s.rosterVersion!==(d.rosterVersion??null)||s.baseRevision!==(d.baseRevision??null)||s.audienceVersion!==(d.audienceVersion??null)||s.treeVersion!==(d.treeVersion??null)||s.eventVersion!==(d.eventVersion??null)||ids.length>=total)invalid('Knowledge Base continuation could not be verified.');}}
function resourceCheck(d:KB.KnowledgeReadScope&{base:KB.KnowledgeBase},q:Read){if(d.baseId!==q.baseId||d.base.id!==q.baseId||d.baseRevision!==d.base.revision||d.view==='library'&&(!d.base.canRead||d.base.status!=='published'))invalid();}
function pathCheck(p:KB.KnowledgePathItem[],n:KB.KnowledgeNode,reader:boolean){if(p.length!==n.depth-1||p.some(x=>x.id===n.id)||p.at(-1)?.id!==(n.parentId??undefined)||reader&&(n.status!=='active'||p.some(x=>x.status!=='active')))invalid('Knowledge Base hierarchy could not be verified.');}
export async function readKnowledgeBases(c:SupabaseClient,query:KB.KnowledgeBasesQuery):Promise<KB.KnowledgeBasesData>{const q={...query,kind:'catalog'as const};const{data:d,actor}=await snapshot(c,q,catalogSchema);identityCheck(d,q,actor);pageCheck(d,q,d.bases.map(b=>b.id),q.status==='all'?d.counts.total:d.counts[q.status]);if(d.company.id!==d.tenantId||d.capabilities.canManage!==['owner','admin'].includes(d.role)||d.bases.some(b=>q.status!=='all'&&b.status!==q.status||d.view==='library'&&!b.canRead))invalid();await recheck(c,q,d,d.bases);return{...d,nextCursor:encode(d.nextCursor)};}
export async function readKnowledgeBase(c:SupabaseClient,query:KB.KnowledgeBaseQuery):Promise<KB.KnowledgeBaseData>{const q={...query,kind:'base'as const};const{data:d,actor}=await snapshot(c,q,baseSchema);identityCheck(d,q,actor);resourceCheck(d,q);if(d.company.id!==d.tenantId||new Set(d.assignees.map(u=>u.actorId)).size!==d.assignees.length||d.view==='library'&&d.assignees.length||d.view==='manage'&&(d.assignees.length!==d.base.audienceCount||d.assignees.filter(u=>u.eligible).length!==d.base.eligibleAudienceCount))invalid();await recheck(c,q,d);return d;}
export async function readKnowledgeNodes(c:SupabaseClient,query:KB.KnowledgeNodesQuery):Promise<KB.KnowledgeNodesData>{const q={...query,kind:'children'as const};const{data:d,actor}=await snapshot(c,q,childrenSchema);identityCheck(d,q,actor);resourceCheck(d,q);pageCheck(d,q,d.nodes.map(n=>n.id),d.matchedCount);if((d.parent?.id??null)!==(q.parentId??null)||d.parent&&d.parent.kind!=='folder'||d.path.length!==(d.parent?.depth??0)||d.parent&&d.path.at(-1)?.id!==d.parent.id||d.nodes.some(n=>n.baseId!==q.baseId||n.parentId!==(q.parentId??null)||n.depth!==(d.parent?.depth??0)+1||q.status!=='all'&&n.status!==q.status||d.view==='library'&&n.status!=='active'))invalid();await recheck(c,q,d);return{...d,nextCursor:encode(d.nextCursor)};}
export async function readKnowledgeNode(c:SupabaseClient,query:KB.KnowledgeNodeQuery):Promise<KB.KnowledgeNodeData>{const q={...query,kind:'node'as const};const{data:d,actor}=await snapshot(c,q,nodeSchema);identityCheck(d,q,actor);resourceCheck(d,q);if(d.node.id!==q.nodeId||d.node.baseId!==q.baseId)invalid();pathCheck(d.path,d.node,d.view==='library');await recheck(c,q,d);return d;}
export async function searchKnowledgeBase(c:SupabaseClient,query:KB.KnowledgeSearchQuery):Promise<KB.KnowledgeSearchData>{const q={...query,kind:'search'as const};const{data:d,actor}=await snapshot(c,q,searchSchema);identityCheck(d,q,actor);resourceCheck(d,q);pageCheck(d,q,d.results.map(x=>x.node.id),d.matchedCount);for(const x of d.results){if(x.node.baseId!==q.baseId)invalid();pathCheck(x.path,x.node,d.view==='library');}await recheck(c,q,d);return{...d,nextCursor:encode(d.nextCursor)};}
export async function readKnowledgeAssignees(c:SupabaseClient,query:KB.KnowledgeAssigneesQuery):Promise<KB.KnowledgeAssigneesData>{const q={...query,kind:'assignees'as const};const{data:d,actor}=await snapshot(c,q,rosterSchema);identityCheck(d,q,actor);pageCheck(d,q,d.users.map(u=>u.actorId),d.matchedCount);if(d.users.some(u=>!u.eligible))invalid();await recheck(c,q,d);return{...d,nextCursor:encode(d.nextCursor)};}
export async function readKnowledgeInsights(c:SupabaseClient,query:KB.KnowledgeInsightsQuery):Promise<KB.KnowledgeInsightsData>{const q={...query,kind:'insights'as const};const{data:d,actor}=await snapshot(c,q,insightsSchema);identityCheck(d,q,actor);resourceCheck(d,q);pageCheck(d,q,d.users.map(u=>u.actorId),d.matchedCount);if((d.node?.id??null)!==(q.nodeId??null)||d.counts.assigned!==d.base.audienceCount||d.counts.eligible!==d.base.eligibleAudienceCount||d.matchedCount>d.counts.assigned||d.users.filter(u=>u.eligible).length>d.counts.eligible||d.users.filter(u=>!u.eligible).length>d.counts.unavailable||d.chart.some((x,i)=>i>0&&x.date<=d.chart[i-1].date))invalid();if(d.node)pathCheck(d.path,d.node,false);else if(d.path.length)invalid();await recheck(c,q,d);return{...d,nextCursor:encode(d.nextCursor)};}
export async function saveKnowledgeBase(c:SupabaseClient,input:KB.KnowledgeMutation):Promise<KB.KnowledgeSaved>{await signed(c);const validated=knowledgeMutation.safeParse(input);if(!validated.success)throw new KnowledgeBaseError('Choose valid Knowledge Base details.',400);if(!knowledgePayloadFits(input))throw new KnowledgeBaseError('Knowledge Base payload is too large.',413);const{data,error}=await c.rpc('save_knowledge_base',{target_tenant:input.tenantId,operation_id:input.operationId,change:input.change});fail(error);const p=savedSchema.safeParse(data);if(!p.success)invalid('The save acknowledgement could not be verified. Refresh and review.');const s=p.data,v=input.change,isView=v.action==='view',nodeAction=v.action.endsWith('_node');if(s.operationId!==input.operationId||s.action!==v.action||'baseId'in v&&s.baseId!==v.baseId||s.revision!==('revision'in v?v.revision+(isView?0:1):1)||isView!==!!s.eventId||isView!==!!s.recordedAt||('nodeId'in v&&v.nodeId!==null?s.nodeId!==v.nodeId:!nodeAction&&s.nodeId!==undefined)||nodeAction&&(!s.nodeId||s.nodeRevision!==('nodeRevision'in v&&v.nodeRevision!==null?v.nodeRevision+1:1))||isView&&(s.nodeId!==(v.nodeId??undefined)||s.nodeRevision!==(v.nodeRevision??undefined)))invalid('The save acknowledgement could not be verified. Refresh and review.');return s;}
export async function reconcileKnowledgeView(c:SupabaseClient,input:{tenantId:string;operationId:string}):Promise<KB.KnowledgeViewReconciliation>{const actor=await signed(c);const p=knowledgeReconciliation.safeParse(input);if(!p.success)throw new KnowledgeBaseError('Choose a valid view operation.',400);async function read(){const{data,error}=await c.rpc('reconcile_knowledge_view',{target_tenant:input.tenantId,operation_id:input.operationId});fail(error);const v=reconciledSchema.safeParse(data);if(!v.success||v.data.tenantId!==input.tenantId||v.data.actorId!==actor||v.data.operationId!==input.operationId)invalid('View outcome could not be verified.');return v.data;}const first=await read(),fresh=await read();if(first.role!==fresh.role||first.status!==fresh.status)throw new KnowledgeBaseError('View outcome changed. Reconcile again before continuing.',409);return fresh;}
