import {createHash,createHmac} from 'node:crypto';
import {z} from 'zod';
import type {SupabaseClient} from '@supabase/supabase-js';
import {supabaseConfig} from './supabase-config';
import {knowledgeStringValid,KnowledgeBaseError} from './knowledge-base';
import type * as F from './knowledge-base-file-types';
import {KNOWLEDGE_FILE_MAX_BYTES,KNOWLEDGE_FILE_MAX_MULTIPART_BYTES,KNOWLEDGE_FILE_MAX_METADATA_BYTES} from './knowledge-base-file-types';
export class KnowledgeFileError extends KnowledgeBaseError {}
const uuid=z.uuid().transform(v=>v.toLowerCase()),rev=z.number().int().min(1).max(2147483647),expected=rev.max(2147483646),time=z.iso.datetime({offset:true}),role=z.enum(['owner','admin','manager','employee']);
const text=(max:number,min=0)=>z.string().refine(v=>v.length>=min&&v.length<=max&&knowledgeStringValid(v));
const name=text(100,1).refine(v=>v.trim().length>0),description=text(500),filename=text(255,1).refine(v=>v.trim().length>0&&!/[\r\n]/.test(v)&&Buffer.byteLength(v)<=1024);
const common={tenantId:uuid,operationId:uuid,baseId:uuid,expectedBaseRevision:expected,name,description,filename};
export const knowledgeFileMetadata:z.ZodType<F.KnowledgeFileMetadata>=z.discriminatedUnion('mode',[z.object({...common,mode:z.literal('create'),parentId:uuid}).strict(),z.object({...common,mode:z.literal('replace'),nodeId:uuid,expectedNodeRevision:expected}).strict()]);
export const knowledgeFileOperation=z.object({tenantId:uuid,operationId:uuid}).strict();
export const knowledgeFileAttemptChange=knowledgeFileOperation.extend({expectedAttemptRevision:rev}).strict();
export const knowledgeFileCleanup=knowledgeFileOperation.extend({uploadActorId:uuid,uploadOperationId:uuid,expectedAttemptRevision:rev}).strict();
const identity={tenantId:uuid,actorId:uuid,role};
const saved=z.object({...identity,operationId:uuid,action:z.literal('save_file'),baseId:uuid,nodeId:uuid,revision:rev,nodeRevision:rev,versionId:uuid}).strict();
const states=['upload_attempted','uploaded_unverified','provider_succeeded','finalized','closed','cleanup_acknowledged'] as const;
const capabilities=z.object({canFinalize:z.boolean(),canClose:z.boolean(),canCleanup:z.boolean()}).strict();
const attempt=z.object({...identity,operationId:uuid,action:z.literal('save_file'),status:z.enum(['not_recorded',...states]),attemptRevision:rev.nullable(),deadline:time.nullable(),capabilities,saved:saved.nullable(),serverTime:time}).strict().refine(d=>(d.status==='not_recorded')===(d.attemptRevision===null)&&(d.status==='not_recorded')===(d.deadline===null)&&(d.status==='finalized')===(d.saved!==null)&&d.capabilities.canClose===['upload_attempted','uploaded_unverified','provider_succeeded'].includes(d.status)&&(!d.capabilities.canFinalize||d.status==='provider_succeeded')&&(!d.capabilities.canCleanup||d.status==='closed')&&['owner','admin'].includes(d.role)&&(!d.saved||(d.saved.tenantId===d.tenantId&&d.saved.actorId===d.actorId&&d.saved.role===d.role&&d.saved.operationId===d.operationId)));
const media=z.enum(['application/pdf','text/plain','text/csv','image/png','image/jpeg']),digest=z.string().regex(/^[a-f0-9]{64}$/);
const internal=attempt.safeExtend({baseId:uuid,nodeId:uuid,parentId:uuid,mode:z.enum(['create','replace']),path:z.string().max(150),bytes:z.number().int().min(1).max(KNOWLEDGE_FILE_MAX_BYTES),sha256:digest,mediaType:media,filename,expectedBaseRevision:expected,expectedNodeRevision:expected.nullable(),attemptId:uuid,providerId:uuid.nullable(),providerVersion:uuid.nullable()}).refine(d=>d.path===[d.tenantId,d.baseId,d.nodeId,d.attemptId].join('/')&&(d.providerId===null)===(d.providerVersion===null)&&(!['uploaded_unverified','provider_succeeded','finalized'].includes(d.status)||d.providerId!==null)&&(!d.saved||(d.saved.baseId===d.baseId&&d.saved.nodeId===d.nodeId)));
type Internal=z.infer<typeof internal>;
const budget=z.object({...identity,allocatedBytes:z.number().int().min(0).max(104857600),allocatedAttempts:z.number().int().min(0).max(2048),byteLimit:z.literal(104857600),globalAttemptLimit:z.literal(4096),companyAttemptLimit:z.literal(2048),states:z.object(Object.fromEntries(states.map(s=>[s,z.number().int().min(0).max(2048)])) as Record<typeof states[number],z.ZodNumber>).strict(),serverTime:time}).strict().refine(d=>Object.values(d.states).reduce((n,v)=>n+v,0)===d.allocatedAttempts&&d.allocatedBytes>=d.allocatedAttempts&&d.allocatedBytes<=d.allocatedAttempts*KNOWLEDGE_FILE_MAX_BYTES&&['owner','admin'].includes(d.role));
function fail(error:{code?:string}|null){if(!error)return;throw new KnowledgeFileError(error.code==='42501'?'File access changed. Refresh and review.':error.code==='40001'?'File state changed. Refresh and review.':error.code==='54000'?'Reserved and retained file budget is unavailable.':'File operation could not be verified.',error.code==='42501'?403:error.code==='40001'?409:error.code==='54000'?413:error.code==='22023'?400:503);}
function invalid():never{throw new KnowledgeFileError('File outcome could not be verified. Reconcile before another action.',503);}
async function signed(c:SupabaseClient){const{data,error}=await c.auth.getUser();if(error||!data.user?.id||!data.user.email_confirmed_at||data.user.is_anonymous)throw new KnowledgeFileError('Sign in to access company files.',401);return data.user.id;}
function scope(d:F.KnowledgeFileIdentity,input:{tenantId:string;operationId?:string},actor:string){if(d.tenantId!==input.tenantId||d.actorId!==actor||'operationId'in d&&input.operationId!==(d as F.KnowledgeFileAttemptData).operationId)invalid();}
async function rpc(c:SupabaseClient,name:string,args:Record<string,unknown>){const{data,error}=await c.rpc(name,args);fail(error);return data;}
export async function boundedBody(r:Response|Request,max:number){const announced=r.headers.get('content-length');if(announced&&(!/^\d+$/.test(announced)||Number(announced)>max))throw new KnowledgeFileError('File request is too large.',413);const reader=r.body?.getReader();if(!reader)return Buffer.alloc(0);const chunks:Uint8Array[]=[];let size=0;try{for(;;){const{value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new KnowledgeFileError('File request is too large.',413);}chunks.push(value);}}finally{reader.releaseLock();}return Buffer.concat(chunks,size);}
/** Commands and metadata are flat strict objects; duplicate JSON keys are rejected. */
export function fileJson(raw:string){if(Buffer.byteLength(raw)>KNOWLEDGE_FILE_MAX_METADATA_BYTES)throw new KnowledgeFileError('File metadata is too large.',413);try{const keys=new Set<string>();for(let i=0;i<raw.length;i++){if(raw[i]!=='"')continue;const start=i++;while(i<raw.length&&raw[i]!=='"'){if(raw[i]==='\\')i++;i++;}const token=raw.slice(start,i+1);let next=i+1;while(/\s/.test(raw[next]??'')&&next<raw.length)next++;if(raw[next]===':'){const key=JSON.parse(token) as string;if(keys.has(key))throw Error('duplicate');keys.add(key);}}return JSON.parse(raw) as unknown;}catch{throw new KnowledgeFileError('Choose valid file details.',400);}}
export function inspectKnowledgeFile(bytes:Uint8Array,originalFilename:string,declaredType:string):F.KnowledgeFileMediaType{if(bytes.length<1||bytes.length>KNOWLEDGE_FILE_MAX_BYTES)throw new KnowledgeFileError('Choose a nonempty file up to 2 MiB.',413);const ext=originalFilename.toLowerCase().split('.').at(-1);let type:F.KnowledgeFileMediaType;const b=Buffer.from(bytes);
 if(ext==='pdf'&&b.subarray(0,5).toString('ascii')==='%PDF-')type='application/pdf';else if(ext==='png'&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))type='image/png';else if(['jpg','jpeg'].includes(ext??'')&&b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255)type='image/jpeg';else if(ext==='txt'||ext==='csv'){let content:string;try{content=new TextDecoder('utf-8',{fatal:true}).decode(b);}catch{throw new KnowledgeFileError('Choose valid UTF8 text or CSV.',422);}if(content.includes('\0')||/^\s*(?:<!doctype\s+html|<html|<svg|<script)/i.test(content))throw new KnowledgeFileError('This file format is not supported.',422);type=ext==='txt'?'text/plain':'text/csv';}else throw new KnowledgeFileError('Choose PDF, UTF8 text or CSV, PNG or JPEG.',422);
 if(declaredType!==type&&declaredType!==''&&declaredType!=='application/octet-stream'&&!(ext==='csv'&&declaredType==='application/vnd.ms-excel'))throw new KnowledgeFileError('File extension, media type and bytes must agree.',422);return type;}
export async function parseKnowledgeFileUpload(request:Request,baseId:string){const raw=await boundedBody(request,KNOWLEDGE_FILE_MAX_MULTIPART_BYTES);let form:FormData;try{form=await new Request('http://local.invalid',{method:'POST',headers:{'Content-Type':request.headers.get('content-type')??''},body:raw}).formData();}catch{throw new KnowledgeFileError('Choose one file and valid metadata.',400);}const entries=[...form.entries()];if(entries.length!==2||form.getAll('metadata').length!==1||form.getAll('file').length!==1||typeof form.get('metadata')!=='string'||!(form.get('file')instanceof File))throw new KnowledgeFileError('Choose exactly one file.',400);const p=knowledgeFileMetadata.safeParse(fileJson(form.get('metadata') as string));if(!p.success||p.data.baseId!==baseId.toLowerCase())throw new KnowledgeFileError('Choose valid file details.',400);const file=form.get('file') as File;const bytes=Buffer.from(await file.arrayBuffer());const type=inspectKnowledgeFile(bytes,p.data.filename,file.type);return{metadata:p.data,bytes,mediaType:type,sha256:createHash('sha256').update(bytes).digest('hex')};}
function verifier(){const keyId=process.env.CT_ALT_KB_FILE_HMAC_KEY_ID,key=process.env.CT_ALT_KB_FILE_HMAC_KEY;if(!keyId||!/^[A-Za-z0-9_-]{1,32}$/.test(keyId)||!key||!/^[A-Za-z0-9+/]+={0,2}$/.test(key)||Buffer.from(key,'base64').length<32)throw new KnowledgeFileError('Private file verification is not configured.',503);return{keyId,key:Buffer.from(key,'base64')};}
export function fileProofMessage(a:Internal,stage:string,keyId:string,expires?:number){return[stage,keyId,a.tenantId,a.baseId,a.nodeId,a.attemptId,a.actorId,a.operationId,a.path,String(a.bytes),a.sha256,a.mediaType,String(new Date(a.deadline!).getTime()),stage==='upload-v1'?'':a.providerId??'',stage==='upload-v1'?'':a.providerVersion??'',expires===undefined?'':String(expires)].map(v=>`${Buffer.byteLength(v)}:${v}`).join('');}
function proof(a:Internal,stage:string,expires?:number){const{keyId,key}=verifier();return{keyId,proof:createHmac('sha256',key).update(fileProofMessage(a,stage,keyId,expires)).digest('hex')};}
async function provider(c:SupabaseClient,path:string,method='GET',body?:Buffer,headers:Record<string,string>={}){const config=supabaseConfig();const{data,error}=await c.auth.getSession();if(!config||error||!data.session?.access_token)throw new KnowledgeFileError('File sign-in could not be verified.',401);try{return await fetch(`${config.url}/storage/v1${path}`,{method,headers:{apikey:config.key,Authorization:`Bearer ${data.session.access_token}`,...headers},body:body?new Uint8Array(body):undefined,cache:'no-store',signal:AbortSignal.timeout(30000)});}catch{throw new KnowledgeFileError('The provider outcome is unknown. Reconcile before another action.',503);}}
function objectPath(a:{path:string},version?:string){return`/object${version?'/authenticated':''}/ct-alt-knowledge-base/${a.path}${version?`?versionId=${version}`:''}`;}
async function readInternal(c:SupabaseClient,input:F.KnowledgeFileOperation,actor:string):Promise<Internal>{const d=internal.safeParse(await rpc(c,'read_knowledge_file',{target_tenant:input.tenantId,operation_id:input.operationId,internal:true}));if(!d.success)invalid();scope(d.data,input,actor);return d.data;}
export async function reconcileKnowledgeFile(c:SupabaseClient,input:F.KnowledgeFileOperation):Promise<F.KnowledgeFileAttemptData>{const actor=await signed(c);const first=attempt.safeParse(await rpc(c,'read_knowledge_file',{target_tenant:input.tenantId,operation_id:input.operationId})),fresh=attempt.safeParse(await rpc(c,'read_knowledge_file',{target_tenant:input.tenantId,operation_id:input.operationId}));if(!first.success||!fresh.success)invalid();scope(first.data,input,actor);scope(fresh.data,input,actor);if(first.data.actorId!==fresh.data.actorId||first.data.role!==fresh.data.role||first.data.status!==fresh.data.status||first.data.attemptRevision!==fresh.data.attemptRevision)throw new KnowledgeFileError('File outcome changed. Reconcile again.',409);return fresh.data;}
export async function readKnowledgeFileBudget(c:SupabaseClient,tenantId:string):Promise<F.KnowledgeFileBudgetData>{const actor=await signed(c);const first=budget.safeParse(await rpc(c,'read_knowledge_file_budget',{target_tenant:tenantId})),fresh=budget.safeParse(await rpc(c,'read_knowledge_file_budget',{target_tenant:tenantId}));if(!first.success||!fresh.success)invalid();scope(first.data,{tenantId},actor);scope(fresh.data,{tenantId},actor);if(first.data.role!==fresh.data.role)throw new KnowledgeFileError('File access changed.',403);return fresh.data;}
async function change(c:SupabaseClient,a:Internal,action:'provider_success'|'finalize'|'close',stage?:string){const expires=stage?new Date(a.serverTime).getTime()+59000:undefined,p=stage?proof(a,stage,expires):undefined;const d=attempt.safeParse(await rpc(c,'change_knowledge_file',{target_tenant:a.tenantId,operation_id:a.operationId,action,expected_revision:a.attemptRevision,key_id:p?.keyId??null,proof:p?.proof??null,expires_ms:expires??null}));if(!d.success)invalid();scope(d.data,a,a.actorId);return d.data;}
async function verifyBytes(c:SupabaseClient,a:Internal){if(!a.providerVersion||!a.providerId)invalid();const r=await provider(c,objectPath(a,a.providerVersion));if(r.status!==200)throw new KnowledgeFileError('File bytes could not be verified.',503);const bytes=await boundedBody(r,KNOWLEDGE_FILE_MAX_BYTES);if(bytes.length!==a.bytes||createHash('sha256').update(bytes).digest('hex')!==a.sha256||inspectKnowledgeFile(bytes,a.filename,a.mediaType)!==a.mediaType)throw new KnowledgeFileError('File bytes differ from the accepted intent.',422);return bytes;}
export async function finalizeKnowledgeFile(c:SupabaseClient,input:F.KnowledgeFileAttemptChange):Promise<F.KnowledgeFileSaved>{const actor=await signed(c);verifier();const a=await readInternal(c,input,actor);if(a.status==='finalized'&&a.saved)return a.saved;if(a.attemptRevision!==input.expectedAttemptRevision)throw new KnowledgeFileError('File attempt changed.',409);if(a.status!=='provider_succeeded')throw new KnowledgeFileError('Provider success was not durably attested. Close this attempt.',409);if(!a.capabilities.canFinalize){await change(c,a,'finalize','finalize-v1');throw new KnowledgeFileError('The stale file attempt was closed; the previous file remains current.',409);}await verifyBytes(c,a);const fresh=await readInternal(c,input,actor);if(fresh.role!==a.role||fresh.status!==a.status||fresh.attemptRevision!==a.attemptRevision||fresh.providerVersion!==a.providerVersion||fresh.sha256!==a.sha256)throw new KnowledgeFileError('File attempt changed during verification.',409);const d=await change(c,fresh,'finalize','finalize-v1');if(d.status==='closed')throw new KnowledgeFileError('The stale file attempt was closed; the previous file remains current.',409);if(!d.saved)invalid();return d.saved;}
export async function closeKnowledgeFile(c:SupabaseClient,input:F.KnowledgeFileAttemptChange){const actor=await signed(c),a=await readInternal(c,input,actor);if(a.attemptRevision!==input.expectedAttemptRevision&&!['closed','cleanup_acknowledged'].includes(a.status))throw new KnowledgeFileError('File attempt changed.',409);return change(c,a,'close');}
export async function uploadKnowledgeFile(c:SupabaseClient,upload:Awaited<ReturnType<typeof parseKnowledgeFileUpload>>):Promise<F.KnowledgeFileSaved>{const actor=await signed(c);verifier();const input=upload.metadata;const reserved=await rpc(c,'reserve_knowledge_file',{target_tenant:input.tenantId,operation_id:input.operationId,intent:{metadata:input,bytes:upload.bytes.length,sha256:upload.sha256,mediaType:upload.mediaType}});const r=z.object({claimed:z.boolean(),attempt}).strict().safeParse(reserved);if(!r.success)invalid();scope(r.data.attempt,input,actor);let a=await readInternal(c,input,actor);if(a.status==='finalized'&&a.saved)return a.saved;
 if(r.data.claimed){const p=proof(a,'upload-v1'),metadata={ct_alt:{v:'upload-v1',keyId:p.keyId,attemptId:a.attemptId,operationId:a.operationId,proof:p.proof}};const response=await provider(c,objectPath(a),'POST',upload.bytes,{'Content-Type':a.mediaType,'x-upsert':'false','x-metadata':Buffer.from(JSON.stringify(metadata)).toString('base64')});if(response.status!==200)throw new KnowledgeFileError('Upload was not acknowledged. Reconcile or close this attempt.',503);const raw=await boundedBody(response,16384);let ack:unknown;try{ack=JSON.parse(raw.toString());}catch{invalid();}const ackSchema=z.object({Key:z.string(),Id:uuid}).strict().safeParse(ack);if(!ackSchema.success||ackSchema.data.Key!==`ct-alt-knowledge-base/${a.path}`)invalid();a=await readInternal(c,input,actor);if(a.status!=='uploaded_unverified'||a.providerId!==ackSchema.data.Id)invalid();await change(c,a,'provider_success','provider-success-v1');a=await readInternal(c,input,actor);
 }
 if(a.status!=='provider_succeeded')throw new KnowledgeFileError('This attempt cannot upload again. Reconcile or close it.',409);return finalizeKnowledgeFile(c,{tenantId:a.tenantId,operationId:a.operationId,expectedAttemptRevision:a.attemptRevision!});}
const file=z.object({versionId:uuid,filename,mediaType:media,bytes:z.number().int().min(1).max(KNOWLEDGE_FILE_MAX_BYTES),sha256:digest,uploadedAt:time,uploaderName:z.string().refine(v=>knowledgeStringValid(v)&&Array.from(v).length>=1&&Array.from(v).length<=100)}).strict();
const download=z.object({...identity,baseId:uuid,nodeId:uuid,versionId:uuid,baseRevision:rev,nodeRevision:rev,baseStatus:z.enum(['draft','published','archived']),nodeStatus:z.enum(['active','archived']),audienceVersion:z.string().regex(/^[a-f0-9]{32}$/),treeVersion:z.string().regex(/^[a-f0-9]{32}$/),path:z.string().max(150),providerId:uuid,providerVersion:uuid,file}).strict();
export async function downloadKnowledgeFile(c:SupabaseClient,q:F.KnowledgeFileDownloadQuery){const actor=await signed(c);const args={target_tenant:q.tenantId,target_base:q.baseId,target_node:q.nodeId,target_version:q.versionId};async function read(){const p=download.safeParse(await rpc(c,'read_knowledge_file_download',args));if(!p.success)invalid();scope(p.data,q,actor);if(p.data.baseId!==q.baseId||p.data.nodeId!==q.nodeId||p.data.versionId!==q.versionId||p.data.file.versionId!==q.versionId||!new RegExp(`^${q.tenantId}/${q.baseId}/${q.nodeId}/[a-f0-9-]{36}$`).test(p.data.path))invalid();return p.data;}
 const d=await read(),r=await provider(c,objectPath(d,d.providerVersion));if(r.status!==200)throw new KnowledgeFileError('File bytes are unavailable.',503);const bytes=await boundedBody(r,KNOWLEDGE_FILE_MAX_BYTES);if(bytes.length!==d.file.bytes||createHash('sha256').update(bytes).digest('hex')!==d.file.sha256||inspectKnowledgeFile(bytes,d.file.filename,d.file.mediaType)!==d.file.mediaType)throw new KnowledgeFileError('File bytes could not be verified.',503);const fresh=await read();if(JSON.stringify(fresh)!==JSON.stringify(d))throw new KnowledgeFileError('File access or current version changed during download.',409);return{bytes,file:d.file,identity:{tenantId:d.tenantId,actorId:d.actorId,baseId:d.baseId,nodeId:d.nodeId,versionId:d.versionId}};}
const cleanupSaved=z.object({...identity,operationId:uuid,action:z.literal('cleanup_file'),uploadOperationId:uuid,attemptRevision:rev,status:z.literal('cleanup_acknowledged')}).strict();
export async function cleanupKnowledgeFile(c:SupabaseClient,input:F.KnowledgeFileCleanup):Promise<F.KnowledgeFileCleanupSaved>{const actor=await signed(c);verifier();const args={target_tenant:input.tenantId,operation_id:input.operationId,upload_actor:input.uploadActorId,upload_operation:input.uploadOperationId,expected_revision:input.expectedAttemptRevision};const prepared=z.union([z.object({claimed:z.literal(false),saved:cleanupSaved}).strict(),z.object({claimed:z.boolean(),internal}).strict()]).safeParse(await rpc(c,'cleanup_knowledge_file',args));if(!prepared.success)invalid();if('saved'in prepared.data){scope(prepared.data.saved,input,actor);if(prepared.data.saved.uploadOperationId!==input.uploadOperationId)invalid();return prepared.data.saved;}const a=prepared.data.internal;if(a.tenantId!==input.tenantId||a.actorId!==input.uploadActorId||a.operationId!==input.uploadOperationId||a.status!=='closed'||!a.providerVersion)invalid();if(!prepared.data.claimed)throw new KnowledgeFileError('Cleanup outcome is unknown. The retained budget remains charged.',409);
 const response=await provider(c,`/object/ct-alt-knowledge-base/${a.path}?versionId=${a.providerVersion}`,'DELETE');if(response.status!==200)throw new KnowledgeFileError('Cleanup was not acknowledged. The retained budget remains charged.',503);const ack=z.object({message:z.literal('Successfully deleted')}).strict();let value:unknown;try{value=JSON.parse((await boundedBody(response,16384)).toString());}catch{invalid();}if(!ack.safeParse(value).success)invalid();const signing={...a,actorId:actor,operationId:input.operationId},expires=new Date(a.serverTime).getTime()+59000,p=proof(signing,'cleanup-v1',expires);const parsed=z.object({claimed:z.literal(false),saved:cleanupSaved}).strict().safeParse(await rpc(c,'cleanup_knowledge_file',{...args,key_id:p.keyId,proof:p.proof,expires_ms:expires}));if(!parsed.success)invalid();scope(parsed.data.saved,input,actor);return parsed.data.saved;}
export function fileQuery(p:URLSearchParams,keys:string[]){const result:Record<string,string>={};for(const[k,v]of p){if(!keys.includes(k)||k in result)throw new KnowledgeFileError('Choose valid file query details.',400);result[k]=v;}return result;}
export function safeFileDisposition(original:string){const ascii=original.replace(/[^A-Za-z0-9 ._-]/g,'_').replace(/^\.+/,'').slice(0,120)||'document';return`attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(original).replace(/[!'()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`)}`;}
