import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import type * as T from './rota-template-types';
import { ROTA_TEMPLATE_LIMITS as L } from './rota-template-types';
import { formsParseJSON, formsStringValid } from './forms';
import { supportedRotaZone } from './rota-time';
export class RotaTemplateError extends Error { status:number; constructor(message:string,status=503) {super(message);this.status=status;} }
const uuid = z.uuid().transform(v => v.toLowerCase());
const revision = z.number().int().min(1).max(2147483647);
const text = (max: number) => z.string().refine(v => v.length <= max && formsStringValid(v));
const name = text(100).refine(v => v.trim().length > 0);
const recipe = { name, title: text(100), job_id: uuid, start_minute: z.number().int().min(0).max(1439), end_minute: z.number().int().min(0).max(1439), end_day_offset: z.number().int().min(0).max(2) };
const base = { schedule_id: uuid, schedule_revision: revision.max(2147483646) };
const target = { template_id: uuid, template_revision: revision.max(2147483646) };
const action = z.enum(['create', 'edit', 'duplicate', 'delete', 'apply']);
function validDate(v: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(v) || v.startsWith('0000')) return false; const d = new Date(v + 'T00:00:00Z'); return Number.isFinite(d.getTime()) && d.toISOString().slice(0,10) === v; }
const change = z.discriminatedUnion('action', [
 z.object({action:z.literal('create'),...base,...recipe}).strict(),
 z.object({action:z.literal('edit'),...base,...target,...recipe}).strict(),
 z.object({action:z.literal('duplicate'),...base,...target,name}).strict(),
 z.object({action:z.literal('delete'),...base,...target}).strict(),
 z.object({action:z.literal('apply'),...base,...target,agent_id:uuid,date:z.string().refine(validDate),start_occurrence:z.enum(['','earlier','later']),end_occurrence:z.enum(['','earlier','later']),allow_overlap:z.boolean()}).strict()
]).refine(v => !('start_minute' in v) || v.end_day_offset*1440+v.end_minute-v.start_minute>0 && v.end_day_offset*1440+v.end_minute-v.start_minute<=2880);
export const rotaTemplateMutation: z.ZodType<T.RotaTemplateMutation> = z.object({tenantId:uuid,operationId:uuid,change}).strict();
export const rotaTemplateRecoveryMutation: z.ZodType<T.RotaTemplateRecoveryQuery> = z.object({mode:z.literal('reconcile'),tenantId:uuid,operationId:uuid,action,scheduleId:uuid,templateId:uuid.nullable()}).strict().refine(v => (v.action==='create') === (v.templateId===null));
const query = z.object({tenantId:uuid,scheduleId:uuid,q:text(100).default(''),limit:z.coerce.number().int().min(1).max(L.pageMax).default(L.pageDefault),cursor:z.string().min(1).max(4096).regex(/^[A-Za-z0-9_-]+$/).optional()}).strict();
export function parseRotaTemplateQuery(p: URLSearchParams): T.RotaTemplateQuery { const seen=new Set<string>();for(const [k] of p) { if(seen.has(k)) throw new RotaTemplateError('Duplicate template filter.',400);seen.add(k); } const v=query.safeParse(Object.fromEntries(p));if(!v.success) throw new RotaTemplateError('Choose valid template filters.',400);return v.data; }
const schedule = z.object({id:uuid,revision,time_zone:text(100).refine(supportedRotaZone),status:z.enum(['active','archived'])}).strict();
const identity = {schemaVersion:z.literal(1),tenantId:uuid,actorId:uuid,schedule};
const access = z.object(identity).strict();
const template = z.object({id:uuid,tenant_id:uuid,schedule_id:uuid,revision,...recipe}).strict().refine(v => v.end_day_offset*1440+v.end_minute-v.start_minute>0 && v.end_day_offset*1440+v.end_minute-v.start_minute<=2880);
const cursor = z.object({v:z.literal(1),tenantId:uuid,actorId:uuid,scheduleId:uuid,scheduleRevision:revision,search:text(100),key:text(200),id:uuid}).strict();
const data = z.object({...identity,templates:z.array(template).max(L.pageMax),page:z.object({total:z.number().int().min(0).max(L.perSchedule),nextCursor:cursor.nullable()}).strict()}).strict();
const saved = z.object({schemaVersion:z.literal(1),tenantId:uuid,actorId:uuid,operationId:uuid,action,template_id:uuid,template_revision:revision,schedule_id:uuid,schedule_revision:revision,shift_id:uuid.nullable()}).strict().refine(v => (v.action==='apply') === (v.shift_id!==null));
const reconciled = z.object({schemaVersion:z.literal(1),tenantId:uuid,actorId:uuid,operationId:uuid,action,scheduleId:uuid,templateId:uuid.nullable(),status:z.enum(['recorded','not_recorded']),saved:saved.nullable()}).strict().refine(v => (v.status==='recorded') === (v.saved!==null));
function invalid(): never { throw new RotaTemplateError('Template response could not be verified. Refresh and review.'); }
function fail(e: {code?:string}|null) { if(!e)return;const c=e.code;if(c==='42501')throw new RotaTemplateError('Current schedule access is unavailable.',403);if(c==='P0002')throw new RotaTemplateError('Template is no longer available.',404);if(c==='P0001')throw new RotaTemplateError('This worker has an overlapping shift. Review and explicitly allow overlap.',409);if(c==='54000')throw new RotaTemplateError('Scheduling capacity reached. Ask your administrator to review retained records.',409);if(c==='40001'||c==='40P01'||c==='23505')throw new RotaTemplateError('Schedule or template changed. Reload and review.',409);if(c==='22007')throw new RotaTemplateError('This time does not exist because the clocks change. Choose another date or template time.',400);if(c==='22008')throw new RotaTemplateError('This time occurs twice because the clocks change. Choose the earlier or later occurrence.',400);if(c==='23514')throw new RotaTemplateError('Shift must last more than zero and at most 24 elapsed hours.',400);if(c?.startsWith('22')||c==='23503'||c==='23502')throw new RotaTemplateError('Choose valid template fields and an active assigned worker.',400);throw new RotaTemplateError('Templates could not be read or saved. Refresh and review.'); }
async function signed(c:SupabaseClient) { const {data,error}=await c.auth.getUser();if(error||!data.user)throw new RotaTemplateError('Sign in to use templates.',401);if(data.user.is_anonymous)throw new RotaTemplateError('Current account cannot use templates.',403);return data.user.id.toLowerCase(); }
async function fresh(c:SupabaseClient,t:string,s:string,actor:string) { if(await signed(c)!==actor)throw new RotaTemplateError('Current account changed.',403);const {data,error}=await c.rpc('read_rota_template_access',{target_tenant:t,target_schedule:s});fail(error);const p=access.safeParse(data);if(!p.success)invalid();if(p.data.actorId!==actor||p.data.tenantId!==t||p.data.schedule.id!==s)invalid();return p.data; }
function decode(v:string) { try { const b=Buffer.from(v,'base64url');if(b.toString('base64url')!==v)throw Error();const p=cursor.safeParse(JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(b)));if(!p.success)throw Error();return p.data; }catch {throw new RotaTemplateError('Choose a valid template page.',400);} }
export async function readRotaTemplates(c:SupabaseClient,value:T.RotaTemplateQuery):Promise<T.RotaTemplateData> { const p=query.safeParse(value);if(!p.success)throw new RotaTemplateError('Choose valid template filters.',400);const q=p.data,actor=await signed(c),after=q.cursor?decode(q.cursor):null;if(after&&(after.tenantId!==q.tenantId||after.actorId!==actor||after.scheduleId!==q.scheduleId||after.search!==q.q))throw new RotaTemplateError('Template page belongs to another scope.',409);const {data:d,error}=await c.rpc('read_rota_templates',{target_tenant:q.tenantId,target_schedule:q.scheduleId,search_text:q.q,page_limit:q.limit,after_row:after});fail(error);const checked=data.safeParse(d);if(!checked.success)invalid();const v=checked.data;if(v.actorId!==actor||v.tenantId!==q.tenantId||v.schedule.id!==q.scheduleId||v.templates.length>q.limit||v.templates.length>v.page.total||new Set(v.templates.map(x=>x.id)).size!==v.templates.length)invalid();if(after&&after.scheduleRevision!==v.schedule.revision)throw new RotaTemplateError('Template page changed. Reload.',409);for(const x of v.templates)if(x.tenant_id!==q.tenantId||x.schedule_id!==q.scheduleId)invalid();if(!after && (v.templates.length!==Math.min(v.page.total,q.limit) || (v.page.total>q.limit)!==(v.page.nextCursor!==null)))invalid();const n=v.page.nextCursor;if(n&&(v.templates.length!==q.limit||n.tenantId!==q.tenantId||n.actorId!==actor||n.scheduleId!==q.scheduleId||n.scheduleRevision!==v.schedule.revision||n.search!==q.q||n.id!==v.templates.at(-1)?.id))invalid();const current=await fresh(c,q.tenantId,q.scheduleId,actor);if(current.schedule.revision!==v.schedule.revision||current.schedule.time_zone!==v.schedule.time_zone||current.schedule.status!==v.schedule.status)throw new RotaTemplateError('Schedule changed. Reload templates.',409);return {...v,page:{total:v.page.total,nextCursor:n?Buffer.from(JSON.stringify(n)).toString('base64url'):null}}; }
function verifySaved(v:T.RotaTemplateSaved,t:string,actor:string,op:string,a:T.RotaTemplateAction,s:string) { if(v.tenantId!==t||v.actorId!==actor||v.operationId!==op||v.action!==a||v.schedule_id!==s)invalid(); }
export async function saveRotaTemplate(c:SupabaseClient,value:unknown):Promise<T.RotaTemplateSaved> { const p=rotaTemplateMutation.safeParse(value);if(!p.success)throw new RotaTemplateError('Choose valid template details.',400);const v=p.data,actor=await signed(c);const {data,error}=await c.rpc('save_rota_template',{target_tenant:v.tenantId,operation_id:v.operationId,change_text:JSON.stringify(v.change)});fail(error);const res=saved.safeParse(data);if(!res.success)invalid();verifySaved(res.data,v.tenantId,actor,v.operationId,v.change.action,v.change.schedule_id);if(res.data.schedule_revision!==v.change.schedule_revision+1 || (v.change.action==='create'||v.change.action==='duplicate')&&res.data.template_revision!==1 || (v.change.action==='edit'||v.change.action==='delete')&&'template_revision'in v.change&&res.data.template_revision!==v.change.template_revision+1 || v.change.action==='apply'&&res.data.template_revision!==v.change.template_revision)invalid();if(['edit','delete','apply'].includes(v.change.action)&&'template_id'in v.change&&res.data.template_id!==v.change.template_id)invalid();await fresh(c,v.tenantId,v.change.schedule_id,actor);return res.data; }
export async function reconcileRotaTemplate(c:SupabaseClient,value:unknown):Promise<T.RotaTemplateReconciliation> { const p=rotaTemplateRecoveryMutation.safeParse(value);if(!p.success)throw new RotaTemplateError('Choose a valid template recovery operation.',400);const v=p.data,actor=await signed(c);const {data,error}=await c.rpc('reconcile_rota_template_operation',{target_tenant:v.tenantId,operation_id:v.operationId,action_name:v.action,target_schedule:v.scheduleId,target_template:v.templateId});fail(error);const res=reconciled.safeParse(data);if(!res.success)invalid();const r=res.data;if(r.tenantId!==v.tenantId||r.actorId!==actor||r.operationId!==v.operationId||r.action!==v.action||r.scheduleId!==v.scheduleId||r.templateId!==v.templateId)invalid();if(r.saved){verifySaved(r.saved,v.tenantId,actor,v.operationId,v.action,v.scheduleId);if(['edit','delete','apply'].includes(v.action)&&r.saved.template_id!==v.templateId)invalid();}await fresh(c,v.tenantId,v.scheduleId,actor);return r; }
export async function readRotaTemplateBody(request:Request):Promise<unknown> { const length=request.headers.get('content-length');if(length&&(!/^\d+$/.test(length)||Number(length)>L.requestBytes))throw new RotaTemplateError('Request is too large.',413);const reader=request.body?.getReader();if(!reader)throw new RotaTemplateError('Choose template details.',400);const parts:Uint8Array[]=[];let size=0;try {while(true){const p=await reader.read();if(p.done)break;size+=p.value.length;if(size>L.requestBytes){await reader.cancel();throw new RotaTemplateError('Request is too large.',413);}parts.push(p.value);}}finally{reader.releaseLock();}const raw=new Uint8Array(size);let at=0;for(const p of parts){raw.set(p,at);at+=p.length;}try{return formsParseJSON(new TextDecoder('utf8',{fatal:true}).decode(raw));}catch{throw new RotaTemplateError('Choose valid UTF8 template details without duplicate fields.',400);} }
