import { z } from 'zod';
import type { SupabaseClient } from '@supabase/supabase-js';
import { formsParseJSON } from './forms';
import { ROTA_PERIOD_LIMITS as L } from './rota-period-template-types';
import type * as T from './rota-period-template-types';
import * as V from './rota-period-template-validation';
export class RotaPeriodTemplateError extends Error { status:number; constructor(message:string,status=503){super(message);this.status=status;} }
function invalid():never { throw new RotaPeriodTemplateError('Template response could not be verified. Recover pending changes before trying again.'); }
function fail(e:{code?:string;message?:string}|null){if(!e)return;const c=e.code;if(c==='22023'&&e.message==='Some source names are too long to save. Shorten them and review again.')throw new RotaPeriodTemplateError(e.message,400);if(c==='22023'&&e.message==='Unsupported source endpoint')throw new RotaPeriodTemplateError('Some source endpoints are outside the supported UTC years. Choose another period.',400);if(c==='22023'&&e.message==='Unsupported source period boundary')throw new RotaPeriodTemplateError('This source period has an unsupported midnight boundary. Choose another date.',400);if(c==='42501')throw new RotaPeriodTemplateError('Current schedule access is unavailable.',403);if(c==='P0002')throw new RotaPeriodTemplateError('Template is no longer available.',404);if(['40001','40P01','23505'].includes(c||''))throw new RotaPeriodTemplateError('Review changed. Reload and review the complete period.',409);if(c==='54000')throw new RotaPeriodTemplateError('Retained scheduling capacity reached. Recovery could not establish absence if no result was returned.',409);if(c==='P0001')throw new RotaPeriodTemplateError('Review and acknowledge all overlaps, including unavailable conflict details.',409);if(c?.startsWith('22')||['23503','23514','23502'].includes(c||''))throw new RotaPeriodTemplateError('Choose valid period details and supported local dates. Review unavailable assignments and time boundaries.',400);throw new RotaPeriodTemplateError('Templates could not be confirmed. Recover pending changes before trying again.');}
async function signed(c:SupabaseClient){const {data,error}=await c.auth.getUser();if(error||!data.user)throw new RotaPeriodTemplateError('Sign in to use templates.',401);if(data.user.is_anonymous)throw new RotaPeriodTemplateError('Current account cannot use templates.',403);return data.user.id.toLowerCase();}
const accessSchema=z.strictObject({schemaVersion:z.literal(1),tenantId:V.periodUuid,actorId:V.periodUuid,schedule:z.strictObject({id:V.periodUuid,revision:z.number().int().min(1).max(2147483647),time_zone:z.string().min(1).max(100),status:z.enum(['active','archived'])}),companyUsageVisible:z.boolean()});
async function fresh(c:SupabaseClient,t:string,s:string,actor:string){if(await signed(c)!==actor)throw new RotaPeriodTemplateError('Current account changed.',403);const r=await c.rpc('read_rota_period_access',{target_tenant:t,target_schedule:s});fail(r.error);const p=accessSchema.safeParse(r.data);if(!p.success||p.data.tenantId!==t||p.data.actorId!==actor||p.data.schedule.id!==s)invalid();return p.data;}
function parse<S extends z.ZodType>(schema:S,v:unknown):z.output<S>{const p=schema.safeParse(v);if(!p.success)throw new RotaPeriodTemplateError('Choose valid template details.',400);return p.data;}
function pageProof(q:T.RotaPeriodCatalogueQuery|T.RotaPeriodHistoricalQuery|T.RotaPeriodSourcePreviewQuery|T.RotaPeriodTargetPreviewQuery,value:unknown){
 const v=value as T.RotaPeriodCatalogueData|T.RotaPeriodHistoricalData|T.RotaPeriodSourcePreview|T.RotaPeriodTargetPreview;
 const decode=(s:string)=>{try{const bytes=Buffer.from(s,'base64url');if(bytes.toString('base64url')!==s)invalid();const j=formsParseJSON(new TextDecoder('utf8',{fatal:true}).decode(bytes),4096);if(typeof j!=='object'||j===null||Array.isArray(j))invalid();return j as Record<string,unknown>;}catch{invalid();}};
 const rows=('templates'in v?v.templates:'commitments'in v?v.commitments:v.entries)??[];
 const limit=q.limit??('templates'in v?30:100);const before=q.cursor?decode(q.cursor):null;const after=v.page.nextCursor?decode(v.page.nextCursor):null;
 if(rows.length>limit||rows.length>v.page.total||(!before&&rows.length!==Math.min(limit,v.page.total))||(after&&rows.length!==limit))invalid();
 if('templates'in v){if(after&&after.id!==v.templates.at(-1)?.id)invalid();return;}
 const pos=before?before.position:0;if(typeof pos!=='number'||!Number.isSafeInteger(pos)||pos<0||pos>v.page.total)invalid();
 if(rows.length!==Math.min(limit,v.page.total-pos)||(after!==null)!==(pos+rows.length<v.page.total))invalid();if(after&&(after.position!==pos+rows.length||JSON.stringify(after.scope)!==JSON.stringify(before?.scope??after.scope)))invalid();
 if('entries'in v&&(!('pageKind'in v)||v.pageKind==='entries')){const entries=v.entries??[];for(let i=0;i<entries.length;i++){const row=entries[i];if(('entry'in row?row.entry.index:row.index)!==pos+i)invalid();}}
}
export function parseRotaPeriodQuery(p:URLSearchParams):T.RotaPeriodCatalogueQuery|T.RotaPeriodHistoricalQuery{const raw:Record<string,unknown>={};for(const [k,v]of p){if(k in raw)throw new RotaPeriodTemplateError('Duplicate template filter.',400);raw[k]=v;}for(const k of ['limit','templateRevision'])if(k in raw){if(typeof raw[k]!=='string'||!/^\d+$/.test(raw[k] as string))throw new RotaPeriodTemplateError('Choose valid template page numbers.',400);raw[k]=Number(raw[k]);}return raw.mode==='history'?parse(V.rotaPeriodHistoricalQuerySchema,raw):parse(V.rotaPeriodCatalogueQuerySchema,raw);}
async function read<Q extends T.RotaPeriodCatalogueQuery|T.RotaPeriodHistoricalQuery|T.RotaPeriodSourcePreviewQuery|T.RotaPeriodTargetPreviewQuery,R extends {tenantId:string;actorId:string;schedule:T.RotaPeriodSchedule}>(c:SupabaseClient,q:Q,schema:z.ZodType<R>,rpc:string):Promise<R>{const actor=await signed(c);let cursorVisibility:boolean|undefined;
 if(q.cursor){try{const bytes=Buffer.from(q.cursor,'base64url');if(bytes.toString('base64url')!==q.cursor)throw Error();const decoded=formsParseJSON(new TextDecoder('utf8',{fatal:true}).decode(bytes),4096)as{scope?:{identity?:unknown}};const identity=accessSchema.safeParse(decoded?.scope?.identity);if(identity.success&&identity.data.tenantId===q.tenantId&&identity.data.actorId===actor&&identity.data.schedule.id===q.scheduleId)cursorVisibility=identity.data.companyUsageVisible;}catch{throw new RotaPeriodTemplateError('Choose a valid template page.',400);}}
 const proofOnError=async(error:{code?:string;message?:string}|null,reviewedVisibility?:boolean)=>{if(!error)return;const current=await fresh(c,q.tenantId,q.scheduleId,actor);if(reviewedVisibility!==undefined&&reviewedVisibility!==current.companyUsageVisible)throw new RotaPeriodTemplateError('Current access changed. Reload templates.',403);fail(error);};
 const args={target_tenant:q.tenantId,request_text:JSON.stringify(q)};const first=await c.rpc(rpc,args);await proofOnError(first.error,cursorVisibility);const checked=schema.safeParse(first.data);if(!checked.success){const current=await fresh(c,q.tenantId,q.scheduleId,actor);if(cursorVisibility!==undefined&&cursorVisibility!==current.companyUsageVisible)throw new RotaPeriodTemplateError('Current access changed. Reload templates.',403);invalid();}const value=checked.data;
 // Recompute the complete authorized page after a fresh signed check. This fences
 // conflict visibility and current availability changes, including other schedules.
 if(await signed(c)!==actor)throw new RotaPeriodTemplateError('Current account changed.',403);const again=await c.rpc(rpc,args);const current=await fresh(c,q.tenantId,q.scheduleId,actor);if('capacity'in value&&(value as unknown as T.RotaPeriodTargetPreview).capacity.companyUsageVisible!==current.companyUsageVisible)throw new RotaPeriodTemplateError('Current access changed. Reload templates.',403);fail(again.error);const next=schema.safeParse(again.data);if(!next.success){invalid();}if('capacity'in value&&'capacity'in next.data&&(value as unknown as T.RotaPeriodTargetPreview).capacity.companyUsageVisible!==(next.data as unknown as T.RotaPeriodTargetPreview).capacity.companyUsageVisible)throw new RotaPeriodTemplateError('Current access changed. Reload templates.',403);if(value.tenantId!==q.tenantId||value.actorId!==actor||value.schedule.id!==q.scheduleId)invalid();if('scheduleRevision'in q&&value.schedule.revision!==q.scheduleRevision)throw new RotaPeriodTemplateError('Schedule changed. Reload the review.',409);pageProof(q,value);if(JSON.stringify(value)!==JSON.stringify(next.data))throw new RotaPeriodTemplateError('Review changed. Reload before combining pages.',409);if(JSON.stringify(current.schedule)!==JSON.stringify(value.schedule))throw new RotaPeriodTemplateError('Schedule changed. Reload the review.',409);if(('templates'in value&&(value as unknown as T.RotaPeriodCatalogueData).templates.length>(q.limit??30))||('entries'in value&&(value as unknown as T.RotaPeriodHistoricalData).entries.length>(q.limit??100))||('commitments'in value&&(value as unknown as T.RotaPeriodTargetPreview & {commitments:unknown[]}).commitments.length>(q.limit??100)))invalid();if(Buffer.byteLength(JSON.stringify(value),'utf8')>L.responseBytes)invalid();return value;}
export async function readRotaPeriodTemplates(c:SupabaseClient,v:unknown):Promise<T.RotaPeriodCatalogueData|T.RotaPeriodHistoricalData>{if(typeof v==='object'&&v!==null&&'mode'in v){const q=parse(V.rotaPeriodHistoricalQuerySchema,v);const result=await read(c,q,V.rotaPeriodHistoricalDataSchema,'read_rota_period_templates');if(result.template.id!==q.templateId||result.template.revision!==q.templateRevision)invalid();return result;}const q=parse(V.rotaPeriodCatalogueQuerySchema,v);const result=await read(c,q,V.rotaPeriodCatalogueDataSchema,'read_rota_period_templates');if(result.kind!==q.kind||result.q!==(q.q??''))invalid();return result;}
export async function previewRotaPeriodSource(c:SupabaseClient,v:unknown):Promise<T.RotaPeriodSourcePreview>{const q=parse(V.rotaPeriodSourcePreviewQuerySchema,v);const r=await read(c,q,V.rotaPeriodSourcePreviewSchema,'preview_rota_period_template');if(r.firstPage!==!q.cursor||r.source.kind!==q.kind||r.source.anchor!==q.sourceAnchor||r.source.zone!==r.schedule.time_zone||JSON.stringify(r.source.filters)!==JSON.stringify(q.sourceFilters)||r.entries.length>(q.limit??100))invalid();return r;}
export async function previewRotaPeriodTarget(c:SupabaseClient,v:unknown):Promise<T.RotaPeriodTargetPreview>{const q=parse(V.rotaPeriodTargetPreviewQuerySchema,v);const r=await read(c,q,V.rotaPeriodTargetPreviewSchema,'preview_rota_period_template');if(r.template.id!==q.templateId||r.template.revision!==q.templateRevision||r.targetAnchor!==q.targetAnchor||r.pageKind!==q.pageKind||JSON.stringify(r.occurrences)!==JSON.stringify([...q.occurrences].sort((a,b)=>a.index-b.index)))invalid();return r;}
export async function saveRotaPeriodTemplate(c:SupabaseClient,v:unknown):Promise<T.RotaPeriodSaved>{const q=parse(V.rotaPeriodMutationSchema,v),actor=await signed(c);const r=await c.rpc('save_rota_period_template',{target_tenant:q.tenantId,operation_id:q.operationId,change_text:JSON.stringify(q.change)});fail(r.error);const p=V.rotaPeriodSavedSchema.safeParse(r.data);if(!p.success)invalid();const s=p.data,ch=q.change;if(s.tenantId!==q.tenantId||s.actorId!==actor||s.operationId!==q.operationId||s.action!==ch.action||s.schedule_id!==ch.schedule_id||s.schedule_revision!==ch.schedule_revision+1)invalid();if(ch.action==='save'){if(s.template_revision!==1||s.entry_count!==ch.sources.length)invalid();}else{if(s.template_id!==ch.template_id||s.template_revision!==ch.template_revision+(ch.action==='add'?0:1))invalid();}if(ch.action==='add'&&(s.entry_count!==ch.expected_entry_count||s.plan_digest!==ch.plan_digest))invalid();const current=await fresh(c,q.tenantId,ch.schedule_id,actor);if(current.schedule.revision<s.schedule_revision)invalid();return s;}
export async function reconcileRotaPeriodTemplate(c:SupabaseClient,v:unknown):Promise<T.RotaPeriodReconciliation>{const q=parse(V.rotaPeriodRecoveryQuerySchema,v),actor=await signed(c);const r=await c.rpc('reconcile_rota_period_template_operation',{target_tenant:q.tenantId,operation_id:q.operationId,action_name:q.action,target_schedule:q.scheduleId,target_template:q.templateId});fail(r.error);const p=V.rotaPeriodReconciliationSchema.safeParse(r.data);if(!p.success)invalid();const x=p.data;if(x.tenantId!==q.tenantId||x.actorId!==actor||x.operationId!==q.operationId||x.action!==q.action||x.scheduleId!==q.scheduleId||x.templateId!==q.templateId)invalid();const current=await fresh(c,q.tenantId,q.scheduleId,actor);if(x.status==='recorded'&&current.schedule.revision<x.saved.schedule_revision)invalid();return x;}
export async function readRotaPeriodBody(request:Request):Promise<unknown>{const length=request.headers.get('content-length');if(length&&(!/^\d+$/.test(length)||Number(length)>L.requestBytes))throw new RotaPeriodTemplateError('Request is too large.',413);const reader=request.body?.getReader();if(!reader)throw new RotaPeriodTemplateError('Choose template details.',400);const parts:Uint8Array[]=[];let size=0;try{while(true){const p=await reader.read();if(p.done)break;size+=p.value.length;if(size>L.requestBytes){await reader.cancel();throw new RotaPeriodTemplateError('Request is too large.',413);}parts.push(p.value);}}finally{reader.releaseLock();}const raw=new Uint8Array(size);let at=0;for(const p of parts){raw.set(p,at);at+=p.length;}try{return formsParseJSON(new TextDecoder('utf8',{fatal:true}).decode(raw),L.requestBytes);}catch{throw new RotaPeriodTemplateError('Choose valid UTF8 details without duplicate fields.',400);}}
