import { z } from 'zod';
import { ROTA_PERIOD_LIMITS as L } from './rota-period-template-types';
export const periodUuid = z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i).transform(v => v.toLowerCase());
const validText = (s: string) => !/[\u0000\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(s);
const text = (max: number) => z.string().refine(v=>v.length<=max&&validText(v));
const title = text(100).trim().min(1).refine(v => !/[\u0000-\u001f\u007f-\u009f]/u.test(v));
const rev = z.number().int().min(1).max(2147483647), requestRev = rev.max(2147483646);
const count = z.number().int().min(0).max(L.entries), nonzeroCount = count.min(1);
const digest = z.string().regex(/^[0-9a-f]{64}$/);
export function periodDateValid(v: string): boolean { const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(v); if (!m) return false; const [y,mo,d] = m.slice(1).map(Number); const leap = y%4===0&&(y%100!==0||y%400===0); return y>=1&&mo>=1&&mo<=12&&d>=1&&d<=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31][mo-1]; }
export function periodMonday(v:string):boolean {if(!periodDateValid(v))return false;const [year,m,d]=v.split('-').map(Number);const y=year-(m<3?1:0);return(y+Math.floor(y/4)-Math.floor(y/100)+Math.floor(y/400)+[0,3,2,5,0,3,5,1,4,6,2,4][m-1]+d)%7===1;}
export function periodUtcMicros(v:string):bigint {if(!/^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d\.\d{6}Z$/.test(v)||!periodDateValid(v.slice(0,10)))return 0n;const [y,m,d]=v.slice(0,10).split('-').map(Number);const prior=y-1;const leap=y%4===0&&(y%100!==0||y%400===0);const days=365*prior+Math.floor(prior/4)-Math.floor(prior/100)+Math.floor(prior/400)+[0,31,59,90,120,151,181,212,243,273,304,334][m-1]+(leap&&m>2?1:0)+d-1;return BigInt(days)*86400000000n+BigInt(v.slice(11,13))*3600000000n+BigInt(v.slice(14,16))*60000000n+BigInt(v.slice(17,19))*1000000n+BigInt(v.slice(20,26));}
const date = z.string().refine(periodDateValid);
const utc = z.string().regex(/^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d\.\d{6}Z$/).refine(v => periodDateValid(v.slice(0,10)));
const zone = text(100).min(1);
const cursor = z.string().min(1).max(4096).regex(/^[A-Za-z0-9_-]+$/);
const kind = z.enum(['day','week']);
const action = z.enum(['save','rename','delete','add']);
export const rotaPeriodFiltersSchema = z.strictObject({jobId:periodUuid.nullable(),status:z.enum(['all','draft','published']),workerSearch:text(100)});
export const rotaPeriodSelectorSchema = z.strictObject({id:periodUuid,revision:requestRev});
const selectors = z.array(rotaPeriodSelectorSchema).min(1).max(L.entries).refine(v => new Set(v.map(r=>r.id)).size===v.length);
export const rotaPeriodOccurrenceSchema = z.strictObject({index:z.number().int().min(0).max(4999),start:z.enum(['earlier','later']).optional(),end:z.enum(['earlier','later']).optional()}).refine(v=>v.start!==undefined||v.end!==undefined);
const occurrences = z.array(rotaPeriodOccurrenceSchema).max(5000).refine(v=>new Set(v.map(r=>r.index)).size===v.length);
const paging = {limit:z.number().int().min(1).max(100).optional(),cursor:cursor.optional()};
const scope = {tenantId:periodUuid,scheduleId:periodUuid};
export const rotaPeriodCatalogueQuerySchema = z.strictObject({...scope,kind,q:text(100).optional(),...paging});
export const rotaPeriodHistoricalQuerySchema = z.strictObject({mode:z.literal('history'),...scope,templateId:periodUuid,templateRevision:requestRev,...paging});
export const rotaPeriodSourcePreviewQuerySchema = z.strictObject({mode:z.literal('source-preview'),...scope,scheduleRevision:requestRev,kind,sourceAnchor:date,sourceFilters:rotaPeriodFiltersSchema,...paging}).refine(v=>v.kind!=='week'||periodMonday(v.sourceAnchor));
export const rotaPeriodTargetPreviewQuerySchema = z.strictObject({mode:z.literal('preview'),...scope,scheduleRevision:requestRev,templateId:periodUuid,templateRevision:requestRev,targetAnchor:date,occurrences,pageKind:z.enum(['entries','blocked','affected','visibleCommitments']),...paging});
const base = {schedule_id:periodUuid,schedule_revision:requestRev}, target={template_id:periodUuid,template_revision:requestRev};
export const rotaPeriodChangeSchema = z.discriminatedUnion('action',[
 z.strictObject({action:z.literal('save'),...base,kind,title,source_anchor:date,source_zone:zone,source_filters:rotaPeriodFiltersSchema,source_review_digest:digest,sources:selectors}).refine(v=>v.kind!=='week'||periodMonday(v.source_anchor)),
 z.strictObject({action:z.literal('rename'),...base,...target,title}),
 z.strictObject({action:z.literal('delete'),...base,...target}),
 z.strictObject({action:z.literal('add'),...base,...target,target_anchor:date,occurrences,plan_digest:digest,expected_entry_count:nonzeroCount,allow_overlap:z.boolean()}).refine(v=>v.occurrences.every(r=>r.index<v.expected_entry_count))
]);
export const rotaPeriodMutationSchema = z.strictObject({tenantId:periodUuid,operationId:periodUuid,change:rotaPeriodChangeSchema});
export const rotaPeriodRecoveryQuerySchema = z.strictObject({mode:z.literal('reconcile'),tenantId:periodUuid,operationId:periodUuid,action,scheduleId:periodUuid,templateId:periodUuid.nullable()}).refine(v=>(v.action==='save')===(v.templateId===null));
const schedule = z.strictObject({id:periodUuid,revision:rev,time_zone:zone,status:z.enum(['active','archived'])});
const envelope = {schemaVersion:z.literal(1),tenantId:periodUuid,actorId:periodUuid,schedule};
const micros = z.number().int().min(0).max(L.elapsedMicros);
const metadata = z.strictObject({id:periodUuid,tenant_id:periodUuid,schedule_id:periodUuid,kind,title,source_anchor:date,source_zone:zone,source_schedule_revision:rev,source_filters:rotaPeriodFiltersSchema,entry_count:nonzeroCount,user_count:nonzeroCount,elapsed_micros:micros,revision:rev,created_at:utc,updated_at:utc}).refine(v=>v.user_count<=v.entry_count);
const entry = z.strictObject({index:z.number().int().min(0).max(4999),source_shift_id:periodUuid,source_revision:rev,source_status:z.enum(['draft','published']),source_starts_at:utc,source_ends_at:utc,agent_id:periodUuid,agent_name:text(401),job_id:periodUuid,job_name:text(200),job_color:z.string().regex(/^#[0-9A-Fa-f]{6}$/),title:text(200),start_day_offset:z.number().int().min(-2).max(8),end_day_offset:z.number().int().min(-2).max(8),start_clock_micros:z.number().int().min(0).max(L.clockMicros),end_clock_micros:z.number().int().min(0).max(L.clockMicros)}).refine(v=>{const diff=periodUtcMicros(v.source_ends_at)-periodUtcMicros(v.source_starts_at);return diff>0n&&diff<=86400000000n;});
const availability = z.strictObject({workerAvailable:z.boolean(),jobAvailable:z.boolean(),currentAgentName:text(401).nullable(),currentJobName:text(200).nullable(),currentJobColor:z.string().regex(/^#[0-9a-fA-F]{6}$/).nullable()});
const historicalEntry = z.strictObject({entry,availability});
const page = z.strictObject({total:z.number().int().min(0).max(20000),nextCursor:cursor.nullable()});
const capacity = z.discriminatedUnion('companyUsageVisible',[z.strictObject({companyUsageVisible:z.literal(true),shifts:z.number().int().min(0),metadata:z.number().int().min(0),entries:z.number().int().min(0),operations:z.number().int().min(0),generated:z.number().int().min(0)}),z.strictObject({companyUsageVisible:z.literal(false),shifts:z.null(),metadata:z.number().int().min(0),entries:z.null(),operations:z.null(),generated:z.null()})]);
const rows = <T extends z.ZodType>(schema:T) => z.array(schema).max(100);
export const rotaPeriodCatalogueDataSchema = z.strictObject({...envelope,kind,q:text(100),capacity,canEdit:z.boolean(),editBlockers:z.array(z.enum(['schedule_archived','operation_capacity'])).max(2),templates:rows(metadata),page}).refine(v=>(!v.canEdit||v.editBlockers.length===0)&&v.templates.every(t=>t.tenant_id===v.tenantId&&t.schedule_id===v.schedule.id&&t.kind===v.kind)&&v.templates.length<=v.page.total);
export const rotaPeriodHistoricalDataSchema = z.strictObject({...envelope,template:metadata,historyDigest:digest,entries:rows(historicalEntry),page}).refine(v=>v.template.tenant_id===v.tenantId&&v.template.schedule_id===v.schedule.id&&v.page.total===v.template.entry_count&&v.entries.every((r,i)=>r.entry.start_day_offset<=(v.template.kind==='day'?2:8)&&r.entry.end_day_offset<=(v.template.kind==='day'?2:8)&&r.entry.index<v.template.entry_count&&(i===0||v.entries[i-1].entry.index+1===r.entry.index)));
const sourceScope = z.strictObject({kind,anchor:date,zone,filters:rotaPeriodFiltersSchema,entryCount:count,userCount:count,elapsedMicros:micros});
const sourceBase={...envelope,source:sourceScope,capacity,canSave:z.boolean(),saveBlockers:z.array(z.enum(['schedule_archived','metadata_capacity','entry_capacity','operation_capacity'])).max(4),sourceReviewDigest:digest,entries:rows(entry),page};
export const rotaPeriodSourcePreviewSchema = z.discriminatedUnion('firstPage',[
 z.strictObject({...sourceBase,firstPage:z.literal(true),selectors:z.array(rotaPeriodSelectorSchema).max(5000)}),z.strictObject({...sourceBase,firstPage:z.literal(false)})
]).refine(v=>(!v.canSave||(v.saveBlockers.length===0&&v.source.entryCount>0))&&v.source.userCount<=v.source.entryCount&&v.page.total===v.source.entryCount&&v.entries.every((r,i)=>r.start_day_offset<=(v.source.kind==='day'?2:8)&&r.end_day_offset<=(v.source.kind==='day'?2:8)&&r.index<v.source.entryCount&&(i===0||v.entries[i-1].index+1===r.index))&&(v.source.entryCount===0?v.entries.length===0:v.entries.length>0)&&(v.firstPage? (v.source.entryCount===0||v.entries[0]?.index===0)&&v.selectors.length===v.source.entryCount&&v.selectors.every((r,i)=>i===0||v.selectors[i-1].id<r.id)&&v.entries.every(r=>v.selectors[r.index]?.id===r.source_shift_id&&v.selectors[r.index]?.revision===r.source_revision):true));
const targetEntry = z.strictObject({entry,availability,starts_at:utc.nullable(),ends_at:utc.nullable(),elapsed_micros:z.number().int().min(1).max(86400000000).nullable(),blockers:z.array(z.enum(['worker_unavailable','job_unavailable','start_gap','end_gap','start_ambiguous','end_ambiguous','start_occurrence','end_occurrence','unsupported_endpoint','invalid_duration'])).max(10),internalConflict:z.boolean(),existingConflict:z.boolean()}).refine(v=>v.elapsed_micros===null||v.starts_at!==null&&v.ends_at!==null&&periodUtcMicros(v.ends_at)-periodUtcMicros(v.starts_at)===BigInt(v.elapsed_micros));
const commitment=z.strictObject({id:periodUuid,revision:rev,schedule_id:periodUuid,agent_id:periodUuid,agent_name:text(401),job_id:periodUuid,job_name:text(200),job_color:z.string().regex(/^#[0-9a-fA-F]{6}$/),title:text(200),starts_at:utc,ends_at:utc,status:z.enum(['draft','published'])});
const targetBase={...envelope,template:metadata,targetAnchor:date,occurrences,planDigest:digest,canAdd:z.boolean(),entryCount:nonzeroCount,userCount:nonzeroCount,elapsedMicros:micros,blockedEntryCount:count,affectedEntryCount:count,visibleCommitmentCount:count,hasHiddenConflicts:z.boolean(),capacity,blockers:z.array(z.enum(['schedule_archived','shift_capacity','operation_capacity','generated_capacity'])).max(4),page};
export const rotaPeriodTargetPreviewSchema = z.union([z.strictObject({...targetBase,pageKind:z.enum(['entries','blocked','affected']),entries:rows(targetEntry)}),z.strictObject({...targetBase,pageKind:z.literal('visibleCommitments'),commitments:rows(commitment)})]).refine(v=>v.template.tenant_id===v.tenantId&&v.template.schedule_id===v.schedule.id&&v.entryCount===v.template.entry_count&&v.userCount<=v.entryCount&&v.blockedEntryCount<=v.entryCount&&v.affectedEntryCount<=v.entryCount&&(!v.canAdd||(v.blockedEntryCount===0&&v.blockers.length===0))&&v.page.total===(v.pageKind==='visibleCommitments'?v.visibleCommitmentCount:v.pageKind==='blocked'?v.blockedEntryCount:v.pageKind==='affected'?v.affectedEntryCount:v.entryCount)&&(v.pageKind==='visibleCommitments'?v.commitments.length<=v.page.total&&v.commitments.every((r,i)=>r.starts_at<r.ends_at&&(i===0||v.commitments[i-1].id<r.id)):v.entries.length<=v.page.total&&v.entries.every((r,i)=>r.entry.start_day_offset<=(v.template.kind==='day'?2:8)&&r.entry.end_day_offset<=(v.template.kind==='day'?2:8)&&r.entry.index<v.entryCount&&(i===0||(v.pageKind==='entries'?v.entries[i-1].entry.index+1===r.entry.index:v.entries[i-1].entry.index<r.entry.index))&&(v.pageKind!=='blocked'||r.blockers.length>0)&&(v.pageKind!=='affected'||r.internalConflict||r.existingConflict)&&(!v.canAdd||(r.blockers.length===0&&r.starts_at!==null&&r.ends_at!==null&&r.starts_at<r.ends_at&&r.elapsed_micros!==null)))));
export const rotaPeriodSavedSchema=z.strictObject({schemaVersion:z.literal(1),tenantId:periodUuid,actorId:periodUuid,operationId:periodUuid,action,template_id:periodUuid,template_revision:rev,schedule_id:periodUuid,schedule_revision:rev,entry_count:nonzeroCount,generated:z.array(z.strictObject({index:z.number().int().min(0).max(4999),id:periodUuid,revision:z.literal(1)})).max(5000),plan_digest:digest.nullable()}).refine(v=>v.action==='add'?v.plan_digest!==null&&v.generated.length===v.entry_count&&v.generated.every((r,i)=>r.index===i)&&new Set(v.generated.map(r=>r.id)).size===v.entry_count:v.plan_digest===null&&v.generated.length===0);
const recoveryBase={schemaVersion:z.literal(1),tenantId:periodUuid,actorId:periodUuid,operationId:periodUuid,action,scheduleId:periodUuid,templateId:periodUuid.nullable()};
export const rotaPeriodReconciliationSchema=z.discriminatedUnion('status',[z.strictObject({...recoveryBase,status:z.literal('recorded'),saved:rotaPeriodSavedSchema}),z.strictObject({...recoveryBase,status:z.literal('not_recorded'),saved:z.null()})]).refine(v=>(v.action==='save')===(v.templateId===null)&&(v.status==='not_recorded'||v.saved.tenantId===v.tenantId&&v.saved.actorId===v.actorId&&v.saved.operationId===v.operationId&&v.saved.action===v.action&&v.saved.schedule_id===v.scheduleId&&(v.templateId===null||v.saved.template_id===v.templateId)));
export const parseRotaPeriodCatalogue = (v:unknown) => rotaPeriodCatalogueDataSchema.parse(v);
export const parseRotaPeriodHistorical = (v:unknown) => rotaPeriodHistoricalDataSchema.parse(v);
export const parseRotaPeriodSourcePreview = (v:unknown) => rotaPeriodSourcePreviewSchema.parse(v);
export const parseRotaPeriodTargetPreview = (v:unknown) => rotaPeriodTargetPreviewSchema.parse(v);
export const parseRotaPeriodSaved = (v:unknown) => rotaPeriodSavedSchema.parse(v);
export const parseRotaPeriodReconciliation = (v:unknown) => rotaPeriodReconciliationSchema.parse(v);
