import {z} from 'zod';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {SmartGroupRule,SmartGroupsQuery,SmartGroupSegmentsQuery,SmartGroupMembersQuery,SmartGroupPreviewInput,SmartGroupsData,SmartGroupSegmentsData,SmartGroupMembersData,SmartGroupPreviewData,SmartGroupMutation,SmartGroupSaved} from './smart-group-types';
const uuid=z.uuid().transform(v=>v.toLowerCase()),revision=z.number().int().min(1).max(2147483647),count=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),role=z.enum(['owner','admin']),status=z.enum(['active','archived']),digest=z.string().regex(/^[a-f0-9]{32}$/),time=z.iso.datetime({offset:true});
const name=z.string().trim().min(1).max(100).refine(v=>v.length<=100),description=z.string().max(500).refine(v=>v.length<=500),field=z.union([z.literal('title'),z.literal('team'),z.string().regex(/^custom:[a-z][a-z0-9_]{0,39}$/)]).transform(v=>v as SmartGroupRule['field']),alternative=z.string().max(500).refine(v=>v.length<=500&&v.trim().length>0);
export const smartGroupRules=z.array(z.object({field,values:z.array(alternative).min(1).max(25).refine(v=>new Set(v).size===v.length)}).strict()).min(1).max(10);
const expectedRevision=revision.max(2147483646),details={name,description},definition={...details,segmentId:uuid,rules:smartGroupRules};
export const smartGroupMutation=z.object({tenantId:uuid,operationId:uuid,change:z.discriminatedUnion('action',[
 z.object({action:z.literal('create_segment'),...details}).strict(),z.object({action:z.literal('edit_segment'),segmentId:uuid,revision:expectedRevision,...details}).strict(),z.object({action:z.enum(['archive_segment','restore_segment']),segmentId:uuid,revision:expectedRevision}).strict(),
 z.object({action:z.literal('create_group'),...definition}).strict(),z.object({action:z.literal('edit_group'),groupId:uuid,revision:expectedRevision,...definition}).strict(),z.object({action:z.enum(['archive_group','restore_group']),groupId:uuid,revision:expectedRevision}).strict()
])}).strict();
export const smartGroupPreview=z.object({tenantId:uuid,rules:smartGroupRules,search:z.string().max(100).optional(),limit:z.number().int().min(1).max(100).optional(),cursor:z.string().regex(/^[A-Za-z0-9_-]+$/).max(30000).optional()}).strict();
const population=z.object({records:count,unlinked:count,eligible:count,unavailable:count}).strict().refine(c=>c.records===c.unlinked+c.eligible+c.unavailable);
const fields=z.array(z.object({key:field,label:z.string().min(1).max(200).refine(v=>Array.from(v).length<=100)}).strict()).refine(a=>new Set(a.map(f=>f.key)).size===a.length&&a.some(f=>f.key==='title')&&a.some(f=>f.key==='team'));
// SQL character limits count Unicode codepoints; do not reject valid non-BMP stored values.
const storedText=(max:number)=>z.string().max(max*2).refine(v=>Array.from(v).length<=max);
const storedRules=z.array(z.object({field,values:z.array(storedText(500).refine(v=>v.trim().length>0)).min(1).max(25).refine(v=>new Set(v).size===v.length)}).strict()).min(1).max(10);
const segment=z.object({id:uuid,name:storedText(100).refine(v=>v.trim().length>0),description:storedText(500),status,revision,activeGroupCount:count,canArchive:z.boolean(),canRestore:z.boolean()}).strict().refine(s=>s.canArchive===(s.status==='active'&&s.activeGroupCount===0)&&s.canRestore===(s.status==='archived'));
const group=z.object({id:uuid,segmentId:uuid,name:storedText(100).refine(v=>v.trim().length>0),description:storedText(500),status,revision,rules:storedRules,needsReview:z.boolean(),invalidFields:z.array(field).max(10).refine(a=>new Set(a).size===a.length),counts:population.nullable(),canEdit:z.boolean(),canArchive:z.boolean(),canRestore:z.boolean()}).strict().refine(g=>g.needsReview===(g.invalidFields.length>0)&&g.needsReview===(g.counts===null)&&g.canArchive===(g.status==='active')&&(!g.canRestore||(g.status==='archived'&&!g.needsReview&&g.canEdit)));
const member=z.object({id:uuid,name:storedText(201),title:storedText(100),team:storedText(100),linkStatus:z.enum(['unlinked','eligible','unavailable'])}).strict();
const identity={tenantId:uuid,actorId:uuid,role,fieldFingerprint:digest,datasetVersion:digest};
const scope=z.object({...identity,kind:z.enum(['groups','segments','members','preview']),groupId:uuid.nullable(),segmentId:uuid.nullable(),status:z.enum(['all','active','archived']),search:z.string().max(100),rulesFingerprint:digest.nullable(),groupRevision:revision.nullable()}).strict();
const cursorSchema=z.object({scope,id:uuid,position:z.string().min(1).max(500)}).strict();
const listCounts=z.object({total:count,active:count,archived:count}).strict().refine(c=>c.total===c.active+c.archived);
const groupsSchema=z.object({...identity,company:z.object({id:uuid,name:z.string(),time_zone:z.string()}).strict(),fields,groups:z.array(group).max(100),counts:z.object({total:count,active:count,archived:count,needsReview:count}).strict().refine(c=>c.total===c.active+c.archived&&c.needsReview<=c.total),nextCursor:cursorSchema.nullable(),serverTime:time}).strict();
const segmentsSchema=z.object({...identity,segments:z.array(segment).max(100),counts:listCounts,nextCursor:cursorSchema.nullable(),serverTime:time}).strict();
const membersSchema=z.object({...identity,group,segment,fields,members:z.array(member).max(100),counts:population.nullable(),matchedCount:count.nullable(),nextCursor:cursorSchema.nullable(),serverTime:time}).strict().refine(d=>d.group.segmentId===d.segment.id&&(d.group.needsReview?(d.counts===null&&d.matchedCount===null&&d.members.length===0&&d.nextCursor===null):d.counts!==null&&d.matchedCount!==null));
const previewSchema=z.object({...identity,fields,rules:storedRules,members:z.array(member).max(100),counts:population,matchedCount:count,nextCursor:cursorSchema.nullable(),serverTime:time}).strict();
const savedSchema=z.object({operationId:uuid,action:z.enum(['create_segment','edit_segment','archive_segment','restore_segment','create_group','edit_group','archive_group','restore_group']),segmentId:uuid,groupId:uuid.optional(),revision}).strict();
export class SmartGroupsError extends Error{status:number;constructor(message:string,status=503){super(message);this.status=status;}}
function fail(error:{code?:string}|null){if(!error)return;const code=error.code??'';throw new SmartGroupsError(code==='42501'?'Company or Smart Groups access is unavailable.':code==='40001'?'The groups or matching records changed. Refresh and review.':['22023','22P02','22003','23514','23502'].includes(code)?'Choose valid group details, rules and filters.':'Smart Groups could not be verified. Refresh and review before another change.',code==='42501'?403:code==='40001'?409:['22023','22P02','22003','23514','23502'].includes(code)?400:503);}
const pageLimit=z.string().regex(/^[1-9][0-9]{0,2}$/).transform(Number).refine(v=>v<=100).optional(),queryCursor=z.string().regex(/^[A-Za-z0-9_-]+$/).max(30000).optional();
function params<T>(p:URLSearchParams,s:z.ZodType<T>):T{if([...p.keys()].some(k=>p.getAll(k).length!==1))throw new SmartGroupsError('Choose valid group filters.',400);const v=s.safeParse(Object.fromEntries(p));if(!v.success)throw new SmartGroupsError('Choose valid group filters.',400);return v.data;}
export function parseSmartGroupsQuery(p:URLSearchParams):SmartGroupsQuery{const q=params(p,z.object({tenantId:uuid,status:z.enum(['all','active','archived']).optional(),search:z.string().max(100).optional(),limit:pageLimit,segmentId:uuid.optional(),cursor:queryCursor}).strict());return {...q,status:q.status??'active',search:q.search??'',limit:q.limit??50};}
export function parseSmartGroupSegmentsQuery(p:URLSearchParams):SmartGroupSegmentsQuery{const q=params(p,z.object({tenantId:uuid,status:z.enum(['all','active','archived']).optional(),search:z.string().max(100).optional(),limit:pageLimit,cursor:queryCursor}).strict());return {...q,status:q.status??'all',search:q.search??'',limit:q.limit??50};}
export function parseSmartGroupMembersQuery(p:URLSearchParams,groupId:string):SmartGroupMembersQuery{const id=uuid.safeParse(groupId);if(!id.success)throw new SmartGroupsError('Choose a valid group.',400);const q=params(p,z.object({tenantId:uuid,search:z.string().max(100).optional(),limit:pageLimit,cursor:queryCursor}).strict());return {...q,groupId:id.data,search:q.search??'',limit:q.limit??50};}
export function decodeSmartGroupsCursor(v?:string){if(!v)return null;try{if(v.length>30000||!/^[A-Za-z0-9_-]+$/.test(v))throw Error();return cursorSchema.parse(JSON.parse(Buffer.from(v,'base64url').toString()));}catch{throw new SmartGroupsError('Choose a valid group cursor.',400);}}
const encode=(c:z.infer<typeof cursorSchema>|null)=>c?Buffer.from(JSON.stringify(c)).toString('base64url'):null;
type Read={tenantId:string;kind:z.infer<typeof scope>['kind'];groupId?:string;segmentId?:string;status?:'all'|'active'|'archived';search:string;limit:number;cursor?:string;rules?:SmartGroupPreviewInput['rules']};
async function signed(c:SupabaseClient){const{data:{user},error}=await c.auth.getUser();if(error||!user)throw new SmartGroupsError('Sign in to view Smart Groups.',401);return user.id;}
async function snapshot<T>(c:SupabaseClient,q:Read,s:z.ZodType<T>){const actor=await signed(c),after=decodeSmartGroupsCursor(q.cursor);if(after&&(after.scope.actorId!==actor||after.scope.tenantId!==q.tenantId))throw new SmartGroupsError('Group cursor belongs to another account or company.',400);
 const{data,error}=await c.rpc('read_smart_groups',{target_tenant:q.tenantId,read_kind:q.kind,target_group:q.groupId??null,target_segment:q.segmentId??null,status_filter:q.status??'all',search_text:q.search,page_limit:q.limit,after_item:after,preview_rules:q.rules??null});fail(error);const p=s.safeParse(data);if(!p.success)throw new SmartGroupsError('Smart Groups response could not be verified.');return {data:p.data,actor,after};}
const accessSchema=z.object({...identity,groups:z.array(z.object({id:uuid,segmentId:uuid,revision,status}).strict()).max(100),segments:z.array(z.object({id:uuid,revision,status}).strict()).max(100)}).strict();
async function recheck(c:SupabaseClient,d:z.infer<typeof groupsSchema>|z.infer<typeof segmentsSchema>|z.infer<typeof membersSchema>|z.infer<typeof previewSchema>,groups:z.infer<typeof group>[]=[],segments:z.infer<typeof segment>[]=[]){const{data,error}=await c.rpc('read_smart_groups_access',{target_tenant:d.tenantId,group_ids:groups.map(g=>g.id),segment_ids:[...new Set([...segments.map(s=>s.id),...groups.map(g=>g.segmentId)])]});fail(error);const p=accessSchema.safeParse(data);if(!p.success)throw new SmartGroupsError('Smart Groups access could not be verified.');const a=p.data;if(a.tenantId!==d.tenantId||a.actorId!==d.actorId||a.role!==d.role)throw new SmartGroupsError('Company or Smart Groups access changed.',403);
 if(a.fieldFingerprint!==d.fieldFingerprint||a.datasetVersion!==d.datasetVersion||groups.some(g=>!a.groups.some(x=>x.id===g.id&&x.segmentId===g.segmentId&&x.status===g.status&&x.revision===g.revision))||segments.some(s=>!a.segments.some(x=>x.id===s.id&&x.status===s.status&&x.revision===s.revision))||new Set(a.groups.map(g=>g.id)).size!==a.groups.length||new Set(a.segments.map(s=>s.id)).size!==a.segments.length)throw new SmartGroupsError('The groups or matching records changed. Refresh and review.',409);}
function validatePage(d:{tenantId:string;actorId:string;role:string;fieldFingerprint:string;datasetVersion:string;nextCursor:z.infer<typeof cursorSchema>|null},q:Read,actor:string,ids:string[]){if(d.tenantId!==q.tenantId||d.actorId!==actor||ids.length>q.limit||new Set(ids).size!==ids.length)throw new SmartGroupsError('Group page could not be verified.');const n=d.nextCursor;if(n&&(ids.length!==q.limit||n.id!==ids.at(-1)||n.scope.tenantId!==d.tenantId||n.scope.actorId!==d.actorId||n.scope.role!==d.role||n.scope.fieldFingerprint!==d.fieldFingerprint||n.scope.datasetVersion!==d.datasetVersion||n.scope.kind!==q.kind||n.scope.groupId!==(q.groupId??null)||n.scope.segmentId!==(q.segmentId??null)||n.scope.status!==(q.status??'all')||n.scope.search!==q.search||(['members','preview'].includes(q.kind)?n.scope.rulesFingerprint===null:n.scope.rulesFingerprint!==null)||q.kind!=='members'&&n.scope.groupRevision!==null))throw new SmartGroupsError('Group continuation could not be verified.');}
function validFields(d:{fields:z.infer<typeof fields>},g:z.infer<typeof group>){const unknown=[...new Set(g.rules.map(r=>r.field).filter(f=>!d.fields.some(x=>x.key===f)))].sort();if(JSON.stringify(unknown)!==JSON.stringify([...g.invalidFields].sort()))throw new SmartGroupsError('Group rule fields could not be verified.');}
function validateMembers(d:{members:z.infer<typeof member>[];counts:z.infer<typeof population>|null;matchedCount:number|null},search:string){if(d.counts===null){if(d.members.length||d.matchedCount!==null)throw new SmartGroupsError('Group population could not be verified.');return;}if(d.matchedCount===null||d.matchedCount>d.counts.records||d.members.length>d.matchedCount||search===''&&d.matchedCount!==d.counts.records)throw new SmartGroupsError('Group population could not be verified.');for(const key of ['unlinked','eligible','unavailable']as const)if(d.members.filter(m=>m.linkStatus===key).length>d.counts[key])throw new SmartGroupsError('Group eligibility could not be verified.');}
export async function readSmartGroups(c:SupabaseClient,query:SmartGroupsQuery):Promise<SmartGroupsData>{const q={...query,kind:'groups'as const};const{data:d,actor}=await snapshot(c,q,groupsSchema);validatePage(d,q,actor,d.groups.map(g=>g.id));if(d.company.id!==d.tenantId||d.groups.length>(q.status==='all'?d.counts.total:d.counts[q.status])||d.groups.filter(g=>g.needsReview).length>d.counts.needsReview||d.groups.some(g=>q.status!=='all'&&g.status!==q.status||q.segmentId&&g.segmentId!==q.segmentId))throw new SmartGroupsError('Group catalog could not be verified.');d.groups.forEach(g=>validFields(d,g));await recheck(c,d,d.groups);return {...d,nextCursor:encode(d.nextCursor)}as SmartGroupsData;}
export async function readSmartGroupSegments(c:SupabaseClient,query:SmartGroupSegmentsQuery):Promise<SmartGroupSegmentsData>{const q={...query,kind:'segments'as const};const{data:d,actor}=await snapshot(c,q,segmentsSchema);validatePage(d,q,actor,d.segments.map(s=>s.id));if(d.segments.length>(q.status==='all'?d.counts.total:d.counts[q.status])||d.segments.some(s=>q.status!=='all'&&s.status!==q.status))throw new SmartGroupsError('Segments could not be verified.');await recheck(c,d,[],d.segments);return {...d,nextCursor:encode(d.nextCursor)};}
export async function readSmartGroupMembers(c:SupabaseClient,query:SmartGroupMembersQuery):Promise<SmartGroupMembersData>{const q={...query,kind:'members'as const};const{data:d,actor}=await snapshot(c,q,membersSchema);validatePage(d,q,actor,d.members.map(m=>m.id));if(d.group.id!==q.groupId||d.group.segmentId!==d.segment.id||JSON.stringify(d.counts)!==JSON.stringify(d.group.counts)||d.group.canEdit!==(d.segment.status==='active')||d.group.canRestore!==(d.group.status==='archived'&&d.segment.status==='active'&&!d.group.needsReview)||d.nextCursor&&(d.nextCursor.scope.groupRevision!==d.group.revision))throw new SmartGroupsError('Group definition could not be verified.');validFields(d,d.group);validateMembers(d,q.search);await recheck(c,d,[d.group],[d.segment]);return {...d,nextCursor:encode(d.nextCursor)}as SmartGroupMembersData;}
export async function previewSmartGroup(c:SupabaseClient,input:SmartGroupPreviewInput):Promise<SmartGroupPreviewData>{const q={...input,kind:'preview'as const,search:input.search??'',limit:input.limit??50};const{data:d,actor}=await snapshot(c,q,previewSchema);validatePage(d,q,actor,d.members.map(m=>m.id));if(JSON.stringify(d.rules)!==JSON.stringify(input.rules)||d.rules.some(r=>!d.fields.some(f=>f.key===r.field)))throw new SmartGroupsError('Rule preview could not be verified.');validateMembers(d,q.search);await recheck(c,d);return {...d,nextCursor:encode(d.nextCursor)}as SmartGroupPreviewData;}
export async function saveSmartGroup(c:SupabaseClient,input:SmartGroupMutation):Promise<SmartGroupSaved>{await signed(c);const{data,error}=await c.rpc('save_smart_group',{target_tenant:input.tenantId,operation_id:input.operationId,change:input.change});fail(error);const p=savedSchema.safeParse(data);if(!p.success)throw new SmartGroupsError('The save acknowledgement could not be verified. Refresh and review.');const s=p.data,v=input.change;const isGroup=v.action.endsWith('_group');if(s.operationId!==input.operationId||s.action!==v.action||s.revision!==('revision'in v?v.revision+1:1)||isGroup!==!!s.groupId||'groupId'in v&&s.groupId!==v.groupId||'segmentId'in v&&s.segmentId!==v.segmentId)throw new SmartGroupsError('The save acknowledgement could not be verified. Refresh and review.');return s;}
