import type {Company,Member} from './agent-types';
export type TimeOffType={id:string;name:string;description:string;paid:boolean;status:'active'|'archived';revision:number;canArchive:boolean};
export type TimeOffStatus='pending'|'approved'|'rejected'|'withdrawn'|'cancelled';
export type TimeOffEvent={action:string;actor_name:string;occurred_at:string;revision:number;reason:string|null};
export type TimeOffRequest={id:string;tenant_id:string;agent_id:string;agent_name:string;type_id:string;type_name:string;type_description:string;type_paid:boolean;start_date:string;end_date:string;calendar_days:number;note:string;status:TimeOffStatus;revision:number;requested_by:string;requested_at:string;decision_by:string|null;decision_name:string|null;decision_reason:string|null;decided_at:string|null;history:TimeOffEvent[];canWithdraw:boolean;canApprove:boolean;canReject:boolean;canCancel:boolean};
export type TimeOffData={company:Company;role:Member['role'];actorId:string;agent:{id:string;name:string}|null;types:TimeOffType[];requests:TimeOffRequest[];counts:{total:number;pending:number;approved:number;rejected:number;withdrawn:number;cancelled:number};nextCursor:string|null;serverTime:string;timeZone:string;capabilities:{canRequest:boolean;canManageTypes:boolean;canViewTeam:boolean}};
export type TimeOffChange={action:'create_type';name:string;description:string;paid:boolean}|{action:'archive_type';typeId:string;revision:number}|{action:'request';agentId:string;typeId:string;startDate:string;endDate:string;note:string}|{action:'withdraw';requestId:string;revision:number}|{action:'approve'|'reject'|'cancel';requestId:string;revision:number;reason:string};
export type TimeOffSaved={operationId:string;action:TimeOffChange['action'];typeId:string;requestId?:string;revision:number};
export type TimeOffQuery={tenantId:string;view:'mine'|'team';status:'all'|TimeOffStatus;search:string;limit:number;agentId?:string;typeId?:string;startDate?:string;endDate?:string;cursor?:string};
