import {z} from 'zod';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {UpdatesData,UpdatesQuery,UpdatesRosterQuery,UpdatesRosterData,UpdateDetailsQuery,UpdateDetailsData,UpdateRecipientsQuery,UpdateRecipientsData,UpdatesSaved} from './updates-types';
const uuid=z.uuid().transform(v=>v.toLowerCase()),revision=z.number().int().min(1).max(2147483646),count=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),time=z.iso.datetime({offset:true}),role=z.enum(['owner','admin','manager','employee']);
const text=(max:number)=>z.string().trim().min(1).max(max);
const draft={title:text(160),body:text(5000),recipientIds:z.array(uuid).min(1).max(500).refine(a=>new Set(a).size===a.length),allowComments:z.boolean(),allowReactions:z.boolean(),requireConfirmation:z.boolean()};
const engagement={postId:uuid,contentRevision:z.literal(1)};
export const updatesMutation=z.object({tenantId:uuid,operationId:uuid,change:z.discriminatedUnion('action',[
 z.object({action:z.literal('create'),...draft}).strict(),z.object({action:z.literal('edit'),postId:uuid,revision,...draft}).strict(),
 z.object({action:z.enum(['publish','archive','restore']),postId:uuid,revision}).strict(),z.object({action:z.enum(['view','confirm','like','unlike']),...engagement}).strict(),
 z.object({action:z.literal('comment'),...engagement,body:text(2000)}).strict(),z.object({action:z.literal('edit_comment'),...engagement,commentId:uuid,revision,body:text(2000)}).strict(),z.object({action:z.literal('remove_comment'),...engagement,commentId:uuid,revision}).strict()
])}).strict();
const recipient=z.object({id:uuid,name:z.string().min(1).max(200).refine(v=>Array.from(v).length<=100)}).strict();
const post=z.object({id:uuid,tenant_id:uuid,title:text(320).refine(v=>Array.from(v).length<=160),body:text(10000).refine(v=>Array.from(v).length<=5000),status:z.enum(['draft','published','archived']),revision,content_revision:z.number().int().min(0).max(1),created_by:uuid,created_name:z.string(),created_at:time,published_at:time.nullable(),allowComments:z.boolean(),allowReactions:z.boolean(),requireConfirmation:z.boolean(),recipientCount:count,viewedCount:count,confirmedCount:count,likeCount:count,commentCount:count,liked:z.boolean(),viewedAt:time.nullable(),confirmedAt:time.nullable(),canEdit:z.boolean(),canPublish:z.boolean(),canArchive:z.boolean(),canRestore:z.boolean(),canEngage:z.boolean(),isRecipient:z.boolean()}).strict().refine(p=>p.recipientCount>=1&&p.recipientCount<=500&&p.confirmedCount<=p.viewedCount&&p.viewedCount<=p.recipientCount&&p.likeCount<=p.recipientCount&&(p.status==='draft'?p.content_revision===0&&p.published_at===null:p.content_revision===1&&p.published_at!==null)&&(!p.confirmedAt||!!p.viewedAt)&&(!p.canEngage||(p.isRecipient&&p.status==='published')));
const comment=z.object({id:uuid,post_id:uuid,actorId:uuid,author_name:z.string(),body:z.string().max(4000).refine(v=>Array.from(v).length<=2000),status:z.enum(['active','removed']),revision,created_at:time,updated_at:time,canEdit:z.boolean(),canRemove:z.boolean()}).strict().refine(c=>c.status==='active'?c.body.trim().length>0:c.body===''&&!c.canEdit&&!c.canRemove);
const scope=z.object({tenantId:uuid,actorId:uuid,role,kind:z.enum(['feed','manage','detail','roster','recipients']),postId:uuid.nullable(),status:z.string(),search:z.string().max(100),contentRevision:z.number().int().min(0).max(1).nullable(),postRevision:revision.nullable()}).strict();
const cursor=z.object({scope,id:uuid,position:z.string().max(200)}).strict().refine(c=>['feed','manage','detail'].includes(c.scope.kind)?time.safeParse(c.position).success:c.scope.kind==='recipients'?c.position==='':c.position.length>0);
const company=z.object({id:uuid,name:z.string(),time_zone:z.string()}).strict();
const counts=z.object({total:count,draft:count,published:count,archived:count}).strict().refine(c=>c.total===c.draft+c.published+c.archived);
const feedSchema=z.object({company,role,actorId:uuid,capabilities:z.object({canManage:z.boolean()}).strict(),posts:z.array(post).max(100),counts,nextCursor:cursor.nullable(),serverTime:time}).strict();
const identity={tenantId:uuid,actorId:uuid,role};
const detailSchema=z.object({...identity,post,recipients:z.array(recipient).max(500),comments:z.array(comment).max(100),nextCommentsCursor:cursor.nullable(),serverTime:time}).strict();
const rosterSchema=z.object({...identity,users:z.array(recipient).max(100),nextCursor:cursor.nullable()}).strict();
const analyticsSchema=z.object({...identity,recipients:z.array(z.object({actorId:uuid,name:z.string(),viewedAt:time.nullable(),confirmedAt:time.nullable()}).strict().refine(r=>!r.confirmedAt||!!r.viewedAt)).max(100),counts:z.object({total:count,viewed:count,confirmed:count,likes:count,comments:count}).strict().refine(c=>c.confirmed<=c.viewed&&c.viewed<=c.total&&c.likes<=c.total&&c.total<=500),nextCursor:cursor.nullable()}).strict();
const savedSchema=z.object({operationId:uuid,action:z.enum(['create','edit','publish','archive','restore','view','confirm','like','unlike','comment','edit_comment','remove_comment']),postId:uuid,revision,contentRevision:z.number().int().min(0).max(1),commentId:uuid.optional(),commentRevision:revision.optional()}).strict();
export class UpdatesError extends Error{status:number;constructor(message:string,status=503){super(message);this.status=status;}}
function fail(error:{code?:string}|null){if(!error)return;throw new UpdatesError(error.code==='42501'?'Company or update access is unavailable.':error.code==='40001'?'The update changed. Refresh and review before changing it.':['22023','22P02','22003','23514','23502'].includes(error.code??'')?'Choose valid update details.':'The update could not be confirmed. Refresh and review before another change.',error.code==='42501'?403:error.code==='40001'?409:['22023','22P02','22003','23514','23502'].includes(error.code??'')?400:503);}
const limit=z.string().regex(/^[1-9][0-9]{0,2}$/).transform(Number).refine(v=>v<=100).optional(),cursorString=z.string().regex(/^[A-Za-z0-9_-]+$/).max(2000).optional();
function params<T>(p:URLSearchParams,s:z.ZodType<T>):T{if([...p.keys()].some(k=>p.getAll(k).length!==1))throw new UpdatesError('Choose valid update filters.',400);const v=s.safeParse(Object.fromEntries(p));if(!v.success)throw new UpdatesError('Choose valid update filters.',400);return v.data;}
export function parseUpdatesQuery(p:URLSearchParams):UpdatesQuery{const q=params(p,z.object({tenantId:uuid,view:z.enum(['feed','manage']).optional(),status:z.enum(['all','draft','published','archived']).optional(),search:z.string().trim().max(100).optional(),limit,cursor:cursorString}).strict());return {...q,view:q.view??'feed',status:q.status??'all',search:q.search??'',limit:q.limit??50};}
export function parseUpdatesRosterQuery(p:URLSearchParams):UpdatesRosterQuery{const q=params(p,z.object({tenantId:uuid,search:z.string().trim().max(100).optional(),limit,cursor:cursorString}).strict());return {...q,search:q.search??'',limit:q.limit??50};}
export function parseUpdateDetailsQuery(p:URLSearchParams,postId:string):UpdateDetailsQuery{const id=uuid.safeParse(postId);if(!id.success)throw new UpdatesError('Choose a valid update.',400);const q=params(p,z.object({tenantId:uuid,limit,cursor:cursorString}).strict());return {...q,postId:id.data,limit:q.limit??50};}
export function parseUpdateRecipientsQuery(p:URLSearchParams,postId:string):UpdateRecipientsQuery{const id=uuid.safeParse(postId);if(!id.success)throw new UpdatesError('Choose a valid update.',400);const q=params(p,z.object({tenantId:uuid,status:z.enum(['all','viewed','unviewed','confirmed','unconfirmed']).optional(),limit,cursor:cursorString}).strict());return {...q,postId:id.data,status:q.status??'all',limit:q.limit??50};}
export function decodeUpdatesCursor(v?:string){if(!v)return null;try{if(v.length>2000||!/^[A-Za-z0-9_-]+$/.test(v))throw Error();return cursor.parse(JSON.parse(Buffer.from(v,'base64url').toString()));}catch{throw new UpdatesError('Choose a valid update cursor.',400);}}
const encode=(c:z.infer<typeof cursor>|null)=>c?Buffer.from(JSON.stringify(c)).toString('base64url'):null;
const accessSchema=z.object({actorId:uuid,role,postStatus:z.enum(['draft','published','archived']).nullable(),contentRevision:z.number().int().min(0).max(1).nullable(),postRevision:revision.nullable(),isRecipient:z.boolean(),posts:z.array(z.object({id:uuid,status:z.enum(['draft','published','archived']),revision,contentRevision:z.number().int().min(0).max(1),isRecipient:z.boolean()}).strict()).max(100)}).strict();
async function signed(client:SupabaseClient){const{data:{user},error}=await client.auth.getUser();if(error||!user)throw new UpdatesError('Sign in to view updates.',401);return user.id;}
type Read={tenantId:string;kind:z.infer<typeof scope>['kind'];postId?:string;status?:string;search?:string;limit:number;cursor?:string};
async function snapshot<T>(client:SupabaseClient,q:Read,schema:z.ZodType<T>){const actorId=await signed(client);const after=decodeUpdatesCursor(q.cursor);if(after&&(after.scope.tenantId!==q.tenantId||after.scope.actorId!==actorId||after.scope.kind!==q.kind||after.scope.postId!==(q.postId??null)||after.scope.status!==(q.status??'all')||after.scope.search!==(q.search??'')))throw new UpdatesError('Update filters changed. Start again.',400);
 const{data,error}=await client.rpc('read_updates',{target_tenant:q.tenantId,read_kind:q.kind,target_post:q.postId??null,status_filter:q.status??'all',search_text:q.search??'',page_limit:q.limit,after_item:after});fail(error);const parsed=schema.safeParse(data);if(!parsed.success)throw new UpdatesError('Updates could not be verified. Try again.');return {data:parsed.data,actorId,after};}
async function recheck(client:SupabaseClient,q:Read,actorId:string,posts:z.infer<typeof post>[]=[],expectedRole?:string){const{data,error}=await client.rpc('read_updates_access',{target_tenant:q.tenantId,target_post:q.postId??null,target_posts:posts.map(p=>p.id)});fail(error);const p=accessSchema.safeParse(data);if(!p.success)throw new UpdatesError('Update access could not be verified.');const a=p.data;if(a.actorId!==actorId||expectedRole&&a.role!==expectedRole||['manage','roster','recipients'].includes(q.kind)&&!['owner','admin'].includes(a.role))throw new UpdatesError('Company or update access changed.',403);
 if(posts.some(x=>{const current=a.posts.find(p=>p.id===x.id);return !current||current.revision!==x.revision||current.contentRevision!==x.content_revision||current.status!==x.status||current.isRecipient!==x.isRecipient||q.kind==='feed'&&(!current.isRecipient||current.status!=='published');}))throw new UpdatesError('Update access changed. Refresh and review.',403);return a;}
function pageCursor(c:z.infer<typeof cursor>|null,q:Read,actorId:string,rows:number,lastId?:string,position?:string,expectedRole?:string){if(c&&(c.scope.tenantId!==q.tenantId||c.scope.actorId!==actorId||c.scope.kind!==q.kind||c.scope.postId!==(q.postId??null)||c.scope.status!==(q.status??'all')||c.scope.search!==(q.search??'')||expectedRole&&c.scope.role!==expectedRole||rows!==q.limit||c.id!==lastId||position!==undefined&&c.position!==position))throw new UpdatesError('Update page could not be verified.');}
function micros(v:string){const millis=Date.parse(v);if(!Number.isFinite(millis))throw new UpdatesError('Update time could not be verified.');const fraction=v.match(/\.(\d+)/)?.[1]??'';return BigInt(millis)*1000n+BigInt(fraction.padEnd(6,'0').slice(3,6));}
function ordered(rows:{id:string;at:string}[],after:z.infer<typeof cursor>|null,next:z.infer<typeof cursor>|null){if(new Set(rows.map(r=>r.id)).size!==rows.length||rows.some((r,i)=>{const at=micros(r.at);const previous=i?rows[i-1]:after?{id:after.id,at:after.position}:null;return previous&&(at>micros(previous.at)||at===micros(previous.at)&&r.id>=previous.id);})||next&&rows.length>0&&micros(next.position)!==micros(rows.at(-1)!.at))throw new UpdatesError('Update page order could not be verified.');}
export async function readUpdates(client:SupabaseClient,query:UpdatesQuery):Promise<UpdatesData>{const q={...query,kind:query.view};const{data:d,actorId,after}=await snapshot(client,q,feedSchema);const admin=['owner','admin'].includes(d.role);if(d.company.id!==q.tenantId||d.actorId!==actorId||d.posts.length>q.limit||d.counts.total<d.posts.length||d.capabilities.canManage!==admin||d.posts.some(p=>p.tenant_id!==q.tenantId||q.view==='feed'&&(!p.isRecipient||p.status!=='published')||p.canEdit!==(admin&&p.status==='draft')||p.canPublish!==(admin&&p.status==='draft')||p.canArchive!==(admin&&p.status==='published')||p.canRestore!==(admin&&p.status==='archived')))throw new UpdatesError('Updates could not be verified.');try{new Intl.DateTimeFormat('en',{timeZone:d.company.time_zone});}catch{throw new UpdatesError('Company time zone could not be verified.');}ordered(d.posts.map(p=>({id:p.id,at:q.view==='feed'?p.published_at!:p.created_at})),after,d.nextCursor);pageCursor(d.nextCursor,q,actorId,d.posts.length,d.posts.at(-1)?.id,undefined,d.role);await recheck(client,q,actorId,d.posts,d.role);return {...d,nextCursor:encode(d.nextCursor)};}
export async function readUpdatesRoster(client:SupabaseClient,query:UpdatesRosterQuery):Promise<UpdatesRosterData>{const q={...query,kind:'roster' as const};const{data:d,actorId}=await snapshot(client,q,rosterSchema);if(d.tenantId!==q.tenantId||d.actorId!==actorId||d.users.length>q.limit||new Set(d.users.map(x=>x.id)).size!==d.users.length)throw new UpdatesError('Recipient list could not be verified.');pageCursor(d.nextCursor,q,actorId,d.users.length,d.users.at(-1)?.id,undefined,d.role);await recheck(client,q,actorId,[],d.role);return {...d,nextCursor:encode(d.nextCursor)};}
export async function readUpdateDetails(client:SupabaseClient,query:UpdateDetailsQuery):Promise<UpdateDetailsData>{const q={...query,kind:'detail' as const};const{data:d,actorId,after}=await snapshot(client,q,detailSchema);if(d.tenantId!==q.tenantId||d.actorId!==actorId||d.post.id!==q.postId||d.post.tenant_id!==q.tenantId||d.comments.length>q.limit||new Set(d.recipients.map(x=>x.id)).size!==d.recipients.length||d.comments.some(c=>c.post_id!==q.postId||c.canEdit&&(c.actorId!==actorId||!d.post.canEngage||!d.post.allowComments)||c.canRemove!==c.canEdit))throw new UpdatesError('Update details could not be verified.');ordered(d.comments.map(c=>({id:c.id,at:c.created_at})),after,d.nextCommentsCursor);pageCursor(d.nextCommentsCursor,q,actorId,d.comments.length,d.comments.at(-1)?.id,undefined,d.role);const a=await recheck(client,q,actorId,[d.post],d.role);if(a.postRevision!==d.post.revision||a.contentRevision!==d.post.content_revision||a.postStatus!==d.post.status||(!['owner','admin'].includes(a.role)&&d.recipients.length>0)||(['owner','admin'].includes(a.role)&&d.recipients.length!==d.post.recipientCount))throw new UpdatesError('Update access changed. Refresh and review.',403);return {...d,nextCommentsCursor:encode(d.nextCommentsCursor)};}
export async function readUpdateRecipients(client:SupabaseClient,query:UpdateRecipientsQuery):Promise<UpdateRecipientsData>{const q={...query,kind:'recipients' as const};const{data:d,actorId}=await snapshot(client,q,analyticsSchema);if(d.tenantId!==q.tenantId||d.actorId!==actorId||d.recipients.length>q.limit||d.counts.total<d.recipients.length||new Set(d.recipients.map(x=>x.actorId)).size!==d.recipients.length)throw new UpdatesError('Engagement could not be verified.');pageCursor(d.nextCursor,q,actorId,d.recipients.length,d.recipients.at(-1)?.actorId,'',d.role);const a=await recheck(client,q,actorId,[],d.role);if(d.nextCursor&&(d.nextCursor.scope.postRevision!==a.postRevision||d.nextCursor.scope.contentRevision!==a.contentRevision))throw new UpdatesError('Update changed. Refresh engagement.',403);return {...d,nextCursor:encode(d.nextCursor)};}
export async function saveUpdate(client:SupabaseClient,input:z.infer<typeof updatesMutation>):Promise<UpdatesSaved>{await signed(client);const{data,error}=await client.rpc('save_update',{target_tenant:input.tenantId,operation_id:input.operationId,change:input.change});fail(error);const p=savedSchema.safeParse(data);if(!p.success)throw new UpdatesError('The save acknowledgement could not be verified. Refresh and review.');const s=p.data,c=input.change;const life=['create','edit','publish','archive','restore'].includes(c.action),expectedContent=c.action==='create'||c.action==='edit'?0:1;if(s.operationId!==input.operationId||s.action!==c.action||'postId'in c&&s.postId!==c.postId||s.contentRevision!==expectedContent||life&&s.revision!==(c.action==='create'?1:'revision'in c?c.revision+1:0)||['comment','edit_comment','remove_comment'].includes(c.action)&&(!s.commentId||s.commentRevision!==(c.action==='comment'?1:'revision'in c?c.revision+1:0))||'commentId'in c&&s.commentId!==c.commentId||!['comment','edit_comment','remove_comment'].includes(c.action)&&(s.commentId!==undefined||s.commentRevision!==undefined))throw new UpdatesError('The save acknowledgement could not be verified. Refresh and review.');return s;}
