import {z} from 'zod';
import type {SupabaseClient} from '@supabase/supabase-js';
import {csvCell} from './csv';
const uuid=z.uuid().transform(v=>v.toLowerCase());
const status=z.enum(['all','viewed','unviewed','confirmed','unconfirmed']);
const postStatus=z.enum(['draft','published','archived']);
const revision=z.number().int().min(1).max(2147483647);
const safeCount=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER);
const utc=z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$/).refine(v=>z.iso.datetime().safeParse(v).success);
const recipient=z.object({actorId:uuid,name:z.string().min(1).max(200).refine(v=>Array.from(v).length<=100),viewedAt:utc.nullable(),confirmedAt:utc.nullable()}).strict().refine(r=>!r.confirmedAt||!!r.viewedAt);
const dataSchema=z.object({tenantId:uuid,actorId:uuid,role:z.enum(['owner','admin']),postId:uuid,postStatus,postRevision:revision,contentRevision:z.number().int().min(0).max(1),requireConfirmation:z.boolean(),status,
 counts:z.object({total:safeCount,viewed:safeCount,confirmed:safeCount}).strict().refine(c=>c.confirmed<=c.viewed&&c.viewed<=c.total),matchedCount:safeCount,recipients:z.array(recipient).max(500)}).strict();
export type UpdatesExportQuery={tenantId:string;postId:string;status:z.infer<typeof status>};
export type UpdatesExportData=z.infer<typeof dataSchema>;
export class UpdatesExportError extends Error{status:number;constructor(message:string,status=503){super(message);this.status=status;}}
export const UPDATES_EXPORT_MAX_BYTES=1048576;
export function parseUpdatesExportQuery(p:URLSearchParams,id:string):UpdatesExportQuery{if([...p.keys()].some(k=>p.getAll(k).length!==1))throw new UpdatesExportError('Choose a valid recipient export scope.',400);const parsed=z.object({tenantId:uuid,status:status.optional()}).strict().safeParse(Object.fromEntries(p));const post=uuid.safeParse(id);if(!parsed.success||!post.success)throw new UpdatesExportError('Choose a valid recipient export scope.',400);return{tenantId:parsed.data.tenantId,postId:post.data,status:parsed.data.status??'all'};}
function databaseError(error:{code?:string}){return new UpdatesExportError(error.code==='42501'?'Company or update access is unavailable.':error.code==='22023'?'Choose a valid recipient export scope.':error.code==='54000'?'The recipient export exceeds the supported size.':'Recipient export could not be loaded. Try again.',error.code==='42501'?403:error.code==='22023'?400:error.code==='54000'?413:503);}
function validate(value:unknown):UpdatesExportData{const p=dataSchema.safeParse(value);if(!p.success)throw new UpdatesExportError('Recipient export could not be verified. Try again.');const d=p.data;if(d.counts.total>500||d.matchedCount>500)throw new UpdatesExportError('The recipient export exceeds the supported size.',413);
 const expected=d.status==='all'?d.counts.total:d.status==='viewed'?d.counts.viewed:d.status==='unviewed'?d.counts.total-d.counts.viewed:d.status==='confirmed'?d.counts.confirmed:d.counts.total-d.counts.confirmed;
 if(d.status==='viewed'&&d.recipients.filter(r=>r.confirmedAt).length!==d.counts.confirmed||d.status==='unconfirmed'&&d.recipients.filter(r=>r.viewedAt).length!==d.counts.viewed-d.counts.confirmed||d.matchedCount!==expected||d.recipients.length!==d.matchedCount||d.postStatus==='draft'&&(d.contentRevision!==0||d.counts.viewed!==0||d.counts.confirmed!==0)||d.postStatus!=='draft'&&d.contentRevision!==1||!d.requireConfirmation&&d.counts.confirmed!==0||d.recipients.some((r,i)=>i>0&&r.actorId<=d.recipients[i-1].actorId||d.status==='viewed'&&!r.viewedAt||d.status==='unviewed'&&r.viewedAt!==null||d.status==='confirmed'&&!r.confirmedAt||d.status==='unconfirmed'&&r.confirmedAt!==null||!d.requireConfirmation&&r.confirmedAt!==null)||d.status==='all'&&(d.recipients.filter(r=>r.viewedAt).length!==d.counts.viewed||d.recipients.filter(r=>r.confirmedAt).length!==d.counts.confirmed))throw new UpdatesExportError('Incomplete or inconsistent recipient export refused.');return d;}
const accessSchema=z.object({actorId:uuid,role:z.enum(['owner','admin','manager','employee']),postStatus:postStatus.nullable(),postRevision:revision.nullable(),contentRevision:z.number().int().min(0).max(1).nullable(),isRecipient:z.boolean(),posts:z.array(z.object({id:uuid,status:postStatus,revision,contentRevision:z.number().int().min(0).max(1),isRecipient:z.boolean()}).strict()).max(100)}).strict();
export async function readUpdatesExport(client:SupabaseClient,q:UpdatesExportQuery):Promise<UpdatesExportData>{const{data:{user},error:authError}=await client.auth.getUser();if(authError||!user)throw new UpdatesExportError('Sign in to export recipient engagement.',401);
 const{data,error}=await client.rpc('read_update_recipients_export',{target_tenant:q.tenantId,target_post:q.postId,status_filter:q.status});if(error)throw databaseError(error);const d=validate(data);if(d.tenantId!==q.tenantId||d.actorId!==user.id||d.postId!==q.postId||d.status!==q.status)throw new UpdatesExportError('Recipient export scope could not be verified.');
 const{data:current,error:checkError}=await client.rpc('read_updates_access',{target_tenant:q.tenantId,target_post:q.postId,target_posts:[]});if(checkError)throw databaseError(checkError);const p=accessSchema.safeParse(current);if(!p.success)throw new UpdatesExportError('Recipient export access could not be verified.');const a=p.data;if(a.actorId!==user.id||a.role!==d.role||!['owner','admin'].includes(a.role)||a.postStatus===null)throw new UpdatesExportError('Company or update access changed. Refresh and try again.',403);if(a.postStatus!==d.postStatus||a.postRevision!==d.postRevision||a.contentRevision!==d.contentRevision)throw new UpdatesExportError('The update changed. Refresh engagement before exporting.',409);return d;}
export function updatesExportCSV(value:UpdatesExportData){const d=validate(value);const rows=[['User name','User ID','Viewed','Viewed at (UTC)','Confirmed','Confirmed at (UTC)'],...d.recipients.map(r=>[r.name,r.actorId,r.viewedAt?'Yes':'No',r.viewedAt??'',d.requireConfirmation?(r.confirmedAt?'Yes':'No'):'Not required',r.confirmedAt??''])];const csv='\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n')+'\r\n';if(new TextEncoder().encode(csv).length>UPDATES_EXPORT_MAX_BYTES)throw new UpdatesExportError('The recipient export exceeds the supported size.',413);return csv;}
