import test from 'node:test';import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,n){return c.parentURL?.includes('/lib/')&&s.startsWith('./')&&!s.endsWith('.ts')?n(new URL(s+'.ts',c.parentURL).href,c):n(s,c);}});
const {directoryMutationSchema,directoryCatalogueSchema,directorySavedSchema,directoryReconciliationSchema}=await import('../../lib/directory-validation.ts');
const {readDirectoryBody,readDirectoryCatalogue,saveDirectory}=await import('../../lib/directory.ts');
const t='d1000000-0000-4000-8000-000000000001',a='00000000-0000-4000-8000-000000980950',op='d6000000-0000-4000-8000-000000000001';
const access={schemaVersion:1,company:{id:t,name:'Harbor Services',time_zone:'UTC'},actorId:a,role:'owner',canManage:true,active:true,viewRevision:1};
const catalogue={...access,search:'',contacts:[],page:{total:0,nextCursor:null}};
const create={tenantId:t,operationId:op,change:{action:'create',directory_revision:1,name:'Kira Stone',description:'',phone:'',email:''}};
test('strict unions allow optional plain channels and canonical Unicode edges',()=>{const v=directoryMutationSchema.parse({...create,change:{...create.change,name:'\u00a0Kira\u3000',phone:'not E164',email:'local internal string'}});assert.equal(v.change.name,'Kira');assert.equal(v.change.phone,'not E164');assert.equal(directoryMutationSchema.safeParse({...create,actorId:a}).success,false);assert.equal(directoryMutationSchema.safeParse({...create,change:{...create.change,url:'https://x.test'}}).success,false);});
test('raw UTF16 bound, malformed surrogate and C0/C1 reject before trim',()=>{for(const name of [' '.repeat(100)+'Kira','😀'.repeat(51),'\ud800','Kira\u0085Stone','\tKira','\u00a0'])assert.equal(directoryMutationSchema.safeParse({...create,change:{...create.change,name}}).success,false);assert.equal(directoryMutationSchema.safeParse({...create,change:{...create.change,name:'😀'.repeat(50)}}).success,true);});
test('activation0 and visibility exact optimistic fence',()=>{assert.equal(directoryMutationSchema.safeParse({tenantId:t,operationId:op,change:{action:'activate',directory_revision:0}}).success,true);for(const revision of [-1,2147483647,1.1])assert.equal(directoryMutationSchema.safeParse({...create,change:{...create.change,directory_revision:revision}}).success,false);});
test('deep hidden-row privacy and role discriminator',()=>{const row={id:op,name:'Kira',description:'',phone:'',email:'',visible_in_app:false,revision:1,created_at:'2026-10-04T09:00:00.000001Z',updated_at:'2026-10-04T09:00:00.000001Z'};assert.equal(directoryCatalogueSchema.safeParse({...catalogue,role:'admin',canManage:false,contacts:[row],page:{total:1,nextCursor:null}}).success,false);assert.equal(directoryCatalogueSchema.safeParse({...catalogue,role:'admin'}).success,false);assert.equal(directoryCatalogueSchema.safeParse({...catalogue,contacts:[row,row],page:{total:2,nextCursor:null}}).success,false);});
test('ACK/recovery action identity and closed absence coherence',()=>{const s={schemaVersion:1,tenantId:t,actorId:a,operationId:op,action:'create',directory_revision:2,contact_id:op,contact_revision:1,active:true};assert.equal(directorySavedSchema.safeParse(s).success,true);assert.equal(directorySavedSchema.safeParse({...s,action:'activate'}).success,false);assert.equal(directoryReconciliationSchema.safeParse({schemaVersion:1,tenantId:t,actorId:a,operationId:op,action:'create',contactId:null,status:'recorded',saved:s}).success,true);assert.equal(directoryReconciliationSchema.safeParse({schemaVersion:1,tenantId:t,actorId:a,operationId:op,action:'visibility',contactId:op,status:'recorded',saved:s}).success,false);});
test('bounded actual64KiB stream, duplicate decoded keys and fatal UTF8',async()=>{const raw='{"name":"x"}'+ ' '.repeat(65536-12);await readDirectoryBody(new Request('http://localhost',{method:'POST',body:raw}));await assert.rejects(readDirectoryBody(new Request('http://localhost',{method:'POST',body:raw+' '})),e=>e.status===413);await assert.rejects(readDirectoryBody(new Request('http://localhost',{method:'POST',body:'{"name":1,"\\u006eame":2}'})),e=>e.status===400);await assert.rejects(readDirectoryBody(new Request('http://localhost',{method:'POST',body:new Uint8Array([0xff])})),e=>e.status===400);});
function mock(responses){return {auth:{getUser:async()=>({data:{user:{id:a,is_anonymous:false}},error:null})},rpc:async()=>responses.shift()??assert.fail('Unexpected RPC')};}
test('owner reread demotion wins over stale/malformed/error paths',async()=>{const member={...access,role:'employee',canManage:false};for(const next of [{data:{...catalogue,viewRevision:2},error:null},{data:{broken:true},error:null},{data:null,error:{code:'40001'}}])await assert.rejects(readDirectoryCatalogue(mock([{data:access,error:null},{data:catalogue,error:null},next,{data:member,error:null}]),{tenantId:t}),e=>e.status===403);});
test('owner cursor demotion403 before stale SQL response',async()=>{const cursor=Buffer.from(JSON.stringify({scope:{tenantId:t,actorId:a,role:'owner',viewRevision:1,search:''},position:100})).toString('base64');await assert.rejects(readDirectoryCatalogue(mock([{data:{...access,role:'employee',canManage:false},error:null}]),{tenantId:t,cursor}),e=>e.status===403);});
test('coherent requested page cardinality and fresh scope',async()=>{const responses=[{data:access,error:null},{data:catalogue,error:null},{data:catalogue,error:null},{data:access,error:null}];assert.deepEqual(await readDirectoryCatalogue(mock(responses),{tenantId:t}),catalogue);const wrong={...catalogue,page:{total:1,nextCursor:null}};await assert.rejects(readDirectoryCatalogue(mock([{data:access,error:null},{data:wrong,error:null},{data:wrong,error:null},{data:access,error:null}]),{tenantId:t}),e=>e.status===503);});
test('save current-role proof precedes held successful ACK and exact revision',async()=>{const saved={schemaVersion:1,tenantId:t,actorId:a,operationId:op,action:'create',directory_revision:2,contact_id:op,contact_revision:1,active:true};await assert.rejects(saveDirectory(mock([{data:access,error:null},{data:saved,error:null},{data:{...access,viewRevision:2,role:'admin',canManage:false},error:null}]),create),e=>e.status===403);await assert.rejects(saveDirectory(mock([{data:access,error:null},{data:{...saved,contact_revision:2},error:null},{data:{...access,viewRevision:2},error:null}]),create),e=>e.status===503);});
test('100 maximal escaped/Unicode contact rows fit bounded response without truncation',()=>{const contacts=Array.from({length:100},(_,i)=>({id:`d7000000-0000-4000-8000-${String(i).padStart(12,'0')}`,name:'"'.repeat(100),description:'\\'.repeat(1000),phone:'"'.repeat(64),email:'😀'.repeat(127),visible_in_app:true,revision:2147483647,created_at:'2026-10-04T09:00:00.000001Z',updated_at:'2026-10-04T09:00:00.000001Z'}));const data={...catalogue,contacts,page:{total:100,nextCursor:null}};assert.equal(directoryCatalogueSchema.safeParse(data).success,true);assert.ok(Buffer.byteLength(JSON.stringify({data}))<1048576);});
test('cursor canonical base64 and decoded duplicate properties reject before SQL',async()=>{for(const cursor of [' '+Buffer.from('{}').toString('base64'),Buffer.from('{"scope":{},"scope":{},"position":1}').toString('base64')])await assert.rejects(readDirectoryCatalogue(mock([]),{tenantId:t,cursor}),e=>e.status===400);});

test('oldactor cursor403 clears protected scope; foreigncompany remains malformed400',async()=>{for(const[field,value,status]of [['actorId',op,403],['tenantId',op,400]]){const cursor=Buffer.from(JSON.stringify({scope:{tenantId:t,actorId:a,role:'owner',viewRevision:1,search:'',[field]:value},position:100})).toString('base64');await assert.rejects(readDirectoryCatalogue(mock([]),{tenantId:t,cursor}),e=>e.status===status);}});
