import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {spawnSync} from 'node:child_process';
registerHooks({resolve(s,c,n){return c.parentURL?.endsWith('/lib/forms-xlsx.ts')&&s==='./forms-reporting-types'?n(new URL('./forms-reporting-types.ts',c.parentURL).href,c):n(s,c);}});
const {formsReportWorkbook}=await import('../../lib/forms-xlsx.ts');
const id=n=>`88000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const instant='2026-10-04T01:02:03.123456Z';
const fields=[{id:id(5),kind:'text',label:'Text',required:false},{id:id(6),kind:'number',label:'Exact decimal',required:false},{id:id(7),kind:'yes_no',label:'Boolean',required:false},{id:id(8),kind:'single_choice',label:'Choice',required:false,options:[{id:id(9),label:'Retained <label>'}]},{id:id(10),kind:'multiple_choice',label:'Multiple',required:false,options:[{id:id(11),label:'Comma, label'},{id:id(12),label:'"Quoted" 😀'}]},{id:id(13),kind:'description',text:'No statistics column'}];
const base={tenantId:id(1),actorId:id(2),role:'owner',company:{id:id(1),name:'Synthetic company',time_zone:'America/Havana'},form:{id:id(3),name:'Current title',revision:2},filters:{from:null,to:null,review:'all',search:'',submission:'all',fieldId:null,fieldAnswer:'all'},collectionVersion:'a'.repeat(32),serverTime:instant};
const response={id:id(4),formId:id(3),actorId:id(2),authorName:'Original author',formName:'Original title',revision:1,status:'submitted',submittedAt:instant,updatedAt:instant,lastEditedBy:id(2),lastEditorName:'Editor',lastEditedAt:instant,reviewed:false,reviewedAt:null,reviewedBy:null,reviewerName:null,canEdit:false,canReview:true,answers:{[id(5)]:'Text',[id(6)]:'+123456789012.123456',[id(7)]:false,[id(8)]:id(9),[id(10)]:[id(11),id(12)]}};
const entries=(responses=[response])=>({...base,kind:'entries',schema:fields,responses,counts:{total:responses.length,reviewed:0,notReviewed:responses.length}});
// Python standard-library ZIP and XML readers are independent of the writer.
// openpyxl additionally verifies that a real spreadsheet reader can open it.
const python=String.raw`import sys,base64,io,zipfile,json,xml.etree.ElementTree as ET,posixpath
import importlib.util
b=base64.b64decode(sys.stdin.read()); z=zipfile.ZipFile(io.BytesIO(b)); assert z.testzip() is None
ns={'s':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
rows={}; relationships={}
for name in z.namelist():
 root=ET.fromstring(z.read(name))
 if name.endswith('.rels'):
  relationships[name]=[dict(e.attrib) for e in root]
 if name.startswith('xl/worksheets/'):
  rows[name]=[[{'type':c.attrib.get('t'), 'value': ''.join(c.find('s:is',ns).itertext()) if c.attrib.get('t')=='inlineStr' else c.find('s:v',ns).text} for c in row] for row in root.findall('s:sheetData/s:row',ns)]
workbook=ET.fromstring(z.read('xl/workbook.xml')); sheets=[s.attrib['name'] for s in workbook.findall('s:sheets/s:sheet',ns)]
reader=False; readerRow=[]
if importlib.util.find_spec('openpyxl'):
 from openpyxl import load_workbook
 w=load_workbook(io.BytesIO(b),read_only=True,data_only=False); assert w.sheetnames==sheets; reader=True
 readerRows=list(w.worksheets[1].iter_rows(max_row=2)); readerRow=[{'value':c.value,'type':c.data_type} for c in readerRows[1]] if len(readerRows)>1 else []
print(json.dumps({'names':z.namelist(),'rows':rows,'relationships':relationships,'sheets':sheets,'reader':reader,'readerRow':readerRow,'xml':{n:z.read(n).decode() for n in z.namelist()}},ensure_ascii=True))`;
function parse(bytes){const p=spawnSync('python3',['-c',python],{input:Buffer.from(bytes).toString('base64'),encoding:'utf8',maxBuffer:32*1024*1024});assert.equal(p.status,0,p.stderr);return JSON.parse(p.stdout);}
const decode=s=>s.replace(/_x([0-9a-f]{4})_/gi,(_,h)=>String.fromCharCode(parseInt(h,16)));
function values(p,sheet,row){return p.rows[`xl/worksheets/sheet${sheet}.xml`][row].map(c=>c.type==='inlineStr'?decode(c.value):Number(c.value));}
function crc(bytes){let c=0xffffffff;for(const byte of bytes){c^=byte;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function verifyZIP(bytes){const b=Buffer.from(bytes),end=b.length-22;assert.equal(b.readUInt32LE(end),0x06054b50);assert.equal(b.readUInt16LE(end+20),0);let at=b.readUInt32LE(end+16);const count=b.readUInt16LE(end+10);assert.equal(count,6);assert.equal(at+b.readUInt32LE(end+12),end);const seen=new Set();for(let i=0;i<count;i++){assert.equal(b.readUInt32LE(at),0x02014b50);assert.equal(b.readUInt16LE(at+10),0);const size=b.readUInt32LE(at+24),len=b.readUInt16LE(at+28),extra=b.readUInt16LE(at+30),comment=b.readUInt16LE(at+32),local=b.readUInt32LE(at+42),name=b.subarray(at+46,at+46+len).toString();assert(!seen.has(name));seen.add(name);assert.equal(b.readUInt32LE(local),0x04034b50);assert.equal(b.readUInt16LE(local+8),0);assert.equal(b.readUInt32LE(local+18),size);assert.equal(b.readUInt32LE(local+22),size);const localLen=b.readUInt16LE(local+26);assert.equal(b.subarray(local+30,local+30+localLen).toString(),name);const payload=b.subarray(local+30+localLen+b.readUInt16LE(local+28),local+30+localLen+b.readUInt16LE(local+28)+size);assert.equal(crc(payload),b.readUInt32LE(at+16));assert.equal(b.readUInt32LE(local+14),b.readUInt32LE(at+16));at+=46+len+extra+comment;}assert.equal(at,end);}
test('Genuine OOXML package opens independently, CRC/local/central records agree and relationships are internal',()=>{const bytes=formsReportWorkbook(entries());verifyZIP(bytes);const p=parse(bytes);assert.deepEqual(p.sheets,['Report','Submissions']);assert.deepEqual(p.names.sort(),['[Content_Types].xml','_rels/.rels','xl/_rels/workbook.xml.rels','xl/workbook.xml','xl/worksheets/sheet1.xml','xl/worksheets/sheet2.xml'].sort());assert.equal(p.relationships['_rels/.rels'][0].Target,'xl/workbook.xml');assert.deepEqual(p.relationships['xl/_rels/workbook.xml.rels'].map(r=>r.Target),['worksheets/sheet1.xml','worksheets/sheet2.xml']);for(const xml of Object.values(p.xml)){assert(!/<(?:\w+:)?f(?:\s|>)/.test(xml));assert(!/TargetMode="External"|<hyperlink|vbaProject|<!DOCTYPE|<!ENTITY/.test(xml));}});
test('Full rows retain decimal/microsecond precision, false, historic labels and omit description columns',()=>{const p=parse(formsReportWorkbook(entries()));const v=values(p,2,1);assert.equal(v[3],'Original title');assert.equal(v[4],instant);assert.equal(v[7],instant);assert.equal(v[13],'+123456789012.123456');assert.equal(v[14],'No');assert.equal(v[15],'Retained <label>');assert.deepEqual(JSON.parse(v[16]),['Comma, label','"Quoted" 😀']);assert.equal(v.length,17);assert(!values(p,2,0).includes('No statistics column'));assert.equal(p.rows['xl/worksheets/sheet2.xml'][1][13].type,'inlineStr');if(p.reader){assert.equal(p.readerRow[13].value,'+123456789012.123456');assert.equal(p.readerRow[13].type,'s');assert.equal(p.readerRow[4].value,instant);}});
test('Unicode, XML controls, CR, literal Excel escapes and formula-shaped text survive without formulas',()=>{const cases=['  😀 e\u0301 İ & < > " \'\t\n\r  ','\u0000\u0001\u000b\u001f\ufffe\uffff','_x000D_ _x005F_ _x00aF_','=_x000A_+SUM(A1:A2)','+123','-123','@SUM(A1)','\ud800\udfff','\ud800x\udfff'];for(const text of cases){const p=parse(formsReportWorkbook(entries([{...response,answers:{...response.answers,[id(5)]:text}}])));assert.equal(values(p,2,1)[12],text);assert.equal(p.rows['xl/worksheets/sheet2.xml'][1][12].type,'inlineStr');}});
test('Complete export is independent of a visible fifty-row page and empty scope remains genuine',()=>{const rows=Array.from({length:1005},(_,i)=>({...response,id:id(100+i),authorName:`User ${i}`}));const p=parse(formsReportWorkbook(entries(rows)));assert.equal(p.rows['xl/worksheets/sheet2.xml'].length,1006);assert.equal(values(p,2,1005)[2],'User 1004');const empty=parse(formsReportWorkbook(entries([])));assert.equal(empty.rows['xl/worksheets/sheet2.xml'].length,1);assert(empty.rows['xl/worksheets/sheet1.xml'].some(row=>row[0].value==='Total submissions'&&row[1].value==='0'));});
test('Status workbook has current assignments, genuine absent response metadata and truthful eligibility',()=>{const p=parse(formsReportWorkbook({...base,kind:'status',users:[{actorId:id(2),name:'Retained',eligible:true,response},{actorId:id(20),name:'Ineligible',eligible:false,response:null}],counts:{total:2,submitted:1,notSubmitted:1,eligible:1,assignmentTotal:2,assignmentEligible:1}}));assert.deepEqual(p.sheets,['Report','Assigned users']);assert.deepEqual(values(p,2,2),[id(20),'Ineligible','No','No','','','','','']);});
test('Complete workbook refuses output and row bounds, never emits truncated valid-looking files',()=>{assert.throws(()=>formsReportWorkbook(entries(Array.from({length:10001},()=>response))),e=>e.status===413);assert.throws(()=>formsReportWorkbook({...base,kind:'status',users:Array.from({length:501},()=>({actorId:id(2),name:'X',eligible:true,response:null})),counts:{total:501,submitted:0,notSubmitted:501,eligible:501,assignmentTotal:501,assignmentEligible:501}}),e=>e.status===413);const huge=Array.from({length:400},(_,i)=>({...response,id:id(100+i),answers:{[id(5)]:'&'.repeat(5000)}}));assert(Buffer.byteLength(JSON.stringify(huge.map(r=>r.answers)))<2097152);assert.throws(()=>formsReportWorkbook(entries(huge)),e=>e.status===413);assert.throws(()=>formsReportWorkbook(entries([{...response,status:'in_progress'}])),e=>e.status===503);});

test('Legal complete workbooks can exceed buffered-host limits while retaining the eight MiB contract',()=>{const rows=Array.from({length:3500},(_,i)=>({...response,id:id(100+i),answers:{...response.answers,[id(5)]:'😀'.repeat(100)}}));const bytes=formsReportWorkbook(entries(rows));assert(bytes.length>4.5*1024*1024);assert(bytes.length<=8*1024*1024);verifyZIP(bytes);});
