import test from 'node:test';import assert from 'node:assert/strict';import{registerHooks}from'node:module';
registerHooks({resolve(specifier,context,next){try{return next(specifier,context);}catch(e){if(specifier.startsWith('.')&&!/\.[a-z]+$/i.test(specifier))return next(specifier+'.ts',context);throw e;}}});
const {knowledgeFileMetadata,knowledgeFileAttemptChange,fileJson,inspectKnowledgeFile,parseKnowledgeFileUpload,boundedBody,fileProofMessage,reconcileKnowledgeFile,readKnowledgeFileBudget,safeFileDisposition}=await import('../../lib/knowledge-base-files.ts');
const tenantId='88000000-0000-4000-8000-000000000001',actorId='00000000-0000-4000-8000-000000000901',baseId='6f000000-0000-4000-8000-000000000001',parentId='6f000000-0000-4000-8000-000000000002',operationId='6f000000-0000-4000-8000-000000000003';
const metadata={tenantId,operationId,baseId,mode:'create',expectedBaseRevision:1,parentId,name:' Exact ',description:'\n',filename:'Synthetic.txt'};
const identity={tenantId,actorId,role:'owner'},serverTime='2026-10-04T01:00:00.123456Z';
const attempt={...identity,operationId,action:'save_file',status:'upload_attempted',attemptRevision:1,deadline:'2026-10-04T01:10:00.123Z',capabilities:{canClose:true,canFinalize:false,canCleanup:false},saved:null,serverTime};
const user={id:actorId,email_confirmed_at:serverTime,is_anonymous:false};
function fixture(responses){const calls=[];return{calls,client:{auth:{getUser:async()=>({data:{user},error:null})},rpc:async(name,args)=>{calls.push({name,args});return responses.shift();}}};}
const reject=(p,status=503)=>assert.rejects(p,e=>e.status===status);
test('strict create/replace UUID/revision/text metadata never accepts privileged or extra fields',()=>{assert.equal(knowledgeFileMetadata.parse(metadata).name,' Exact ');for(const patch of [{providerVersion:operationId},{sha256:'a'.repeat(64)},{proof:'a'.repeat(64)},{filename:'a\r.txt'},{filename:'\ud800.txt'},{filename:'😀'.repeat(128)},{name:'\ufeff'},{expectedBaseRevision:2147483647},{parentId:null},{mode:'replace'}])assert.equal(knowledgeFileMetadata.safeParse({...metadata,...patch}).success,false,JSON.stringify(patch));assert.equal(knowledgeFileMetadata.safeParse({...metadata,name:'😀'.repeat(50)}).success,true);assert.equal(knowledgeFileAttemptChange.safeParse({tenantId,operationId,expectedAttemptRevision:1,filename:'private'}).success,false);});
test('duplicate JSON and size limits are enforced before strict shape validation',()=>{assert.throws(()=>fileJson('{"tenantId":"x","tenantId":"y"}'),e=>e.status===400);assert.throws(()=>fileJson(' '.repeat(16385)),e=>e.status===413);assert.deepEqual(fileJson(JSON.stringify(metadata)),metadata);});
test('supported signatures UTF8 aliases and exact raw bytes, unsupported/conflicting types fail',()=>{const text=Buffer.from('Exact\n😀,=SUM(A1)');assert.equal(inspectKnowledgeFile(text,'x.csv','application/vnd.ms-excel'),'text/csv');assert.equal(inspectKnowledgeFile(text,'x.txt',''),'text/plain');assert.equal(inspectKnowledgeFile(Buffer.from('%PDF-1.7\n'),'x.pdf','application/pdf'),'application/pdf');for(const[b,n,t]of [[Buffer.alloc(0),'x.txt',''],[Buffer.from([255]),'x.txt','text/plain'],[Buffer.from('x\0'),'x.txt','text/plain'],[Buffer.from('<html>'),'x.txt',''],[text,'x.txt','text/html'],[text,'x.svg','image/svg+xml']])assert.throws(()=>inspectKnowledgeFile(b,n,t));assert.equal(inspectKnowledgeFile(Buffer.alloc(2097152,65),'x.txt','text/plain'),'text/plain');assert.throws(()=>inspectKnowledgeFile(Buffer.alloc(2097153,65),'x.txt','text/plain'),e=>e.status===413);});
test('multipart only one file and metadata, exact route base and bounded decoded data',async()=>{const form=new FormData();form.set('metadata',JSON.stringify(metadata));form.set('file',new File(['Exact😀'],'ignored-transport-name.txt',{type:'text/plain'}));const value=await parseKnowledgeFileUpload(new Request('http://local',{method:'POST',body:form}),baseId);assert.equal(value.bytes.toString(),'Exact😀');assert.equal(value.metadata.filename,'Synthetic.txt');form.append('file',new File(['other'],'x.txt'));await reject(parseKnowledgeFileUpload(new Request('http://local',{method:'POST',body:form}),baseId),400);});
test('stream limits stop chunked and misleading content-length bodies',async()=>{await reject(boundedBody(new Response(new Uint8Array(17)),16),413);await reject(boundedBody(new Response('x',{headers:{'content-length':'17'}}),16),413);assert.equal((await boundedBody(new Response('abc'),3)).toString(),'abc');});
test('proof encoding binds stage exact identity/hash/provider version/deadline with UTF8 length prefixes',()=>{const a={...attempt,baseId,nodeId:parentId,attemptId:operationId,path:[tenantId,baseId,parentId,operationId].join('/'),bytes:8,sha256:'a'.repeat(64),mediaType:'text/plain',providerId:parentId,providerVersion:baseId};const first=fileProofMessage(a,'upload-v1','fixture-v1');assert.notEqual(first,fileProofMessage({...a,actorId:parentId},'upload-v1','fixture-v1'));assert.notEqual(fileProofMessage(a,'finalize-v1','fixture-v1',1),fileProofMessage({...a,providerVersion:operationId},'finalize-v1','fixture-v1',1));assert.notEqual(first,fileProofMessage(a,'provider-success-v1','fixture-v1',1));});
test('field-free recovery rechecks current scope/state and refuses malformed or revoked reads',async()=>{const f=fixture([{data:attempt,error:null},{data:attempt,error:null}]);assert.deepEqual(await reconcileKnowledgeFile(f.client,{tenantId,operationId}),attempt);assert.equal(f.calls.length,2);for(const patch of [{filename:'private'},{actorId:parentId},{status:'finalized'},{attemptRevision:null},{capabilities:{canClose:true,canFinalize:true,canCleanup:false}}]){const f=fixture([{data:attempt,error:null},{data:{...attempt,...patch},error:null}]);await reject(reconcileKnowledgeFile(f.client,{tenantId,operationId}));}const revoked=fixture([{data:attempt,error:null},{data:null,error:{code:'42501'}}]);await reject(reconcileKnowledgeFile(revoked.client,{tenantId,operationId}),403);});
test('budget has exact safe state counts and reports company-only lifetime allocation',async()=>{const b={...identity,allocatedBytes:8,allocatedAttempts:1,byteLimit:104857600,globalAttemptLimit:4096,companyAttemptLimit:2048,states:{upload_attempted:1,uploaded_unverified:0,provider_succeeded:0,finalized:0,closed:0,cleanup_acknowledged:0},serverTime};const f=fixture([{data:b,error:null},{data:b,error:null}]);assert.deepEqual(await readKnowledgeFileBudget(f.client,tenantId),b);for(const patch of [{states:{}},{allocatedAttempts:2},{allocatedBytes:104857601},{allocatedAttempts:1.5},{tenantId:parentId},{states:{...b.states,closed:-1}}]){const f=fixture([{data:b,error:null},{data:{...b,...patch},error:null}]);await reject(readKnowledgeFileBudget(f.client,tenantId));}});
test('attachment names are bounded normalized and Unicode encoded without injection',()=>{const d=safeFileDisposition('😀 report.csv');assert.match(d,/attachment;/);assert.match(d,/filename\*=UTF-8''%F0%9F%98%80/);assert.ok(!safeFileDisposition('";evil.txt').includes('filename="";evil'));});
