import test from 'node:test';
import assert from 'node:assert/strict';
import {parseKnowledgeBasesQuery,parseKnowledgeNodesQuery,knowledgeMutation,knowledgeReconciliation,knowledgePayloadFits,knowledgeSemanticBytes,knowledgeStringValid,knowledgeLinkValid,readKnowledgeBases,readKnowledgeNode,reconcileKnowledgeView,saveKnowledgeBase} from '../../lib/knowledge-base.ts';
const tenantId='88000000-0000-4000-8000-000000000001',actorId='00000000-0000-4000-8000-000000000901',baseId='66000000-0000-4000-8000-000000000001',nodeId='66000000-0000-4000-8000-000000000002',operationId='66000000-0000-4000-8000-000000000003';
const identity={tenantId,actorId,role:'owner',view:'manage'},company={id:tenantId,name:'Synthetic',time_zone:'America/Havana'},serverTime='2026-10-04T00:00:00.123456Z',version='a'.repeat(32),scope={...identity,baseId,baseRevision:1,audienceVersion:version,treeVersion:version};
const base={id:baseId,name:'Exact name',description:'',status:'draft',restoreStatus:null,revision:1,audienceCount:0,eligibleAudienceCount:0,isAssigned:false,canRead:false,canEdit:true,canPublish:false,canArchive:true,canRestore:false};
const catalog={...identity,company,bases:[base],counts:{total:1,draft:1,published:0,archived:0},catalogVersion:version,nextCursor:null,serverTime,capabilities:{canManage:true}};
const access={...identity,timeZone:company.time_zone,catalogVersion:version,rosterVersion:version,baseRevision:null,baseStatus:null,audienceVersion:null,treeVersion:null,eventVersion:null,nodeRevision:null,nodeStatus:null,bases:[{id:baseId,revision:1,status:'draft',audienceVersion:version}]};
const node={id:nodeId,baseId,parentId:baseId,kind:'text',name:'Text',description:'',status:'active',revision:1,depth:2,rank:'9223372036854775807',activeChildCount:0,canEdit:true,canMove:true,canMoveEarlier:false,canMoveLater:false,canArchive:true,canRestore:false};
const detail={...scope,base,node,path:[{id:baseId,name:'Folder',status:'active',revision:1}],body:' \nExact\t😀',url:null,serverTime};
function fixture(data=catalog,current=access,error=null){const calls=[];return{calls,client:{auth:{getUser:async()=>({data:{user:{id:actorId}},error:null})},rpc:async(name,args)=>{calls.push({name,args});return{name,data:name==='read_knowledge_base_access'?current:data,error};}}};}
const reject=(p,status=503)=>assert.rejects(p,e=>e.status===status);
test('KB singular strict bounded literal filters and root defaults',()=>{assert.deepEqual(parseKnowledgeBasesQuery(new URLSearchParams({tenantId})),{tenantId,view:'auto',status:'all',search:'',limit:50});assert.equal(parseKnowledgeNodesQuery(new URLSearchParams({tenantId,search:'%_\\ İ'}),baseId).search,'%_\\ İ');for(const patch of [{limit:'101'},{view:'all'},{search:'😀'.repeat(51)},{cursor:'='},{unknown:'x'}])assert.throws(()=>parseKnowledgeBasesQuery(new URLSearchParams({tenantId,...patch})),e=>e.status===400);assert.throws(()=>parseKnowledgeBasesQuery(new URLSearchParams(`tenantId=${tenantId}&status=all&status=all`)));});
test('Exact Unicode whitespace and typed content shapes, no implicit trim or NUL/surrogates',()=>{const change={action:'create_base',name:' Exact ',description:'\n',audienceIds:[]};assert.equal(knowledgeMutation.parse({tenantId,operationId,change}).change.name,' Exact ');for(const name of ['\t','\r','\u00a0','\ufeff','😀'.repeat(51),'\ud800','\u0000'])assert.equal(knowledgeMutation.safeParse({tenantId,operationId,change:{...change,name}}).success,false);assert.equal(knowledgeStringValid('😀\v\f\r'),true);const v={action:'create_node',baseId,revision:1,parentId:nodeId,kind:'text',name:'Text',description:'',body:' '.repeat(50000)};assert.equal(knowledgeMutation.safeParse({tenantId,operationId,change:v}).success,true);for(const patch of [{body:'x'.repeat(50001)},{body:''},{url:'https://example.test'},{kind:'folder'}])assert.equal(knowledgeMutation.safeParse({tenantId,operationId,change:{...v,...patch}}).success,false);});
test('Separate exact raw transport and deterministic semantic byte budgets',()=>{assert.equal(knowledgeSemanticBytes({a:'😀',b:[null]}),64+4+32+16);const change={action:'create_node',baseId,revision:1,parentId:nodeId,kind:'text',name:'Text',description:'',body:'\u0001'.repeat(50000)},v={tenantId,operationId,change};assert.equal(knowledgeMutation.safeParse(v).success,true);assert.equal(knowledgePayloadFits(v),false);assert.equal(knowledgePayloadFits({...v,change:{...change,body:'😀'.repeat(25000)}}),true);});
test('One signed stable read then fresh current resource check without write',async()=>{const f=fixture();assert.equal((await readKnowledgeBases(f.client,{tenantId,view:'auto',status:'all',search:'',limit:50})).bases[0].name,base.name);assert.deepEqual(f.calls.map(x=>x.name),['read_knowledge_base','read_knowledge_base_access']);assert.deepEqual(f.calls[1].args.target_bases,[baseId]);});
test('Exact missing/unsafe/fractional counts and foreign/private fields fail closed',async()=>{for(const patch of [{counts:{}},{counts:{total:2,draft:1,published:0,archived:0}},{counts:{total:1.5,draft:1.5,published:0,archived:0}},{counts:{total:Number.MAX_SAFE_INTEGER+1,draft:Number.MAX_SAFE_INTEGER+1,published:0,archived:0}},{actorId:baseId},{tenantId:baseId},{privateNote:'private'},{bases:[base,base]}])await reject(readKnowledgeBases(fixture({...catalog,...patch}).client,{tenantId,view:'auto',status:'all',search:'',limit:50}));});
test('Failed/currently revoked read and changed hierarchy/role/calendar never become zeros',async()=>{const q={tenantId,view:'auto',status:'all',search:'',limit:50};await reject(readKnowledgeBases(fixture(catalog,access,{code:'42501'}).client,q),403);for(const patch of [{actorId:baseId},{role:'admin'}])await reject(readKnowledgeBases(fixture(catalog,{...access,...patch}).client,q),403);for(const patch of [{catalogVersion:'b'.repeat(32)},{bases:[]},{timeZone:'UTC'}])await reject(readKnowledgeBases(fixture(catalog,{...access,...patch}).client,q),409);await reject(readKnowledgeBases(fixture(catalog,{...access,timeZone:'Factory'}).client,q));});
test('Exact node body/rank, ancestor identity and fresh node revision bound',async()=>{const a={...access,baseRevision:1,baseStatus:'draft',audienceVersion:version,treeVersion:version,nodeRevision:1,nodeStatus:'active',bases:[]};const q={tenantId,baseId,nodeId,view:'manage'};assert.equal((await readKnowledgeNode(fixture(detail,a).client,q)).body,detail.body);for(const patch of [{path:[]},{node:{...node,baseId:nodeId}},{body:null},{node:{...node,rank:'9223372036854775808'}},{path:[...detail.path,...detail.path]}])await reject(readKnowledgeNode(fixture({...detail,...patch},a).client,q));await reject(readKnowledgeNode(fixture(detail,{...a,nodeRevision:2}).client,q),409);});
test('Field-free view recovery repeats resource-scoped check and fails revocation in second read',async()=>{const d={tenantId,actorId,role:'owner',operationId,status:'recorded'},f=fixture(d);assert.deepEqual(await reconcileKnowledgeView(f.client,{tenantId,operationId}),d);assert.deepEqual(f.calls.map(x=>x.name),['reconcile_knowledge_view','reconcile_knowledge_view']);assert.equal(knowledgeReconciliation.safeParse({tenantId,operationId,nodeId}).success,false);let calls=0;f.client.rpc=async()=>++calls===1?{data:d,error:null}:{data:null,error:{code:'42501'}};await reject(reconcileKnowledgeView(f.client,{tenantId,operationId}),403);});
test('UUID payload acknowledgement exact revision/action/event shape',async()=>{const change={action:'create_base',name:'Base',description:'',audienceIds:[]},input={tenantId,operationId,change},saved={operationId,action:change.action,baseId,revision:1};assert.deepEqual(await saveKnowledgeBase(fixture(saved).client,input),saved);for(const patch of [{revision:2},{action:'view'},{eventId:nodeId},{operationId:nodeId}])await reject(saveKnowledgeBase(fixture({...saved,...patch}).client,input));});

test('Conservative parsed URL grammar matches direct SQL authority and exact tails',()=>{for(const v of ['https://example.test/path?q=😀%20x#section','http://localhost:8080/guide','http://127.0.0.1:65535/'])assert.equal(knowledgeLinkValid(v),true,v);for(const v of ['https://[bad]','https://[::1]/','https://example.com\\evil','https://user:password@example.test','https://%65xample.test','https://xn--a/','https://example.0xdeadbeef','https://example.0x','https://example.123','https://256.0.0.1/','https://127.00.0.1/','https://example.test:65536/','https://example.test:0/','https://example.test/bad%ZZ','https://example.test/\u00a0'])assert.equal(knowledgeLinkValid(v),false,v);});
test('Opaque Turkish SQL keyset binds every query/version and exact1005 count without JS case-folding',async()=>{const cursor={scope:{...identity,kind:'catalog',baseId:null,nodeId:null,parentId:null,status:'all',search:'',catalogVersion:version,baseRevision:null,audienceVersion:null,treeVersion:null,rosterVersion:null,eventVersion:null,timeZone:company.time_zone},id:baseId,position:'i'},d={...catalog,bases:[{...base,name:'İ'}],counts:{total:1005,draft:1005,published:0,archived:0},nextCursor:cursor},q={tenantId,view:'auto',status:'all',search:'',limit:1};const result=await readKnowledgeBases(fixture(d).client,q);assert.equal(JSON.parse(Buffer.from(result.nextCursor,'base64url').toString()).position,'i');for(const patch of [{role:'admin'},{kind:'children'},{catalogVersion:'b'.repeat(32)},{status:'draft'},{search:'other'},{baseId},{actorId:baseId}])await reject(readKnowledgeBases(fixture({...d,nextCursor:{...cursor,scope:{...cursor.scope,...patch}}}).client,q));const other=Buffer.from(JSON.stringify({...cursor,scope:{...cursor.scope,actorId:baseId}})).toString('base64url');const f=fixture(d);await reject(readKnowledgeBases(f.client,{...q,cursor:other}),409);assert.equal(f.calls.length,0);});
