import test from 'node:test';
import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
registerHooks({resolve(s,c,n){return c.parentURL?.includes('/lib/')&&s.startsWith('./')&&!s.endsWith('.ts')?n(new URL(s+'.ts',c.parentURL).href,c):n(s,c);}});
const V=await import('../../lib/rota-period-template-validation.ts');
const id=n=>`a1000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const filters={jobId:null,status:'all',workerSearch:''};
const save={tenantId:id(1),operationId:id(2),change:{action:'save',schedule_id:id(3),schedule_revision:2147483646,kind:'day',title:'Morning coverage',source_anchor:'2026-10-05',source_zone:'UTC',source_filters:filters,source_review_digest:'a'.repeat(64),sources:Array.from({length:5000},(_,i)=>({id:id(i+10),revision:2147483646}))}};
test('complete 5000 highest revision Save fits supported request bound',()=>{assert.equal(V.rotaPeriodMutationSchema.safeParse(save).success,true);assert.ok(Buffer.byteLength(JSON.stringify(save))<=524288);});
test('5000 sparse two-endpoint fold choices fit without truncation',()=>{const change={action:'add',schedule_id:id(3),schedule_revision:2147483646,template_id:id(4),template_revision:2147483646,target_anchor:'2026-11-02',occurrences:Array.from({length:5000},(_,index)=>({index,start:'earlier',end:'later'})),plan_digest:'b'.repeat(64),expected_entry_count:5000,allow_overlap:true};const v={tenantId:id(1),operationId:id(2),change};assert.equal(V.rotaPeriodMutationSchema.safeParse(v).success,true);assert.ok(Buffer.byteLength(JSON.stringify(v))<=524288);});
test('strict Gregorian dates retain year1 and reject normalized or nonexistent dates',()=>{for(const x of ['0001-01-01','2000-02-29','9999-12-31'])assert.equal(V.periodDateValid(x),true);for(const x of ['0000-01-01','1900-02-29','2026-02-30','2026-1-01'])assert.equal(V.periodDateValid(x),false);});
test('Save rejects duplicate selectors, unknown recipe data, malformed Unicode and overflow',()=>{for(const change of [{...save.change,sources:[save.change.sources[0],save.change.sources[0]]},{...save.change,entries:[]},{...save.change,title:'bad\ud800'},{...save.change,schedule_revision:2147483647},{...save.change,title:'x\nname'}])assert.equal(V.rotaPeriodMutationSchema.safeParse({...save,change}).success,false);});
test('sparse occurrences cannot duplicate indexes or escape expected complete batch',()=>{const change={action:'add',schedule_id:id(3),schedule_revision:1,template_id:id(4),template_revision:1,target_anchor:'2026-10-05',occurrences:[{index:1,start:'earlier'}],plan_digest:'a'.repeat(64),expected_entry_count:1,allow_overlap:false};assert.equal(V.rotaPeriodMutationSchema.safeParse({...save,change}).success,false);change.expected_entry_count=2;change.occurrences=[{index:0,start:'earlier'},{index:0,end:'later'}];assert.equal(V.rotaPeriodMutationSchema.safeParse({...save,change}).success,false);});
const saved={schemaVersion:1,tenantId:id(1),actorId:id(2),operationId:id(3),action:'add',template_id:id(4),template_revision:1,schedule_id:id(5),schedule_revision:2,entry_count:5000,generated:Array.from({length:5000},(_,index)=>({index,id:id(index+10),revision:1})),plan_digest:'a'.repeat(64)};
test('complete indexed 5000 ACK bounded; last index and duplicate IDs rejected',()=>{assert.equal(V.rotaPeriodSavedSchema.safeParse(saved).success,true);assert.ok(Buffer.byteLength(JSON.stringify(saved))<=524288);for(const last of [{...saved.generated.at(-1),index:4998},{...saved.generated.at(-1),id:saved.generated[0].id},{...saved.generated.at(-1),revision:2}])assert.equal(V.rotaPeriodSavedSchema.safeParse({...saved,generated:[...saved.generated.slice(0,-1),last]}).success,false);assert.equal(V.rotaPeriodSavedSchema.safeParse({...saved,generated:saved.generated.slice(0,-1)}).success,false);});
test('recovery cannot substitute scope or turn absent error into recorded identity',()=>{const v={schemaVersion:1,tenantId:saved.tenantId,actorId:saved.actorId,operationId:saved.operationId,action:'add',scheduleId:saved.schedule_id,templateId:saved.template_id,status:'recorded',saved};assert.equal(V.rotaPeriodReconciliationSchema.safeParse(v).success,true);assert.equal(V.rotaPeriodReconciliationSchema.safeParse({...v,actorId:id(9)}).success,false);assert.equal(V.rotaPeriodReconciliationSchema.safeParse({...v,status:'not_recorded'}).success,false);assert.equal(V.rotaPeriodRecoveryQuerySchema.safeParse({mode:'reconcile',tenantId:id(1),operationId:id(2),action:'add',scheduleId:id(3),templateId:null}).success,false);});
const sourceEntries=Array.from({length:100},(_,index)=>({index,source_shift_id:save.change.sources[index].id,source_revision:2147483646,source_status:'draft',source_starts_at:'2026-10-05T09:00:00.000001Z',source_ends_at:'2026-10-05T17:00:00.000002Z',agent_id:id(2),agent_name:'😀'.repeat(100)+' '+'😀'.repeat(100),job_id:id(3),job_name:'😀'.repeat(100),job_color:'#3487ee',title:'😀'.repeat(100),start_day_offset:0,end_day_offset:0,start_clock_micros:32400000001,end_clock_micros:61200000002}));
const source={schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:{id:id(3),revision:1,time_zone:'UTC',status:'active'},source:{kind:'day',anchor:'2026-10-05',zone:'UTC',filters,entryCount:5000,userCount:1,elapsedMicros:5000},capacity:{companyUsageVisible:false,metadata:0,shifts:null,entries:null,operations:null,generated:null},canSave:true,saveBlockers:[],sourceReviewDigest:'a'.repeat(64),firstPage:true,selectors:save.change.sources,entries:sourceEntries,page:{total:5000,nextCursor:'e30'}};
test('source firstPage requires exact complete sorted selector set; later omits it',()=>{assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse(source).success,true);assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,selectors:source.selectors.slice(0,4999)}).success,false);assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,firstPage:false}).success,false);const {selectors,...later}=source;assert.equal(selectors.length,5000);assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...later,firstPage:false}).success,true);});
test('authoritative zero source preview permitted but empty Save denied',()=>{assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,canSave:false,source:{...source.source,entryCount:0,userCount:0,elapsedMicros:0},selectors:[],entries:[],page:{total:0,nextCursor:null}}).success,true);assert.equal(V.rotaPeriodMutationSchema.safeParse({...save,change:{...save.change,sources:[]}}).success,false);});

test('first source response 5000selectors/100 maximum raw Unicode captured rows fits1MiB',()=>{assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse(source).success,true);assert.ok(Buffer.byteLength(JSON.stringify(source))<=1048576);assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,entries:[]}).success,false);assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,entries:source.entries.slice(1)}).success,false);assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,entries:[source.entries[0],source.entries[2]]}).success,false);});
test('new titles and filters respect UTF16 while captured max Unicode remains exact',()=>{assert.equal(V.rotaPeriodMutationSchema.safeParse({...save,change:{...save.change,title:'😀'.repeat(51)}}).success,false);assert.equal(V.rotaPeriodFiltersSchema.safeParse({...filters,workerSearch:'😀'.repeat(51)}).success,false);});

const S=await import('../../lib/rota-period-template-server.ts');
const sourceQuery={mode:'source-preview',tenantId:id(1),scheduleId:id(3),scheduleRevision:1,kind:'day',sourceAnchor:'2026-10-05',sourceFilters:filters};
const ownerSource={...source,capacity:{companyUsageVisible:true,metadata:0,shifts:0,entries:0,operations:0,generated:0},page:{total:5000,nextCursor:Buffer.from(JSON.stringify({scope:{fixture:true},position:100})).toString('base64url')}};
const managerSource={...ownerSource,capacity:source.capacity};
const clientFor=(responses)=>({auth:{getUser:async()=>({data:{user:{id:id(2),is_anonymous:false}},error:null})},rpc:async()=>({data:responses.shift(),error:null})});
test('role downgrade between whole source reads is403 so previous owner quota state is cleared',async()=>{await assert.rejects(S.previewRotaPeriodSource(clientFor([ownerSource,managerSource,{schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:source.schedule,companyUsageVisible:false}]),sourceQuery),e=>e.status===403);});
test('role downgrade at fresh final access check is403 rather than unverifiable receipt error',async()=>{const access={schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:source.schedule,companyUsageVisible:false};await assert.rejects(S.previewRotaPeriodSource(clientFor([ownerSource,ownerSource,access]),sourceQuery),e=>e.status===403);});

test('paged reread SQL stale-cursor error after owner demotion becomes403',async()=>{let calls=0;const c={auth:clientFor([]).auth,rpc:async()=>{calls++;return calls===1?{data:ownerSource,error:null}:calls===2?{data:null,error:{code:'40001'}}:{data:{schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:source.schedule,companyUsageVisible:false},error:null};}};await assert.rejects(S.previewRotaPeriodSource(c,sourceQuery),e=>e.status===403);});
test('initial owner-scoped old cursor SQL error after demotion becomes403',async()=>{const identity={schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:source.schedule,companyUsageVisible:true};const cursor=Buffer.from(JSON.stringify({scope:{identity},position:100})).toString('base64url');let calls=0;const c={auth:clientFor([]).auth,rpc:async()=>++calls===1?{data:null,error:{code:'40001'}}:{data:{...identity,companyUsageVisible:false},error:null}};await assert.rejects(S.previewRotaPeriodSource(c,{...sourceQuery,cursor}),e=>e.status===403);});
test('worst legacy-valid escaped source labels plus5000 selectors remain within1MiB',()=>{const entries=sourceEntries.map(r=>({...r,agent_name:' '.repeat(100)+'\u0001'.repeat(100)+' '+'\u0001'.repeat(100)+' '.repeat(100),job_name:' '.repeat(100)+'\u0001'.repeat(100),title:'\u0001'.repeat(100)}));const v={...source,entries};assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse(v).success,true);assert.ok(Buffer.byteLength(JSON.stringify(v))<=1048576);});

test('final simultaneous role downgrade and schedule edit clears quota state with403 first',async()=>{const access={schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:{...source.schedule,revision:2},companyUsageVisible:false};await assert.rejects(S.previewRotaPeriodSource(clientFor([ownerSource,ownerSource,access]),sourceQuery),e=>e.status===403);});
test('streamed actual512KiB period body accepted while512KiB+1 rejected and malformed UTF8/decodedduplicates denied',async()=>{const raw=JSON.stringify(save).padEnd(524288,' ');assert.equal(Buffer.byteLength(raw),524288);assert.equal((await S.readRotaPeriodBody(new Request('http://localhost/api/rota-period-templates',{method:'POST',body:raw}))).change.sources.length,5000);await assert.rejects(S.readRotaPeriodBody(new Request('http://localhost/api/rota-period-templates',{method:'POST',body:raw+' '})),e=>e.status===413);await assert.rejects(S.readRotaPeriodBody(new Request('http://localhost/api/rota-period-templates',{method:'POST',body:new Uint8Array([0xc3,0x28])})),e=>e.status===400);await assert.rejects(S.readRotaPeriodBody(new Request('http://localhost/api/rota-period-templates',{method:'POST',body:'{"a":1,"\\u0061":2}'})),e=>e.status===400);});

test('successful owner snapshots changed before finalmanager proof return403 before generic409',async()=>{const access={schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:{...source.schedule,revision:2},companyUsageVisible:false};await assert.rejects(S.previewRotaPeriodSource(clientFor([ownerSource,{...ownerSource,sourceReviewDigest:'b'.repeat(64)},access]),sourceQuery),e=>e.status===403);});

test('malformed second read after demotion still clears protected first owner capacity with403',async()=>{const access={schemaVersion:1,tenantId:id(1),actorId:id(2),schedule:source.schedule,companyUsageVisible:false};await assert.rejects(S.previewRotaPeriodSource(clientFor([ownerSource,{unverifiable:true},access]),sourceQuery),e=>e.status===403);});

test('new title canonical whitespace and C1 controls are independent of captured raw strings',()=>{for(const title of ['\u0085','Name\u0085 title','\u00a0'.repeat(5)])assert.equal(V.rotaPeriodMutationSchema.safeParse({...save,change:{...save.change,title}}).success,false);const p=V.rotaPeriodMutationSchema.parse({...save,change:{...save.change,title:'\u00a0\u2003Canonical title\u3000\ufeff'}});assert.equal(p.change.title,'Canonical title');assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,entries:source.entries.map(r=>({...r,title:'Captured\u0085 raw'}))}).success,true);});

test('Day response offsets cannot claim Week-only carryout even under valid DTO numeric bound',()=>{assert.equal(V.rotaPeriodSourcePreviewSchema.safeParse({...source,entries:source.entries.map(r=>({...r,end_day_offset:8}))}).success,false);});
