begin;
-- Genuine Storage70 provider migrations are required before this additive migration.
create extension if not exists pgcrypto;
alter table public.knowledge_nodes drop constraint knowledge_nodes_kind_check;
alter table public.knowledge_nodes add constraint knowledge_nodes_kind_check check(kind in('folder','text','link','file'));
alter table public.knowledge_nodes drop constraint knowledge_nodes_check;
alter table public.knowledge_nodes add constraint knowledge_nodes_check check((kind='text'and body is not null and url is null)or(kind='link'and url is not null and body is null)or(kind in('folder','file')and body is null and url is null));
create table workforce_private.knowledge_file_verifier_keys(key_id text primary key check(key_id~'^[A-Za-z0-9_-]{1,32}$'),key_bytes bytea not null check(octet_length(key_bytes)>=32),active boolean not null default true);
create table workforce_private.knowledge_file_quota(id boolean primary key default true check(id),allocated_bytes bigint not null default 0 check(allocated_bytes between 0 and 104857600),allocated_attempts integer not null default 0 check(allocated_attempts between 0 and 4096));
insert into workforce_private.knowledge_file_quota default values;
create table workforce_private.knowledge_file_company_quota(tenant_id uuid primary key references public.tenants(id),allocated_bytes bigint not null default 0 check(allocated_bytes>=0),allocated_attempts integer not null default 0 check(allocated_attempts between 0 and 2048));
create table workforce_private.knowledge_file_attempts(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null,actor_id uuid not null,operation_id uuid not null,base_id uuid not null,node_id uuid not null,parent_id uuid not null,mode text not null check(mode in('create','replace')),payload jsonb not null,
 expected_base_revision integer not null,expected_node_revision integer,name text not null,description text not null,filename text not null,media_type text not null check(media_type in('application/pdf','text/plain','text/csv','image/png','image/jpeg')),bytes integer not null check(bytes between 1 and 2097152),sha256 text not null check(sha256~'^[a-f0-9]{64}$'),actor_name text not null,
 path text not null unique,revision integer not null default 1 check(revision>0),state text not null default 'upload_attempted'check(state in('upload_attempted','uploaded_unverified','provider_succeeded','finalized','closed','cleanup_acknowledged')),allocated_at timestamptz not null default clock_timestamp(),deadline timestamptz not null,accepted_id uuid,accepted_version uuid,completion_at timestamptz,provider_success_at timestamptz,finalized_at timestamptz,close_reason text,cleanup_ack_at timestamptz,result jsonb,
 unique(tenant_id,actor_id,operation_id),unique(tenant_id,base_id,node_id,id),foreign key(tenant_id,actor_id)references public.tenant_memberships(tenant_id,user_id),foreign key(tenant_id,base_id)references public.knowledge_bases(tenant_id,id),foreign key(tenant_id,base_id,parent_id)references public.knowledge_nodes(tenant_id,base_id,id),check((accepted_id is null)=(accepted_version is null))
);
create table workforce_private.knowledge_file_versions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,base_id uuid not null,node_id uuid not null,attempt_id uuid not null unique,foreign key(tenant_id,base_id,node_id)references public.knowledge_nodes(tenant_id,base_id,id),foreign key(tenant_id,base_id,node_id,attempt_id)references workforce_private.knowledge_file_attempts(tenant_id,base_id,node_id,id),unique(tenant_id,base_id,node_id,id));
create table workforce_private.knowledge_file_current(tenant_id uuid not null,base_id uuid not null,node_id uuid not null,version_id uuid not null,primary key(tenant_id,base_id,node_id),foreign key(tenant_id,base_id,node_id,version_id)references workforce_private.knowledge_file_versions(tenant_id,base_id,node_id,id));
create table workforce_private.knowledge_file_cleanup_operations(tenant_id uuid not null,actor_id uuid not null,operation_id uuid not null,attempt_id uuid not null unique references workforce_private.knowledge_file_attempts(id),payload jsonb not null,result jsonb not null,primary key(tenant_id,actor_id,operation_id));

create function workforce_private.knowledge_file_actor_role(t uuid,a uuid)returns text language sql stable security definer set search_path=''as $$select m.role from public.tenant_memberships m join public.tenants x on x.id=m.tenant_id join auth.users u on u.id=m.user_id where m.tenant_id=t and m.user_id=a and m.status='active'and x.status='active'and u.email_confirmed_at is not null and u.is_anonymous is not true$$;
create function workforce_private.knowledge_file_locks(t uuid,a uuid,o uuid)returns void language plpgsql security definer set search_path=''as $$begin perform pg_advisory_xact_lock(hashtextextended(t::text||a::text||o::text,63));perform pg_advisory_xact_lock(hashtextextended(t::text,64));perform pg_advisory_xact_lock(hashtextextended('ct-alt-knowledge-base-file-allocation',65));perform 1 from workforce_private.knowledge_file_quota where id for update;end$$;
create function workforce_private.knowledge_file_intent_valid(a workforce_private.knowledge_file_attempts)returns boolean language plpgsql stable security definer set search_path=''as $$declare x public.knowledge_bases;n public.knowledge_nodes;p public.knowledge_nodes;begin
 if workforce_private.knowledge_file_actor_role(a.tenant_id,a.actor_id)not in('owner','admin')or workforce_private.knowledge_file_actor_role(a.tenant_id,a.actor_id)is null then return false;end if;
 select *into x from public.knowledge_bases where tenant_id=a.tenant_id and id=a.base_id;if not found or x.status='archived'or x.revision<>a.expected_base_revision or x.revision>=2147483647 then return false;end if;
 select *into p from public.knowledge_nodes where tenant_id=a.tenant_id and base_id=a.base_id and id=a.parent_id;
 if not found or p.kind<>'folder'or p.depth>=16 then return false;end if;
 -- Internal boolean walk avoids using the service JWT as original requester.
 if exists(with recursive chain as(select id,parent_id,status,1 d,array[id]seen from public.knowledge_nodes where tenant_id=a.tenant_id and base_id=a.base_id and id=a.parent_id union all select nk.id,nk.parent_id,nk.status,c.d+1,c.seen||nk.id from public.knowledge_nodes nk join chain c on nk.id=c.parent_id where nk.tenant_id=a.tenant_id and nk.base_id=a.base_id and c.d<17 and not nk.id=any(c.seen))select 1 from chain where status<>'active'or d>16 or parent_id=any(seen))then return false;end if;
 if a.mode='replace'then select *into n from public.knowledge_nodes where tenant_id=a.tenant_id and base_id=a.base_id and id=a.node_id;if not found or n.kind<>'file'or n.status<>'active'or n.parent_id<>a.parent_id or n.revision<>a.expected_node_revision or n.revision>=2147483647 then return false;end if;end if;return true;
end$$;
create function workforce_private.knowledge_file_message(a workforce_private.knowledge_file_attempts,stage text,k text,expiry bigint default null)returns text language plpgsql immutable security invoker set search_path=''as $$declare vals text[];v text;result text:='';begin
 vals:=array[stage,k,a.tenant_id::text,a.base_id::text,a.node_id::text,a.id::text,a.actor_id::text,a.operation_id::text,a.path,a.bytes::text,a.sha256,a.media_type,(floor(extract(epoch from a.deadline)*1000)::bigint)::text,case when stage='upload-v1'then ''else a.accepted_id::text end,case when stage='upload-v1'then ''else a.accepted_version::text end,coalesce(expiry::text,'')];foreach v in array vals loop if v is null then return null;end if;result:=result||octet_length(convert_to(v,'UTF8'))::text||':'||v;end loop;return result;end$$;
create function workforce_private.knowledge_file_proof(a workforce_private.knowledge_file_attempts,stage text,k text,proof text,expiry bigint default null)returns boolean language plpgsql stable security definer set search_path=''as $$declare secret bytea;ns text;expected bytea;actual bytea;diff integer:=0;i integer;msg text;begin
 if proof is null or proof!~'^[a-f0-9]{64}$'or k is null then return false;end if;
 select key_bytes into secret from workforce_private.knowledge_file_verifier_keys where key_id=k and active;if not found then return false;end if;
 msg:=workforce_private.knowledge_file_message(a,stage,k,expiry);if msg is null then return false;end if;
 select n.nspname into ns from pg_extension e join pg_namespace n on n.oid=e.extnamespace where e.extname='pgcrypto';execute format('select %I.hmac($1,$2,''sha256'')',ns)into expected using convert_to(msg,'UTF8'),secret;actual:=decode(proof,'hex');for i in 0..31 loop diff:=diff|(get_byte(expected,i)#get_byte(actual,i));end loop;return diff=0;
end$$;
create function workforce_private.knowledge_file_scope(a workforce_private.knowledge_file_attempts)returns void language plpgsql stable security definer set search_path=''as $$begin if auth.uid()is distinct from a.actor_id or workforce_private.membership_role(a.tenant_id)is null or workforce_private.membership_role(a.tenant_id)not in('owner','admin')or not workforce_private.knowledge_access(a.tenant_id,a.base_id)then raise exception using errcode='42501',message='File operation unavailable';end if;end$$;
create function workforce_private.knowledge_file_public(a workforce_private.knowledge_file_attempts)returns jsonb language sql stable security definer set search_path=''as $$select jsonb_build_object('tenantId',a.tenant_id,'actorId',a.actor_id,'role',workforce_private.membership_role(a.tenant_id),'operationId',a.operation_id,'action','save_file','status',a.state,'attemptRevision',a.revision,'deadline',a.deadline,'capabilities',jsonb_build_object('canFinalize',a.state='provider_succeeded'and a.deadline>clock_timestamp()and workforce_private.knowledge_file_intent_valid(a),'canClose',a.state in('upload_attempted','uploaded_unverified','provider_succeeded'),'canCleanup',a.state='closed'and a.accepted_version is not null and not exists(select 1 from workforce_private.knowledge_file_cleanup_operations z where z.attempt_id=a.id)),'saved',case when a.state='finalized'then a.result||jsonb_build_object('role',workforce_private.membership_role(a.tenant_id))else null end,'serverTime',clock_timestamp())$$;
create function workforce_private.reserve_knowledge_file(t uuid,o uuid,intent jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare actor uuid:=auth.uid();a workforce_private.knowledge_file_attempts;m jsonb:=intent->'metadata';x public.knowledge_bases;n public.knowledge_nodes;p public.knowledge_nodes;q workforce_private.knowledge_file_quota;c workforce_private.knowledge_file_company_quota;keys text[];begin
 if workforce_private.membership_role(t)is null or workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='File management unavailable';end if;
 if jsonb_typeof(intent)is distinct from 'object'or(select array_agg(key order by key)from jsonb_object_keys(intent)key)is distinct from array['bytes','mediaType','metadata','sha256']or jsonb_typeof(m)is distinct from 'object'or octet_length(intent::text)>16384 then raise exception using errcode='22023',message='Invalid file intent';end if;
 keys:=case m->>'mode'when'create'then array['baseId','description','expectedBaseRevision','filename','mode','name','operationId','parentId','tenantId']when'replace'then array['baseId','description','expectedBaseRevision','expectedNodeRevision','filename','mode','name','nodeId','operationId','tenantId']end;
 if keys is null or(select array_agg(key order by key)from jsonb_object_keys(m)key)is distinct from keys or exists(select 1 from jsonb_each(m)where key in('tenantId','baseId','operationId','parentId','nodeId')and not workforce_private.knowledge_uuid(value))or m->>'tenantId'<>t::text or m->>'operationId'<>o::text then raise exception using errcode='22023',message='Invalid file identity';end if;
 if exists(select 1 from jsonb_each(m)where key in('expectedBaseRevision','expectedNodeRevision')and(jsonb_typeof(value)is distinct from 'number'or(value#>>'{}')!~'^[1-9][0-9]{0,9}$'or(value#>>'{}')::numeric>2147483646))or exists(select 1 from jsonb_each(m)where key in('name','description','filename','mode')and jsonb_typeof(value)is distinct from 'string')or not workforce_private.knowledge_nonblank(m->>'name')or workforce_private.knowledge_utf16(m->>'name')>100 or workforce_private.knowledge_utf16(m->>'description')>500 or not workforce_private.knowledge_nonblank(m->>'filename')or workforce_private.knowledge_utf16(m->>'filename')>255 or octet_length(m->>'filename')>1024 or(m->>'filename')~E'[\r\n]'or jsonb_typeof(intent->'bytes')is distinct from 'number'or(intent->>'bytes')!~'^[1-9][0-9]{0,6}$'or(intent->>'bytes')::numeric>2097152 or jsonb_typeof(intent->'sha256')is distinct from 'string'or(intent->>'sha256')!~'^[a-f0-9]{64}$'or jsonb_typeof(intent->'mediaType')is distinct from 'string'or(intent->>'mediaType')not in('application/pdf','text/plain','text/csv','image/png','image/jpeg')then raise exception using errcode='22023',message='Invalid file details';end if;
 perform workforce_private.knowledge_file_locks(t,actor,o);
 select *into x from public.knowledge_bases where tenant_id=t and id=(m->>'baseId')::uuid for update;if not found then raise exception using errcode='42501',message='Base unavailable';end if;
 select *into a from workforce_private.knowledge_file_attempts where tenant_id=t and actor_id=actor and operation_id=o for update;
 if found then perform workforce_private.knowledge_file_scope(a);if a.payload is distinct from intent then raise exception using errcode='22023',message='Operation UUID is bound to another file';end if;return jsonb_build_object('claimed',false,'attempt',workforce_private.knowledge_file_public(a));end if;
 if m->>'mode'='replace'then select *into n from public.knowledge_nodes where tenant_id=t and base_id=x.id and id=(m->>'nodeId')::uuid for update;if not found then raise exception using errcode='42501',message='Node unavailable';end if;p.id:=n.parent_id;else p.id:=(m->>'parentId')::uuid;end if;
 a.tenant_id:=t;a.actor_id:=actor;a.operation_id:=o;a.base_id:=x.id;a.node_id:=case when n.id is not null then n.id else gen_random_uuid()end;a.parent_id:=p.id;a.mode:=m->>'mode';a.expected_base_revision:=(m->>'expectedBaseRevision')::integer;a.expected_node_revision:=(m->>'expectedNodeRevision')::integer;
 if not workforce_private.knowledge_file_intent_valid(a)then raise exception using errcode='40001',message='File hierarchy or revision changed';end if;
 select *into q from workforce_private.knowledge_file_quota where id for update;
 insert into workforce_private.knowledge_file_company_quota(tenant_id)values(t)on conflict do nothing;select *into c from workforce_private.knowledge_file_company_quota where tenant_id=t for update;
 if q.allocated_bytes+(intent->>'bytes')::integer>104857600 or q.allocated_attempts>=4096 or c.allocated_attempts>=2048 then raise exception using errcode='54000',message='Reserved and retained file budget unavailable';end if;
 a.id:=gen_random_uuid();a.path:=t::text||'/'||a.base_id::text||'/'||a.node_id::text||'/'||a.id::text;
 insert into workforce_private.knowledge_file_attempts(id,tenant_id,actor_id,operation_id,base_id,node_id,parent_id,mode,payload,expected_base_revision,expected_node_revision,name,description,filename,media_type,bytes,sha256,actor_name,path,deadline)values(a.id,t,actor,o,a.base_id,a.node_id,a.parent_id,a.mode,intent,a.expected_base_revision,a.expected_node_revision,m->>'name',m->>'description',m->>'filename',intent->>'mediaType',(intent->>'bytes')::integer,intent->>'sha256',(select display_name from public.tenant_memberships where tenant_id=t and user_id=actor),a.path,date_trunc('milliseconds',clock_timestamp()+interval'10 minutes'))returning *into a;
 update workforce_private.knowledge_file_quota set allocated_bytes=allocated_bytes+a.bytes,allocated_attempts=allocated_attempts+1 where id;update workforce_private.knowledge_file_company_quota set allocated_bytes=allocated_bytes+a.bytes,allocated_attempts=allocated_attempts+1 where tenant_id=t;
 return jsonb_build_object('claimed',true,'attempt',workforce_private.knowledge_file_public(a));
end$$;

create function workforce_private.knowledge_file_internal(a workforce_private.knowledge_file_attempts)returns jsonb language sql stable security definer set search_path=''as $$select workforce_private.knowledge_file_public(a)||jsonb_build_object('baseId',a.base_id,'nodeId',a.node_id,'parentId',a.parent_id,'mode',a.mode,'path',a.path,'bytes',a.bytes,'sha256',a.sha256,'mediaType',a.media_type,'filename',a.filename,'expectedBaseRevision',a.expected_base_revision,'expectedNodeRevision',a.expected_node_revision,'attemptId',a.id,'providerId',a.accepted_id,'providerVersion',a.accepted_version)$$;
create function workforce_private.read_knowledge_file(t uuid,o uuid,internal boolean default false)returns jsonb language plpgsql security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;r text;begin
 perform pg_advisory_xact_lock(hashtextextended(t::text||auth.uid()::text||o::text,63));
 r:=workforce_private.membership_role(t);
 if r is null or r not in('owner','admin')then raise exception using errcode='42501',message='File operation unavailable';end if;
 select *into a from workforce_private.knowledge_file_attempts where tenant_id=t and actor_id=auth.uid()and operation_id=o;
 if not found then return jsonb_build_object('tenantId',t,'actorId',auth.uid(),'role',r,'operationId',o,'action','save_file','status','not_recorded','attemptRevision',null,'deadline',null,'capabilities',jsonb_build_object('canFinalize',false,'canClose',false,'canCleanup',false),'saved',null,'serverTime',clock_timestamp());end if;
 perform workforce_private.knowledge_file_scope(a);return case when internal then workforce_private.knowledge_file_internal(a)else workforce_private.knowledge_file_public(a)end;
end$$;
create function workforce_private.knowledge_file_storage_insert(n storage.objects)returns boolean language plpgsql stable security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;u jsonb:=n.user_metadata->'ct_alt';begin
 if n.bucket_id<>'ct-alt-knowledge-base'then return false;end if;
 if current_setting('storage.operation',true)<>'storage.object.upload'or current_setting('role',true)<>'authenticated'or auth.uid()is null then return false;end if;
 select *into a from workforce_private.knowledge_file_attempts where path=n.name;
 return found and a.actor_id=auth.uid()and n.owner_id=a.actor_id::text and a.state='upload_attempted'and a.deadline>clock_timestamp()and workforce_private.knowledge_file_intent_valid(a)and n.version='1'and coalesce(n.metadata->>'contentLength','')=a.bytes::text and n.metadata->>'mimetype'=a.media_type and n.user_metadata=jsonb_build_object('ct_alt',u)and(select array_agg(key order by key)from jsonb_object_keys(u)key)=array['attemptId','keyId','operationId','proof','v']and u->>'v'='upload-v1'and u->>'attemptId'=a.id::text and u->>'operationId'=a.operation_id::text and workforce_private.knowledge_file_proof(a,'upload-v1',u->>'keyId',u->>'proof');
exception when others then return false;
end$$;
create function workforce_private.knowledge_file_storage_guard()returns trigger language plpgsql security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;u jsonb;begin
 if new.bucket_id<>'ct-alt-knowledge-base'and(tg_op='INSERT'or old.bucket_id<>'ct-alt-knowledge-base')then return new;end if;
 if exists(select 1 from storage.buckets b where b.id=new.bucket_id and coalesce(to_jsonb(b)->>'versioning_status','DISABLED')<>'DISABLED')then raise exception using errcode='42501',message='Versioned file buckets are unsupported';end if;
 if coalesce(to_jsonb(new)->>'is_versioned','false')<>'false'or coalesce(to_jsonb(new)->>'is_delete_marker','false')<>'false'or to_jsonb(new)->>'archived_at'is not null then raise exception using errcode='42501',message='Versioned file objects are unsupported';end if;
 if tg_op='UPDATE'then raise exception using errcode='42501',message='File object paths are immutable';end if;
 if new.version='1'and current_setting('role',true)='authenticated'then if not workforce_private.knowledge_file_storage_insert(new)then raise exception using errcode='42501',message='Upload preflight denied';end if;return new;end if;
 if current_setting('role',true)<>'service_role'or current_setting('storage.operation',true)<>'storage.object.upload'or not workforce_private.knowledge_uuid(to_jsonb(new.version))then raise exception using errcode='42501',message='File completion issuer denied';end if;
 select *into a from workforce_private.knowledge_file_attempts where path=new.name;if not found then raise exception using errcode='42501',message='Unknown file attempt';end if;
 perform workforce_private.knowledge_file_locks(a.tenant_id,a.actor_id,a.operation_id);
 perform 1 from public.knowledge_bases where tenant_id=a.tenant_id and id=a.base_id for update;if a.mode='replace'then perform 1 from public.knowledge_nodes where tenant_id=a.tenant_id and base_id=a.base_id and id=a.node_id for update;end if;
 select *into a from workforce_private.knowledge_file_attempts where id=a.id for update;u:=new.user_metadata->'ct_alt';
 if a.state<>'upload_attempted'or a.deadline<=clock_timestamp()or not workforce_private.knowledge_file_intent_valid(a)or new.owner_id is distinct from a.actor_id::text or new.metadata->>'size'is distinct from a.bytes::text or new.metadata->>'mimetype'is distinct from a.media_type or new.user_metadata is distinct from jsonb_build_object('ct_alt',u)or(select array_agg(key order by key)from jsonb_object_keys(u)key)is distinct from array['attemptId','keyId','operationId','proof','v']or u->>'v'is distinct from 'upload-v1'or u->>'attemptId'is distinct from a.id::text or u->>'operationId'is distinct from a.operation_id::text or not workforce_private.knowledge_file_proof(a,'upload-v1',u->>'keyId',u->>'proof')then raise exception using errcode='42501',message='File completion denied';end if;
 update workforce_private.knowledge_file_attempts set state='uploaded_unverified',revision=revision+1,accepted_id=new.id,accepted_version=new.version::uuid,completion_at=clock_timestamp()where id=a.id;
 return new;
end$$;
create function workforce_private.knowledge_file_placeholder_guard()returns trigger language plpgsql security definer set search_path=''as $$begin if new.bucket_id='ct-alt-knowledge-base'and new.version='1'then raise exception using errcode='42501',message='Upload preflight cannot persist';end if;return new;end$$;
create trigger ct_alt_file_objects_immutable before insert or update on storage.objects for each row execute function workforce_private.knowledge_file_storage_guard();
create constraint trigger ct_alt_file_preflight_rollback after insert on storage.objects deferrable initially deferred for each row execute function workforce_private.knowledge_file_placeholder_guard();
create function workforce_private.knowledge_file_storage_read(n storage.objects,cleanup boolean default false)returns boolean language plpgsql stable security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;op text:=current_setting('storage.operation',true);r text;begin
 if n.bucket_id<>'ct-alt-knowledge-base'or current_setting('role',true)<>'authenticated'or coalesce(to_jsonb(n)->>'is_versioned','false')<>'false'or coalesce(to_jsonb(n)->>'is_delete_marker','false')<>'false'or to_jsonb(n)->>'archived_at'is not null then return false;end if;
 select *into a from workforce_private.knowledge_file_attempts where path=n.name and accepted_id=n.id and accepted_version::text=n.version;if not found then return false;end if;
 r:=workforce_private.membership_role(a.tenant_id);if r is null then return false;end if;
 if cleanup then return op='storage.object.delete'and r in('owner','admin')and a.state='closed'and exists(select 1 from workforce_private.knowledge_file_cleanup_operations z where z.attempt_id=a.id and z.actor_id=auth.uid()and z.result->>'status'='prepared')and not exists(select 1 from workforce_private.knowledge_file_current c join workforce_private.knowledge_file_versions v on v.id=c.version_id where v.attempt_id=a.id);end if;
 if op='storage.object.delete'then return workforce_private.knowledge_file_storage_read(n,true);end if;
 if op<>'storage.object.get_authenticated'then return false;end if;
 if a.state in('uploaded_unverified','provider_succeeded')then return auth.uid()=a.actor_id and r in('owner','admin')and a.deadline>clock_timestamp()and workforce_private.knowledge_file_intent_valid(a);end if;
 return a.state='finalized'and workforce_private.knowledge_access(a.tenant_id,a.base_id,a.node_id)and exists(select 1 from workforce_private.knowledge_file_current c join workforce_private.knowledge_file_versions v on v.id=c.version_id where v.attempt_id=a.id);
end$$;
create policy ct_alt_file_upload on storage.objects for insert to authenticated with check(workforce_private.knowledge_file_storage_insert(objects));
create policy ct_alt_file_read on storage.objects for select to authenticated using(workforce_private.knowledge_file_storage_read(objects));
create policy ct_alt_file_delete on storage.objects for delete to authenticated using(workforce_private.knowledge_file_storage_read(objects,true));

-- Restrictive guards also constrain any existing permissive policies without changing other buckets.
create policy ct_alt_file_isolation on storage.objects as restrictive for all to authenticated using(bucket_id<>'ct-alt-knowledge-base'or workforce_private.knowledge_file_storage_read(objects))with check(bucket_id<>'ct-alt-knowledge-base'or workforce_private.knowledge_file_storage_insert(objects));
create policy ct_alt_file_anon_isolation on storage.objects as restrictive for all to anon using(bucket_id<>'ct-alt-knowledge-base')with check(bucket_id<>'ct-alt-knowledge-base');

create function workforce_private.change_knowledge_file(t uuid,o uuid,act text,expected integer default null,k text default null,proof text default null,expires bigint default null)returns jsonb language plpgsql security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;x public.knowledge_bases;n public.knowledge_nodes;p public.knowledge_nodes;v workforce_private.knowledge_file_versions;rank_value bigint;res jsonb;begin
 if workforce_private.membership_role(t)is null or workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='File operation unavailable';end if;
 if act not in('provider_success','finalize','close')or act is null or expected is null or expected<1 then raise exception using errcode='22023',message='Invalid file transition';end if;
 perform workforce_private.knowledge_file_locks(t,auth.uid(),o);
 select *into a from workforce_private.knowledge_file_attempts where tenant_id=t and actor_id=auth.uid()and operation_id=o;if not found then raise exception using errcode='42501',message='File operation unavailable';end if;
 select *into x from public.knowledge_bases where tenant_id=t and id=a.base_id for update;if a.mode='replace'then select *into n from public.knowledge_nodes where tenant_id=t and base_id=a.base_id and id=a.node_id for update;end if;
 select *into a from workforce_private.knowledge_file_attempts where id=a.id for update;perform workforce_private.knowledge_file_scope(a);
 if a.state='finalized'then if act='close'then raise exception using errcode='40001',message='Finalized files cannot close';end if;return workforce_private.knowledge_file_public(a);end if;
 if act='close'and a.state in('closed','cleanup_acknowledged')then return workforce_private.knowledge_file_public(a);end if;
 if act='provider_success'and a.state='provider_succeeded'then return workforce_private.knowledge_file_public(a);end if;
 if a.revision<>expected then raise exception using errcode='40001',message='File attempt changed';end if;
 if act='close'then
  if a.state not in('upload_attempted','uploaded_unverified','provider_succeeded')then raise exception using errcode='40001',message='File cannot close';end if;
  update workforce_private.knowledge_file_attempts set state='closed',close_reason='Explicitly closed',revision=revision+1 where id=a.id returning *into a;return workforce_private.knowledge_file_public(a);
 end if;
 -- A stale finalize commits CLOSED instead of throwing away that transition.
 if not workforce_private.knowledge_file_intent_valid(a)or a.deadline<=clock_timestamp()then update workforce_private.knowledge_file_attempts set state='closed',close_reason='Authority, hierarchy, revision or deadline changed',revision=revision+1 where id=a.id returning *into a;return workforce_private.knowledge_file_public(a);end if;
 if expires is null or expires<floor(extract(epoch from clock_timestamp())*1000)::bigint or expires>floor(extract(epoch from clock_timestamp())*1000)::bigint+60000 or not workforce_private.knowledge_file_proof(a,case act when'provider_success'then'provider-success-v1'else'finalize-v1'end,k,proof,expires)then raise exception using errcode='42501',message='File verification proof denied';end if;
 if act='provider_success'then
  if a.state<>'uploaded_unverified'then raise exception using errcode='40001',message='Provider completion unavailable';end if;
  update workforce_private.knowledge_file_attempts set state='provider_succeeded',provider_success_at=clock_timestamp(),revision=revision+1 where id=a.id returning *into a;return workforce_private.knowledge_file_public(a);
 end if;
 if a.state<>'provider_succeeded'then raise exception using errcode='42501',message='Provider success was not attested';end if;
 -- Ordinary MVCC reads only: no Storage foreign key, object or advisory lock here.
 if not exists(select 1 from storage.objects s where s.bucket_id='ct-alt-knowledge-base'and s.name=a.path and s.id=a.accepted_id and s.version=a.accepted_version::text and s.owner_id=a.actor_id::text and s.metadata->>'size'=a.bytes::text and s.metadata->>'mimetype'=a.media_type)then raise exception using errcode='40001',message='Accepted provider object changed';end if;
 if a.mode='create'then
  select *into p from public.knowledge_nodes where tenant_id=t and base_id=a.base_id and id=a.parent_id;select coalesce(max(rank),0)+1024 into rank_value from public.knowledge_nodes where tenant_id=t and base_id=a.base_id and parent_id=a.parent_id;
  insert into public.knowledge_nodes(id,tenant_id,base_id,parent_id,kind,name,description,depth,rank)values(a.node_id,t,a.base_id,a.parent_id,'file',a.name,a.description,p.depth+1,rank_value)returning *into n;
 else update public.knowledge_nodes set name=a.name,description=a.description,revision=revision+1 where tenant_id=t and base_id=a.base_id and id=a.node_id returning *into n;end if;
 insert into workforce_private.knowledge_file_versions(tenant_id,base_id,node_id,attempt_id)values(t,a.base_id,a.node_id,a.id)returning *into v;
 insert into workforce_private.knowledge_file_current(tenant_id,base_id,node_id,version_id)values(t,a.base_id,a.node_id,v.id)on conflict(tenant_id,base_id,node_id)do update set version_id=excluded.version_id;
 update public.knowledge_bases set revision=revision+1 where tenant_id=t and id=a.base_id returning *into x;
 res:=jsonb_build_object('tenantId',t,'actorId',a.actor_id,'role',workforce_private.membership_role(t),'operationId',o,'action','save_file','baseId',a.base_id,'nodeId',a.node_id,'revision',x.revision,'nodeRevision',n.revision,'versionId',v.id);
 insert into public.knowledge_audit(tenant_id,base_id,node_id,actor_id,actor_name,action,revision,node_revision)values(t,a.base_id,a.node_id,a.actor_id,a.actor_name,'save_file',x.revision,n.revision);
 update workforce_private.knowledge_file_attempts set state='finalized',revision=revision+1,finalized_at=clock_timestamp(),result=res where id=a.id returning *into a;return workforce_private.knowledge_file_public(a);
end$$;

create function workforce_private.read_knowledge_file_budget(t uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare c workforce_private.knowledge_file_company_quota;counts jsonb;r text:=workforce_private.membership_role(t);begin if r is null or r not in('owner','admin')then raise exception using errcode='42501',message='File budget unavailable';end if;
 select *into c from workforce_private.knowledge_file_company_quota where tenant_id=t;
 select jsonb_build_object('upload_attempted',count(*)filter(where state='upload_attempted'),'uploaded_unverified',count(*)filter(where state='uploaded_unverified'),'provider_succeeded',count(*)filter(where state='provider_succeeded'),'finalized',count(*)filter(where state='finalized'),'closed',count(*)filter(where state='closed'),'cleanup_acknowledged',count(*)filter(where state='cleanup_acknowledged'))into counts from workforce_private.knowledge_file_attempts where tenant_id=t;
 return jsonb_build_object('tenantId',t,'actorId',auth.uid(),'role',r,'allocatedBytes',coalesce(c.allocated_bytes,0),'allocatedAttempts',coalesce(c.allocated_attempts,0),'byteLimit',104857600,'globalAttemptLimit',4096,'companyAttemptLimit',2048,'states',counts,'serverTime',clock_timestamp());end$$;

create function workforce_private.knowledge_file_current_json(t uuid,b uuid,n uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;v workforce_private.knowledge_file_versions;begin
 if not workforce_private.knowledge_access(t,b,n)then raise exception using errcode='42501',message='File unavailable';end if;
 select f.*into v from workforce_private.knowledge_file_current c join workforce_private.knowledge_file_versions f on f.id=c.version_id where c.tenant_id=t and c.base_id=b and c.node_id=n;
 if not found then raise exception using errcode='42501',message='Current file unavailable';end if;
 select *into a from workforce_private.knowledge_file_attempts where id=v.attempt_id;
 return jsonb_build_object('versionId',v.id,'filename',a.filename,'mediaType',a.media_type,'bytes',a.bytes,'sha256',a.sha256,'uploadedAt',a.finalized_at,'uploaderName',a.actor_name);
end$$;
create function workforce_private.read_knowledge_file_download(t uuid,b uuid,n uuid,v uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;f workforce_private.knowledge_file_versions;x public.knowledge_bases;node public.knowledge_nodes;begin
 if workforce_private.membership_role(t)is null or not workforce_private.knowledge_access(t,b,n)then raise exception using errcode='42501',message='File unavailable';end if;
 select *into node from public.knowledge_nodes where tenant_id=t and base_id=b and id=n;if not found or node.kind<>'file'then raise exception using errcode='42501',message='File unavailable';end if;
 select z.*into f from workforce_private.knowledge_file_current c join workforce_private.knowledge_file_versions z on z.id=c.version_id where c.tenant_id=t and c.base_id=b and c.node_id=n;if not found or f.id<>v then raise exception using errcode='40001',message='Current file version changed';end if;
 select *into a from workforce_private.knowledge_file_attempts where id=f.attempt_id;select *into x from public.knowledge_bases where tenant_id=t and id=b;
 return jsonb_build_object('tenantId',t,'actorId',auth.uid(),'role',workforce_private.membership_role(t),'baseId',b,'nodeId',n,'versionId',v,'baseRevision',x.revision,'nodeRevision',node.revision,'baseStatus',x.status,'nodeStatus',node.status,'audienceVersion',workforce_private.knowledge_audience_version(t,b),'treeVersion',workforce_private.knowledge_tree_version(t,b),'path',a.path,'providerId',a.accepted_id,'providerVersion',a.accepted_version,'file',workforce_private.knowledge_file_current_json(t,b,n));
end$$;
create function workforce_private.cleanup_knowledge_file(t uuid,o uuid,u uuid,upload_op uuid,expected integer,k text default null,proof text default null,expires bigint default null)returns jsonb language plpgsql security definer set search_path=''as $$declare a workforce_private.knowledge_file_attempts;s workforce_private.knowledge_file_attempts;r workforce_private.knowledge_file_cleanup_operations;payload jsonb;res jsonb;begin
 if workforce_private.membership_role(t)is null or workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='File cleanup unavailable';end if;
 if expected is null or expected<1 then raise exception using errcode='22023',message='Invalid cleanup revision';end if;
 payload:=jsonb_build_object('uploadActorId',u,'uploadOperationId',upload_op,'expectedAttemptRevision',expected);perform workforce_private.knowledge_file_locks(t,auth.uid(),o);
 select *into a from workforce_private.knowledge_file_attempts where tenant_id=t and actor_id=u and operation_id=upload_op;if not found then raise exception using errcode='42501',message='File cleanup unavailable';end if;
 perform 1 from public.knowledge_bases where tenant_id=t and id=a.base_id for update;
 select *into a from workforce_private.knowledge_file_attempts where id=a.id for update;
 if workforce_private.membership_role(t)is null or workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='File cleanup unavailable';end if;
 if not workforce_private.knowledge_access(t,a.base_id)or a.accepted_version is null or exists(select 1 from workforce_private.knowledge_file_current c join workforce_private.knowledge_file_versions v on v.id=c.version_id where v.attempt_id=a.id)then raise exception using errcode='42501',message='Only closed noncurrent known files can be cleaned';end if;
 select *into r from workforce_private.knowledge_file_cleanup_operations where tenant_id=t and actor_id=auth.uid()and operation_id=o;
 if found then if r.payload is distinct from payload then raise exception using errcode='22023',message='Cleanup operation bound to another file';end if;if r.result->>'status'='cleanup_acknowledged'then return jsonb_build_object('claimed',false,'saved',r.result||jsonb_build_object('role',workforce_private.membership_role(t)));end if;
 else
  if exists(select 1 from workforce_private.knowledge_file_cleanup_operations where attempt_id=a.id)then raise exception using errcode='40001',message='This attempt already consumed its only cleanup claim';end if;
  if a.revision<>expected then raise exception using errcode='40001',message='Cleanup attempt changed';end if;
  if a.state in('upload_attempted','uploaded_unverified','provider_succeeded')and(a.deadline<=clock_timestamp()or not workforce_private.knowledge_file_intent_valid(a))then
   update workforce_private.knowledge_file_attempts set state='closed',close_reason='Management closed invalid or expired candidate',revision=revision+1 where id=a.id returning *into a;
   insert into public.knowledge_audit(tenant_id,base_id,node_id,actor_id,actor_name,action,revision,node_revision)select t,a.base_id,null,auth.uid(),m.display_name,'close_file',b.revision,null from public.knowledge_bases b join public.tenant_memberships m on m.tenant_id=b.tenant_id and m.user_id=auth.uid()where b.tenant_id=t and b.id=a.base_id;
  end if;
  if a.state<>'closed'then raise exception using errcode='40001',message='Only permanently closed invalid candidates can clean';end if;
  insert into workforce_private.knowledge_file_cleanup_operations values(t,auth.uid(),o,a.id,payload,jsonb_build_object('status','prepared'));
  update workforce_private.knowledge_file_attempts set revision=revision+1 where id=a.id returning *into a;
  return jsonb_build_object('claimed',true,'internal',workforce_private.knowledge_file_internal(a));
 end if;
 if proof is null then return jsonb_build_object('claimed',false,'internal',workforce_private.knowledge_file_internal(a));end if;
 s:=a;s.actor_id:=auth.uid();s.operation_id:=o;
 if a.state<>'closed'or expires is null or expires<floor(extract(epoch from clock_timestamp())*1000)::bigint or expires>floor(extract(epoch from clock_timestamp())*1000)::bigint+60000 or not workforce_private.knowledge_file_proof(s,'cleanup-v1',k,proof,expires)then raise exception using errcode='42501',message='Cleanup acknowledgement proof denied';end if;
 update workforce_private.knowledge_file_attempts set state='cleanup_acknowledged',revision=revision+1,cleanup_ack_at=clock_timestamp()where id=a.id returning *into a;
 res:=jsonb_build_object('tenantId',t,'actorId',auth.uid(),'role',workforce_private.membership_role(t),'operationId',o,'action','cleanup_file','uploadOperationId',upload_op,'attemptRevision',a.revision,'status','cleanup_acknowledged');
 update workforce_private.knowledge_file_cleanup_operations set result=res where tenant_id=t and actor_id=auth.uid()and operation_id=o;
 insert into public.knowledge_audit(tenant_id,base_id,node_id,actor_id,actor_name,action,revision,node_revision)select t,a.base_id,null,auth.uid(),m.display_name,'cleanup_file',b.revision,null from public.knowledge_bases b join public.tenant_memberships m on m.tenant_id=b.tenant_id and m.user_id=auth.uid()where b.tenant_id=t and b.id=a.base_id;
 return jsonb_build_object('claimed',false,'saved',res);
end$$;

create function public.reserve_knowledge_file(target_tenant uuid,operation_id uuid,intent jsonb)returns jsonb language sql security invoker set search_path=''as $$select workforce_private.reserve_knowledge_file(target_tenant,operation_id,intent)$$;
create function public.read_knowledge_file(target_tenant uuid,operation_id uuid,internal boolean default false)returns jsonb language sql volatile security invoker set search_path=''as $$select workforce_private.read_knowledge_file(target_tenant,operation_id,internal)$$;
create function public.change_knowledge_file(target_tenant uuid,operation_id uuid,action text,expected_revision integer,key_id text default null,proof text default null,expires_ms bigint default null)returns jsonb language sql security invoker set search_path=''as $$select workforce_private.change_knowledge_file(target_tenant,operation_id,action,expected_revision,key_id,proof,expires_ms)$$;
create function public.read_knowledge_file_budget(target_tenant uuid)returns jsonb language sql stable security invoker set search_path=''as $$select workforce_private.read_knowledge_file_budget(target_tenant)$$;
create function public.read_knowledge_file_download(target_tenant uuid,target_base uuid,target_node uuid,target_version uuid)returns jsonb language sql stable security invoker set search_path=''as $$select workforce_private.read_knowledge_file_download(target_tenant,target_base,target_node,target_version)$$;
create function public.cleanup_knowledge_file(target_tenant uuid,operation_id uuid,upload_actor uuid,upload_operation uuid,expected_revision integer,key_id text default null,proof text default null,expires_ms bigint default null)returns jsonb language sql security invoker set search_path=''as $$select workforce_private.cleanup_knowledge_file(target_tenant,operation_id,upload_actor,upload_operation,expected_revision,key_id,proof,expires_ms)$$;

-- Other kinds retain their exact existing JSON; file metadata is added only to file.
create or replace function workforce_private.knowledge_node_json(n public.knowledge_nodes)returns jsonb language sql stable security invoker set search_path=''as $$
 select jsonb_build_object('id',n.id,'baseId',n.base_id,'parentId',n.parent_id,'kind',n.kind,'name',n.name,'description',n.description,'status',n.status,'revision',n.revision,'depth',n.depth,'rank',n.rank::text,'activeChildCount',(select count(*)from public.knowledge_nodes where tenant_id=n.tenant_id and base_id=n.base_id and parent_id=n.id and status='active'),
 'canEdit',editable,'canMove',editable,'canMoveEarlier',editable and exists(select 1 from public.knowledge_nodes where tenant_id=n.tenant_id and base_id=n.base_id and parent_id is not distinct from n.parent_id and(rank,id)<(n.rank,n.id)),
 'canMoveLater',editable and exists(select 1 from public.knowledge_nodes where tenant_id=n.tenant_id and base_id=n.base_id and parent_id is not distinct from n.parent_id and(rank,id)>(n.rank,n.id)),
 'canArchive',editable and n.status='active'and not exists(select 1 from public.knowledge_nodes where tenant_id=n.tenant_id and base_id=n.base_id and parent_id=n.id and status='active'),'canRestore',editable and n.status='archived')
 ||case when n.kind='file'then jsonb_build_object('currentFile',workforce_private.knowledge_file_current_json(n.tenant_id,n.base_id,n.id))else '{}'::jsonb end
 from(select workforce_private.membership_role(n.tenant_id)in('owner','admin')and b.status<>'archived'and workforce_private.knowledge_path_active(n.tenant_id,n.base_id,n.parent_id)editable from public.knowledge_bases b where b.tenant_id=n.tenant_id and b.id=n.base_id)q
$$;
do $$declare r record;begin
 for r in select tablename from pg_tables where schemaname='workforce_private'and tablename in('knowledge_file_verifier_keys','knowledge_file_quota','knowledge_file_company_quota','knowledge_file_attempts','knowledge_file_versions','knowledge_file_current','knowledge_file_cleanup_operations')loop execute format('alter table workforce_private.%I enable row level security',r.tablename);execute format('revoke all on workforce_private.%I from public,anon,authenticated,service_role',r.tablename);end loop;
 for r in select p.oid::regprocedure fn from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','workforce_private')and p.proname in('knowledge_file_actor_role','knowledge_file_locks','knowledge_file_intent_valid','knowledge_file_message','knowledge_file_proof','knowledge_file_scope','knowledge_file_public','knowledge_file_internal','reserve_knowledge_file','read_knowledge_file','knowledge_file_storage_insert','knowledge_file_storage_guard','knowledge_file_placeholder_guard','knowledge_file_storage_read','change_knowledge_file','read_knowledge_file_budget','knowledge_file_current_json','read_knowledge_file_download','cleanup_knowledge_file')loop execute format('revoke all on function %s from public,anon,authenticated,service_role',r.fn);end loop;
 for r in select p.oid::regprocedure fn from pg_proc p join pg_namespace n on n.oid=p.pronamespace where(n.nspname='public'and p.proname in('reserve_knowledge_file','read_knowledge_file','change_knowledge_file','read_knowledge_file_budget','read_knowledge_file_download','cleanup_knowledge_file'))or(n.nspname='workforce_private'and p.proname in('reserve_knowledge_file','read_knowledge_file','change_knowledge_file','read_knowledge_file_budget','read_knowledge_file_download','cleanup_knowledge_file','knowledge_file_storage_insert','knowledge_file_storage_read','knowledge_file_current_json'))loop execute format('grant execute on function %s to authenticated',r.fn);end loop;
end$$;
commit;
