-- CT Alt desktop Forms. Additive; no applied table/function is replaced.
create table public.forms(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),name text not null,description text not null,schema jsonb not null default '[]',schema_frozen boolean not null default false,status text not null default 'draft'check(status in('draft','published','archived')),restore_status text check(restore_status in('draft','published')),allow_respondent_edit boolean not null default false,revision integer not null default 1 check(revision>0),created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),unique(tenant_id,id));
create table public.form_assignments(tenant_id uuid not null,form_id uuid not null,actor_id uuid not null,name text not null,primary key(tenant_id,form_id,actor_id),foreign key(tenant_id,form_id)references public.forms(tenant_id,id));
create table public.form_responses(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,form_id uuid not null,actor_id uuid not null,author_name text not null,status text not null default 'in_progress'check(status in('in_progress','submitted')),revision integer not null default 1 check(revision>0),answers jsonb not null default '{}',schema jsonb not null,form_name text not null,submitted_at timestamptz,updated_at timestamptz not null default clock_timestamp(),last_edited_by uuid not null,last_editor_name text not null,last_edited_at timestamptz not null default clock_timestamp(),reviewed boolean not null default false,reviewed_at timestamptz,reviewed_by uuid,reviewer_name text,content_edits integer not null default 0 check(content_edits between 0 and 50),unique(tenant_id,id),unique(tenant_id,form_id,actor_id),foreign key(tenant_id,form_id)references public.forms(tenant_id,id),check((status='submitted')=(submitted_at is not null)));
create table public.form_audit(id bigint generated always as identity primary key,tenant_id uuid not null,form_id uuid not null,response_id uuid,actor_id uuid not null,actor_name text not null,action text not null,form_revision integer not null,response_revision integer,occurred_at timestamptz not null default clock_timestamp(),foreign key(tenant_id,form_id)references public.forms(tenant_id,id),foreign key(tenant_id,response_id)references public.form_responses(tenant_id,id));
create table workforce_private.form_operations(tenant_id uuid not null,actor_id uuid not null,operation_id uuid not null,form_id uuid,response_id uuid,action text not null,state text not null default'recorded'check(state in('recorded','closed_absent')),payload_hash text,result jsonb,check((state='recorded'and form_id is not null and payload_hash is not null and payload_hash~'^[a-f0-9]{64}$'and result is not null and jsonb_typeof(result)='object')or(state='closed_absent'and form_id is null and response_id is null and payload_hash is null and result is null)),primary key(tenant_id,actor_id,operation_id),foreign key(tenant_id,form_id)references public.forms(tenant_id,id),foreign key(tenant_id,response_id)references public.form_responses(tenant_id,id));
create table workforce_private.form_response_history(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,response_id uuid not null,revision integer not null,answers jsonb not null,status text not null,submitted_at timestamptz not null,updated_at timestamptz not null,last_edited_by uuid not null,last_editor_name text not null,last_edited_at timestamptz not null default clock_timestamp(),reviewed boolean not null,reviewed_at timestamptz,reviewed_by uuid,reviewer_name text,retained_at timestamptz not null default clock_timestamp(),unique(tenant_id,response_id,revision),foreign key(tenant_id,response_id)references public.form_responses(tenant_id,id));
create table workforce_private.form_history_counter(id boolean primary key default true check(id),retained_rows integer not null default 0 check(retained_rows between 0 and 4096));insert into workforce_private.form_history_counter default values;
create index forms_catalog on public.forms(tenant_id,created_at desc,id desc);create index form_response_page on public.form_responses(tenant_id,form_id,submitted_at desc,id desc);create index form_response_history_page on workforce_private.form_response_history(tenant_id,response_id,revision desc);
alter table public.forms enable row level security;alter table public.form_assignments enable row level security;alter table public.form_responses enable row level security;alter table public.form_audit enable row level security;alter table workforce_private.form_operations enable row level security;alter table workforce_private.form_response_history enable row level security;alter table workforce_private.form_history_counter enable row level security;
revoke all on public.forms,public.form_assignments,public.form_responses,public.form_audit,workforce_private.form_operations,workforce_private.form_response_history,workforce_private.form_history_counter from public,anon,authenticated,service_role;grant select on public.forms,public.form_assignments,public.form_responses,public.form_audit to authenticated;
create function workforce_private.forms_reader(t uuid,f uuid)returns boolean language sql stable security definer set search_path=''as $$select workforce_private.membership_role(t)is not null and exists(select 1 from public.forms x join public.form_assignments a on a.tenant_id=x.tenant_id and a.form_id=x.id where x.tenant_id=t and x.id=f and x.status='published'and a.actor_id=(select auth.uid()))$$;
create function workforce_private.forms_access(t uuid,f uuid,mode text)returns boolean language sql stable security definer set search_path=''as $$select coalesce(case mode when'manage'then workforce_private.membership_role(t)in('owner','admin')and exists(select 1 from public.forms where tenant_id=t and id=f)when'mine'then workforce_private.forms_reader(t,f)else false end,false)$$;
create function workforce_private.forms_eligible(t uuid,u uuid)returns boolean language sql stable security definer set search_path=''as $$select workforce_private.membership_role(t)is not null and exists(select 1 from public.tenant_memberships m join public.tenants x on x.id=m.tenant_id join auth.users a on a.id=m.user_id where m.tenant_id=t and m.user_id=u and m.status='active'and x.status='active'and a.email_confirmed_at is not null and a.is_anonymous is not true)$$;
create policy forms_read on public.forms for select to authenticated using(workforce_private.membership_role(tenant_id)in('owner','admin')or workforce_private.forms_reader(tenant_id,id));
create policy form_assignment_read on public.form_assignments for select to authenticated using(workforce_private.membership_role(tenant_id)in('owner','admin')or actor_id=(select auth.uid())and workforce_private.forms_reader(tenant_id,form_id));
create policy form_response_read on public.form_responses for select to authenticated using((status='submitted'and workforce_private.membership_role(tenant_id)in('owner','admin'))or actor_id=(select auth.uid())and workforce_private.forms_reader(tenant_id,form_id));
create policy form_audit_read on public.form_audit for select to authenticated using(workforce_private.membership_role(tenant_id)in('owner','admin')and(response_id is null or exists(select 1 from public.form_responses r where r.tenant_id=form_audit.tenant_id and r.id=form_audit.response_id and r.status='submitted')));
-- The RPC takes raw JSON text, preserving duplicate keys before jsonb normalization.
create function workforce_private.forms_json_unique(v json,depth integer default 0)returns boolean language plpgsql immutable security invoker set search_path=''as $$declare item json;begin
 if depth>8 then return false;end if;
 if json_typeof(v)='object'then if exists(select 1 from json_each(v)group by key having count(*)>1)then return false;end if;for item in select value from json_each(v)loop if not workforce_private.forms_json_unique(item,depth+1)then return false;end if;end loop;
 elsif json_typeof(v)='array'then for item in select value from json_array_elements(v)loop if not workforce_private.forms_json_unique(item,depth+1)then return false;end if;end loop;end if;return true;end$$;
create function workforce_private.forms_schema_valid(s jsonb)returns boolean language plpgsql immutable security invoker set search_path=''as $$declare f jsonb;o jsonb;k text;begin
 if jsonb_typeof(s)is distinct from'array'or jsonb_array_length(s)>50 or octet_length(s::text)>131072 then return false;end if;
 if(select count(distinct lower(v->>'id'))from jsonb_array_elements(s)v)<>jsonb_array_length(s)then return false;end if;
 for f in select value from jsonb_array_elements(s)loop
  if jsonb_typeof(f)is distinct from'object'or not workforce_private.knowledge_uuid(f->'id')then return false;end if;k:=f->>'kind';
  if k='description'then if(select array_agg(key order by key)from jsonb_object_keys(f)key)is distinct from array['id','kind','text']or jsonb_typeof(f->'text')is distinct from'string'or workforce_private.knowledge_utf16(f->>'text')>5000 then return false;end if;
  elsif k in('text','yes_no','number','single_choice','multiple_choice')then
   if(select array_agg(key order by key)from jsonb_object_keys(f)key)is distinct from(case when k in('single_choice','multiple_choice')then array['id','kind','label','options','required']else array['id','kind','label','required']end)or jsonb_typeof(f->'label')is distinct from'string'or not workforce_private.knowledge_nonblank(f->>'label')or workforce_private.knowledge_utf16(f->>'label')>100 or jsonb_typeof(f->'required')is distinct from'boolean'then return false;end if;
   if k in('single_choice','multiple_choice')then if jsonb_typeof(f->'options')is distinct from'array'or jsonb_array_length(f->'options')not between 1 and 50 or(select count(distinct lower(v->>'id'))from jsonb_array_elements(f->'options')v)<>jsonb_array_length(f->'options')then return false;end if;for o in select value from jsonb_array_elements(f->'options')loop if jsonb_typeof(o)is distinct from'object'or(select array_agg(key order by key)from jsonb_object_keys(o)key)is distinct from array['id','label']or not workforce_private.knowledge_uuid(o->'id')or jsonb_typeof(o->'label')is distinct from'string'or not workforce_private.knowledge_nonblank(o->>'label')or workforce_private.knowledge_utf16(o->>'label')>100 then return false;end if;end loop;end if;
  else return false;end if;
 end loop;return true;
exception when others then return false;end$$;
create function workforce_private.forms_answers_valid(s jsonb,a jsonb,complete boolean)returns boolean language plpgsql immutable security invoker set search_path=''as $$declare f jsonb;v jsonb;k text;present boolean;begin
 if jsonb_typeof(a)is distinct from'object'or octet_length(a::text)>65536 or exists(select 1 from jsonb_each(a)e where not exists(select 1 from jsonb_array_elements(s)sf where sf->>'kind'<>'description'and sf->>'id'=e.key))then return false;end if;
 for f in select value from jsonb_array_elements(s)loop k:=f->>'kind';if k='description'then continue;end if;present:=a?(f->>'id');v:=a->(f->>'id');
  if not present then if complete and(f->>'required')::boolean then return false;end if;continue;end if;
  if k='text'then if jsonb_typeof(v)is distinct from'string'or workforce_private.knowledge_utf16(v#>>'{}')>5000 or complete and(f->>'required')::boolean and not workforce_private.knowledge_nonblank(v#>>'{}')then return false;end if;
  elsif k='yes_no'then if jsonb_typeof(v)is distinct from'boolean'then return false;end if;
  elsif k='number'then if jsonb_typeof(v)is distinct from'string'or workforce_private.knowledge_utf16(v#>>'{}')>32 or(case when complete then(v#>>'{}')!~'^[+-]?[0-9]{1,12}(\.[0-9]{1,6})?$'else(v#>>'{}')!~'^[+-]?[0-9]*(\.[0-9]*)?$'end)then return false;end if;if complete then perform(v#>>'{}')::numeric;end if;
  elsif k='single_choice'then if not workforce_private.knowledge_uuid(v)or not exists(select 1 from jsonb_array_elements(f->'options')o where o->>'id'=v#>>'{}')then return false;end if;
  elsif k='multiple_choice'then if jsonb_typeof(v)is distinct from'array'or jsonb_array_length(v)>50 or(select count(distinct e::text)from jsonb_array_elements(v)e)<>jsonb_array_length(v)or exists(select 1 from jsonb_array_elements(v)e where not workforce_private.knowledge_uuid(e)or not exists(select 1 from jsonb_array_elements(f->'options')o where o->>'id'=e#>>'{}'))or complete and(f->>'required')::boolean and jsonb_array_length(v)=0 then return false;end if;
  else return false;end if;
 end loop;return true;
exception when others then return false;end$$;
create function workforce_private.forms_name_valid(c jsonb)returns boolean language sql immutable security invoker set search_path=''as $$select jsonb_typeof(c->'name')='string'and workforce_private.knowledge_nonblank(c->>'name')and workforce_private.knowledge_utf16(c->>'name')<=100 and jsonb_typeof(c->'description')='string'and workforce_private.knowledge_utf16(c->>'description')<=500$$;
create function workforce_private.forms_audience_valid(t uuid,a jsonb)returns boolean language plpgsql stable security definer set search_path=''as $$begin return jsonb_typeof(a)='array'and jsonb_array_length(a)<=500 and(select count(distinct lower(v#>>'{}'))from jsonb_array_elements(a)v)=jsonb_array_length(a)and not exists(select 1 from jsonb_array_elements(a)v where not workforce_private.knowledge_uuid(v)or not workforce_private.forms_eligible(t,(v#>>'{}')::uuid));exception when others then return false;end$$;
create function workforce_private.forms_schema_canonical(s jsonb)returns jsonb language sql immutable security invoker set search_path=''as $$select coalesce(jsonb_agg(case when f->>'kind'in('single_choice','multiple_choice')then jsonb_set(jsonb_set(f,'{id}',to_jsonb(lower(f->>'id'))),'{options}',(select jsonb_agg(jsonb_set(o,'{id}',to_jsonb(lower(o->>'id')))order by n)from jsonb_array_elements(f->'options')with ordinality v(o,n)))else jsonb_set(f,'{id}',to_jsonb(lower(f->>'id')))end order by i),'[]'::jsonb)from jsonb_array_elements(s)with ordinality x(f,i)$$;
create function workforce_private.forms_answers_canonical(s jsonb,a jsonb)returns jsonb language plpgsql immutable security invoker set search_path=''as $$declare result jsonb:='{}';e record;f jsonb;v jsonb;begin
 if jsonb_typeof(a)is distinct from'object'or(select count(distinct lower(key))from jsonb_each(a))<>(select count(*)from jsonb_each(a))then raise exception using errcode='22023',message='Invalid answer identity';end if;
 for e in select key,value from jsonb_each(a)loop select value into f from jsonb_array_elements(s)where value->>'id'=lower(e.key);v:=e.value;
 if f->>'kind'='single_choice'and workforce_private.knowledge_uuid(v)then v:=to_jsonb(lower(v#>>'{}'));elsif f->>'kind'='multiple_choice'and jsonb_typeof(v)='array'then select coalesce(jsonb_agg(case when workforce_private.knowledge_uuid(value)then to_jsonb(lower(value#>>'{}'))else value end),'[]'::jsonb)into v from jsonb_array_elements(v);end if;
 result:=result||jsonb_build_object(lower(e.key),v);end loop;return result;end$$;
create function workforce_private.forms_lock_audience(t uuid,a jsonb)returns void language plpgsql security definer set search_path=''as $$begin
 perform 1 from public.tenant_memberships m join auth.users u on u.id=m.user_id where m.tenant_id=t and m.user_id in(select(value#>>'{}')::uuid from jsonb_array_elements(a))order by m.user_id for share of m,u;end$$;
create function workforce_private.forms_locks(t uuid,a uuid,o uuid,history boolean default false)returns void language plpgsql security definer set search_path=''as $$begin perform pg_advisory_xact_lock(hashtextextended(a::text||':'||o::text,63));perform pg_advisory_xact_lock(hashtextextended(t::text,64));if history then perform pg_advisory_xact_lock(hashtextextended('forms-history',65));perform 1 from workforce_private.form_history_counter where form_history_counter.id for update;end if;end$$;
create function workforce_private.save_form(t uuid,o uuid,raw_change text)returns jsonb language plpgsql security definer set search_path=''as $$declare c jsonb;j json;act text;actor uuid:=auth.uid();r text;actor_name text;x public.forms;y public.form_responses;old workforce_private.form_operations;keys text[];new_answers jsonb;stamp timestamptz:=clock_timestamp();result jsonb;personal boolean;max_history integer;begin
 if t is null or o is null then raise exception using errcode='22023',message='Invalid form operation identity';end if;
 if actor is null or workforce_private.membership_role(t)is null then raise exception using errcode='42501',message='Forms unavailable';end if;
 if raw_change is null or octet_length(raw_change)+256>262144 then raise exception using errcode='22023',message='Form request too large';end if;
 j:=raw_change::json;if octet_length((j->'schema')::text)>131072 or octet_length((j->'answers')::text)>65536 then raise exception using errcode='22023',message='Form schema or answers too large';end if;if not workforce_private.forms_json_unique(j)then raise exception using errcode='22023',message='Duplicate form properties';end if;c:=j::jsonb;
 if jsonb_typeof(c)is distinct from'object'or octet_length(c::text)+256>262144 then raise exception using errcode='22023',message='Invalid form command';end if;act:=c->>'action';personal:=act in('save_progress','submit_response','edit_response');
 keys:=case act when'create_form'then array['action','allowRespondentEdit','audienceIds','description','name','schema']when'edit_form'then array['action','allowRespondentEdit','description','formId','formRevision','name','schema']when'set_audience'then array['action','audienceIds','formId','formRevision']when'publish_form'then array['action','formId','formRevision']when'archive_form'then array['action','formId','formRevision']when'restore_form'then array['action','formId','formRevision']when'save_progress'then array['action','answers','formId','formRevision','responseRevision']when'submit_response'then array['action','answers','formId','formRevision','responseRevision']when'edit_response'then array['action','answers','formId','formRevision','responseRevision']when'admin_edit_response'then array['action','answers','formId','formRevision','responseId','responseRevision']when'review_response'then array['action','formId','formRevision','responseId','responseRevision','reviewed']end;
 if keys is null or(select array_agg(key order by key)from jsonb_object_keys(c)key)is distinct from keys then raise exception using errcode='22023',message='Unknown form command properties';end if;
 if exists(select 1 from jsonb_each(c)where key in('formId','responseId')and not workforce_private.knowledge_uuid(value))or exists(select 1 from jsonb_each(c)where key in('formRevision','responseRevision')and(jsonb_typeof(value)is distinct from'number'or(value#>>'{}')!~'^(0|[1-9][0-9]{0,9})$'or(value#>>'{}')::numeric>2147483647 or key='formRevision'and(value#>>'{}')='0'))then raise exception using errcode='22023',message='Invalid form revision or identity';end if;
 if not personal and workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='Form management unavailable';end if;
 perform workforce_private.forms_locks(t,actor,o,act in('edit_response','admin_edit_response'));
 perform 1 from public.tenants where id=t for share;perform 1 from auth.users where id=actor for share;perform 1 from public.tenant_memberships where tenant_id=t and user_id=actor for share;r:=workforce_private.membership_role(t);select display_name into actor_name from public.tenant_memberships where tenant_id=t and user_id=actor;
 if r is null or not personal and r not in('owner','admin')then raise exception using errcode='42501',message='Forms unavailable';end if;
 if act<>'create_form'then select *into x from public.forms where tenant_id=t and id=(c->>'formId')::uuid for update;if not found or personal and workforce_private.forms_reader(t,x.id) is distinct from true then raise exception using errcode='42501',message='Form unavailable';end if;end if;
 select *into old from workforce_private.form_operations where tenant_id=t and actor_id=actor and operation_id=o;
 if found then if old.state='closed_absent'then if old.action<>act then raise exception using errcode='22023',message='Operation UUID bound to another action';end if;raise exception using errcode='40001',message='Operation was durably reconciled absent; choose a new operation';end if;if old.payload_hash is distinct from encode(sha256(convert_to(c::text,'UTF8')),'hex') then raise exception using errcode='22023',message='Operation UUID bound to another form command';end if;if workforce_private.forms_access(t,old.form_id,case when personal then'mine'else'manage'end) is distinct from true then raise exception using errcode='42501',message='Form receipt unavailable';end if;return old.result||jsonb_build_object('role',r);end if;
 if act<>'create_form'and x.revision<>(c->>'formRevision')::integer then raise exception using errcode='40001',message='Form changed; refresh and review';end if;
 if act in('create_form','edit_form')then if workforce_private.forms_name_valid(c)is distinct from true or jsonb_typeof(c->'allowRespondentEdit')is distinct from'boolean'or not workforce_private.forms_schema_valid(c->'schema')then raise exception using errcode='22023',message='Invalid form details or schema';end if;end if;
 if act in('create_form','set_audience')then if jsonb_typeof(c->'audienceIds')is distinct from'array'or exists(select 1 from jsonb_array_elements(c->'audienceIds')v where not workforce_private.knowledge_uuid(v))then raise exception using errcode='22023',message='Invalid audience identity';end if;perform workforce_private.forms_lock_audience(t,c->'audienceIds');if not workforce_private.forms_audience_valid(t,c->'audienceIds')then raise exception using errcode='22023',message='Choose eligible form recipients';end if;end if;
 stamp:=clock_timestamp();
 if act='create_form'then insert into public.forms(tenant_id,name,description,schema,allow_respondent_edit)values(t,c->>'name',c->>'description',workforce_private.forms_schema_canonical(c->'schema'),(c->>'allowRespondentEdit')::boolean)returning *into x;
 elsif act='edit_form'then if x.status='archived'then raise exception using errcode='40001',message='Archived forms are read only';end if;if x.schema_frozen and x.schema is distinct from workforce_private.forms_schema_canonical(c->'schema')then raise exception using errcode='40001',message='Published schema is immutable';end if;if x.revision=2147483647 then raise exception using errcode='40001',message='Form revision limit reached';end if;update public.forms set name=c->>'name',description=c->>'description',schema=workforce_private.forms_schema_canonical(c->'schema'),allow_respondent_edit=(c->>'allowRespondentEdit')::boolean,revision=revision+1,updated_at=stamp where id=x.id returning *into x;
 elsif act='set_audience'then if x.status='archived'or x.revision=2147483647 then raise exception using errcode='40001',message='Form assignment cannot change';end if;delete from public.form_assignments where tenant_id=t and form_id=x.id;update public.forms set revision=revision+1,updated_at=stamp where id=x.id returning *into x;
 elsif act='publish_form'then perform workforce_private.forms_lock_audience(t,(select coalesce(jsonb_agg(to_jsonb(actor_id)),'[]')from public.form_assignments where tenant_id=t and form_id=x.id));if x.status<>'draft'or x.revision=2147483647 or not exists(select 1 from jsonb_array_elements(x.schema)f where f->>'kind'<>'description')or not exists(select 1 from public.form_assignments where tenant_id=t and form_id=x.id)or exists(select 1 from public.form_assignments a where a.tenant_id=t and a.form_id=x.id and not workforce_private.forms_eligible(t,a.actor_id))then raise exception using errcode='40001',message='Publication requires answerable fields and eligible recipients';end if;update public.forms set status='published',schema_frozen=true,revision=revision+1,updated_at=stamp where id=x.id returning *into x;
 elsif act='archive_form'then if x.status='archived'or x.revision=2147483647 then raise exception using errcode='40001',message='Form cannot archive';end if;update public.forms set restore_status=status,status='archived',revision=revision+1,updated_at=stamp where id=x.id returning *into x;
 elsif act='restore_form'then if x.status<>'archived'or x.restore_status is null or x.revision=2147483647 then raise exception using errcode='40001',message='Form cannot restore';end if;update public.forms set status=restore_status,restore_status=null,revision=revision+1,updated_at=stamp where id=x.id returning *into x;
 else
  if x.status<>'published'then raise exception using errcode='40001',message='Only published forms accept response changes';end if;
  if personal then select *into y from public.form_responses where tenant_id=t and form_id=x.id and actor_id=actor for update;else select *into y from public.form_responses where tenant_id=t and form_id=x.id and id=(c->>'responseId')::uuid and status='submitted'for update;if not found then raise exception using errcode='42501',message='Submitted response unavailable';end if;end if;
  if coalesce(y.revision,0)<>(c->>'responseRevision')::integer then raise exception using errcode='40001',message='Response changed; refresh and review';end if;if y.revision=2147483647 then raise exception using errcode='40001',message='Response revision limit reached';end if;
  stamp:=clock_timestamp();
  if act='save_progress'and y.status='submitted'or act='submit_response'and y.status='submitted'or act='edit_response'and(y.status is distinct from'submitted'or not x.allow_respondent_edit)then raise exception using errcode='40001',message='Response action unavailable';end if;
  if act='review_response'then if jsonb_typeof(c->'reviewed')is distinct from'boolean'then raise exception using errcode='22023',message='Invalid review command';end if;update public.form_responses set reviewed=(c->>'reviewed')::boolean,reviewed_at=case when(c->>'reviewed')::boolean then stamp else null end,reviewed_by=case when(c->>'reviewed')::boolean then actor else null end,reviewer_name=case when(c->>'reviewed')::boolean then actor_name else null end,revision=revision+1,updated_at=stamp where id=y.id returning *into y;
  else
   new_answers:=workforce_private.forms_answers_canonical(x.schema,c->'answers');if not workforce_private.forms_answers_valid(x.schema,new_answers,act<>'save_progress')then raise exception using errcode='22023',message='Answers do not satisfy the form';end if;
   if act in('edit_response','admin_edit_response')then select retained_rows into max_history from workforce_private.form_history_counter where form_history_counter.id for update;if y.content_edits>=50 or max_history>=4096 then raise exception using errcode='54000',message='Retained answer history limit reached';end if;
    insert into workforce_private.form_response_history(tenant_id,response_id,revision,answers,status,submitted_at,updated_at,last_edited_by,last_editor_name,last_edited_at,reviewed,reviewed_at,reviewed_by,reviewer_name)values(t,y.id,y.revision,y.answers,y.status,y.submitted_at,y.updated_at,y.last_edited_by,y.last_editor_name,y.last_edited_at,y.reviewed,y.reviewed_at,y.reviewed_by,y.reviewer_name);update workforce_private.form_history_counter set retained_rows=retained_rows+1 where form_history_counter.id;
   end if;
   if y.id is null then insert into public.form_responses(tenant_id,form_id,actor_id,author_name,answers,schema,form_name,status,submitted_at,last_edited_by,last_editor_name,updated_at,last_edited_at)values(t,x.id,actor,actor_name,new_answers,x.schema,x.name,case when act='submit_response'then'submitted'else'in_progress'end,case when act='submit_response'then stamp else null end,actor,actor_name,stamp,stamp)returning *into y;
   else update public.form_responses set answers=new_answers,schema=x.schema,form_name=case when submitted_at is null then x.name else form_name end,status=case when act='save_progress'then'in_progress'else'submitted'end,submitted_at=case when act='save_progress'then null else coalesce(submitted_at,stamp)end,last_edited_by=actor,last_editor_name=actor_name,last_edited_at=stamp,updated_at=stamp,reviewed=false,reviewed_at=null,reviewed_by=null,reviewer_name=null,revision=revision+1,content_edits=content_edits+case when act in('edit_response','admin_edit_response')then 1 else 0 end where id=y.id returning *into y;end if;
  end if;
 end if;
 if act in('create_form','set_audience')then insert into public.form_assignments(tenant_id,form_id,actor_id,name)select t,x.id,(v#>>'{}')::uuid,m.display_name from jsonb_array_elements(c->'audienceIds')v join public.tenant_memberships m on m.tenant_id=t and m.user_id=(v#>>'{}')::uuid;end if;
 result:=jsonb_build_object('tenantId',t,'actorId',actor,'role',r,'operationId',o,'action',act,'formId',x.id,'formRevision',x.revision,'updatedAt',workforce_private.forms_time(case when y.id is not null then y.updated_at else x.updated_at end));if y.id is not null then result:=result||jsonb_build_object('responseId',y.id,'responseRevision',y.revision,'responseStatus',y.status,'submittedAt',workforce_private.forms_time(y.submitted_at));end if;
 insert into public.form_audit(tenant_id,form_id,response_id,actor_id,actor_name,action,form_revision,response_revision)values(t,x.id,y.id,actor,actor_name,act,x.revision,y.revision);
 insert into workforce_private.form_operations(tenant_id,actor_id,operation_id,form_id,response_id,action,payload_hash,result)values(t,actor,o,x.id,y.id,act,encode(sha256(convert_to(c::text,'UTF8')),'hex'),result);return result;
end$$;
create function public.save_form(target_tenant uuid,operation_id uuid,change_text text)returns jsonb language sql security invoker set search_path=''as $$select workforce_private.save_form(target_tenant,operation_id,change_text)$$;
create function workforce_private.reconcile_form_operation(t uuid,o uuid,act text)returns jsonb language plpgsql security definer set search_path=''as $$declare a uuid:=auth.uid();r text;receipt workforce_private.form_operations;personal boolean:=act in('save_progress','submit_response','edit_response');begin
 if t is null or o is null then raise exception using errcode='22023',message='Invalid form recovery identity';end if;
 if act is null or act not in('create_form','edit_form','set_audience','publish_form','archive_form','restore_form','save_progress','submit_response','edit_response','admin_edit_response','review_response')or a is null or workforce_private.membership_role(t)is null then raise exception using errcode='42501',message='Form recovery unavailable';end if;
 perform pg_advisory_xact_lock(hashtextextended(a::text||':'||o::text,63));r:=workforce_private.membership_role(t);if r is null or not personal and r not in('owner','admin')then raise exception using errcode='42501',message='Form recovery unavailable';end if;
 select *into receipt from workforce_private.form_operations where tenant_id=t and actor_id=a and operation_id=o;
 if found then if receipt.action<>act then raise exception using errcode='22023',message='Recovery action differs from operation';end if;if receipt.state='recorded'and workforce_private.forms_access(t,receipt.form_id,case when personal then'mine'else'manage'end) is distinct from true then raise exception using errcode='42501',message='Form recovery unavailable';end if;
 else insert into workforce_private.form_operations(tenant_id,actor_id,operation_id,action,state)values(t,a,o,act,'closed_absent')returning *into receipt;end if;
 return jsonb_build_object('tenantId',t,'actorId',a,'role',r,'operationId',o,'action',act,'status',case when receipt.state='closed_absent'then'not_recorded'else'recorded'end,'saved',case when receipt.state='closed_absent'then null else receipt.result||jsonb_build_object('role',r)end);end$$;
create function public.reconcile_form_operation(target_tenant uuid,operation_id uuid,action_name text)returns jsonb language sql volatile security invoker set search_path=''as $$select workforce_private.reconcile_form_operation(target_tenant,operation_id,action_name)$$;
create function workforce_private.forms_version(t uuid,mode text,f uuid default null)returns text language plpgsql stable security definer set search_path=''as $$begin
 if workforce_private.membership_role(t)is null or mode='manage'and workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='Forms unavailable';end if;
 return md5(jsonb_build_array((select coalesce(jsonb_agg(jsonb_build_array(x.id,x.revision,x.status,(select coalesce(jsonb_agg(jsonb_build_array(a.actor_id,workforce_private.forms_eligible(t,a.actor_id))order by a.actor_id),'[]')from public.form_assignments a where a.tenant_id=t and a.form_id=x.id))order by x.id),'[]')from public.forms x where x.tenant_id=t and(f is null or x.id=f)and(mode='manage'or workforce_private.forms_reader(t,x.id))),(select coalesce(jsonb_agg(jsonb_build_array(y.id,y.revision,y.status)order by y.id),'[]')from public.form_responses y where y.tenant_id=t and(f is null or y.form_id=f)and(mode='manage'and y.status='submitted'or mode='mine'and y.actor_id=auth.uid()and workforce_private.forms_reader(t,y.form_id))),(select retained_rows<4096 from workforce_private.form_history_counter where form_history_counter.id),(select jsonb_build_array(name,time_zone)from public.tenants where id=t))::text);
end$$;
create function workforce_private.forms_roster_version(t uuid)returns text language plpgsql stable security definer set search_path=''as $$begin if workforce_private.membership_role(t)not in('owner','admin')or workforce_private.membership_role(t)is null then raise exception using errcode='42501',message='Form roster unavailable';end if;return md5((select coalesce(jsonb_agg(jsonb_build_array(m.user_id,m.display_name,m.status,a.email_confirmed_at,a.is_anonymous)order by m.user_id),'[]')from public.tenant_memberships m join auth.users a on a.id=m.user_id where m.tenant_id=t)::text);end$$;
create function workforce_private.forms_response_json(t uuid,id uuid,mode text,include_answers boolean default false)returns jsonb language plpgsql stable security definer set search_path=''as $$declare y public.form_responses;x public.forms;can_edit boolean;res jsonb;begin
 select *into y from public.form_responses where tenant_id=t and form_responses.id=forms_response_json.id;if not found then raise exception using errcode='42501',message='Response unavailable';end if;
 if mode='manage'then if workforce_private.membership_role(t)not in('owner','admin')or workforce_private.membership_role(t)is null or y.status<>'submitted'then raise exception using errcode='42501',message='Submitted response unavailable';end if;
 elsif mode is distinct from'mine'or y.actor_id is distinct from auth.uid()or workforce_private.forms_reader(t,y.form_id) is distinct from true then raise exception using errcode='42501',message='Own response unavailable';end if;
 select *into x from public.forms where tenant_id=t and forms.id=y.form_id;can_edit:=x.status='published'and y.status='submitted'and y.revision<2147483647 and y.content_edits<50 and(select retained_rows<4096 from workforce_private.form_history_counter where form_history_counter.id)and(mode='manage'or x.allow_respondent_edit);
 res:=jsonb_build_object('id',y.id,'formId',y.form_id,'actorId',y.actor_id,'authorName',y.author_name,'revision',y.revision,'status',y.status,'submittedAt',workforce_private.forms_time(y.submitted_at),'updatedAt',workforce_private.forms_time(y.updated_at),'lastEditedBy',y.last_edited_by,'lastEditorName',y.last_editor_name,'lastEditedAt',workforce_private.forms_time(y.last_edited_at),'reviewed',y.reviewed,'reviewedAt',workforce_private.forms_time(y.reviewed_at),'reviewedBy',y.reviewed_by,'reviewerName',y.reviewer_name,'canEdit',can_edit,'canReview',mode='manage'and x.status='published'and y.revision<2147483647);
 if include_answers then res:=res||jsonb_build_object('answers',y.answers,'schema',y.schema,'formName',y.form_name);end if;return res;
end$$;
create function workforce_private.forms_form_json(t uuid,id uuid,mode text)returns jsonb language plpgsql stable security definer set search_path=''as $$declare x public.forms;y public.form_responses;mine boolean;own jsonb:=null;begin
 if workforce_private.forms_access(t,id,mode) is distinct from true then raise exception using errcode='42501',message='Form unavailable';end if;select *into x from public.forms where tenant_id=t and forms.id=forms_form_json.id;mine:=exists(select 1 from public.form_assignments where tenant_id=t and form_id=forms_form_json.id and actor_id=auth.uid());
 if mode='mine'then select *into y from public.form_responses where tenant_id=t and form_id=forms_form_json.id and actor_id=auth.uid();if found then own:=jsonb_build_object('id',y.id,'revision',y.revision,'status',y.status,'submittedAt',workforce_private.forms_time(y.submitted_at),'updatedAt',workforce_private.forms_time(y.updated_at));end if;end if;
 return jsonb_build_object('id',x.id,'name',x.name,'description',x.description,'status',x.status,'restoreStatus',x.restore_status,'revision',x.revision,'schemaFrozen',x.schema_frozen,'allowRespondentEdit',x.allow_respondent_edit,'isAssigned',mine,'audienceCount',case when mode='manage'then(select count(*)from public.form_assignments where tenant_id=t and form_id=forms_form_json.id)else null end,'eligibleAudienceCount',case when mode='manage'then(select count(*)from public.form_assignments a where a.tenant_id=t and a.form_id=forms_form_json.id and workforce_private.forms_eligible(t,a.actor_id))else null end,'createdAt',workforce_private.forms_time(x.created_at),'updatedAt',workforce_private.forms_time(x.updated_at),'ownResponse',own,'capabilities',jsonb_build_object('canEdit',mode='manage'and x.status<>'archived'and x.revision<2147483647,'canPublish',mode='manage'and x.status='draft'and x.revision<2147483647 and exists(select 1 from public.form_assignments where tenant_id=t and form_id=forms_form_json.id)and exists(select 1 from jsonb_array_elements(x.schema)f where f->>'kind'<>'description')and not exists(select 1 from public.form_assignments a where a.tenant_id=t and a.form_id=forms_form_json.id and not workforce_private.forms_eligible(t,a.actor_id)),'canArchive',mode='manage'and x.status<>'archived'and x.revision<2147483647,'canRestore',mode='manage'and x.status='archived'and x.revision<2147483647,'canSaveProgress',mode='mine'and mine and y.status is distinct from'submitted'and coalesce(y.revision,0)<2147483647,'canSubmit',mode='mine'and mine and y.status is distinct from'submitted'and coalesce(y.revision,0)<2147483647,'canEditResponse',mode='mine'and mine and coalesce(y.status='submitted',false)and x.allow_respondent_edit and y.revision<2147483647 and y.content_edits<50 and(select retained_rows<4096 from workforce_private.form_history_counter where form_history_counter.id),'canViewResponses',mode='manage'));
end$$;
create function workforce_private.forms_roster(t uuid,q text,n integer,after_key text default null,after_id uuid default null)returns jsonb language plpgsql stable security definer set search_path=''as $$declare rows jsonb;next_item jsonb;total bigint;begin
 if workforce_private.membership_role(t)is null or workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='Form roster unavailable';end if;
 select count(*)into total from public.tenant_memberships m join auth.users a on a.id=m.user_id where m.tenant_id=t and m.status='active'and a.email_confirmed_at is not null and a.is_anonymous is not true and strpos(lower(m.display_name),lower(q))>0;
 with eligible as(select m.user_id,m.display_name,lower(m.display_name)k from public.tenant_memberships m join auth.users a on a.id=m.user_id where m.tenant_id=t and m.status='active'and a.email_confirmed_at is not null and a.is_anonymous is not true and strpos(lower(m.display_name),lower(q))>0 and(after_id is null or(lower(m.display_name),m.user_id)>(after_key,after_id))order by lower(m.display_name),m.user_id limit n+1),page as(select *from eligible order by k,user_id limit n)
 select coalesce((select jsonb_agg(jsonb_build_object('actorId',user_id,'name',display_name,'eligible',true)order by k,user_id)from page),'[]'),case when(select count(*)from eligible)>n then(select jsonb_build_object('id',user_id,'key',k)from page order by k desc,user_id desc limit 1)else null end into rows,next_item;
 return jsonb_build_object('users',rows,'matchedCount',total,'position',next_item);end$$;
create function workforce_private.forms_history(t uuid,f uuid,r uuid,n integer,after_revision integer default null)returns jsonb language plpgsql stable security definer set search_path=''as $$declare rows jsonb;next_item jsonb;y public.form_responses;total bigint;begin
 if n is null or n not between 1 and 10 then raise exception using errcode='22023',message='History page must contain 1 to 10 records';end if;
 if workforce_private.membership_role(t)is null or workforce_private.membership_role(t)not in('owner','admin')then raise exception using errcode='42501',message='Response history unavailable';end if;select *into y from public.form_responses where tenant_id=t and form_id=f and id=r and status='submitted';if not found then raise exception using errcode='42501',message='Submitted response unavailable';end if;
 select count(*)into total from workforce_private.form_response_history where tenant_id=t and response_id=r;
 with available as(select *from workforce_private.form_response_history where tenant_id=t and response_id=r and(after_revision is null or revision<after_revision)order by revision desc limit n+1),page as(select *from available order by revision desc limit n)
 select coalesce((select jsonb_agg(jsonb_build_object('id',id,'responseId',response_id,'revision',revision,'answers',answers,'formName',y.form_name,'status',status,'submittedAt',workforce_private.forms_time(submitted_at),'updatedAt',workforce_private.forms_time(updated_at),'lastEditedBy',last_edited_by,'lastEditorName',last_editor_name,'lastEditedAt',workforce_private.forms_time(last_edited_at),'reviewed',reviewed,'reviewedAt',workforce_private.forms_time(reviewed_at),'reviewedBy',reviewed_by,'reviewerName',reviewer_name,'retainedAt',workforce_private.forms_time(retained_at))order by revision desc)from page),'[]'),case when(select count(*)from available)>n then(select jsonb_build_object('id',id,'key',revision::text)from page order by revision limit 1)else null end into rows,next_item;
 return jsonb_build_object('history',rows,'historyCount',total,'position',next_item);end$$;
create function workforce_private.forms_assignees(t uuid,f uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$begin
 if workforce_private.forms_access(t,f,'manage') is distinct from true then raise exception using errcode='42501',message='Form audience unavailable';end if;
 return(select coalesce(jsonb_agg(jsonb_build_object('actorId',a.actor_id,'name',a.name,'eligible',workforce_private.forms_eligible(t,a.actor_id))order by a.actor_id),'[]')from public.form_assignments a where a.tenant_id=t and a.form_id=f);end$$;
create function workforce_private.forms_time(v timestamptz)returns text language sql immutable security invoker set search_path=''as $$select to_char(v at time zone'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')$$;
create function workforce_private.forms_position_valid(t uuid,kind text,f uuid,r uuid,id uuid,key text,q text)returns boolean language plpgsql stable security definer set search_path=''as $$begin
 if workforce_private.membership_role(t)is null or workforce_private.membership_role(t)not in('owner','admin')then return false;end if;
 if kind='roster'then return exists(select 1 from public.tenant_memberships m join auth.users a on a.id=m.user_id where m.tenant_id=t and m.user_id=forms_position_valid.id and lower(m.display_name)=key and strpos(lower(m.display_name),lower(q))>0 and m.status='active'and a.email_confirmed_at is not null and a.is_anonymous is not true);
 elsif kind='response'then return exists(select 1 from workforce_private.form_response_history h join public.form_responses y on y.tenant_id=h.tenant_id and y.id=h.response_id where y.tenant_id=t and y.form_id=f and y.id=r and y.status='submitted'and h.id=forms_position_valid.id and h.revision::text=key);end if;return false;end$$;
create function public.read_forms(target_tenant uuid,read_kind text default'catalog',read_view text default'mine',target_form uuid default null,target_response uuid default null,status_filter text default'all',review_filter text default'all',search_text text default'',page_limit integer default 50,after_item jsonb default null)returns jsonb language plpgsql stable security invoker set search_path=''as $$declare r text:=workforce_private.membership_role(target_tenant);identity jsonb;scope jsonb;version text;rows jsonb;counts jsonb;position jsonb:=null;extra jsonb;res jsonb;x public.forms;y public.form_responses;cursor_key text;cursor_id uuid;begin
 if r is null or read_view is null or read_kind is null or read_view not in('mine','manage')or read_kind not in('catalog','form','roster','responses','response')or read_view='manage'and r not in('owner','admin')or read_kind in('roster','responses','response')and(read_view<>'manage'or r not in('owner','admin'))then raise exception using errcode='42501',message='Forms unavailable';end if;
 if page_limit is null or page_limit not between 1 and(case when read_kind='response'then 10 else 100 end)or search_text is null or workforce_private.knowledge_utf16(search_text)>100 or octet_length(search_text)>512 or review_filter is null or status_filter is null or review_filter not in('all','reviewed','not_reviewed')or read_kind='catalog'and status_filter not in('all','draft','published','archived')or read_kind='responses'and status_filter not in('all','submitted')then raise exception using errcode='22023',message='Invalid Forms query';end if;
 if read_kind in('catalog','roster')and target_form is not null or read_kind<>'response'and target_response is not null or read_kind<>'responses'and review_filter<>'all'or read_kind in('form','roster','response')and status_filter<>'all'or read_kind in('form','response')and search_text<>''or read_kind='form'and after_item is not null then raise exception using errcode='22023',message='Unsupported Forms query';end if;
 if read_kind in('form','responses','response')then if workforce_private.forms_access(target_tenant,target_form,read_view) is distinct from true then raise exception using errcode='42501',message='Form unavailable';end if;select *into x from public.forms where tenant_id=target_tenant and forms.id=target_form;end if;
 if read_kind='response'then select *into y from public.form_responses where tenant_id=target_tenant and form_id=target_form and form_responses.id=target_response and status='submitted';if not found then raise exception using errcode='42501',message='Submitted response unavailable';end if;end if;
 version:=case when read_kind='roster'then workforce_private.forms_roster_version(target_tenant)else workforce_private.forms_version(target_tenant,read_view,case when read_kind='catalog'then null else target_form end)end;
 identity:=jsonb_build_object('tenantId',target_tenant,'actorId',auth.uid(),'role',r);scope:=identity||jsonb_build_object('kind',read_kind,'view',read_view,'formId',target_form,'responseId',target_response,'status',status_filter,'review',review_filter,'search',search_text,'version',version);
 if after_item is not null then
  if jsonb_typeof(after_item)is distinct from'object'or(select array_agg(k order by k)from jsonb_object_keys(after_item)k)is distinct from array['position','scope']or jsonb_typeof(after_item->'position')is distinct from'object'or(select array_agg(k order by k)from jsonb_object_keys(after_item->'position')k)is distinct from array['id','key']or not workforce_private.knowledge_uuid(after_item->'position'->'id')or jsonb_typeof(after_item->'position'->'key')is distinct from'string'or workforce_private.knowledge_utf16(after_item->'position'->>'key')>200 then raise exception using errcode='22023',message='Invalid Forms cursor';end if;
  if after_item->'scope'is distinct from scope then raise exception using errcode='40001',message='Forms scope or collection changed';end if;cursor_id:=(after_item->'position'->>'id')::uuid;cursor_key:=after_item->'position'->>'key';
 end if;
 res:=identity||jsonb_build_object('serverTime',workforce_private.forms_time(clock_timestamp()));
 if read_kind='catalog'then
  with visible as(select *from public.forms f where f.tenant_id=target_tenant and(read_view='manage'or workforce_private.forms_reader(target_tenant,f.id))and strpos(lower(f.name),lower(search_text))>0)
  select jsonb_build_object('total',count(*),'draft',count(*)filter(where status='draft'),'published',count(*)filter(where status='published'),'archived',count(*)filter(where status='archived'))into counts from visible;
  if cursor_id is not null and not exists(select 1 from public.forms f where f.tenant_id=target_tenant and f.id=cursor_id and f.created_at=cursor_key::timestamptz and(read_view='manage'or workforce_private.forms_reader(target_tenant,f.id))and(status_filter='all'or f.status=status_filter)and strpos(lower(f.name),lower(search_text))>0)then raise exception using errcode='40001',message='Forms cursor changed';end if;
  with available as(select *from public.forms f where f.tenant_id=target_tenant and(read_view='manage'or workforce_private.forms_reader(target_tenant,f.id))and(status_filter='all'or f.status=status_filter)and strpos(lower(f.name),lower(search_text))>0 and(cursor_id is null or(f.created_at,f.id)<(cursor_key::timestamptz,cursor_id))order by created_at desc,f.id desc limit page_limit+1),page as(select *from available order by created_at desc,id desc limit page_limit)
  select coalesce((select jsonb_agg(workforce_private.forms_form_json(target_tenant,p.id,read_view)order by created_at desc,p.id desc)from page p),'[]'),case when(select count(*)from available)>page_limit then(select jsonb_build_object('id',p.id,'key',workforce_private.forms_time(created_at))from page p order by created_at,p.id limit 1)else null end into rows,position;
  res:=res||jsonb_build_object('view',read_view,'company',(select jsonb_build_object('id',t.id,'name',name,'time_zone',time_zone)from public.tenants t where t.id=target_tenant),'forms',rows,'counts',counts,'catalogVersion',version,'capabilities',jsonb_build_object('canManage',r in('owner','admin')));
 elsif read_kind='form'then
  res:=res||jsonb_build_object('view',read_view,'company',(select jsonb_build_object('id',t.id,'name',name,'time_zone',time_zone)from public.tenants t where t.id=target_tenant),'form',workforce_private.forms_form_json(target_tenant,target_form,read_view),'schema',x.schema,'collectionVersion',version);
  if read_view='mine'then select *into y from public.form_responses where tenant_id=target_tenant and form_id=target_form and actor_id=auth.uid();res:=res||jsonb_build_object('response',case when y.id is not null then workforce_private.forms_response_json(target_tenant,y.id,'mine',true)else null end);
  else res:=res||jsonb_build_object('assignees',workforce_private.forms_assignees(target_tenant,target_form));end if;return res;
 elsif read_kind='roster'then if cursor_id is not null and not workforce_private.forms_position_valid(target_tenant,'roster',null,null,cursor_id,cursor_key,search_text)then raise exception using errcode='40001',message='Roster cursor changed';end if;extra:=workforce_private.forms_roster(target_tenant,search_text,page_limit,cursor_key,cursor_id);position:=extra->'position';res:=res||(extra-'position')||jsonb_build_object('rosterVersion',version);
 elsif read_kind='responses'then
  select jsonb_build_object('total',count(*),'reviewed',count(*)filter(where reviewed),'notReviewed',count(*)filter(where not reviewed))into counts from public.form_responses z where z.tenant_id=target_tenant and z.form_id=target_form and z.status='submitted'and strpos(lower(z.author_name),lower(search_text))>0;
  if cursor_id is not null and not exists(select 1 from public.form_responses z where z.tenant_id=target_tenant and z.form_id=target_form and z.id=cursor_id and z.status='submitted'and z.submitted_at=cursor_key::timestamptz and strpos(lower(z.author_name),lower(search_text))>0 and(review_filter='all'or review_filter='reviewed'and z.reviewed or review_filter='not_reviewed'and not z.reviewed))then raise exception using errcode='40001',message='Response cursor changed';end if;
  with available as(select *from public.form_responses z where z.tenant_id=target_tenant and z.form_id=target_form and z.status='submitted'and strpos(lower(z.author_name),lower(search_text))>0 and(review_filter='all'or review_filter='reviewed'and z.reviewed or review_filter='not_reviewed'and not z.reviewed)and(cursor_id is null or(z.submitted_at,z.id)<(cursor_key::timestamptz,cursor_id))order by submitted_at desc,z.id desc limit page_limit+1),page as(select *from available order by submitted_at desc,id desc limit page_limit)
  select coalesce((select jsonb_agg(workforce_private.forms_response_json(target_tenant,p.id,'manage')order by submitted_at desc,p.id desc)from page p),'[]'),case when(select count(*)from available)>page_limit then(select jsonb_build_object('id',p.id,'key',workforce_private.forms_time(submitted_at))from page p order by submitted_at,p.id limit 1)else null end into rows,position;
  res:=res||jsonb_build_object('form',workforce_private.forms_form_json(target_tenant,target_form,'manage'),'responses',rows,'counts',counts,'collectionVersion',version);
 else
  if cursor_id is not null and(cursor_key!~'^[1-9][0-9]{0,9}$'or cursor_key::numeric>2147483647 or not workforce_private.forms_position_valid(target_tenant,'response',target_form,target_response,cursor_id,cursor_key,''))then raise exception using errcode='22023',message='Invalid response history cursor';end if;
  extra:=workforce_private.forms_history(target_tenant,target_form,target_response,page_limit,case when cursor_id is null then null else cursor_key::integer end);position:=extra->'position';res:=res||(extra-'position')||jsonb_build_object('form',workforce_private.forms_form_json(target_tenant,target_form,'manage'),'response',workforce_private.forms_response_json(target_tenant,target_response,'manage',true),'collectionVersion',version);
 end if;
 return res||jsonb_build_object('nextCursor',case when position is null or position='null'::jsonb then null else jsonb_build_object('scope',scope,'position',position)end);
end$$;
create function public.read_forms_access(target_tenant uuid,read_kind text default'catalog',read_view text default'mine',target_form uuid default null,target_response uuid default null)returns jsonb language plpgsql stable security invoker set search_path=''as $$declare r text:=workforce_private.membership_role(target_tenant);x public.forms;y public.form_responses;begin
 if r is null or read_view is null or read_kind is null or read_view not in('mine','manage')or read_kind not in('catalog','form','roster','responses','response')or read_view='manage'and r not in('owner','admin')or read_kind in('roster','responses','response')and(read_view<>'manage'or r not in('owner','admin'))then raise exception using errcode='42501',message='Forms unavailable';end if;
 if read_kind in('form','responses','response')then if workforce_private.forms_access(target_tenant,target_form,read_view) is distinct from true then raise exception using errcode='42501',message='Form unavailable';end if;select *into x from public.forms where tenant_id=target_tenant and id=target_form;end if;
 if read_kind='response'then select *into y from public.form_responses where tenant_id=target_tenant and form_id=target_form and id=target_response and status='submitted';if not found then raise exception using errcode='42501',message='Submitted response unavailable';end if;end if;
 return jsonb_build_object('tenantId',target_tenant,'actorId',auth.uid(),'role',r,'view',read_view,'collectionVersion',case when read_kind='roster'then workforce_private.forms_roster_version(target_tenant)else workforce_private.forms_version(target_tenant,read_view,case when read_kind='catalog'then null else target_form end)end,'formRevision',x.revision,'responseRevision',y.revision);end$$;
-- Explicit default-ACL defense on every new helper/RPC; no baseline ACL is changed.
do $$declare fn record;begin
 for fn in select p.oid::regprocedure f from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','workforce_private')and(p.proname like'forms\_%'escape'\'or p.proname in('save_form','reconcile_form_operation','read_forms','read_forms_access'))loop execute format('revoke all on function %s from public,anon,authenticated,service_role',fn.f);end loop;
 for fn in select p.oid::regprocedure f from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname in('save_form','reconcile_form_operation','read_forms','read_forms_access')or n.nspname='workforce_private'and p.proname in('forms_reader','forms_access','forms_assignees','forms_version','forms_roster_version','forms_form_json','forms_response_json','forms_roster','forms_history','forms_time','forms_position_valid','save_form','reconcile_form_operation')loop execute format('grant execute on function %s to authenticated',fn.f);end loop;
end$$;
