-- Proposed additive Day/Week templates. Root assigns actual registration timestamp.
-- No previously applied function, relation, policy or trigger is replaced.
begin;
create table public.rota_period_templates (
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null,schedule_id uuid not null,
 kind text not null check(kind in('day','week')),title text not null check(workforce_private.knowledge_utf16(title) between 1 and 100),
 source_anchor date not null,source_zone text not null,source_schedule_revision integer not null check(source_schedule_revision>0),source_filters jsonb not null,
 entry_count integer not null check(entry_count between 1 and 5000),user_count integer not null check(user_count between 1 and entry_count),elapsed_micros bigint not null check(elapsed_micros between 1 and 432000000000000),
 revision integer not null default 1 check(revision>0),creator_id uuid not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,
 unique(tenant_id,schedule_id,id),foreign key(tenant_id,schedule_id) references public.rota_schedules(tenant_id,id)
);
create index rota_period_catalogue on public.rota_period_templates(tenant_id,schedule_id,kind,(lower(title) collate "C"),id) where deleted_at is null;
create table public.rota_period_entries (
 tenant_id uuid not null,schedule_id uuid not null,template_id uuid not null,entry_index integer not null check(entry_index between 0 and 4999),
 source_shift_id uuid not null,agent_id uuid not null,job_id uuid not null,snapshot jsonb not null,
 primary key(tenant_id,schedule_id,template_id,entry_index),unique(tenant_id,schedule_id,template_id,source_shift_id),
 foreign key(tenant_id,schedule_id,template_id) references public.rota_period_templates(tenant_id,schedule_id,id)
);
create table public.rota_period_audit (
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null,schedule_id uuid not null,template_id uuid not null,actor_id uuid not null,operation_id uuid not null,
 action text not null check(action in('save','rename','delete','add')),template_revision integer not null check(template_revision>0),schedule_revision integer not null check(schedule_revision>0),occurred_at timestamptz not null default now(),
 unique(tenant_id,schedule_id,template_id,id),foreign key(tenant_id,schedule_id,template_id) references public.rota_period_templates(tenant_id,schedule_id,id)
);
create table public.rota_period_generated (
 tenant_id uuid not null,schedule_id uuid not null,template_id uuid not null,audit_id uuid not null,entry_index integer not null,shift_id uuid not null,snapshot jsonb not null,
 primary key(tenant_id,schedule_id,template_id,audit_id,entry_index),unique(tenant_id,shift_id),
 foreign key(tenant_id,schedule_id,template_id,audit_id) references public.rota_period_audit(tenant_id,schedule_id,template_id,id),
 foreign key(tenant_id,schedule_id,template_id,entry_index) references public.rota_period_entries(tenant_id,schedule_id,template_id,entry_index)
);
create table workforce_private.rota_period_operations (
 tenant_id uuid not null,actor_id uuid not null,operation_id uuid not null,schedule_id uuid not null,action text not null check(action in('save','rename','delete','add')),target_template_id uuid,
 state text not null check(state in('recorded','closed_absent')),payload_hash text,result jsonb,
 primary key(tenant_id,actor_id,operation_id),foreign key(tenant_id,schedule_id) references public.rota_schedules(tenant_id,id),
 check((state='recorded' and payload_hash~'^[0-9a-f]{64}$' and result is not null) or (state='closed_absent' and payload_hash is null and result is null))
);
alter table public.rota_period_templates enable row level security;
alter table public.rota_period_entries enable row level security;
alter table public.rota_period_audit enable row level security;
alter table public.rota_period_generated enable row level security;
alter table workforce_private.rota_period_operations enable row level security;
revoke all on public.rota_period_templates,public.rota_period_entries,public.rota_period_audit,public.rota_period_generated,workforce_private.rota_period_operations from public,anon,authenticated,service_role;

create function workforce_private.rota_period_utc(v timestamptz) returns text language plpgsql immutable set search_path='' as $$begin if v is null then return null;end if;if v<timestamptz '0001-01-01 00:00:00+00'or v>=timestamptz '10000-01-01 00:00:00+00'then raise exception using errcode='22023',message='Unsupported source endpoint';end if;return to_char(v at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"');end$$;
create function workforce_private.rota_period_source_utc(v timestamptz,zone text) returns text language plpgsql stable set search_path='' as $$begin if v at time zone zone<timestamp '0001-01-01'or v at time zone zone>=timestamp '10000-01-01'then raise exception using errcode='22023',message='Unsupported source endpoint';end if;return workforce_private.rota_period_utc(v);end$$;
create function workforce_private.rota_period_hash(v jsonb) returns text language sql immutable set search_path='' as $$select encode(sha256(convert_to(v::text,'UTF8')),'hex')$$;
create function workforce_private.rota_period_keys(v jsonb,required text[],optional text[] default array[]::text[]) returns void language plpgsql immutable set search_path='' as $$begin
 if v is null or jsonb_typeof(v)<>'object' or not v ?& required or v-(required||optional)<>'{}'::jsonb then raise exception using errcode='22023',message='Invalid period fields';end if;
end$$;
create function workforce_private.rota_period_number(v jsonb,lo bigint,hi bigint) returns bigint language plpgsql immutable set search_path='' as $$begin
 if jsonb_typeof(v) is distinct from 'number' or v::text !~ '^[0-9]{1,16}$' or v::numeric not between lo and hi then raise exception using errcode='22023',message='Invalid period number';end if;return v::text::bigint;end$$;
create function workforce_private.rota_period_text(v jsonb,maximum integer,nonblank boolean default false) returns text language plpgsql immutable set search_path='' as $$declare s text;begin
 if jsonb_typeof(v) is distinct from 'string' then raise exception using errcode='22023',message='Invalid period text';end if;s:=v#>>'{}';if workforce_private.knowledge_utf16(s)>maximum or (nonblank and btrim(s)='') then raise exception using errcode='22023',message='Invalid period text length';end if;return s;end$$;
create function workforce_private.rota_period_uuid(v jsonb) returns uuid language plpgsql immutable set search_path='' as $$declare s text;begin s:=workforce_private.rota_period_text(v,36);if s !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then raise exception using errcode='22023',message='Invalid period identity';end if;return s::uuid;end$$;
create function workforce_private.rota_period_date(v jsonb,k text) returns date language plpgsql immutable set search_path='' as $$declare s text;d date;begin s:=workforce_private.rota_period_text(v,10);if s!~'^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or s<'0001-01-01' or s>'9999-12-31' or k not in('day','week') then raise exception using errcode='22023',message='Invalid period date';end if;d:=s::date;if to_char(d,'YYYY-MM-DD')<>s or(k='week' and extract(isodow from d)<>1)then raise exception using errcode='22023',message='Week date must be Monday';end if;return d;end$$;
create function workforce_private.rota_period_filters(v jsonb) returns jsonb language plpgsql immutable set search_path='' as $$declare j uuid;s text;q text;begin
 perform workforce_private.rota_period_keys(v,array['jobId','status','workerSearch']);if v->'jobId'<>'null'::jsonb then j:=workforce_private.rota_period_uuid(v->'jobId');end if;s:=workforce_private.rota_period_text(v->'status',10);q:=workforce_private.rota_period_text(v->'workerSearch',100);if s not in('all','draft','published')then raise exception using errcode='22023',message='Invalid source status';end if;return jsonb_build_object('jobId',j,'status',s,'workerSearch',q);end$$;
create function workforce_private.rota_period_access(t uuid,sid uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare s public.rota_schedules;r text;begin
 r:=workforce_private.membership_role(t);if auth.uid() is null or r is null or workforce_private.rota_manage(t,sid) is distinct from true then raise exception using errcode='42501',message='Period access unavailable';end if;select * into s from public.rota_schedules where tenant_id=t and id=sid;if not found then raise exception using errcode='42501',message='Period access unavailable';end if;
 return jsonb_build_object('schemaVersion',1,'tenantId',t,'actorId',auth.uid(),'schedule',jsonb_build_object('id',s.id,'revision',s.revision,'time_zone',s.time_zone,'status',s.status),'companyUsageVisible',r in('owner','admin'));
end$$;
create function workforce_private.rota_period_metadata(x public.rota_period_templates) returns jsonb language sql stable set search_path='' as $$select jsonb_build_object('id',(x).id,'tenant_id',(x).tenant_id,'schedule_id',(x).schedule_id,'kind',(x).kind,'title',(x).title,'source_anchor',to_char((x).source_anchor,'YYYY-MM-DD'),'source_zone',(x).source_zone,'source_schedule_revision',(x).source_schedule_revision,'source_filters',(x).source_filters,'entry_count',(x).entry_count,'user_count',(x).user_count,'elapsed_micros',(x).elapsed_micros,'revision',(x).revision,'created_at',workforce_private.rota_period_utc((x).created_at),'updated_at',workforce_private.rota_period_utc((x).updated_at))$$;
create function workforce_private.rota_period_availability(t uuid,sid uuid,aid uuid,jid uuid) returns jsonb language sql stable security definer set search_path='' as $$
 select jsonb_build_object('workerAvailable',exists(select 1 from public.agents a join public.rota_agents r on r.tenant_id=a.tenant_id and r.agent_id=a.id and r.schedule_id=sid where a.tenant_id=t and a.id=aid and a.status='active' and(a.user_id is null or exists(select 1 from public.tenant_memberships m where m.tenant_id=t and m.user_id=a.user_id and m.status='active'))),'jobAvailable',exists(select 1 from public.rota_jobs where tenant_id=t and schedule_id=sid and id=jid),'currentAgentName',(select btrim(first_name)||' '||btrim(last_name) from public.agents where tenant_id=t and id=aid),'currentJobName',(select btrim(name) from public.rota_jobs where tenant_id=t and schedule_id=sid and id=jid),'currentJobColor',(select color from public.rota_jobs where tenant_id=t and schedule_id=sid and id=jid))
$$;
-- Integer decomposition avoids floating point precision loss in timestamp construction.
create function workforce_private.rota_period_wall(d date,off integer,clock bigint) returns timestamp language sql immutable set search_path='' as $$select (d+off)::timestamp+make_interval(secs=>(clock/1000000)::integer)+((clock%1000000)::text||' microseconds')::interval$$;
create function workforce_private.rota_period_endpoint(local_time timestamp,zone text,choice text) returns jsonb language plpgsql stable set search_path='' as $$declare v timestamptz;begin
 if local_time is null or local_time<timestamp '0001-01-01'or local_time>=timestamp '10000-01-01'then return jsonb_build_object('instant',null,'diagnostic','unsupported_endpoint');end if;
 if choice is null or choice not in('','earlier','later') then raise exception using errcode='22023',message='Invalid endpoint choice';end if;
 begin v:=workforce_private.rota_template_instant(local_time,zone,'');if choice<>'' then return jsonb_build_object('instant',null,'diagnostic','occurrence');end if;return jsonb_build_object('instant',workforce_private.rota_period_utc(v),'diagnostic',null);
 exception when sqlstate '22008' then
 if choice='' then return jsonb_build_object('instant',null,'diagnostic','ambiguous');end if;v:=workforce_private.rota_template_instant(local_time,zone,choice);if v<timestamptz '0001-01-01 00:00:00+00'or v>=timestamptz '10000-01-01 00:00:00+00'then return jsonb_build_object('instant',null,'diagnostic','unsupported_endpoint');end if;return jsonb_build_object('instant',workforce_private.rota_period_utc(v),'diagnostic',null);
 when sqlstate '22007' then return jsonb_build_object('instant',null,'diagnostic','gap');
 when sqlstate '22023' or datetime_field_overflow then return jsonb_build_object('instant',null,'diagnostic','unsupported_endpoint');end;
end$$;
create function workforce_private.rota_period_cursor(v jsonb) returns text language sql immutable set search_path='' as $$select translate(rtrim(replace(encode(convert_to(v::text,'UTF8'),'base64'),E'\n',''),'='),'+/','-_')$$;
create function workforce_private.rota_period_uncursor(v jsonb) returns jsonb language plpgsql immutable set search_path='' as $$declare s text;b bytea;j jsonb;begin
 if v is null then return null;end if;s:=workforce_private.rota_period_text(v,4096);if s!~'^[A-Za-z0-9_-]+$'then raise exception using errcode='22023',message='Invalid period cursor';end if;b:=decode(translate(s,'-_','+/')||repeat('=',(4-length(s)%4)%4),'base64');j:=convert_from(b,'UTF8')::jsonb;if workforce_private.rota_period_cursor(j)<>s then raise exception using errcode='22023',message='Noncanonical period cursor';end if;return j;
end$$;
create function workforce_private.rota_period_page(rows jsonb,ident jsonb,page_limit integer,after_cursor jsonb default null) returns jsonb language plpgsql immutable set search_path='' as $$declare pos integer:=0;total integer:=jsonb_array_length(rows);c jsonb;items jsonb;next_cursor text;begin
 c:=workforce_private.rota_period_uncursor(after_cursor);if c is not null then perform workforce_private.rota_period_keys(c,array['scope','position']);if c->'scope' is distinct from ident then raise exception using errcode='40001',message='Period page changed';end if;pos:=workforce_private.rota_period_number(c->'position',0,total);end if;
 select coalesce(jsonb_agg(value order by ordinality),'[]'::jsonb) into items from jsonb_array_elements(rows)with ordinality where ordinality>pos and ordinality<=pos+page_limit;
 if pos+page_limit<total then next_cursor:=workforce_private.rota_period_cursor(jsonb_build_object('scope',ident,'position',pos+page_limit));end if;return jsonb_build_object('items',items,'page',jsonb_build_object('total',total,'nextCursor',next_cursor));
end$$;
-- Source selection is authoritative, uses exact positive overlap and literal SQL search.
create function workforce_private.rota_period_source(t uuid,sid uuid,k text,anchor date,filters jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare s public.rota_schedules;f jsonb;lo timestamptz;hi timestamptz;rows jsonb;selectors jsonb;n integer;users integer;elapsed bigint;dig text;begin
 perform workforce_private.rota_period_access(t,sid);select * into s from public.rota_schedules where tenant_id=t and id=sid;f:=workforce_private.rota_period_filters(filters);
 begin lo:=workforce_private.rota_template_instant(anchor::timestamp,s.time_zone,'');hi:=workforce_private.rota_template_instant((anchor+case when k='week'then 7 else 1 end)::timestamp,s.time_zone,'');exception when sqlstate '22007' or sqlstate '22008' or sqlstate '22023' then raise exception using errcode='22023',message='Unsupported source period boundary';end;
 if lo<timestamptz '0001-01-01 00:00:00+00'or hi>=timestamptz '10000-01-01 00:00:00+00'then raise exception using errcode='22023',message='Unsupported source period boundary';end if;
 with selected as (select x.*,a.first_name||' '||a.last_name agent_name,j.name job_name,j.color job_color,x.starts_at at time zone s.time_zone ls,x.ends_at at time zone s.time_zone le,row_number()over(order by x.id)-1 idx from public.rota_shifts x join public.agents a on a.tenant_id=x.tenant_id and a.id=x.agent_id join public.rota_jobs j on j.tenant_id=x.tenant_id and j.schedule_id=x.schedule_id and j.id=x.job_id where x.tenant_id=t and x.schedule_id=sid and x.starts_at<hi and x.ends_at>lo and(f->>'jobId' is null or x.job_id=(f->>'jobId')::uuid)and(f->>'status'='all'or x.status=f->>'status')and strpos(lower(a.first_name||' '||a.last_name),lower(f->>'workerSearch'))>0),
 captured as(select *,jsonb_build_object('index',idx,'source_shift_id',id,'source_revision',revision,'source_status',status,'source_starts_at',workforce_private.rota_period_source_utc(starts_at,s.time_zone),'source_ends_at',workforce_private.rota_period_source_utc(ends_at,s.time_zone),'agent_id',agent_id,'agent_name',agent_name,'job_id',job_id,'job_name',job_name,'job_color',job_color,'title',title,'start_day_offset',ls::date-anchor,'end_day_offset',le::date-anchor,'start_clock_micros',(extract(epoch from(ls-ls::date::timestamp))*1000000)::bigint,'end_clock_micros',(extract(epoch from(le-le::date::timestamp))*1000000)::bigint) e from selected)
 select coalesce(jsonb_agg(e order by idx),'[]'::jsonb),coalesce(jsonb_agg(jsonb_build_object('id',id,'revision',revision)order by id),'[]'::jsonb),count(*),count(distinct agent_id),coalesce(sum((extract(epoch from(ends_at-starts_at))*1000000)::bigint),0) into rows,selectors,n,users,elapsed from captured;
 if exists(select 1 from jsonb_array_elements(rows)e where workforce_private.knowledge_utf16(e->>'agent_name')>401 or workforce_private.knowledge_utf16(e->>'job_name')>200 or workforce_private.knowledge_utf16(e->>'title')>200)then raise exception using errcode='22023',message='Some source names are too long to save. Shorten them and review again.';end if;
 if n>5000 then raise exception using errcode='54000',message='Source period exceeds complete batch capacity';end if;
 if exists(select 1 from jsonb_array_elements(rows)e where(e->>'start_day_offset')::integer not between -2 and case when k='week'then 8 else 2 end or(e->>'end_day_offset')::integer not between -2 and case when k='week'then 8 else 2 end)then raise exception using errcode='22023',message='Unsupported source local offset';end if;
 -- Verify original endpoints match a supported extreme, preserving submilliseconds.
 if exists(with endpoints as materialized(select distinct(e->>'source_starts_at')::timestamptz instant from jsonb_array_elements(rows)e union select distinct(e->>'source_ends_at')::timestamptz from jsonb_array_elements(rows)e)select 1 from endpoints where workforce_private.rota_template_instant(instant at time zone s.time_zone,s.time_zone,'earlier')<>instant and workforce_private.rota_template_instant(instant at time zone s.time_zone,s.time_zone,'later')<>instant)then raise exception using errcode='22023',message='Unsupported source occurrence';end if;
 dig:=workforce_private.rota_period_hash(jsonb_build_object('actor',auth.uid(),'tenant',t,'schedule',sid,'revision',s.revision,'kind',k,'anchor',anchor,'zone',s.time_zone,'filters',f,'entries',rows));
 return jsonb_build_object('source',jsonb_build_object('kind',k,'anchor',to_char(anchor,'YYYY-MM-DD'),'zone',s.time_zone,'filters',f,'entryCount',n,'userCount',users,'elapsedMicros',elapsed),'entries',rows,'selectors',selectors,'sourceReviewDigest',dig);
end$$;
create function workforce_private.rota_period_choices(v jsonb,n integer) returns jsonb language plpgsql immutable set search_path='' as $$declare e jsonb;idx integer;outrows jsonb;begin
 if jsonb_typeof(v) is distinct from 'array' or jsonb_array_length(v)>5000 then raise exception using errcode='22023',message='Invalid occurrence choices';end if;
 for e in select value from jsonb_array_elements(v)loop perform workforce_private.rota_period_keys(e,array['index'],array['start','end']);idx:=workforce_private.rota_period_number(e->'index',0,n-1);if not(e?'start'or e?'end')then raise exception using errcode='22023',message='Missing endpoint choice';end if;if(e?'start'and(jsonb_typeof(e->'start')<>'string'or e->>'start'not in('earlier','later')))or(e?'end'and(jsonb_typeof(e->'end')<>'string'or e->>'end'not in('earlier','later')))then raise exception using errcode='22023',message='Invalid endpoint occurrence';end if;end loop;
 if(select count(distinct(value->>'index')::integer)from jsonb_array_elements(v))<>jsonb_array_length(v)then raise exception using errcode='22023',message='Duplicate occurrence index';end if;select coalesce(jsonb_agg(value order by(value->>'index')::integer),'[]'::jsonb)into outrows from jsonb_array_elements(v);return outrows;
end$$;
create function workforce_private.rota_period_plan(t uuid,sid uuid,tid uuid,expected integer,anchor date,choices jsonb) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare ident jsonb;s public.rota_schedules;x public.rota_period_templates;occ jsonb;generated jsonb;commitments jsonb;visible jsonb;allconflicts jsonb;cap jsonb;blockers jsonb;raw_shifts bigint;raw_entries bigint;raw_ops bigint;raw_links bigint;raw_meta bigint;blocked integer;affected integer;users integer;elapsed bigint;hidden boolean;dig text;begin
 ident:=workforce_private.rota_period_access(t,sid);select *into s from public.rota_schedules where tenant_id=t and id=sid;select *into x from public.rota_period_templates where tenant_id=t and schedule_id=sid and id=tid and deleted_at is null;if not found then raise exception using errcode='P0002',message='Period template unavailable';end if;if x.revision<>expected then raise exception using errcode='40001',message='Period template changed';end if;perform workforce_private.rota_period_date(to_jsonb(to_char(anchor,'YYYY-MM-DD')),x.kind);occ:=workforce_private.rota_period_choices(choices,x.entry_count);
 select count(*)into raw_shifts from public.rota_shifts where tenant_id=t;select count(*)into raw_entries from public.rota_period_entries where tenant_id=t;select count(*)into raw_ops from workforce_private.rota_period_operations where tenant_id=t;select count(*)into raw_links from public.rota_period_generated where tenant_id=t;select count(*)into raw_meta from public.rota_period_templates where tenant_id=t and schedule_id=sid;
 cap:=jsonb_build_object('companyUsageVisible',(ident->>'companyUsageVisible')::boolean,'metadata',raw_meta,'shifts',case when(ident->>'companyUsageVisible')::boolean then raw_shifts end,'entries',case when(ident->>'companyUsageVisible')::boolean then raw_entries end,'operations',case when(ident->>'companyUsageVisible')::boolean then raw_ops end,'generated',case when(ident->>'companyUsageVisible')::boolean then raw_links end);
 select coalesce(jsonb_agg(reason),'[]'::jsonb)into blockers from(values(case when s.status<>'active'then 'schedule_archived'end),(case when raw_shifts+x.entry_count>5000 then 'shift_capacity'end),(case when raw_ops>=20000 then 'operation_capacity'end),(case when raw_links+x.entry_count>20000 then 'generated_capacity'end))b(reason)where reason is not null;
 with available as materialized(select agent_id,job_id,workforce_private.rota_period_availability(t,sid,agent_id,job_id)availability from(select distinct agent_id,job_id from public.rota_period_entries where tenant_id=t and schedule_id=sid and template_id=tid)p),base as materialized(select e.entry_index,e.agent_id,e.snapshot,e.job_id,av.availability,workforce_private.rota_period_wall(anchor,(e.snapshot->>'start_day_offset')::integer,(e.snapshot->>'start_clock_micros')::bigint)ls,workforce_private.rota_period_wall(anchor,(e.snapshot->>'end_day_offset')::integer,(e.snapshot->>'end_clock_micros')::bigint)le,coalesce(o->>'start','')sc,coalesce(o->>'end','')ec from public.rota_period_entries e join available av on av.agent_id=e.agent_id and av.job_id=e.job_id left join jsonb_array_elements(occ)o on(o->>'index')::integer=e.entry_index where e.tenant_id=t and e.schedule_id=sid and e.template_id=tid),
 endpoints as materialized(select distinct ls local_time,sc choice from base union select distinct le,ec from base),
 resolved as materialized(select local_time,choice,workforce_private.rota_period_endpoint(local_time,s.time_zone,choice)r from endpoints),
 tuples as materialized(select b.*,rs.r sr,re.r er,(rs.r->>'instant')::timestamptz st,(re.r->>'instant')::timestamptz en from base b join resolved rs on rs.local_time=b.ls and rs.choice=b.sc join resolved re on re.local_time=b.le and re.choice=b.ec),
 sweeps as(select *,max(en)over(partition by agent_id order by st,en,entry_index rows between unbounded preceding and 1 preceding)prev_end,lead(st)over(partition by agent_id order by st,en,entry_index)next_start from tuples),
 diagnostics as(select *,coalesce((select jsonb_agg(reason)from(values(case when(availability->>'workerAvailable')::boolean is not true then 'worker_unavailable'end),(case when(availability->>'jobAvailable')::boolean is not true then 'job_unavailable'end),(case when sr->>'diagnostic'='gap'then 'start_gap'when sr->>'diagnostic'='ambiguous'then 'start_ambiguous'when sr->>'diagnostic'='occurrence'then 'start_occurrence'when sr->>'diagnostic' is not null then 'unsupported_endpoint'end),(case when er->>'diagnostic'='gap'then 'end_gap'when er->>'diagnostic'='ambiguous'then 'end_ambiguous'when er->>'diagnostic'='occurrence'then 'end_occurrence'when er->>'diagnostic' is not null then 'unsupported_endpoint'end),(case when st is not null and en is not null and(en<=st or en-st>interval '24 hours')then 'invalid_duration'end))v(reason)where reason is not null),'[]'::jsonb) reasons from sweeps)
 select coalesce(jsonb_agg(jsonb_build_object('entry',snapshot,'availability',availability,'starts_at',sr->'instant','ends_at',er->'instant','elapsed_micros',case when en>st and en-st<=interval '24 hours'then(extract(epoch from(en-st))*1000000)::bigint end,'blockers',reasons,'internalConflict',coalesce(en>st and(prev_end>st or next_start<en),false),'existingConflict',false)order by entry_index),'[]'::jsonb)into generated from diagnostics;
 -- Merge intervals per assigned worker first. No generated/existing pair rows.
 with ranges as materialized(select (e->'entry'->>'agent_id')::uuid aid,range_agg(tstzrange((e->>'starts_at')::timestamptz,(e->>'ends_at')::timestamptz,'[)')) spans from jsonb_array_elements(generated)e where e->>'starts_at'is not null and e->>'ends_at'is not null and(e->>'ends_at')::timestamptz>(e->>'starts_at')::timestamptz group by 1),
 hits as(select sh.*,btrim(a.first_name)||' '||btrim(a.last_name) agent_name,btrim(j.name) job_name,j.color job_color,workforce_private.rota_manage(t,sh.schedule_id)or(sh.status='published'and workforce_private.rota_access(t,sh.schedule_id)and a.user_id=auth.uid()and a.status='active') vis from ranges r join public.rota_shifts sh on sh.tenant_id=t and sh.agent_id=r.aid and tstzrange(sh.starts_at,sh.ends_at,'[)')&&r.spans join public.agents a on a.tenant_id=sh.tenant_id and a.id=sh.agent_id join public.rota_jobs j on j.tenant_id=sh.tenant_id and j.schedule_id=sh.schedule_id and j.id=sh.job_id)
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'revision',revision,'schedule_id',schedule_id,'agent_id',agent_id,'agent_name',agent_name,'job_id',job_id,'job_name',job_name,'job_color',job_color,'title',title,'starts_at',workforce_private.rota_period_utc(starts_at),'ends_at',workforce_private.rota_period_utc(ends_at),'status',status,'visible',vis)order by id),'[]'::jsonb)into allconflicts from hits;
 with ranges as materialized(select(e->>'agent_id')::uuid aid,range_agg(tstzrange((e->>'starts_at')::timestamptz,(e->>'ends_at')::timestamptz,'[)'))spans from jsonb_array_elements(allconflicts)e group by 1)
 select coalesce(jsonb_agg(e||jsonb_build_object('existingConflict',case when e->>'starts_at'is not null and e->>'ends_at'is not null and(e->>'ends_at')::timestamptz>(e->>'starts_at')::timestamptz then coalesce(r.spans&&tstzrange((e->>'starts_at')::timestamptz,(e->>'ends_at')::timestamptz,'[)'),false)else false end)order by(e->'entry'->>'index')::integer),'[]'::jsonb)into generated from jsonb_array_elements(generated)e left join ranges r on r.aid=(e->'entry'->>'agent_id')::uuid and e->>'starts_at'is not null and e->>'ends_at'is not null and(e->>'ends_at')::timestamptz>(e->>'starts_at')::timestamptz;
 select coalesce(jsonb_agg(e-'visible'order by e->>'id')filter(where(e->>'visible')::boolean),'[]'::jsonb),coalesce(bool_or((e->>'visible')::boolean is not true),false)into visible,hidden from jsonb_array_elements(allconflicts)e;
 select count(*)filter(where jsonb_array_length(e->'blockers')>0),count(*)filter(where(e->>'internalConflict')::boolean or(e->>'existingConflict')::boolean),count(distinct e->'entry'->>'agent_id'),coalesce(sum((e->>'elapsed_micros')::bigint),0)into blocked,affected,users,elapsed from jsonb_array_elements(generated)e;
 -- Restricted actors bind opaque quota decisions, never small-domain hidden usage.
 dig:=workforce_private.rota_period_hash(jsonb_build_object('actor',auth.uid(),'tenant',t,'schedule',ident->'schedule','template',workforce_private.rota_period_metadata(x),'anchor',anchor,'choices',occ,'generated',generated,'conflicts',allconflicts,'capacity',cap,'blockers',blockers));
 return(ident-'companyUsageVisible')||jsonb_build_object('template',workforce_private.rota_period_metadata(x),'targetAnchor',to_char(anchor,'YYYY-MM-DD'),'occurrences',occ,'planDigest',dig,'canAdd',blocked=0 and jsonb_array_length(blockers)=0,'entryCount',x.entry_count,'userCount',users,'elapsedMicros',elapsed,'blockedEntryCount',blocked,'affectedEntryCount',affected,'visibleCommitmentCount',jsonb_array_length(visible),'hasHiddenConflicts',hidden,'capacity',cap,'blockers',blockers,'entries',generated,'commitments',visible);
end$$;
create function workforce_private.rota_period_budget(t uuid,sid uuid,n integer) returns jsonb language plpgsql stable security definer set search_path='' as $$declare a jsonb;sh bigint;en bigint;op bigint;ge bigint;me bigint;visible boolean;begin
 a:=workforce_private.rota_period_access(t,sid);visible:=(a->>'companyUsageVisible')::boolean;select count(*)into sh from public.rota_shifts where tenant_id=t;select count(*)into en from public.rota_period_entries where tenant_id=t;select count(*)into op from workforce_private.rota_period_operations where tenant_id=t;select count(*)into ge from public.rota_period_generated where tenant_id=t;select count(*)into me from public.rota_period_templates where tenant_id=t and schedule_id=sid;
 return jsonb_build_object('capacity',jsonb_build_object('companyUsageVisible',visible,'metadata',me,'shifts',case when visible then sh end,'entries',case when visible then en end,'operations',case when visible then op end,'generated',case when visible then ge end),'editBlockers',(select coalesce(jsonb_agg(reason),'[]'::jsonb)from(values(case when a->'schedule'->>'status'<>'active'then 'schedule_archived'end),(case when op>=20000 then 'operation_capacity'end))b(reason)where reason is not null),'saveBlockers',(select coalesce(jsonb_agg(reason),'[]'::jsonb)from(values(case when a->'schedule'->>'status'<>'active'then 'schedule_archived'end),(case when me>=500 then 'metadata_capacity'end),(case when en+n>20000 then 'entry_capacity'end),(case when op>=20000 then 'operation_capacity'end))b(reason)where reason is not null));
end$$;
create function workforce_private.rota_period_catalogue_page(rows jsonb,ident jsonb,page_limit integer,after_cursor jsonb default null) returns jsonb language plpgsql immutable set search_path='' as $$declare c jsonb;k text;rid uuid;items jsonb;has_next boolean;lastrow jsonb;begin
 c:=workforce_private.rota_period_uncursor(after_cursor);if c is not null then perform workforce_private.rota_period_keys(c,array['scope','key','id']);if c->'scope'is distinct from ident then raise exception using errcode='40001',message='Catalogue changed';end if;k:=workforce_private.rota_period_text(c->'key',200);rid:=workforce_private.rota_period_uuid(c->'id');end if;
 with filtered as(select value e,row_number()over(order by lower(value->>'title')collate "C",(value->>'id')::uuid)n from jsonb_array_elements(rows)where c is null or(lower(value->>'title')collate "C",(value->>'id')::uuid)>(k collate "C",rid)),limited as(select *from filtered where n<=page_limit+1)
 select coalesce(jsonb_agg(e order by n)filter(where n<=page_limit),'[]'::jsonb),count(*)>page_limit into items,has_next from limited;lastrow:=items->(jsonb_array_length(items)-1);
 return jsonb_build_object('items',items,'page',jsonb_build_object('total',jsonb_array_length(rows),'nextCursor',case when has_next then workforce_private.rota_period_cursor(jsonb_build_object('scope',ident,'key',lower(lastrow->>'title'),'id',lastrow->'id'))end));
end$$;
create function workforce_private.read_rota_period_templates(t uuid,request_text text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare q jsonb;sid uuid;ident jsonb;x public.rota_period_templates;rows jsonb;pg jsonb;scope jsonb;lim integer;search text;k text;dig text;budget jsonb;begin
 if request_text is null or octet_length(request_text)>8192 or workforce_private.forms_json_unique(request_text::json)is distinct from true then raise exception using errcode='22023',message='Invalid period query';end if;q:=request_text::jsonb;
 if q?'mode'then perform workforce_private.rota_period_keys(q,array['mode','tenantId','scheduleId','templateId','templateRevision'],array['limit','cursor']);if q->>'mode'<>'history'then raise exception using errcode='22023',message='Invalid history mode';end if;
 else perform workforce_private.rota_period_keys(q,array['tenantId','scheduleId','kind'],array['q','limit','cursor']);end if;
 if workforce_private.rota_period_uuid(q->'tenantId')<>t then raise exception using errcode='22023',message='Invalid company scope';end if;sid:=workforce_private.rota_period_uuid(q->'scheduleId');ident:=workforce_private.rota_period_access(t,sid);lim:=case when q?'limit'then workforce_private.rota_period_number(q->'limit',1,100)else case when q?'mode'then 100 else 30 end end;
 if q?'mode'then
 select *into x from public.rota_period_templates where tenant_id=t and schedule_id=sid and id=workforce_private.rota_period_uuid(q->'templateId')and deleted_at is null;if not found then raise exception using errcode='P0002',message='Period template unavailable';end if;if x.revision<>workforce_private.rota_period_number(q->'templateRevision',1,2147483646)then raise exception using errcode='40001',message='Template changed';end if;
 select coalesce(jsonb_agg(jsonb_build_object('entry',snapshot,'availability',workforce_private.rota_period_availability(t,sid,agent_id,job_id))order by entry_index),'[]'::jsonb)into rows from public.rota_period_entries where tenant_id=t and schedule_id=sid and template_id=x.id;
 dig:=workforce_private.rota_period_hash(jsonb_build_object('identity',ident,'template',workforce_private.rota_period_metadata(x),'entries',rows));scope:=jsonb_build_object('mode','history','identity',ident,'template',x.id,'revision',x.revision,'digest',dig);pg:=workforce_private.rota_period_page(rows,scope,lim,q->'cursor');return(ident-'companyUsageVisible')||jsonb_build_object('template',workforce_private.rota_period_metadata(x),'historyDigest',dig,'entries',pg->'items','page',pg->'page');
 else
 k:=workforce_private.rota_period_text(q->'kind',10);if k not in('day','week')then raise exception using errcode='22023',message='Invalid period kind';end if;search:=case when q?'q'then workforce_private.rota_period_text(q->'q',100)else ''end;
 select coalesce(jsonb_agg(workforce_private.rota_period_metadata(m)order by lower(m.title)collate "C",m.id),'[]'::jsonb)into rows from public.rota_period_templates m where m.tenant_id=t and m.schedule_id=sid and m.kind=k and m.deleted_at is null and strpos(lower(m.title),lower(search))>0;
 scope:=jsonb_build_object('mode','catalogue','identity',ident,'kind',k,'search',search);pg:=workforce_private.rota_period_catalogue_page(rows,scope,lim,q->'cursor');budget:=workforce_private.rota_period_budget(t,sid,0);return(ident-'companyUsageVisible')||jsonb_build_object('kind',k,'q',search,'templates',pg->'items','page',pg->'page','capacity',budget->'capacity','editBlockers',budget->'editBlockers','canEdit',jsonb_array_length(budget->'editBlockers')=0);
 end if;
end$$;
create function workforce_private.preview_rota_period_template(t uuid,request_text text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare q jsonb;sid uuid;ident jsonb;rev integer;lim integer;k text;anchor date;fullplan jsonb;rows jsonb;pg jsonb;scope jsonb;pk text;budget jsonb;x public.rota_period_templates;begin
 if request_text is null or octet_length(request_text)>524288 or workforce_private.forms_json_unique(request_text::json)is distinct from true then raise exception using errcode='22023',message='Invalid period preview';end if;q:=request_text::jsonb;
 if q->>'mode'='source-preview'then perform workforce_private.rota_period_keys(q,array['mode','tenantId','scheduleId','scheduleRevision','kind','sourceAnchor','sourceFilters'],array['limit','cursor']);elsif q->>'mode'='preview'then perform workforce_private.rota_period_keys(q,array['mode','tenantId','scheduleId','scheduleRevision','templateId','templateRevision','targetAnchor','occurrences','pageKind'],array['limit','cursor']);else raise exception using errcode='22023',message='Invalid period preview mode';end if;
 if workforce_private.rota_period_uuid(q->'tenantId')<>t then raise exception using errcode='22023',message='Invalid company scope';end if;sid:=workforce_private.rota_period_uuid(q->'scheduleId');rev:=workforce_private.rota_period_number(q->'scheduleRevision',1,2147483646);ident:=workforce_private.rota_period_access(t,sid);if rev<>(ident->'schedule'->>'revision')::integer then raise exception using errcode='40001',message='Schedule changed';end if;lim:=case when q?'limit'then workforce_private.rota_period_number(q->'limit',1,100)else 100 end;
 if q->>'mode'='source-preview'then
 k:=workforce_private.rota_period_text(q->'kind',10);anchor:=workforce_private.rota_period_date(q->'sourceAnchor',k);fullplan:=workforce_private.rota_period_source(t,sid,k,anchor,q->'sourceFilters');scope:=jsonb_build_object('mode','source-preview','identity',ident,'source',fullplan->'source','digest',fullplan->'sourceReviewDigest');pg:=workforce_private.rota_period_page(fullplan->'entries',scope,lim,q->'cursor');budget:=workforce_private.rota_period_budget(t,sid,(fullplan->'source'->>'entryCount')::integer);
 return(ident-'companyUsageVisible')||(fullplan-'entries'-'selectors')||jsonb_build_object('entries',pg->'items','page',pg->'page','firstPage',not(q?'cursor'),'capacity',budget->'capacity','saveBlockers',budget->'saveBlockers','canSave',(fullplan->'source'->>'entryCount')::integer>0 and jsonb_array_length(budget->'saveBlockers')=0)||case when not(q?'cursor')then jsonb_build_object('selectors',fullplan->'selectors')else '{}'::jsonb end;
 else
 select *into x from public.rota_period_templates where tenant_id=t and schedule_id=sid and id=workforce_private.rota_period_uuid(q->'templateId')and deleted_at is null;if not found then raise exception using errcode='P0002',message='Period template unavailable';end if;anchor:=workforce_private.rota_period_date(q->'targetAnchor',x.kind);fullplan:=workforce_private.rota_period_plan(t,sid,x.id,workforce_private.rota_period_number(q->'templateRevision',1,2147483646)::integer,anchor,q->'occurrences');pk:=workforce_private.rota_period_text(q->'pageKind',30);if pk not in('entries','blocked','affected','visibleCommitments')then raise exception using errcode='22023',message='Invalid target page kind';end if;
 if pk='visibleCommitments'then rows:=fullplan->'commitments';else select coalesce(jsonb_agg(e order by(e->'entry'->>'index')::integer),'[]'::jsonb)into rows from jsonb_array_elements(fullplan->'entries')e where pk='entries'or(pk='blocked'and jsonb_array_length(e->'blockers')>0)or(pk='affected'and((e->>'internalConflict')::boolean or(e->>'existingConflict')::boolean));end if;
 scope:=jsonb_build_object('mode','preview','identity',ident,'template',x.id,'revision',x.revision,'anchor',anchor,'pageKind',pk,'digest',fullplan->'planDigest');pg:=workforce_private.rota_period_page(rows,scope,lim,q->'cursor');return(fullplan-'entries'-'commitments')||jsonb_build_object('pageKind',pk,'page',pg->'page')||jsonb_build_object(case when pk='visibleCommitments'then 'commitments'else 'entries'end,pg->'items');
 end if;
end$$;
create function workforce_private.rota_period_entry_locks(t uuid,sid uuid,entries jsonb) returns void language plpgsql volatile security definer set search_path='' as $$declare aids uuid[];jids uuid[];begin
 select array_agg(distinct coalesce(e->>'agent_id',e->'entry'->>'agent_id')::uuid),array_agg(distinct coalesce(e->>'job_id',e->'entry'->>'job_id')::uuid)into aids,jids from jsonb_array_elements(entries)e;
 perform 1 from public.agents where tenant_id=t and id=any(aids)order by id for share;
 perform 1 from public.rota_jobs where tenant_id=t and schedule_id=sid and id=any(jids)order by id for share;
 perform 1 from public.rota_agents where tenant_id=t and schedule_id=sid and agent_id=any(aids)order by agent_id for share;
 perform 1 from auth.users where id in(select user_id from public.agents where tenant_id=t and id=any(aids))order by id for share;
 perform 1 from public.tenant_memberships where tenant_id=t and user_id in(select user_id from public.agents where tenant_id=t and id=any(aids))order by user_id for share;
 perform 1 from public.rota_admins where tenant_id=t and user_id=auth.uid()order by schedule_id for share;
 perform 1 from public.rota_shifts where tenant_id=t and agent_id=any(aids)order by id for share;
end$$;
create function workforce_private.save_rota_period_template(t uuid,op uuid,change_text text) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare c jsonb;a text;sid uuid;tid uuid;actor uuid:=auth.uid();s public.rota_schedules;x public.rota_period_templates;rec workforce_private.rota_period_operations;keys text[];h text;newid uuid;auditid uuid;result jsonb;review jsonb;plan jsonb;selectors jsonb;src jsonb;en jsonb;generated jsonb;anchor date;k text;new_title text;cnt integer;rr integer;chosen uuid[];begin
 if change_text is null or octet_length(change_text)>524288 or workforce_private.forms_json_unique(change_text::json)is distinct from true then raise exception using errcode='22023',message='Invalid period mutation';end if;c:=change_text::jsonb;a:=workforce_private.rota_period_text(c->'action',10);if a not in('save','rename','delete','add')then raise exception using errcode='22023',message='Invalid period action';end if;
 keys:=array['action','schedule_id','schedule_revision'];if a='save'then keys:=keys||array['kind','title','source_anchor','source_zone','source_filters','source_review_digest','sources'];else keys:=keys||array['template_id','template_revision'];if a='rename'then keys:=keys||array['title'];elsif a='add'then keys:=keys||array['target_anchor','occurrences','plan_digest','expected_entry_count','allow_overlap'];end if;end if;perform workforce_private.rota_period_keys(c,keys);
 sid:=workforce_private.rota_period_uuid(c->'schedule_id');rr:=workforce_private.rota_period_number(c->'schedule_revision',1,2147483646);if a<>'save'then tid:=workforce_private.rota_period_uuid(c->'template_id');perform workforce_private.rota_period_number(c->'template_revision',1,2147483646);end if;
 -- Existing lock helper gives the exact legacy actor/operation/company ordering.
 s:=workforce_private.rota_template_locks(t,op,sid);h:=workforce_private.rota_period_hash(c);
 select *into rec from workforce_private.rota_period_operations where tenant_id=t and actor_id=actor and operation_id=op;
 if found then if rec.state<>'recorded'or rec.action<>a or rec.schedule_id<>sid or rec.target_template_id is distinct from tid or rec.payload_hash<>h then raise exception using errcode='40001',message='Period operation closed or changed';end if;return rec.result;end if;
 if s.status<>'active'then raise exception using errcode='22023',message='Restore schedule before changing period templates';end if;if s.revision<>rr then raise exception using errcode='40001',message='Schedule changed';end if;
 if(select count(*)from workforce_private.rota_period_operations where tenant_id=t)>=20000 then raise exception using errcode='54000',message='Retained operation capacity reached';end if;
 if a<>'save'then select *into x from public.rota_period_templates where tenant_id=t and schedule_id=sid and id=tid and deleted_at is null for update;if not found then raise exception using errcode='P0002',message='Period template unavailable';end if;if x.revision<>(c->>'template_revision')::integer then raise exception using errcode='40001',message='Period template changed';end if;end if;
 if a in('save','rename')then new_title:=btrim(workforce_private.rota_period_text(c->'title',100,true),U&'\0009\000A\000B\000C\000D \00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000\FEFF');if workforce_private.knowledge_nonblank(new_title)is distinct from true or new_title~U&'[\0001-\001F\007F-\009F]'then raise exception using errcode='22023',message='Choose a control-free title';end if;end if;
 if a='save'then
 k:=workforce_private.rota_period_text(c->'kind',10);anchor:=workforce_private.rota_period_date(c->'source_anchor',k);if workforce_private.rota_period_text(c->'source_zone',100)<>s.time_zone then raise exception using errcode='40001',message='Source timezone changed';end if;
 if jsonb_typeof(c->'sources')is distinct from 'array'or jsonb_array_length(c->'sources')not between 1 and 5000 then raise exception using errcode='22023',message='Choose complete source selectors';end if;
 for src in select value from jsonb_array_elements(c->'sources')loop perform workforce_private.rota_period_keys(src,array['id','revision']);perform workforce_private.rota_period_uuid(src->'id');perform workforce_private.rota_period_number(src->'revision',1,2147483646);end loop;
 select array_agg((e->>'id')::uuid order by(e->>'id')::uuid),jsonb_agg(jsonb_build_object('id',(e->>'id')::uuid,'revision',(e->>'revision')::integer)order by(e->>'id')::uuid)into chosen,selectors from jsonb_array_elements(c->'sources')e;if(select count(distinct id)from unnest(chosen)id)<>cardinality(chosen)then raise exception using errcode='22023',message='Duplicate source selector';end if;
 perform 1 from public.rota_shifts where tenant_id=t and schedule_id=sid and id=any(chosen)order by id for update;
 review:=workforce_private.rota_period_source(t,sid,k,anchor,c->'source_filters');perform workforce_private.rota_period_entry_locks(t,sid,review->'entries');review:=workforce_private.rota_period_source(t,sid,k,anchor,c->'source_filters');
 if review->'selectors'<>selectors or review->>'sourceReviewDigest'<>workforce_private.rota_period_text(c->'source_review_digest',64)then raise exception using errcode='40001',message='Complete source review changed';end if;cnt:=jsonb_array_length(selectors);
 if(select count(*)from public.rota_period_templates where tenant_id=t and schedule_id=sid)>=500 or(select count(*)from public.rota_period_entries where tenant_id=t)+cnt>20000 then raise exception using errcode='54000',message='Retained snapshot capacity reached';end if;
 insert into public.rota_period_templates(tenant_id,schedule_id,kind,title,source_anchor,source_zone,source_schedule_revision,source_filters,entry_count,user_count,elapsed_micros,creator_id)values(t,sid,k,new_title,anchor,s.time_zone,s.revision,review->'source'->'filters',cnt,(review->'source'->>'userCount')::integer,(review->'source'->>'elapsedMicros')::bigint,actor)returning *into x;
 insert into public.rota_period_entries(tenant_id,schedule_id,template_id,entry_index,source_shift_id,agent_id,job_id,snapshot)select t,sid,x.id,(e->>'index')::integer,(e->>'source_shift_id')::uuid,(e->>'agent_id')::uuid,(e->>'job_id')::uuid,e from jsonb_array_elements(review->'entries')e;
 elsif a='rename'then update public.rota_period_templates set title=new_title,revision=revision+1,updated_at=now()where id=tid returning *into x;
 elsif a='delete'then update public.rota_period_templates set deleted_at=now(),revision=revision+1,updated_at=now()where id=tid returning *into x;
 else
 anchor:=workforce_private.rota_period_date(c->'target_anchor',x.kind);cnt:=workforce_private.rota_period_number(c->'expected_entry_count',1,5000);if cnt<>x.entry_count then raise exception using errcode='22023',message='Expected complete entry count changed';end if;if jsonb_typeof(c->'allow_overlap')is distinct from 'boolean'then raise exception using errcode='22023',message='Invalid overlap consent';end if;
 select jsonb_agg(snapshot order by entry_index)into en from public.rota_period_entries where tenant_id=t and schedule_id=sid and template_id=x.id;perform workforce_private.rota_period_entry_locks(t,sid,en);plan:=workforce_private.rota_period_plan(t,sid,x.id,x.revision,anchor,c->'occurrences');
 if(plan->>'canAdd')::boolean is not true or plan->>'planDigest'<>workforce_private.rota_period_text(c->'plan_digest',64)then raise exception using errcode='40001',message='Complete target plan changed or blocked';end if;if((plan->>'affectedEntryCount')::integer>0 or(plan->>'hasHiddenConflicts')::boolean)and(c->>'allow_overlap')::boolean is not true then raise exception using errcode='P0001',message='Explicit whole-plan overlap consent required';end if;
 end if;
 update public.rota_schedules set revision=revision+1 where tenant_id=t and id=sid returning revision into rr;
 insert into public.rota_period_audit(tenant_id,schedule_id,template_id,actor_id,operation_id,action,template_revision,schedule_revision)values(t,sid,x.id,actor,op,a,x.revision,rr)returning id into auditid;
 generated:='[]'::jsonb;
 if a='add'then
 for en in select value from jsonb_array_elements(plan->'entries')order by(value->'entry'->>'index')::integer loop
 newid:=gen_random_uuid();insert into public.rota_shifts(id,tenant_id,schedule_id,agent_id,job_id,starts_at,ends_at,title,status,revision)values(newid,t,sid,(en->'entry'->>'agent_id')::uuid,(en->'entry'->>'job_id')::uuid,(en->>'starts_at')::timestamptz,(en->>'ends_at')::timestamptz,en->'entry'->>'title','draft',1);
 insert into public.rota_period_generated(tenant_id,schedule_id,template_id,audit_id,entry_index,shift_id,snapshot)values(t,sid,x.id,auditid,(en->'entry'->>'index')::integer,newid,jsonb_build_object('index',(en->'entry'->>'index')::integer,'id',newid,'revision',1,'source_shift_id',en->'entry'->'source_shift_id','agent_id',en->'entry'->'agent_id','job_id',en->'entry'->'job_id','agent_name',en->'availability'->'currentAgentName','job_name',en->'availability'->'currentJobName','job_color',en->'availability'->'currentJobColor','title',en->'entry'->'title','starts_at',en->'starts_at','ends_at',en->'ends_at','status','draft'));
 end loop;select jsonb_agg(jsonb_build_object('index',entry_index,'id',shift_id,'revision',1)order by entry_index)into generated from public.rota_period_generated where tenant_id=t and audit_id=auditid;
 end if;
 result:=jsonb_build_object('schemaVersion',1,'tenantId',t,'actorId',actor,'operationId',op,'action',a,'template_id',x.id,'template_revision',x.revision,'schedule_id',sid,'schedule_revision',rr,'entry_count',x.entry_count,'generated',generated,'plan_digest',case when a='add'then plan->>'planDigest'end);
 insert into workforce_private.rota_period_operations(tenant_id,actor_id,operation_id,schedule_id,action,target_template_id,state,payload_hash,result)values(t,actor,op,sid,a,tid,'recorded',h,result);return result;
end$$;
create function workforce_private.reconcile_rota_period_template_operation(t uuid,op uuid,a text,sid uuid,tid uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$declare s public.rota_schedules;rec workforce_private.rota_period_operations;actor uuid:=auth.uid();begin
 if a is null or a not in('save','rename','delete','add')or((a='save')<>(tid is null))then raise exception using errcode='22023',message='Invalid period recovery scope';end if;s:=workforce_private.rota_template_locks(t,op,sid);
 select *into rec from workforce_private.rota_period_operations where tenant_id=t and actor_id=actor and operation_id=op;
 if found then if rec.action<>a or rec.schedule_id<>sid or rec.target_template_id is distinct from tid then raise exception using errcode='40001',message='Recovery scope changed';end if;
 else
 if(select count(*)from workforce_private.rota_period_operations where tenant_id=t)>=20000 then raise exception using errcode='54000',message='Retained operation capacity cannot reserve absence closure';end if;
 if a<>'save'and not exists(select 1 from public.rota_period_templates where tenant_id=t and schedule_id=sid and id=tid)then raise exception using errcode='42501',message='Recovery scope unavailable';end if;
 insert into workforce_private.rota_period_operations(tenant_id,actor_id,operation_id,schedule_id,action,target_template_id,state)values(t,actor,op,sid,a,tid,'closed_absent')returning *into rec;
 end if;
 return jsonb_build_object('schemaVersion',1,'tenantId',t,'actorId',actor,'operationId',op,'action',a,'scheduleId',sid,'templateId',tid,'status',case when rec.state='recorded'then 'recorded'else 'not_recorded'end,'saved',rec.result);
end$$;
create function public.read_rota_period_access(target_tenant uuid,target_schedule uuid) returns jsonb language sql stable security invoker set search_path='' as $$select workforce_private.rota_period_access(target_tenant,target_schedule)$$;
create function public.read_rota_period_templates(target_tenant uuid,request_text text) returns jsonb language sql stable security invoker set search_path='' as $$select workforce_private.read_rota_period_templates(target_tenant,request_text)$$;
create function public.preview_rota_period_template(target_tenant uuid,request_text text) returns jsonb language sql stable security invoker set search_path='' as $$select workforce_private.preview_rota_period_template(target_tenant,request_text)$$;
create function public.save_rota_period_template(target_tenant uuid,operation_id uuid,change_text text) returns jsonb language sql volatile security invoker set search_path='' as $$select workforce_private.save_rota_period_template(target_tenant,operation_id,change_text)$$;
create function public.reconcile_rota_period_template_operation(target_tenant uuid,operation_id uuid,action_name text,target_schedule uuid,target_template uuid) returns jsonb language sql volatile security invoker set search_path='' as $$select workforce_private.reconcile_rota_period_template_operation(target_tenant,operation_id,action_name,target_schedule,target_template)$$;
-- Explicitly revoke every additive helper, granting only bounded authenticated entries.
revoke all on function workforce_private.rota_period_catalogue_page(jsonb,jsonb,integer,jsonb),workforce_private.rota_period_source_utc(timestamptz,text),workforce_private.rota_period_utc(timestamptz),workforce_private.rota_period_hash(jsonb),workforce_private.rota_period_keys(jsonb,text[],text[]),workforce_private.rota_period_number(jsonb,bigint,bigint),workforce_private.rota_period_text(jsonb,integer,boolean),workforce_private.rota_period_uuid(jsonb),workforce_private.rota_period_date(jsonb,text),workforce_private.rota_period_filters(jsonb),workforce_private.rota_period_access(uuid,uuid),workforce_private.rota_period_metadata(public.rota_period_templates),workforce_private.rota_period_availability(uuid,uuid,uuid,uuid),workforce_private.rota_period_wall(date,integer,bigint),workforce_private.rota_period_endpoint(timestamp,text,text),workforce_private.rota_period_cursor(jsonb),workforce_private.rota_period_uncursor(jsonb),workforce_private.rota_period_page(jsonb,jsonb,integer,jsonb),workforce_private.rota_period_source(uuid,uuid,text,date,jsonb),workforce_private.rota_period_choices(jsonb,integer),workforce_private.rota_period_plan(uuid,uuid,uuid,integer,date,jsonb),workforce_private.rota_period_budget(uuid,uuid,integer),workforce_private.rota_period_entry_locks(uuid,uuid,jsonb),workforce_private.read_rota_period_templates(uuid,text),workforce_private.preview_rota_period_template(uuid,text),workforce_private.save_rota_period_template(uuid,uuid,text),workforce_private.reconcile_rota_period_template_operation(uuid,uuid,text,uuid,uuid),public.read_rota_period_access(uuid,uuid),public.read_rota_period_templates(uuid,text),public.preview_rota_period_template(uuid,text),public.save_rota_period_template(uuid,uuid,text),public.reconcile_rota_period_template_operation(uuid,uuid,text,uuid,uuid) from public,anon,authenticated,service_role;
grant execute on function workforce_private.rota_period_access(uuid,uuid),workforce_private.read_rota_period_templates(uuid,text),workforce_private.preview_rota_period_template(uuid,text),workforce_private.save_rota_period_template(uuid,uuid,text),workforce_private.reconcile_rota_period_template_operation(uuid,uuid,text,uuid,uuid),public.read_rota_period_access(uuid,uuid),public.read_rota_period_templates(uuid,text),public.preview_rota_period_template(uuid,text),public.save_rota_period_template(uuid,uuid,text),public.reconcile_rota_period_template_operation(uuid,uuid,text,uuid,uuid) to authenticated;
commit;
